#!/usr/bin/env python3
import sys
import time
import argparse
import subprocess
import os
from pathlib import Path
from datetime import datetime, timezone
from scrapling.fetchers import StealthySession

COOKIES_PATH = Path(__file__).parent / "cookies.txt"
TEST_URL = "https://www.youtube.com/shorts/ARIy9GQw0ws"
LOG_PREFIX = "[cookie-refresh]"

def log(msg):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"{LOG_PREFIX} {ts} {msg}", flush=True)

def write_netscape_cookies(cookies: list, path: Path):
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by refresh-yt-cookies.py (scrapling)",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", ".youtube.com")
        if not domain.startswith("."):
            domain = "." + domain
        include_sub = "TRUE"
        path_val = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = int(c.get("expires", 0) or 0)
        if expiry <= 0:
            expiry = int(time.time()) + 30 * 86400
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{include_sub}\t{path_val}\t{secure}\t{expiry}\t{name}\t{value}")

    path.write_text("\n".join(lines) + "\n")
    log(f"Wrote {len(cookies)} cookies → {path}")

def harvest_cookies(email=None, password=None) -> list:
    log("Launching StealthySession ...")
    session = StealthySession(headless=True, solve_cloudflare=True)
    session.start()
    
    page = session.context.new_page()
    
    if email and password:
        log("Navigating to Google Login...")
        page.goto("https://accounts.google.com/signin", wait_until="domcontentloaded", timeout=30000)
        page.fill("input[type=\"email\"]", email)
        page.keyboard.press("Enter")
        time.sleep(3)
        page.fill("input[type=\"password\"]", password)
        page.keyboard.press("Enter")
        time.sleep(5)
    
    log("Navigating to youtube.com ...")
    page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=30000)
    time.sleep(3)

    log("Navigating to YouTube Shorts ...")
    page.goto("https://www.youtube.com/shorts/", wait_until="domcontentloaded", timeout=20000)
    time.sleep(2)

    all_cookies = session.context.cookies()
    session.close()

    log(f"Harvested {len(all_cookies)} cookies")
    return all_cookies

def test_cookies(cookies_path: Path) -> bool:
    log(f"Testing cookies against {TEST_URL} ...")
    result = subprocess.run(
        ["yt-dlp", "--cookies", str(cookies_path), "--list-formats", "--no-warnings", "--quiet", TEST_URL],
        capture_output=True, text=True, timeout=30,
    )
    if result.returncode == 0:
        log("✓ Cookie test PASSED — yt-dlp can access YouTube Shorts")
        return True
    stderr_tail = (result.stderr or "").strip()[-300:]
    log(f"✗ Cookie test FAILED: {stderr_tail}")
    return False

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--test", action="store_true", help="Verify cookies with yt-dlp after harvesting")
    parser.add_argument("--test-only", action="store_true", help="Only test existing cookies")
    args = parser.parse_args()

    log("=== YouTube Cookie Refresh (scrapling) ===")

    if args.test_only:
        if not COOKIES_PATH.exists():
            log("ERROR: No cookies.txt found.")
            sys.exit(1)
        sys.exit(0 if test_cookies(COOKIES_PATH) else 1)

    email = os.environ.get("YT_GOOGLE_EMAIL")
    password = os.environ.get("YT_GOOGLE_PASS")
    
    cookies = harvest_cookies(email, password)
    write_netscape_cookies(cookies, COOKIES_PATH)
    COOKIES_PATH.chmod(0o600)

    if args.test:
        if not test_cookies(COOKIES_PATH):
            sys.exit(1)

    log("=== Cookie refresh complete ===")

if __name__ == "__main__":
    main()
