#!/usr/bin/env python3
"""
refresh-yt-cookies.py — Automated YouTube cookie harvester for yt-dlp
Smarter Poker | Operation TikTok Reels M1b

Uses camoufox (stealth Firefox) to visit youtube.com and collect
session cookies, then writes them in Netscape format so yt-dlp can
bypass YouTube's bot-detection on headless datacenter IPs.

Run location: /opt/smarter-poker/yt-transcode-worker/
Output:       /opt/smarter-poker/yt-transcode-worker/cookies.txt
Systemd unit: sp-yt-cookie-refresh.timer (runs every 6h)

Usage:
    python3 refresh-yt-cookies.py          # Normal run
    python3 refresh-yt-cookies.py --test   # Verify cookies work with yt-dlp
"""

import sys
import time
import argparse
import subprocess
import http.client
from pathlib import Path
from datetime import datetime, timezone

COOKIES_PATH = Path(__file__).parent / "cookies.txt"
TEST_URL = "https://www.youtube.com/shorts/ARIy9GQw0ws"
LOG_PREFIX = "[cookie-refresh]"


def log(msg):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"{LOG_PREFIX} {ts} {msg}", flush=True)


def network_available():
    """Quick pre-check before launching the browser (avoids 60s hang on dead net)."""
    try:
        conn = http.client.HTTPSConnection("1.1.1.1", timeout=5)
        conn.request("HEAD", "/")
        conn.getresponse()
        return True
    except Exception:
        return False


def write_netscape_cookies(cookies: list[dict], path: Path):
    """
    Write cookies in Netscape/Mozilla format that yt-dlp accepts.
    Format per line:
        domain  include_subdomains  path  secure  expiry  name  value
    """
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by refresh-yt-cookies.py (camoufox)",
        "# https://curl.haxx.se/docs/http-cookies.html",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", ".youtube.com")
        # Netscape format requires leading dot for domain cookies
        if not domain.startswith("."):
            domain = "." + domain
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path_val = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = int(c.get("expires", 0))
        if expiry <= 0:
            # Session cookie — give it 30 days
            expiry = int(time.time()) + 30 * 86400
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{include_sub}\t{path_val}\t{secure}\t{expiry}\t{name}\t{value}")

    path.write_text("\n".join(lines) + "\n")
    log(f"Wrote {len(cookies)} cookies → {path}")


def harvest_cookies(retries: int = 3) -> list[dict]:
    """
    Launch camoufox (stealth Firefox) headlessly, visit YouTube,
    wait for cookies to settle, and return all cookies for *.youtube.com.
    """
    # Import here so the script fails gracefully if camoufox not installed
    try:
        from camoufox.sync_api import Camoufox
    except ImportError:
        log("FATAL: camoufox not installed. Run: pip3 install camoufox && python3 -m camoufox fetch")
        sys.exit(1)

    for attempt in range(1, retries + 1):
        log(f"Launching camoufox (attempt {attempt}/{retries}) ...")
        try:
            with Camoufox(headless=True, geoip=True) as browser:
                context = browser.new_context()
                page = context.new_page()

                # Visit YouTube homepage — triggers cookie issuance
                log("Navigating to youtube.com ...")
                page.goto("https://www.youtube.com", wait_until="networkidle", timeout=30_000)
                time.sleep(3)  # Let cookie-setting JS settle

                # Also hit the Shorts landing page (triggers Shorts-specific cookies)
                log("Navigating to YouTube Shorts ...")
                page.goto("https://www.youtube.com/shorts/", wait_until="domcontentloaded", timeout=20_000)
                time.sleep(2)

                # Collect all cookies for youtube.com and google.com (required for auth)
                all_cookies = context.cookies(["https://www.youtube.com", "https://www.google.com"])
                context.close()

            log(f"Harvested {len(all_cookies)} cookies successfully")
            return all_cookies

        except Exception as e:
            log(f"Attempt {attempt} failed: {e}")
            if attempt < retries:
                time.sleep(5 * attempt)

    log("FATAL: All cookie-harvest attempts failed")
    sys.exit(1)


def test_cookies(cookies_path: Path) -> bool:
    """Run yt-dlp with the harvested cookies against a test Short to verify they work."""
    log(f"Testing cookies against {TEST_URL} ...")
    result = subprocess.run(
        [
            "yt-dlp",
            "--cookies", str(cookies_path),
            "--list-formats",
            "--no-warnings",
            "--quiet",
            TEST_URL,
        ],
        capture_output=True,
        text=True,
        timeout=30,
    )
    if result.returncode == 0:
        log("✓ Cookie test PASSED — yt-dlp can access YouTube Shorts")
        return True
    else:
        stderr_tail = result.stderr.strip()[-300:]
        log(f"✗ Cookie test FAILED: {stderr_tail}")
        return False


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--test", action="store_true", help="Also verify cookies with yt-dlp after harvesting")
    parser.add_argument("--test-only", action="store_true", help="Only test existing cookies, do not re-harvest")
    args = parser.parse_args()

    log("=== YouTube Cookie Refresh (camoufox) ===")

    if args.test_only:
        if not COOKIES_PATH.exists():
            log("ERROR: No cookies.txt found. Run without --test-only first.")
            sys.exit(1)
        ok = test_cookies(COOKIES_PATH)
        sys.exit(0 if ok else 1)

    # Pre-flight network check
    if not network_available():
        log("FATAL: Network unavailable. Aborting.")
        sys.exit(1)
    log("Network OK")

    # Harvest
    cookies = harvest_cookies()
    write_netscape_cookies(cookies, COOKIES_PATH)
    COOKIES_PATH.chmod(0o600)  # Service-role equivalent — cookie is sensitive

    # Optional verification
    if args.test:
        ok = test_cookies(COOKIES_PATH)
        if not ok:
            log("WARNING: Cookies harvested but test failed. YouTube may require account login.")
            # Don't exit 1 — cookies may still work for non-Shorts URLs
        else:
            log("✓ All done. Worker will use fresh cookies on next job.")

    log("=== Cookie refresh complete ===")


if __name__ == "__main__":
    main()
