#!/usr/bin/env python3
"""
refresh-yt-cookies.py — Automated YouTube cookie harvester for yt-dlp
Smarter Poker | Operation TikTok Reels M1b

Uses camoufox (stealth Firefox) to visit youtube.com and collect
session cookies, then writes them in Netscape format so yt-dlp can
bypass YouTube's bot-detection on headless datacenter IPs.

Run location: /opt/smarter-poker/yt-transcode-worker/
Output:       /opt/smarter-poker/yt-transcode-worker/cookies.txt
Systemd unit: sp-yt-cookie-refresh.timer (runs every 6h)
"""

import sys
import time
import asyncio
import argparse
import subprocess
import http.client
from pathlib import Path
from datetime import datetime, timezone

COOKIES_PATH = Path(__file__).parent / "cookies.txt"
TEST_URL = "https://www.youtube.com/shorts/ARIy9GQw0ws"
LOG_PREFIX = "[cookie-refresh]"


def log(msg):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"{LOG_PREFIX} {ts} {msg}", flush=True)


def network_available():
    try:
        conn = http.client.HTTPSConnection("1.1.1.1", timeout=5)
        conn.request("HEAD", "/")
        conn.getresponse()
        return True
    except Exception:
        return False


def write_netscape_cookies(cookies: list, path: Path):
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by refresh-yt-cookies.py (camoufox)",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", ".youtube.com")
        if not domain.startswith("."):
            domain = "." + domain
        include_sub = "TRUE"
        path_val = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = int(c.get("expires", 0) or 0)
        if expiry <= 0:
            expiry = int(time.time()) + 30 * 86400
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{include_sub}\t{path_val}\t{secure}\t{expiry}\t{name}\t{value}")

    path.write_text("\n".join(lines) + "\n")
    log(f"Wrote {len(cookies)} cookies → {path}")


async def harvest_cookies_async() -> list:
    """Async camoufox session — avoids Playwright sync-in-asyncio-loop error."""
    try:
        from camoufox.async_api import AsyncCamoufox
    except ImportError:
        log("FATAL: camoufox not installed. Run: pip3 install camoufox")
        sys.exit(1)

    log("Launching camoufox (async, headless) ...")
    # geoip=False avoids the GeoLite2 download requirement
    async with AsyncCamoufox(headless=True, geoip=False) as browser:
        context = await browser.new_context()
        page = await context.new_page()

        log("Navigating to youtube.com ...")
        await page.goto("https://www.youtube.com", wait_until="networkidle", timeout=30_000)
        await asyncio.sleep(3)

        log("Navigating to YouTube Shorts ...")
        await page.goto("https://www.youtube.com/shorts/", wait_until="domcontentloaded", timeout=20_000)
        await asyncio.sleep(2)

        all_cookies = await context.cookies(["https://www.youtube.com", "https://www.google.com"])
        await context.close()

    log(f"Harvested {len(all_cookies)} cookies")
    return all_cookies


def harvest_cookies(retries: int = 3) -> list:
    for attempt in range(1, retries + 1):
        log(f"Cookie harvest attempt {attempt}/{retries} ...")
        try:
            return asyncio.run(harvest_cookies_async())
        except Exception as e:
            log(f"Attempt {attempt} failed: {e}")
            if attempt < retries:
                time.sleep(5 * attempt)
    log("FATAL: All cookie-harvest attempts failed")
    sys.exit(1)


def test_cookies(cookies_path: Path) -> bool:
    log(f"Testing cookies against {TEST_URL} ...")
    result = subprocess.run(
        ["yt-dlp", "--cookies", str(cookies_path), "--list-formats", "--no-warnings", "--quiet", TEST_URL],
        capture_output=True, text=True, timeout=30,
    )
    if result.returncode == 0:
        log("✓ Cookie test PASSED — yt-dlp can access YouTube Shorts")
        return True
    stderr_tail = (result.stderr or "").strip()[-300:]
    log(f"✗ Cookie test FAILED: {stderr_tail}")
    return False


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--test", action="store_true", help="Verify cookies with yt-dlp after harvesting")
    parser.add_argument("--test-only", action="store_true", help="Only test existing cookies")
    args = parser.parse_args()

    log("=== YouTube Cookie Refresh (camoufox) ===")

    if args.test_only:
        if not COOKIES_PATH.exists():
            log("ERROR: No cookies.txt found.")
            sys.exit(1)
        sys.exit(0 if test_cookies(COOKIES_PATH) else 1)

    if not network_available():
        log("FATAL: Network unavailable.")
        sys.exit(1)
    log("Network OK")

    cookies = harvest_cookies()
    write_netscape_cookies(cookies, COOKIES_PATH)
    COOKIES_PATH.chmod(0o600)

    if args.test:
        test_cookies(COOKIES_PATH)

    log("=== Cookie refresh complete ===")


if __name__ == "__main__":
    main()
