-- Seed data for memory_charts_gold table
-- 5 sample preflop range charts for testing

-- BTN Open (most common, Level 1)
INSERT INTO memory_charts_gold (chart_name, category, position, stack_depth, chart_grid) VALUES
('BTN Open 100bb', 'Preflop', 'BTN', 100, '{
  "AA": {"action": "Raise", "freq": 100},
  "KK": {"action": "Raise", "freq": 100},
  "QQ": {"action": "Raise", "freq": 100},
  "JJ": {"action": "Raise", "freq": 100},
  "TT": {"action": "Raise", "freq": 100},
  "99": {"action": "Raise", "freq": 100},
  "88": {"action": "Raise", "freq": 100},
  "77": {"action": "Raise", "freq": 100},
  "66": {"action": "Raise", "freq": 100},
  "55": {"action": "Raise", "freq": 100},
  "44": {"action": "Raise", "freq": 100},
  "33": {"action": "Raise", "freq": 100},
  "22": {"action": "Raise", "freq": 100},
  "AKs": {"action": "Raise", "freq": 100},
  "AQs": {"action": "Raise", "freq": 100},
  "AJs": {"action": "Raise", "freq": 100},
  "ATs": {"action": "Raise", "freq": 100},
  "A9s": {"action": "Raise", "freq": 100},
  "A8s": {"action": "Raise", "freq": 100},
  "A7s": {"action": "Raise", "freq": 100},
  "A6s": {"action": "Raise", "freq": 100},
  "A5s": {"action": "Raise", "freq": 100},
  "A4s": {"action": "Raise", "freq": 100},
  "A3s": {"action": "Raise", "freq": 100},
  "A2s": {"action": "Raise", "freq": 100},
  "AKo": {"action": "Raise", "freq": 100},
  "AQo": {"action": "Raise", "freq": 100},
  "AJo": {"action": "Raise", "freq": 100},
  "ATo": {"action": "Raise", "freq": 100},
  "A9o": {"action": "Raise", "freq": 100},
  "A8o": {"action": "Raise", "freq": 100},
  "KQs": {"action": "Raise", "freq": 100},
  "KJs": {"action": "Raise", "freq": 100},
  "KTs": {"action": "Raise", "freq": 100},
  "K9s": {"action": "Raise", "freq": 100},
  "K8s": {"action": "Raise", "freq": 100},
  "KQo": {"action": "Raise", "freq": 100},
  "KJo": {"action": "Raise", "freq": 100},
  "KTo": {"action": "Raise", "freq": 100},
  "QJs": {"action": "Raise", "freq": 100},
  "QTs": {"action": "Raise", "freq": 100},
  "Q9s": {"action": "Raise", "freq": 100},
  "QJo": {"action": "Raise", "freq": 100},
  "QTo": {"action": "Raise", "freq": 100},
  "JTs": {"action": "Raise", "freq": 100},
  "J9s": {"action": "Raise", "freq": 100},
  "JTo": {"action": "Raise", "freq": 100},
  "T9s": {"action": "Raise", "freq": 100},
  "T8s": {"action": "Raise", "freq": 100},
  "98s": {"action": "Raise", "freq": 100},
  "87s": {"action": "Raise", "freq": 100},
  "76s": {"action": "Raise", "freq": 100},
  "65s": {"action": "Raise", "freq": 100},
  "54s": {"action": "Raise", "freq": 100}
}'::jsonb);

-- CO Open (Level 2)
INSERT INTO memory_charts_gold (chart_name, category, position, stack_depth, chart_grid) VALUES
('CO Open 100bb', 'Preflop', 'CO', 100, '{
  "AA": {"action": "Raise", "freq": 100},
  "KK": {"action": "Raise", "freq": 100},
  "QQ": {"action": "Raise", "freq": 100},
  "JJ": {"action": "Raise", "freq": 100},
  "TT": {"action": "Raise", "freq": 100},
  "99": {"action": "Raise", "freq": 100},
  "88": {"action": "Raise", "freq": 100},
  "77": {"action": "Raise", "freq": 100},
  "66": {"action": "Raise", "freq": 100},
  "55": {"action": "Raise", "freq": 100},
  "44": {"action": "Raise", "freq": 100},
  "33": {"action": "Raise", "freq": 100},
  "22": {"action": "Raise", "freq": 100},
  "AKs": {"action": "Raise", "freq": 100},
  "AQs": {"action": "Raise", "freq": 100},
  "AJs": {"action": "Raise", "freq": 100},
  "ATs": {"action": "Raise", "freq": 100},
  "A9s": {"action": "Raise", "freq": 100},
  "A8s": {"action": "Raise", "freq": 100},
  "A7s": {"action": "Raise", "freq": 100},
  "A5s": {"action": "Raise", "freq": 100},
  "A4s": {"action": "Raise", "freq": 100},
  "AKo": {"action": "Raise", "freq": 100},
  "AQo": {"action": "Raise", "freq": 100},
  "AJo": {"action": "Raise", "freq": 100},
  "ATo": {"action": "Raise", "freq": 100},
  "KQs": {"action": "Raise", "freq": 100},
  "KJs": {"action": "Raise", "freq": 100},
  "KTs": {"action": "Raise", "freq": 100},
  "K9s": {"action": "Raise", "freq": 100},
  "KQo": {"action": "Raise", "freq": 100},
  "KJo": {"action": "Raise", "freq": 100},
  "QJs": {"action": "Raise", "freq": 100},
  "QTs": {"action": "Raise", "freq": 100},
  "QJo": {"action": "Raise", "freq": 100},
  "JTs": {"action": "Raise", "freq": 100},
  "J9s": {"action": "Raise", "freq": 100},
  "T9s": {"action": "Raise", "freq": 100},
  "98s": {"action": "Raise", "freq": 100},
  "87s": {"action": "Raise", "freq": 100},
  "76s": {"action": "Raise", "freq": 100}
}'::jsonb);

-- MP Open (Level 3)
INSERT INTO memory_charts_gold (chart_name, category, position, stack_depth, chart_grid) VALUES
('MP Open 100bb', 'Preflop', 'MP', 100, '{
  "AA": {"action": "Raise", "freq": 100},
  "KK": {"action": "Raise", "freq": 100},
  "QQ": {"action": "Raise", "freq": 100},
  "JJ": {"action": "Raise", "freq": 100},
  "TT": {"action": "Raise", "freq": 100},
  "99": {"action": "Raise", "freq": 100},
  "88": {"action": "Raise", "freq": 100},
  "77": {"action": "Raise", "freq": 100},
  "66": {"action": "Raise", "freq": 100},
  "AKs": {"action": "Raise", "freq": 100},
  "AQs": {"action": "Raise", "freq": 100},
  "AJs": {"action": "Raise", "freq": 100},
  "ATs": {"action": "Raise", "freq": 100},
  "A9s": {"action": "Raise", "freq": 100},
  "A5s": {"action": "Raise", "freq": 100},
  "AKo": {"action": "Raise", "freq": 100},
  "AQo": {"action": "Raise", "freq": 100},
  "AJo": {"action": "Raise", "freq": 100},
  "KQs": {"action": "Raise", "freq": 100},
  "KJs": {"action": "Raise", "freq": 100},
  "KTs": {"action": "Raise", "freq": 100},
  "KQo": {"action": "Raise", "freq": 100},
  "QJs": {"action": "Raise", "freq": 100},
  "QTs": {"action": "Raise", "freq": 100},
  "JTs": {"action": "Raise", "freq": 100},
  "T9s": {"action": "Raise", "freq": 100},
  "98s": {"action": "Raise", "freq": 100}
}'::jsonb);

-- UTG Open (Level 4 - tightest)
INSERT INTO memory_charts_gold (chart_name, category, position, stack_depth, chart_grid) VALUES
('UTG Open 100bb', 'Preflop', 'UTG', 100, '{
  "AA": {"action": "Raise", "freq": 100},
  "KK": {"action": "Raise", "freq": 100},
  "QQ": {"action": "Raise", "freq": 100},
  "JJ": {"action": "Raise", "freq": 100},
  "TT": {"action": "Raise", "freq": 100},
  "99": {"action": "Raise", "freq": 100},
  "88": {"action": "Raise", "freq": 100},
  "77": {"action": "Raise", "freq": 100},
  "AKs": {"action": "Raise", "freq": 100},
  "AQs": {"action": "Raise", "freq": 100},
  "AJs": {"action": "Raise", "freq": 100},
  "ATs": {"action": "Raise", "freq": 100},
  "AKo": {"action": "Raise", "freq": 100},
  "AQo": {"action": "Raise", "freq": 100},
  "KQs": {"action": "Raise", "freq": 100},
  "KJs": {"action": "Raise", "freq": 100},
  "KQo": {"action": "Raise", "freq": 100},
  "QJs": {"action": "Raise", "freq": 100},
  "JTs": {"action": "Raise", "freq": 100}
}'::jsonb);

-- BB vs BTN 3-Bet (Level 5 - advanced)
INSERT INTO memory_charts_gold (chart_name, category, position, stack_depth, topology, chart_grid) VALUES
('BB vs BTN 3bet 100bb', 'Preflop', 'BB', 100, 'vs_BTN_Open', '{
  "AA": {"action": "Raise", "freq": 100},
  "KK": {"action": "Raise", "freq": 100},
  "QQ": {"action": "Raise", "freq": 100},
  "JJ": {"action": "Raise", "freq": 100},
  "TT": {"action": "Raise", "freq": 70},
  "99": {"action": "Raise", "freq": 40},
  "AKs": {"action": "Raise", "freq": 100},
  "AQs": {"action": "Raise", "freq": 100},
  "AJs": {"action": "Raise", "freq": 80},
  "ATs": {"action": "Raise", "freq": 50},
  "A5s": {"action": "Raise", "freq": 100},
  "A4s": {"action": "Raise", "freq": 80},
  "AKo": {"action": "Raise", "freq": 100},
  "AQo": {"action": "Raise", "freq": 70},
  "KQs": {"action": "Raise", "freq": 60},
  "K9s": {"action": "Raise", "freq": 40},
  "87s": {"action": "Raise", "freq": 30},
  "76s": {"action": "Raise", "freq": 30},
  "65s": {"action": "Raise", "freq": 30},
  "54s": {"action": "Raise", "freq": 30}
}'::jsonb);

-- Verify insertion
SELECT id, chart_name, category, position, stack_depth FROM memory_charts_gold ORDER BY stack_depth DESC, position;
