import SEOHead from '../../../../src/components/seo/SEOHead';
import UniversalHeader from '../../../../src/components/ui/UniversalHeader';
import BottomNavBar from '../../../../src/components/ui/BottomNavBar';
import { getMlbSupabase } from '../../../../utils/supabase/mlb';
import Link from 'next/link';
import { useRouter } from 'next/router';

export async function getServerSideProps({ params }) {
    try {
        const mlbDb = getMlbSupabase();
        
        // Fetch specific game stats
        const { data: game, error } = await mlbDb
            .from('fact_games')
            .select('*')
            .eq('game_pk', params.game_pk)
            .maybeSingle();
            
        return {
            props: {
                game: game || null,
                error: error ? error.message : null
            }
        };
    } catch (err) {
        return { props: { game: null, error: err.message } };
    }
}

export default function MlbGameDeepDive({ game, error }) {
    const router = useRouter();
    const { game_pk } = router.query;

    return (
        <div style={{ minHeight: '100vh', background: '#0a0a0f', color: '#fff', paddingBottom: 80 }}>
            <SEOHead title={`Game ${game_pk} | MLB Engine`} />
            <UniversalHeader title="Game Deep Dive" />
            
            <main style={{ padding: '20px', maxWidth: '1200px', margin: '0 auto', paddingTop: 80 }}>
                <Link href="/hub/mlb-analytics" style={{ color: '#00d4ff', textDecoration: 'none', display: 'inline-block', marginBottom: 20, fontFamily: 'Orbitron, sans-serif' }}>
                    &larr; Back to Slate
                </Link>

                {error && (
                    <div style={{ background: 'rgba(255,0,0,0.1)', border: '1px solid red', padding: 15, borderRadius: 8, color: '#ff6b6b', marginBottom: 20 }}>
                        Warning: {error}
                    </div>
                )}

                {!game ? (
                    <div style={{ background: 'rgba(255,255,255,0.05)', padding: 40, borderRadius: 12, textAlign: 'center', color: 'rgba(255,255,255,0.5)' }}>
                        Game not found in fact_games table.
                    </div>
                ) : (
                    <div>
                        <h1 style={{ fontFamily: 'Orbitron, sans-serif', color: '#fff', fontSize: 24, margin: '0 0 5px 0' }}>
                            {game.away_team} @ {game.home_team}
                        </h1>
                        <div style={{ color: 'rgba(255,255,255,0.5)', marginBottom: 20 }}>
                            {game.game_date} | Park: {game.venue_name || 'TBD'}
                        </div>

                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, marginBottom: 20 }}>
                            <div style={{ background: 'rgba(255,255,255,0.05)', borderRadius: 12, padding: 20, border: '1px solid rgba(255,255,255,0.1)' }}>
                                <h3 style={{ color: '#00d4ff', margin: '0 0 10px 0', fontFamily: 'Orbitron, sans-serif' }}>Model Edge</h3>
                                <div style={{ fontSize: 32, fontWeight: 'bold' }}>
                                    {game.model_edge ? (game.model_edge * 100).toFixed(1) + '%' : 'N/A'}
                                </div>
                            </div>
                            <div style={{ background: 'rgba(255,255,255,0.05)', borderRadius: 12, padding: 20, border: '1px solid rgba(255,255,255,0.1)' }}>
                                <h3 style={{ color: '#00d4ff', margin: '0 0 10px 0', fontFamily: 'Orbitron, sans-serif' }}>Projected Runs</h3>
                                <div style={{ fontSize: 32, fontWeight: 'bold' }}>
                                    {game.projected_total || 'N/A'}
                                </div>
                            </div>
                        </div>

                        {/* Placeholder for the large analytic tables generated by the background engine */}
                        <div style={{ background: 'rgba(255,255,255,0.05)', borderRadius: 12, padding: 40, border: '1px solid rgba(255,255,255,0.1)', textAlign: 'center', color: 'rgba(255,255,255,0.4)' }}>
                            Full analytical package (Lineup vs Pitcher matrix, Bullpen board, Umpire profile) will render here.
                            <br/><br/>
                            <button style={{
                                background: '#1877f2',
                                border: 'none',
                                color: '#fff',
                                padding: '10px 20px',
                                borderRadius: 20,
                                cursor: 'pointer',
                                fontFamily: 'inherit',
                                marginTop: 10
                            }}>
                                Download Raw JSON Package
                            </button>
                        </div>
                    </div>
                )}
            </main>
            <BottomNavBar />
        </div>
    );
}
