/* ═══════════════════════════════════════════════════════════════════════════
   EXPORT CONVERSATION — Export Jarvis conversations as PDF or share
   ═══════════════════════════════════════════════════════════════════════════ */

import React, { useState } from 'react';

interface Message {
    id: string;
    content: string;
    isUser: boolean;
    timestamp: Date;
}

interface ExportConversationProps {
    messages: Message[];
    onClose?: () => void;
}

export function ExportConversation({ messages, onClose }: ExportConversationProps) {
    const [copying, setCopying] = useState(false);
    const [copied, setCopied] = useState(false);

    const formatAsText = () => {
        let text = '🎩 GEEVES POKER ANALYSIS\n';
        text += '='.repeat(40) + '\n\n';

        messages.forEach(msg => {
            const time = msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
            const speaker = msg.isUser ? '👤 You' : '🎩 Jarvis';
            text += `[${time}] ${speaker}:\n${msg.content}\n\n`;
        });

        text += '='.repeat(40) + '\n';
        text += 'Generated by Jarvis @ smarter.poker\n';
        return text;
    };

    const formatAsMarkdown = () => {
        let md = '# 🎩 Jarvis Poker Analysis\n\n';
        md += `*Generated: ${new Date().toLocaleString()}*\n\n---\n\n`;

        messages.forEach(msg => {
            const speaker = msg.isUser ? '**You**' : '**Jarvis** 🎩';
            md += `### ${speaker}\n\n${msg.content}\n\n`;
        });

        md += '---\n\n*Generated by [Jarvis](https://smarter.poker) - Your Poker Strategy Expert*\n';
        return md;
    };

    const copyToClipboard = async (format: 'text' | 'markdown') => {
        setCopying(true);
        try {
            const content = format === 'text' ? formatAsText() : formatAsMarkdown();
            await navigator.clipboard.writeText(content);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (error) {
            console.warn('[Export] Copy failed:', error);
        } finally {
            setCopying(false);
        }
    };

    const downloadAsFile = (format: 'txt' | 'md') => {
        const content = format === 'txt' ? formatAsText() : formatAsMarkdown();
        const filename = `jarvis-analysis-${new Date().toISOString().split('T')[0]}.${format}`;

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    };

    const shareToTwitter = () => {
        // Create a summary of the conversation
        const lastJarvisMsg = [...messages].reverse().find(m => !m.isUser);
        const summary = lastJarvisMsg
            ? lastJarvisMsg.content.substring(0, 200) + '...'
            : 'Check out this poker analysis!';

        const text = encodeURIComponent(`🎩 Jarvis says:\n\n"${summary}"\n\n#poker #pokerstrategy via @smarterpoker`);
        window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank');
    };

    return (
        <div style={{
            background: 'rgba(20, 10, 40, 0.98)',
            border: '1px solid rgba(255, 215, 0, 0.3)',
            borderRadius: '12px',
            padding: '16px',
            maxWidth: '320px',
            boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)'
        }}>
            {/* Header */}
            <div style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: '12px'
            }}>
                <h4 style={{
                    margin: 0,
                    color: '#FFD700',
                    fontSize: '14px',
                    fontWeight: 600
                }}>
                    📤 Export Conversation
                </h4>
                {onClose && (
                    <button
                        onClick={onClose}
                        style={{
                            background: 'none',
                            border: 'none',
                            color: 'rgba(255, 215, 0, 0.6)',
                            fontSize: '18px',
                            cursor: 'pointer'
                        }}
                    >
                        ×
                    </button>
                )}
            </div>

            {/* Stats */}
            <div style={{
                padding: '8px 12px',
                background: 'rgba(255, 215, 0, 0.1)',
                borderRadius: '6px',
                marginBottom: '12px',
                fontSize: '11px',
                color: 'rgba(255, 255, 255, 0.7)'
            }}>
                {messages.length} messages • {messages.filter(m => m.isUser).length} questions
            </div>

            {/* Copy Options */}
            <div style={{ marginBottom: '12px' }}>
                <p style={{
                    margin: '0 0 8px 0',
                    fontSize: '11px',
                    color: 'rgba(255, 215, 0, 0.7)'
                }}>
                    Copy to clipboard:
                </p>
                <div style={{ display: 'flex', gap: '8px' }}>
                    <button
                        onClick={() => copyToClipboard('text')}
                        style={{
                            flex: 1,
                            padding: '8px',
                            background: 'rgba(255, 215, 0, 0.1)',
                            border: '1px solid rgba(255, 215, 0, 0.3)',
                            borderRadius: '6px',
                            color: '#FFD700',
                            fontSize: '11px',
                            cursor: 'pointer'
                        }}
                    >
                        📄 Plain Text
                    </button>
                    <button
                        onClick={() => copyToClipboard('markdown')}
                        style={{
                            flex: 1,
                            padding: '8px',
                            background: 'rgba(255, 215, 0, 0.1)',
                            border: '1px solid rgba(255, 215, 0, 0.3)',
                            borderRadius: '6px',
                            color: '#FFD700',
                            fontSize: '11px',
                            cursor: 'pointer'
                        }}
                    >
                        📝 Markdown
                    </button>
                </div>
                {copied && (
                    <p style={{
                        margin: '8px 0 0 0',
                        fontSize: '11px',
                        color: '#4CAF50',
                        textAlign: 'center'
                    }}>
                        ✓ Copied to clipboard!
                    </p>
                )}
            </div>

            {/* Download Options */}
            <div style={{ marginBottom: '12px' }}>
                <p style={{
                    margin: '0 0 8px 0',
                    fontSize: '11px',
                    color: 'rgba(255, 215, 0, 0.7)'
                }}>
                    Download as file:
                </p>
                <div style={{ display: 'flex', gap: '8px' }}>
                    <button
                        onClick={() => downloadAsFile('txt')}
                        style={{
                            flex: 1,
                            padding: '8px',
                            background: 'rgba(255, 215, 0, 0.1)',
                            border: '1px solid rgba(255, 215, 0, 0.3)',
                            borderRadius: '6px',
                            color: '#FFD700',
                            fontSize: '11px',
                            cursor: 'pointer'
                        }}
                    >
                        ⬇️ .txt
                    </button>
                    <button
                        onClick={() => downloadAsFile('md')}
                        style={{
                            flex: 1,
                            padding: '8px',
                            background: 'rgba(255, 215, 0, 0.1)',
                            border: '1px solid rgba(255, 215, 0, 0.3)',
                            borderRadius: '6px',
                            color: '#FFD700',
                            fontSize: '11px',
                            cursor: 'pointer'
                        }}
                    >
                        ⬇️ .md
                    </button>
                </div>
            </div>

            {/* Share */}
            <div>
                <p style={{
                    margin: '0 0 8px 0',
                    fontSize: '11px',
                    color: 'rgba(255, 215, 0, 0.7)'
                }}>
                    Share:
                </p>
                <button
                    onClick={shareToTwitter}
                    style={{
                        width: '100%',
                        padding: '10px',
                        background: 'linear-gradient(135deg, #1DA1F2, #0d8bd9)',
                        border: 'none',
                        borderRadius: '6px',
                        color: '#fff',
                        fontSize: '12px',
                        fontWeight: 600,
                        cursor: 'pointer',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        gap: '6px'
                    }}
                >
                    🐦 Share on Twitter
                </button>
            </div>
        </div>
    );
}
