-- ═══════════════════════════════════════════════════════════════════════════
-- PERFORMANCE MIGRATION: Indexes + Atomic Counter RPCs
-- Generated by optimization audit — Phase 4
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Atomic counter RPCs ───────────────────────────────────────────────────
-- Replaces read-then-update N+1 patterns for likes/comments/shares

CREATE OR REPLACE FUNCTION increment_post_count(p_post_id UUID, p_field TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF p_field = 'like_count' THEN
    UPDATE social_posts SET like_count = like_count + 1 WHERE id = p_post_id;
  ELSIF p_field = 'comment_count' THEN
    UPDATE social_posts SET comment_count = comment_count + 1 WHERE id = p_post_id;
  ELSIF p_field = 'share_count' THEN
    UPDATE social_posts SET share_count = share_count + 1 WHERE id = p_post_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION decrement_post_count(p_post_id UUID, p_field TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF p_field = 'like_count' THEN
    UPDATE social_posts SET like_count = GREATEST(like_count - 1, 0) WHERE id = p_post_id;
  ELSIF p_field = 'comment_count' THEN
    UPDATE social_posts SET comment_count = GREATEST(comment_count - 1, 0) WHERE id = p_post_id;
  ELSIF p_field = 'share_count' THEN
    UPDATE social_posts SET share_count = GREATEST(share_count - 1, 0) WHERE id = p_post_id;
  END IF;
END;
$$;

-- ── social_posts indexes ──────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_social_posts_user_id
  ON social_posts(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_posts_created_at
  ON social_posts(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_posts_club_page
  ON social_posts(club_page_id, created_at DESC)
  WHERE club_page_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_social_posts_post_type
  ON social_posts(post_type, created_at DESC)
  WHERE post_type IS NOT NULL;

-- ── social_interactions indexes ───────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_social_interactions_post_user
  ON social_interactions(post_id, user_id, interaction_type);

CREATE INDEX IF NOT EXISTS idx_social_interactions_user
  ON social_interactions(user_id, created_at DESC);

-- ── social_comments indexes ───────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_social_comments_post_id
  ON social_comments(post_id, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_social_comments_user_id
  ON social_comments(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_comments_parent
  ON social_comments(parent_id)
  WHERE parent_id IS NOT NULL;

-- ── profiles indexes ──────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_profiles_username
  ON profiles(username)
  WHERE username IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_profiles_updated_at
  ON profiles(updated_at DESC);

-- ── notifications indexes ─────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
  ON notifications(user_id, is_read, created_at DESC)
  WHERE is_read = false;

CREATE INDEX IF NOT EXISTS idx_notifications_user_all
  ON notifications(user_id, created_at DESC);

-- ── commander_sessions indexes ────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_commander_sessions_venue_date
  ON commander_sessions(venue_id, session_date DESC);

CREATE INDEX IF NOT EXISTS idx_commander_sessions_active
  ON commander_sessions(venue_id, is_active)
  WHERE is_active = true;

-- ── club_arena indexes ────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_club_memberships_user
  ON club_memberships(user_id, status);

CREATE INDEX IF NOT EXISTS idx_club_memberships_club
  ON club_memberships(club_id, status);

CREATE INDEX IF NOT EXISTS idx_chip_transactions_user
  ON chip_transactions(user_id, created_at DESC)
  WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_chip_transactions_club
  ON chip_transactions(club_id, created_at DESC);

-- ── bankroll indexes ──────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_bankroll_sessions_user
  ON bankroll_sessions(user_id, played_at DESC);

CREATE INDEX IF NOT EXISTS idx_bankroll_sessions_user_year
  ON bankroll_sessions(user_id, EXTRACT(YEAR FROM played_at));

-- ── stories indexes ───────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_stories_user_active
  ON stories(user_id, expires_at)
  WHERE expires_at > NOW();

CREATE INDEX IF NOT EXISTS idx_stories_expires
  ON stories(expires_at)
  WHERE expires_at IS NOT NULL;

