/**
 * READING A PDF, WHICH IS HOW A CASINO ACTUALLY SENDS A W-2G.
 *
 * Until 2026-09-09 DealerVault sent images to the reader and PDFs nowhere at
 * all: handleFileSelect routed anything non-image straight to the upload form
 * and analyzeDocument never ran. The file uploaded, it stored, and every
 * field on it was typed in by hand. Casinos email W-2Gs as PDFs. It is the
 * single most common way a player receives one.
 *
 * TEXT FIRST, PIXELS ONLY IF WE MUST. A W-2G generated by a payer's system is
 * a TEXT pdf: the numbers are in the file, exactly, and pdf.js hands them over
 * with no recognition step and therefore no recognition errors. Running OCR
 * over a rendering of text we already have would be slower and strictly worse.
 * A scanned or photographed PDF has no text layer, and that one gets
 * rasterised and read by the same engine everything else uses.
 *
 * SAME ORIGIN, STILL. pdf.js defaults its worker to a CDN exactly as
 * tesseract.js does. scripts/copy-pdfjs-assets.mjs copies the worker to
 * /pdfjs/<version>/, which vercel.json serves immutable, and the version in
 * the path is what makes that promise honest.
 *
 * The obvious webpack idiom does not work here and the build says so:
 * `new URL('pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url)` fails with
 * "ESM packages need to be imported", because webpack resolves only RELATIVE
 * paths inside new URL(), never a bare package specifier.
 *
 * pdf.js itself is still code-split behind a dynamic import, so a player who
 * never opens a PDF never downloads it.
 */

import { readText } from './ocr.mjs';

/** Below this many characters, page one is a picture and not a document. */
const MIN_TEXT_CHARS = 40;

/** Rendered wide enough for 8pt form print to survive, small enough for a phone. */
const RASTER_WIDTH = 1600;

/**
 * The worker version, in the URL, matching what the copy script writes.
 * __tests__/a-pdf-w2g-is-read.law.test.mjs fails the build if they drift: a
 * mismatch is a 404 for the worker and a vault that never reads a PDF again.
 */
export const PDFJS_VERSION = '4.10.38';
export const PDFJS_WORKER_URL = `/pdfjs/${PDFJS_VERSION}/pdf.worker.min.mjs`;

let pdfjsPromise = null;

async function getPdfjs() {
    if (pdfjsPromise) return pdfjsPromise;
    pdfjsPromise = (async () => {
        const pdfjs = await import('pdfjs-dist/build/pdf.min.mjs');
        // Our own origin. Never the CDN this library reaches for by default.
        // Constructed here rather than handed over as `workerSrc` so the
        // module type is explicit: the worker is an .mjs and a classic worker
        // would fail to parse its first import statement.
        pdfjs.GlobalWorkerOptions.workerPort = new Worker(PDFJS_WORKER_URL, { type: 'module' });
        return pdfjs;
    })();
    try {
        return await pdfjsPromise;
    } catch (err) {
        pdfjsPromise = null;
        throw err;
    }
}

export class PdfUnreadableError extends Error {
    constructor(cause) {
        super('pdf-unreadable');
        this.name = 'PdfUnreadableError';
        this.cause = cause;
    }
}

/** Page one's text layer, joined in reading order, or ''. */
function joinTextContent(content) {
    const items = Array.isArray(content && content.items) ? content.items : [];
    let out = '';
    let lastY = null;
    for (const item of items) {
        const str = typeof item.str === 'string' ? item.str : '';
        if (!str) continue;
        // transform[5] is the baseline y. A change means a new line, and the
        // parser reads line by line, so this is not cosmetic.
        const y = Array.isArray(item.transform) ? Math.round(item.transform[5]) : null;
        if (lastY !== null && y !== null && Math.abs(y - lastY) > 2) out += '\n';
        else if (out && !out.endsWith('\n')) out += ' ';
        out += str;
        if (y !== null) lastY = y;
        if (item.hasEOL) { out += '\n'; lastY = null; }
    }
    return out.replace(/[ \t]+\n/g, '\n').trim();
}

/**
 * Read the first page of a PDF.
 *
 * @param {Blob|File|ArrayBuffer|string} file
 * @param {object}   [options]
 * @param {function} [options.onProgress] 0-100, only while OCR is running
 * @returns {Promise<{text: string, confidence: number, source: 'text'|'ocr', pages: number}>}
 *
 * `source` is worth carrying: 'text' means the numbers came out of the file
 * exactly, and 'ocr' means they were recognised from pixels and can be wrong.
 */
export async function readPdf(file, options = {}) {
    if (typeof window === 'undefined') throw new PdfUnreadableError(new Error('no-browser'));

    let pdfjs;
    try {
        pdfjs = await getPdfjs();
    } catch (err) {
        throw new PdfUnreadableError(err);
    }

    let data;
    if (typeof file === 'string') data = file;
    else if (file instanceof ArrayBuffer) data = new Uint8Array(file);
    else data = new Uint8Array(await file.arrayBuffer());

    let doc;
    try {
        doc = await pdfjs.getDocument(typeof data === 'string' ? { url: data } : { data }).promise;
    } catch (err) {
        throw new PdfUnreadableError(err);
    }

    try {
        const page = await doc.getPage(1);

        const text = joinTextContent(await page.getTextContent());
        if (text.length >= MIN_TEXT_CHARS) {
            // Exact, not recognised. Nothing to be unsure about.
            return { text, confidence: 100, source: 'text', pages: doc.numPages };
        }

        // No usable text layer: a scan or a photograph inside a PDF wrapper.
        const base = page.getViewport({ scale: 1 });
        const scale = Math.min(4, Math.max(1, RASTER_WIDTH / base.width));
        const viewport = page.getViewport({ scale });
        const canvas = document.createElement('canvas');
        canvas.width = Math.round(viewport.width);
        canvas.height = Math.round(viewport.height);
        const ctx = canvas.getContext('2d');
        // Forms are black on white. Painting the page white first stops a
        // transparent background rendering as black and hiding every letter.
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        await page.render({ canvasContext: ctx, viewport }).promise;

        const read = await readText(canvas, { onProgress: options.onProgress });
        canvas.width = 0;
        canvas.height = 0;
        return { text: read.text, confidence: read.confidence, source: 'ocr', pages: doc.numPages };
    } finally {
        try { await doc.destroy(); } catch (_err) { /* a destroyed document is the goal */ }
    }
}

/** Does this look like a PDF, by type or by name? */
export function isPdf(file) {
    if (!file) return false;
    const type = String(file.type || '').toLowerCase();
    if (type === 'application/pdf') return true;
    return /\.pdf$/i.test(String(file.name || ''));
}
