/* Club Arena, Bankroll, Toke Tracker, Poker Near Me Knowledge */
export const CLUB_ARENA_ENTRIES = [
    { id: 'ca-1', category: 'Club Arena', keywords: ['club arena', 'online poker', 'poker club', 'join club', 'play online', 'club games'], patterns: ['what is club arena', 'how do i join a club', 'how to play online poker', 'how does club arena work'], answer: '**Club Arena** is the online poker room ecosystem within Smarter.Poker.\n\n**Features:**\n- **Lobby** — Browse available clubs and games\n- **Club Games** — Join cash games and tournaments at your club\n- **Hand Histories** — Review every hand you have played\n- **Leaderboard** — Club-wide rankings\n- **Players** — See who is online and playing\n- **Player Stats** — Detailed performance analytics\n- **Cashier** — Manage your club chip balance\n- **Messages** — In-club communication\n- **Marketplace** — Club merchandise and items\n- **Tournaments** — Club-hosted tournament schedule\n\n**Union System:** Clubs can form unions to share player pools and run cross-club events.', followUps: ['How do I create my own club?', 'What is the union system?', 'How do I deposit to a club?'] },

    { id: 'ca-2', category: 'Club Arena', keywords: ['create club', 'start club', 'new club', 'club admin', 'my clubs'], patterns: ['how do i create a club', 'how to start my own club', 'how do i manage my club'], answer: '**Creating a Club:**\n\n1. Go to Hub > My Clubs\n2. Tap **Create Club**\n3. Set club name, description, and branding\n4. Configure game types and stakes\n5. Invite players\n\n**Club Admin Features:**\n- Set rules and house rake\n- Manage members (approve/ban)\n- Schedule tournaments\n- View club analytics\n- Customize club page\n\nClub admins have full control over their poker room environment.', followUps: ['How do I invite players?', 'What is the union dashboard?'] },

    { id: 'ca-3', category: 'Club Arena', keywords: ['hand histories', 'hand history', 'review hands', 'past hands', 'club hands'], patterns: ['where are my hand histories', 'how do i review hands', 'how to see past hands in club arena'], answer: '**Hand Histories** in Club Arena show every hand you have played.\n\n- Filter by date, game type, or result\n- Replay hands step-by-step\n- See all player actions and showdowns\n- Export for analysis in external tools\n- Send hands to Jarvis for AI analysis\n\nAccess from Club Arena > Hand Histories.', followUps: ['Can I export my hands?', 'How do I analyze a hand with Jarvis?'] },

    { id: 'ca-4', category: 'Club Arena', keywords: ['club cashier', 'deposit', 'withdraw', 'club balance', 'chips'], patterns: ['how do i deposit to a club', 'how does the cashier work', 'how to get chips in club arena'], answer: '**Club Cashier** manages your chip balance within each club.\n\n- **Deposit** — Add chips to play\n- **Withdraw** — Cash out your chips\n- **Transaction History** — Full audit trail\n- **Balance** — See current chip count\n\nEach club manages its own economy. Your balance is separate per club.', followUps: ['Are chips transferable between clubs?', 'How long do withdrawals take?'] },

    { id: 'ca-5', category: 'Club Arena', keywords: ['agent dashboard', 'agent', 'club agent', 'referral', 'agent program'], patterns: ['what is the agent dashboard', 'how do i become an agent', 'what is the agent program'], answer: '**Agent Dashboard** is for club agents who recruit and manage players.\n\n- Track your referred players\n- See their activity and volume\n- Earn commissions based on play\n- Manage your agent network\n- View earnings reports\n\nAgents help grow clubs by bringing in new players.', followUps: ['How do I sign up as an agent?', 'How are commissions calculated?'] },
];

export const BANKROLL_ENTRIES = [
    { id: 'br-1', category: 'Bankroll Manager', keywords: ['bankroll manager', 'bankroll', 'finances', 'money tracking', 'financial', 'roi'], patterns: ['what is the bankroll manager', 'how do i track my bankroll', 'how does bankroll manager work', 'how to manage my poker money'], answer: '**Bankroll Manager** (ORB-08) is your complete poker financial tracking system.\n\n**Features:**\n- **Session Tracking** — Log every poker session with buy-in, cash-out, duration\n- **ROI Analysis** — See your win rate, hourly rate, and ROI over time\n- **Leak Detection** — Identify costly patterns (game types, venues, times)\n- **Charts & Graphs** — Visual profit/loss over time\n- **Location Intelligence** — Track performance by venue\n- **Export** — Download your data as CSV\n- **Player Notes** — Notes on opponents at each venue\n- **Analytics** — Deep statistical analysis\n\nAll data saves in real-time to Supabase and syncs across devices.', followUps: ['How do I log a session?', 'How is ROI calculated?', 'How do I export my data?'] },

    { id: 'br-2', category: 'Bankroll Manager', keywords: ['log session', 'add session', 'record session', 'buy in', 'cash out', 'session entry'], patterns: ['how do i log a session', 'how to add a poker session', 'how do i record my results'], answer: '**Logging a Session:**\n\n1. Open Bankroll Manager\n2. Tap **Add Session**\n3. Enter:\n   - **Date and time**\n   - **Venue/location**\n   - **Game type** (NLH, PLO, tournament, etc.)\n   - **Stakes** (1/2, 2/5, etc.)\n   - **Buy-in amount**\n   - **Cash-out amount**\n   - **Duration**\n   - **Optional notes**\n4. Save — profit/loss is calculated automatically\n\nYour running bankroll total updates instantly.', followUps: ['Can I edit a session later?', 'How do I add multiple buy-ins?'] },

    { id: 'br-3', category: 'Bankroll Manager', keywords: ['bankroll analytics', 'statistics', 'win rate', 'hourly rate', 'profit chart'], patterns: ['how do i see my statistics', 'what analytics are available', 'how to check my win rate', 'where is my profit chart'], answer: '**Bankroll Analytics** gives you deep performance insights:\n\n- **Total Profit/Loss** — Lifetime and filtered by date range\n- **Win Rate** — BB/100 or $/hour\n- **Hourly Rate** — Average earnings per hour\n- **ROI** — Return on investment percentage\n- **Best/Worst Sessions** — Highest wins and losses\n- **By Game Type** — Performance in each variant\n- **By Venue** — Which locations are most profitable\n- **By Day of Week** — When you play best\n- **Profit Graph** — Visual timeline of your bankroll\n\nUse these insights to play your most profitable games at your best venues.', followUps: ['How do I find my leaks?', 'What is a good win rate?'] },
];

export const TOKE_TRACKER_ENTRIES = [
    { id: 'tt-1', category: 'Toke Tracker', keywords: ['toke tracker', 'toke', 'tips', 'dealer tips', 'dealer earnings', 'toke rate', 'ehr'], patterns: ['what is toke tracker', 'how do i track my tips', 'how does toke tracker work', 'what is ehr'], answer: '**Toke Tracker** is designed for poker dealers to track their earnings.\n\n**Features:**\n- **Add Down** — Log each dealer down (shift at a table)\n- **Track Tips** — Record toke amounts per down\n- **EHR (Effective Hourly Rate)** — Your true hourly earnings including tips\n- **Analytics** — Track trends by game type, venue, day, time\n- **Shift View** — See all downs in a shift\n- **Vault** — Historical earnings data\n- **Venues** — Track performance by casino/room\n- **Expenses** — Log work-related expenses\n\n**Down Multiplier:** Apply multipliers when you deal extra-tipping games.\n\nAll data syncs in real-time across devices.', followUps: ['How do I add a down?', 'How is EHR calculated?', 'What is the dealer vault?'] },

    { id: 'tt-2', category: 'Toke Tracker', keywords: ['add down', 'log down', 'new down', 'down entry', 'dealer down', 'cash stakes', 'cash variant'], patterns: ['how do i add a down', 'how to log a dealer down', 'how to record a down'], answer: '**Adding a Down:**\n\n1. Open Toke Tracker\n2. Tap **Add Down**\n3. Enter:\n   - **Game type** (cash or tournament)\n   - **Stakes** (1/2, 2/5, 5/10, etc.)\n   - **Variant** (NLH, PLO, Stud, etc.)\n   - **Toke amount** received\n   - **Duration** of the down\n   - **Down multiplier** (optional, for high-action games)\n4. Save\n\nYour EHR and analytics update instantly. You can edit or delete any down later.', followUps: ['What is the down multiplier?', 'Can I add multiple downs at once?'] },

    { id: 'tt-3', category: 'Toke Tracker', keywords: ['dealer vault', 'earnings history', 'past earnings', 'vault', 'historical data'], patterns: ['what is the dealer vault', 'where do i see past earnings', 'how do i view my history'], answer: '**Dealer Vault** is your complete earnings archive.\n\n- Browse by date, week, month, or year\n- See total tokes, hours worked, and EHR\n- Filter by venue or game type\n- View trends and comparisons\n- Completed events with full details\n\nThe vault stores your entire dealing career history.', followUps: ['Can I export my vault data?', 'How do I compare months?'] },
];

export const POKER_NEAR_ME_ENTRIES = [
    { id: 'pnm-1', category: 'Poker Near Me', keywords: ['poker near me', 'find poker', 'live poker', 'nearby', 'local poker', 'venues', 'card rooms'], patterns: ['how do i find poker near me', 'where can i play live poker', 'how to find local games', 'what is poker near me'], answer: '**Poker Near Me** (ORB-04) helps you find live poker games in your area.\n\n**Features:**\n- **Venues** — Browse card rooms, casinos, and home games nearby\n- **Events** — See upcoming tournaments and special events\n- **Live** — Real-time game availability at local venues\n- **Map** — Interactive map with venue locations\n- **Saved** — Bookmark your favorite venues\n\n**How it works:**\n1. Allow location access (or enter your city)\n2. Browse nearby venues\n3. See what games are running NOW\n4. Get directions, contact info, and schedules\n\nNever miss a game in your area!', followUps: ['How do I save a venue?', 'Can I see what games are running right now?', 'How do I add my own venue?'] },

    { id: 'pnm-2', category: 'Poker Near Me', keywords: ['my venues', 'saved venues', 'favorite venues', 'venue details'], patterns: ['how do i save a venue', 'where are my saved venues', 'how to bookmark a venue'], answer: '**Saved Venues** are your bookmarked favorite poker rooms.\n\n1. Browse venues in Poker Near Me\n2. Tap the bookmark icon on any venue\n3. Access all saved venues from the **Saved** tab\n\nSaved venues show you notifications about new events and game changes.', followUps: ['Do I get notifications for saved venues?', 'How do I remove a saved venue?'] },

    { id: 'pnm-3', category: 'Poker Near Me', keywords: ['daily tournaments', 'tournament schedule', 'local tournaments', 'upcoming tournaments'], patterns: ['where do i see daily tournaments', 'how to find local tournaments', 'what tournaments are near me'], answer: '**Daily Tournaments** shows all upcoming tournament events near you.\n\n- Filter by date, buy-in, game type\n- See full structure info (starting chips, blind levels)\n- Set reminders for events\n- View venue details and directions\n- Register online where available\n\nSynced with the Events Calendar for a complete schedule.', followUps: ['How do I set a tournament reminder?', 'Can I register online?'] },
];

export const MEMORY_GAMES_ENTRIES = [
    { id: 'mg-1', category: 'Memory Games', keywords: ['memory games', 'memory', 'brain training', 'memory training', 'card memory'], patterns: ['what are memory games', 'how do memory games work', 'how to play memory games'], answer: '**Memory Games** train your poker table recall and pattern recognition.\n\n**Features:**\n- Practice remembering card positions and sequences\n- Difficulty levels from beginner to expert\n- Timed challenges\n- Achievements and leaderboard\n- Tutorial for new players\n- Stats tracking\n\nMemory is a crucial poker skill — remembering board textures, bet sizes, and player tendencies gives you an edge at the table.', followUps: ['How do I improve my memory?', 'Are there achievements?'] },
];
