/* Club Commander Knowledge */
export const COMMANDER_ENTRIES = [
    { id: 'cc-1', category: 'Club Commander', keywords: ['club commander', 'poker room management', 'room manager', 'commander', 'manage poker room'], patterns: ['what is club commander', 'how do i use club commander', 'what does club commander do', 'how to manage my poker room'], answer: '**Club Commander** is a complete poker room management system — built for card room managers, floor staff, and tournament directors.\n\n**Core Features:**\n- **Dashboard** — Real-time room overview with active tables, players, and waitlist\n- **Tables** — Open/close tables, assign dealers, track game types\n- **Waitlist** — Digital waitlist with auto-seating and SMS notifications\n- **Tournaments** — Full tournament director with clocks, structures, and registration\n- **Members** — Player database with check-in, stats, and loyalty tracking\n- **Dealers** — Dealer rotation scheduling and shift management\n- **Floor** — Floor call tracking and resolution\n- **Analytics** — Revenue, player count, and utilization reports\n- **Displays** — Public-facing screens for waitlist, promotions, and dealers\n\nAccess via Hub > Commander Orb or commander.smarter.poker', followUps: ['How do I set up my poker room?', 'How does the waitlist work?', 'How do I run a tournament?'] },

    { id: 'cc-2', category: 'Club Commander', keywords: ['waitlist', 'wait list', 'add to waitlist', 'seat player', 'auto seat', 'waiting list'], patterns: ['how does the waitlist work', 'how do i add someone to the waitlist', 'how to manage the waitlist', 'how does auto-seating work'], answer: '**Waitlist** manages player seating across all open games.\n\n**Adding a Player:**\n1. Go to Commander > Waitlist Desk\n2. Search for the member or add a walk-in\n3. Select which game(s) they want\n4. Player is added to the queue\n\n**Auto-Seating:** When a seat opens, Commander automatically notifies the next player via SMS/push notification. They get a time window to claim the seat.\n\n**Features:**\n- Multi-game waitlists (player can wait for 2/5 NLH AND 5/10 PLO)\n- Position tracking\n- Average wait time analytics\n- Public waitlist display screen\n- Check-in via QR code', followUps: ['How do I set up the public display?', 'Can players check in remotely?'] },

    { id: 'cc-3', category: 'Club Commander', keywords: ['tournament', 'tournament director', 'tournament clock', 'run tournament', 'td', 'tournament settings'], patterns: ['how do i run a tournament', 'how to set up a tournament', 'how does the tournament director work', 'how do i create a tournament'], answer: '**Tournament Director** is a full-featured tournament management system.\n\n**Setting Up a Tournament:**\n1. Commander > Tournament Settings\n2. Set name, buy-in, starting chips, blind structure\n3. Configure levels, breaks, and antes\n4. Open registration\n\n**Running the Tournament:**\n- **Tournament Clock** — Displays on the public screen with level, blinds, and time\n- **Registration** — In-person and online registration\n- **Table Assignments** — Auto-seat players at balanced tables\n- **Table Breaks** — Automated table breaking with smart rebalancing\n- **Payouts** — Auto-calculated based on entries and structure\n- **Results** — Published to leaderboards\n\n**Advanced:**\n- Multi-day flights (Day 1A, 1B, etc.)\n- Re-entries and add-ons\n- Bounty tracking\n- ICM deal calculator', followUps: ['How do I set up blind structures?', 'How does table breaking work?', 'Can I run multi-day tournaments?'] },

    { id: 'cc-4', category: 'Club Commander', keywords: ['dealers', 'dealer rotation', 'dealer schedule', 'assign dealer', 'dealer management'], patterns: ['how do i manage dealers', 'how does dealer rotation work', 'how to schedule dealers', 'how to assign dealers to tables'], answer: '**Dealer Management** handles scheduling and rotation.\n\n**Features:**\n- **Dealer Roster** — Add and manage your dealer team\n- **Rotation** — Automatic timed rotation between tables\n- **Schedule** — Build shift schedules\n- **Table Assignment** — Assign specific dealers to tables\n- **Dealer Display** — Public screen showing current dealers per table\n\n**Rotation Setup:**\n1. Commander > Dealer Rotation\n2. Set rotation interval (e.g., 30 minutes)\n3. Assign dealers to the rotation pool\n4. System rotates automatically and updates displays', followUps: ['How often should I rotate dealers?', 'Can dealers see their schedule?'] },

    { id: 'cc-5', category: 'Club Commander', keywords: ['tables', 'open table', 'close table', 'game types', 'table management', 'open game'], patterns: ['how do i open a table', 'how to close a table', 'how do i add a game type', 'how to manage tables'], answer: '**Table Management** controls your poker room floor.\n\n**Opening a Table:**\n1. Commander > Tables (or Open Game)\n2. Select the table number\n3. Choose game type and stakes\n4. Assign a dealer\n5. Table is now live\n\n**Game Types:**\n- Pre-configured: NLH, PLO, Stud, Mixed, etc.\n- Custom: Create your own game types with specific rules\n\n**Must-Move:** Set up must-move games that feed into main games when seats open.\n\n**Table Vibes:** Monitor the mood and pace at each table for floor decisions.', followUps: ['What is a must-move game?', 'How do I set up custom game types?'] },

    { id: 'cc-6', category: 'Club Commander', keywords: ['members', 'player database', 'check in', 'member import', 'player card', 'loyalty'], patterns: ['how do i manage members', 'how does check-in work', 'how to import members', 'how to track player loyalty'], answer: '**Members** is your player database and loyalty system.\n\n**Features:**\n- **Player Profiles** — Name, contact, play history, notes\n- **Check-In** — QR code or name search at the door\n- **Player Card** — Digital loyalty card with stats\n- **Import** — Bulk import from CSV/spreadsheet\n- **Loyalty Tracking** — Hours played, games joined, comp points\n- **Membership Plans** — Create tiered membership levels\n\n**Check-In Flow:**\n1. Player scans QR code or staff searches their name\n2. System logs the visit\n3. Player is added to waitlist or seated\n4. Hours are tracked automatically', followUps: ['How do I create membership plans?', 'Can players check in with their phone?'] },

    { id: 'cc-7', category: 'Club Commander', keywords: ['analytics', 'reports', 'revenue', 'daily summary', 'metrics', 'commander analytics'], patterns: ['how do i see analytics', 'where are the reports', 'how to track revenue', 'what reports are available'], answer: '**Analytics & Reports** provide complete business intelligence.\n\n**Available Reports:**\n- **Daily Summary** — Overview of the day\'s operations\n- **Revenue** — Income tracking by game, table, and time\n- **Player Activity** — Who played, how long, which games\n- **Table Utilization** — % of time each table was active\n- **Waitlist Metrics** — Average wait times, peak hours\n- **Staff Activity** — Floor staff performance\n- **Tournament Results** — All tournament outcomes\n- **Tax Compliance** — Reports for regulatory requirements\n- **Analytics Daily** — Deep daily breakdown\n- **Churn Prediction** — Identify at-risk players\n\nExport any report as CSV for accounting.', followUps: ['How do I export reports?', 'What is churn prediction?'] },

    { id: 'cc-8', category: 'Club Commander', keywords: ['displays', 'public display', 'tv screen', 'waitlist display', 'promotion display', 'announcement'], patterns: ['how do i set up displays', 'what displays are available', 'how to show waitlist on tv'], answer: '**Displays** are public-facing screens for your poker room.\n\n**Available Displays:**\n- **Waitlist** — Live waitlist with estimated wait times\n- **Tables** — Current games running, open seats\n- **Dealers** — Who is dealing at each table\n- **Promotions** — Current promotions and offers\n- **Announcements** — Staff messages to the room\n- **Leaderboard** — Player rankings and competitions\n- **Combined** — Multiple displays in one rotating view\n\n**Setup:** Connect a TV/monitor, open Commander > Displays, choose the display type, and it auto-updates in real-time.', followUps: ['Can I customize the display theme?', 'How do I add a promotion?'] },

    { id: 'cc-9', category: 'Club Commander', keywords: ['floor', 'floor calls', 'floor decision', 'dispute', 'ruling'], patterns: ['how do floor calls work', 'how to handle a floor call', 'what is floor call tracking'], answer: '**Floor Calls** track and resolve player disputes and rulings.\n\n1. Staff creates a floor call with table number and issue\n2. Floor manager is notified\n3. Floor reviews the situation\n4. Resolution is logged with the ruling\n5. All calls are tracked for review\n\nKeeps a complete audit trail for dispute resolution and staff training.', followUps: ['Can I review past floor calls?', 'How do I train new floor staff?'] },

    { id: 'cc-10', category: 'Club Commander', keywords: ['high hands', 'high hand bonus', 'jackpot', 'bad beat', 'promotions', 'comps'], patterns: ['how do high hands work', 'how to set up high hand bonuses', 'how do promotions work', 'how to give comps'], answer: '**Promotions & High Hands** drive player engagement.\n\n**High Hands:**\n- Track qualifying high hands by time period\n- Auto-display on the promotions screen\n- Configure minimum qualifying hand\n- Set prize amounts per period\n\n**Promotions:**\n- Create custom promotions (happy hour, new player bonuses)\n- Schedule start/end times\n- Display on public screens\n\n**Comps:**\n- Issue comps to players (food, drinks, merchandise)\n- Track comp spending per player\n- Set comp rates by game type', followUps: ['How do I set up a bad beat jackpot?', 'Can I schedule recurring promotions?'] },

    { id: 'cc-11', category: 'Club Commander', keywords: ['cashier', 'cash management', 'buy in', 'cash out', 'cage', 'chips'], patterns: ['how does the cashier work', 'how to process buy-ins', 'how does cash management work'], answer: '**Cashier** handles all chip and cash transactions.\n\n**Features:**\n- Process **buy-ins** and **cash-outs**\n- Track chip inventory\n- End-of-day reconciliation\n- Transaction history\n- Multiple payment methods\n\n**Buy-In Flow:**\n1. Player approaches the cage\n2. Cashier enters the amount\n3. Chips are issued\n4. Transaction is logged\n\nFull audit trail for compliance and accounting.', followUps: ['How do I close out the day?', 'Where do I see transaction history?'] },

    { id: 'cc-12', category: 'Club Commander', keywords: ['staff', 'staff management', 'employees', 'shift', 'time clock', 'schedule'], patterns: ['how do i manage staff', 'how does the time clock work', 'how to schedule staff'], answer: '**Staff Management** covers your entire team.\n\n- **Staff Directory** — All employees with roles and permissions\n- **Time Clock** — Digital clock-in/clock-out\n- **Scheduling** — Build shift schedules\n- **Shift Handoff** — Transfer notes between shifts\n- **Activity Tracking** — See what each staff member did\n\n**Roles:** Admin, Floor Manager, Dealer, Cashier, Host — each with appropriate permissions.', followUps: ['How do I add a new staff member?', 'What permissions do different roles have?'] },

    { id: 'cc-13', category: 'Club Commander', keywords: ['onboarding', 'setup', 'get started', 'new room', 'configure commander'], patterns: ['how do i get started with commander', 'how to set up commander', 'how to onboard my poker room'], answer: '**Getting Started with Club Commander:**\n\n1. **Register** your poker room at commander.smarter.poker\n2. **Onboarding Wizard** walks you through:\n   - Room name and branding\n   - Table count and layout\n   - Game types offered\n   - Staff accounts\n   - Dealer rotation settings\n3. **Import Members** — Upload your existing player list\n4. **Configure Displays** — Set up your room TVs\n5. **Go Live!** — Start managing your room\n\nThe docs section has a **Manager Guide** and **Staff Guide** with step-by-step instructions.', followUps: ['Is there a staff training guide?', 'How much does Commander cost?'] },

    { id: 'cc-14', category: 'Club Commander', keywords: ['kiosk', 'self service', 'player kiosk', 'check in kiosk'], patterns: ['what is the kiosk', 'how does the kiosk work', 'how to set up a kiosk'], answer: '**Kiosk Mode** turns any tablet into a self-service check-in station.\n\n**Features:**\n- Players check themselves in\n- Self-add to waitlists\n- View current games and wait times\n- Register for tournaments\n\n**Setup:** Open Commander > Kiosk on a tablet browser. It locks to kiosk mode for public use.', followUps: ['What tablet should I use?', 'Can players register for tournaments at the kiosk?'] },

    { id: 'cc-15', category: 'Club Commander', keywords: ['leagues', 'poker league', 'league standings', 'season'], patterns: ['how do leagues work', 'how to create a poker league', 'what are leagues'], answer: '**Leagues** let you run ongoing poker league seasons.\n\n- Create a league with a name and rules\n- Schedule regular events\n- Track points and standings\n- Season leaderboard\n- Playoff/championship structures\n\nPerfect for recurring home games or club championship series.', followUps: ['How do I set up scoring?', 'Can I import players from members?'] },
];
