/* Core Poker Strategy & Theory Knowledge */
export const POKER_STRATEGY_ENTRIES = [
    // ── GTO Fundamentals ──
    { id: 'ps-1', category: 'GTO Strategy', keywords: ['gto', 'game theory optimal', 'game theory', 'optimal strategy', 'balanced', 'nash equilibrium'], patterns: ['what is gto', 'what does gto mean', 'what is game theory optimal', 'explain gto strategy', 'what is balanced play'], answer: '**GTO (Game Theory Optimal)** is a poker strategy based on game theory that makes you **unexploitable**.\n\n**Key Concepts:**\n- A GTO strategy cannot be beaten in the long run — even if your opponent knows your exact strategy\n- It uses **mixed strategies** — sometimes betting, sometimes checking with the same hand\n- Based on **Nash Equilibrium** — no player can improve by changing their strategy alone\n\n**In Practice:**\n- GTO provides the **baseline** for correct play\n- You can deviate from GTO to **exploit** weaker opponents\n- GTO is most important in tough games against good players\n- Against recreational players, exploitative adjustments often win more\n\n**Bottom Line:** Learn GTO first as your foundation, then learn when and how to deviate from it for maximum profit.', followUps: ['How do I learn GTO?', 'What is exploitative play?', 'When should I deviate from GTO?'] },

    { id: 'ps-2', category: 'GTO Strategy', keywords: ['exploitative', 'exploit', 'adjustments', 'deviate', 'exploit strategy', 'player reads'], patterns: ['what is exploitative play', 'when should i deviate from gto', 'how to exploit opponents', 'how do i adjust to bad players'], answer: '**Exploitative Play** means deviating from GTO to take advantage of opponents\' mistakes.\n\n**When to Exploit:**\n- Opponent folds too much → **Bluff more**\n- Opponent calls too much → **Value bet thinner, bluff less**\n- Opponent bets too big → **Fold more marginal hands**\n- Opponent never bluffs → **Over-fold vs. their bets**\n\n**Key Principle:** Every deviation from GTO creates its own exploitability. Against strong opponents, stay closer to GTO. Against weak players, exploit heavily.\n\n**Example:** If a player folds 80% to river bets, GTO might bluff 30% of the time — but exploitatively, you should bluff nearly 100%.', followUps: ['How do I read my opponents?', 'What are common player types?'] },

    { id: 'ps-3', category: 'GTO Strategy', keywords: ['3 bet', '3bet', 'three bet', 'reraise', '3 bet range', '3 betting'], patterns: ['what is a 3-bet', 'how do i 3-bet', 'what is my 3-bet range', 'when should i 3-bet', '3-bet sizing'], answer: 'A **3-bet** is the second raise preflop (open raise = 2-bet, reraise = 3-bet).\n\n**GTO 3-Bet Ranges (6-max, 100bb):**\n- **Button vs. CO open:** ~12-15% (polarized: premiums + suited connectors)\n- **SB vs. BTN open:** ~10-12%\n- **BB vs. BTN open:** ~8-10%\n\n**Sizing:**\n- **In Position:** 2.5-3x the open raise\n- **Out of Position:** 3-3.5x the open raise\n- **Against limpers:** 4x + 1x per limper\n\n**3-Bet Range Construction:**\n- **Value:** AA, KK, QQ, AKs, AKo, JJ, AQs\n- **Bluffs:** A5s-A2s, K5s-K2s, small suited connectors\n\nThe key is having a balanced range with both value hands and bluffs.', followUps: ['How do I defend against a 3-bet?', 'What is a 4-bet?', 'What is a polarized range?'] },

    { id: 'ps-4', category: 'GTO Strategy', keywords: ['c bet', 'cbet', 'continuation bet', 'flop bet', 'continuation betting'], patterns: ['what is a c-bet', 'when should i c-bet', 'what is continuation betting', 'c-bet sizing', 'c-bet frequency'], answer: 'A **C-Bet (Continuation Bet)** is betting the flop after raising preflop.\n\n**GTO C-Bet Guidelines:**\n- **Frequency:** 50-70% of the time in position, 25-40% out of position\n- **Small sizing** (25-33% pot) on dry/disconnected boards\n- **Large sizing** (66-75% pot) on wet/connected boards\n- **Check more** on boards that favor the caller\'s range\n\n**Best Boards to C-Bet:**\n- Ace-high (A-7-2) — You have more Ax in your range\n- King-high dry (K-8-3) — Your range advantage is strong\n- Paired boards (8-8-3) — Caller missed most of the time\n\n**Worst Boards to C-Bet:**\n- Middle connected (8-7-6) — Caller has more suited connectors\n- Low paired (4-4-9) — Minimal range advantage', followUps: ['What is a delayed c-bet?', 'How do I decide between small and big c-bets?'] },

    { id: 'ps-5', category: 'GTO Strategy', keywords: ['bet sizing', 'sizing', 'how much to bet', 'pot size bet', 'overbet', 'underbet'], patterns: ['how do i size my bets', 'what is correct bet sizing', 'when to overbet', 'how big should i bet'], answer: '**Bet Sizing** is one of the most important skills in poker.\n\n**Common Sizings and When to Use Them:**\n\n| Size | When |\n|---|---|\n| **25-33% pot** | Dry boards, range bets, thin value |\n| **50% pot** | Standard sizing, moderate equity denial |\n| **66-75% pot** | Wet boards, strong hands, draws |\n| **100% pot** | Polarized (very strong or bluffs) |\n| **125-200% pot** | Overbets for max value, nuts vs. 2nd nuts |\n\n**Key Principles:**\n- Size based on your **range**, not just your hand\n- Use **smaller sizes** when your range is wide (many hands)\n- Use **larger sizes** when your range is polarized (strong or bluffs)\n- **River sizing** should be larger than flop/turn for value extraction', followUps: ['When should I overbet?', 'What is a polarized range?', 'How do ranges affect sizing?'] },

    { id: 'ps-6', category: 'GTO Strategy', keywords: ['position', 'positional advantage', 'in position', 'out of position', 'seat', 'button', 'early position', 'late position'], patterns: ['why is position important', 'what positions are best', 'how does position work', 'explain positional play'], answer: '**Position** is the single most important concept in poker.\n\n**Positions (6-max):**\n1. **UTG (Under the Gun)** — First to act, tightest range\n2. **MP (Middle Position)** — Slightly wider\n3. **CO (Cutoff)** — Wide opening range\n4. **BTN (Button)** — Widest opening range, best seat\n5. **SB (Small Blind)** — Forced bet, always out of position postflop\n6. **BB (Big Blind)** — Forced bet, closes preflop action\n\n**Why Position Matters:**\n- You act **last** postflop = **more information**\n- You can **control pot size** more easily\n- You can **bluff more effectively** since opponents must act first\n- GTO ranges are **30-40% wider** on the button vs. UTG\n\n**Rule of thumb:** Play more hands in late position, fewer in early position.', followUps: ['What is an opening range by position?', 'How do I play from the blinds?'] },

    // ── Poker Math ──
    { id: 'ps-7', category: 'Poker Math', keywords: ['pot odds', 'odds', 'call odds', 'price', 'getting odds'], patterns: ['what are pot odds', 'how do i calculate pot odds', 'how to figure out pot odds', 'explain pot odds'], answer: '**Pot Odds** tell you the price you are getting on a call.\n\n**Formula:** Pot Odds = Call Amount / (Pot + Call Amount)\n\n**Example:**\n- Pot is $100, opponent bets $50\n- You must call $50 into a pot of $150\n- Pot odds = $50 / ($150 + $50) = 25%\n- You need **25% equity** to break even on the call\n\n**Quick Rule of 2 and 4:**\n- **Flop with 2 cards to come:** Outs x 4 = approximate equity %\n- **Turn with 1 card to come:** Outs x 2 = approximate equity %\n\n**Example:** Flush draw (9 outs) on the flop = 9 x 4 = 36% equity\n\nIf your equity > pot odds, **call**. If not, **fold** (unless implied odds make up the difference).', followUps: ['What are implied odds?', 'How do I count my outs?', 'What is the rule of 4 and 2?'] },

    { id: 'ps-8', category: 'Poker Math', keywords: ['equity', 'hand equity', 'range equity', 'win probability', 'equity calculation'], patterns: ['what is equity', 'how do i calculate equity', 'what is my equity', 'explain equity in poker'], answer: '**Equity** is your share of the pot based on your probability of winning.\n\n**Types:**\n- **Hand vs. Hand** — AA vs. KK = 82% vs. 18%\n- **Hand vs. Range** — Your hand vs. opponent\'s possible holdings\n- **Range vs. Range** — Both players\' ranges compared\n\n**Common Matchups:**\n| Situation | Equity |\n|---|---|\n| AA vs. KK | 82% vs. 18% |\n| AKs vs. QQ | 46% vs. 54% |\n| AKo vs. 22 | 47% vs. 53% |\n| Overpair vs. flush draw | 65% vs. 35% |\n| Set vs. flush draw | 74% vs. 26% |\n\nUse the **Equity Calculator** in Training to compute exact percentages.', followUps: ['What is equity realization?', 'How do draws affect equity?'] },

    { id: 'ps-9', category: 'Poker Math', keywords: ['ev', 'expected value', 'positive ev', '+ev', 'negative ev', '-ev', 'math'], patterns: ['what is ev', 'what is expected value', 'how do i calculate ev', 'what is +ev'], answer: '**EV (Expected Value)** is how much a decision is worth on average over the long run.\n\n**Formula:** EV = (Win% × Win Amount) - (Lose% × Lose Amount)\n\n**Example — River Bluff:**\n- Pot is $100. You bet $75.\n- If opponent folds 50%: you win $100 half the time\n- If opponent calls 50%: you lose $75 half the time\n- EV = (0.5 × $100) - (0.5 × $75) = $50 - $37.50 = **+$12.50**\n\nThis is a **+EV** (positive expected value) play!\n\n**Key Insight:** Always make +EV decisions, even when individual results vary. In the long run, +EV decisions = profit.', followUps: ['What is EV in tournaments?', 'How does variance affect EV?'] },

    { id: 'ps-10', category: 'Poker Math', keywords: ['outs', 'counting outs', 'draw outs', 'how many outs', 'out count'], patterns: ['how do i count outs', 'how many outs do i have', 'what are outs', 'how to count outs'], answer: '**Outs** are cards remaining in the deck that improve your hand to a likely winner.\n\n**Common Out Counts:**\n| Draw | Outs | Flop Equity |\n|---|---|---|\n| Flush draw | 9 | ~36% |\n| Open-ended straight draw | 8 | ~32% |\n| Gutshot straight draw | 4 | ~16% |\n| Two overcards | 6 | ~24% |\n| Flush + straight draw | 15 | ~54% |\n| Set drawing to full house | 7 | ~28% |\n| One pair to two pair/trips | 5 | ~20% |\n\n**Discount Outs When:**\n- An out gives your opponent a better hand\n- The board pairs and you only have a flush draw\n- Your \"out\" doesn\'t guarantee a win', followUps: ['What is the rule of 2 and 4?', 'How do I use outs with pot odds?'] },

    { id: 'ps-11', category: 'Poker Math', keywords: ['mdf', 'minimum defense frequency', 'defend', 'calling frequency', 'fold frequency'], patterns: ['what is mdf', 'what is minimum defense frequency', 'how often should i call', 'how to calculate mdf'], answer: '**MDF (Minimum Defense Frequency)** tells you how often you must call to prevent opponents from profiting with any two cards.\n\n**Formula:** MDF = Pot Size / (Pot Size + Bet Size)\n\n**Common MDFs:**\n| Bet Size | MDF |\n|---|---|\n| 33% pot | 75% |\n| 50% pot | 67% |\n| 75% pot | 57% |\n| 100% pot (pot-size) | 50% |\n| 150% pot | 40% |\n\n**Example:** Opponent bets $50 into $100. MDF = 100/150 = 67%. You should defend (call or raise) with at least 67% of your range.\n\n**Caveat:** MDF is a theoretical baseline. In practice, adjust based on opponent tendencies and board texture.', followUps: ['When should I fold more than MDF suggests?', 'How does MDF change with position?'] },

    // ── Hand Rankings ──
    { id: 'ps-12', category: 'Hand Rankings', keywords: ['hand rankings', 'poker hands', 'what beats what', 'best hand', 'ranking', 'hand strength'], patterns: ['what are the poker hand rankings', 'what beats what', 'what is the best poker hand', 'rank poker hands', 'hand ranking order'], answer: '**Poker Hand Rankings** (best to worst):\n\n1. **Royal Flush** — A K Q J 10, all same suit\n2. **Straight Flush** — Five in a row, same suit (e.g., 9 8 7 6 5 of hearts)\n3. **Four of a Kind** — Four same rank (e.g., K K K K 7)\n4. **Full House** — Three of a kind + pair (e.g., Q Q Q 8 8)\n5. **Flush** — Five cards same suit, any order\n6. **Straight** — Five in a row, mixed suits (e.g., 10 9 8 7 6)\n7. **Three of a Kind** — Three same rank (e.g., J J J 9 4)\n8. **Two Pair** — Two different pairs (e.g., A A 7 7 3)\n9. **One Pair** — Two same rank (e.g., 10 10 K 5 2)\n10. **High Card** — No combination, highest card plays\n\n**Tie-Breakers:** Compare the rank of the combination first, then kicker cards.', followUps: ['Does a flush beat a straight?', 'What is a kicker?', 'How do ties work?'] },

    { id: 'ps-13', category: 'Hand Rankings', keywords: ['kicker', 'tie breaker', 'split pot', 'same hand', 'who wins'], patterns: ['what is a kicker', 'how do kickers work', 'how are ties broken', 'when is it a split pot'], answer: '**Kickers** break ties when hands have the same ranked combination.\n\n**Example:**\n- Player A: A-K on a board of A-9-7-3-2 → Pair of Aces, King kicker\n- Player B: A-Q on the same board → Pair of Aces, Queen kicker\n- **Player A wins** — King kicker beats Queen kicker\n\n**Split Pot Rules:**\n- If both players have the exact same 5-card hand, it is a split pot\n- Only the **best 5 cards** matter (community cards count)\n- Suits never break ties in standard hold\'em\n\n**Community Card Example:**\n- Board: A-K-Q-J-10 → Both players have the same straight → **Split pot**', followUps: ['Can suits break ties?', 'How do two pair ties work?'] },

    // ── Tournament Strategy ──
    { id: 'ps-14', category: 'Tournament Strategy', keywords: ['tournament', 'tournament strategy', 'mtt', 'multi table', 'tournament play', 'tourney'], patterns: ['how do i play tournaments', 'tournament strategy basics', 'mtt strategy', 'how are tournaments different from cash'], answer: '**Tournament Strategy** differs from cash games in key ways:\n\n**Key Differences:**\n- **Chips have diminishing value** — Losing chips hurts more than winning them helps\n- **Blinds increase** — Puts constant pressure on your stack\n- **ICM considerations** — Near the money/final table, survival matters\n- **Stack-dependent** — Your strategy changes based on your stack size\n\n**Stage-Based Strategy:**\n1. **Early (100+ BB)** — Play close to cash game strategy\n2. **Middle (40-60 BB)** — Tighten up, preserve chips\n3. **Bubble (25-40 BB)** — ICM pressure, exploit short stacks\n4. **Final Table (varies)** — Pay jumps drive decisions\n5. **Heads Up** — Wide ranges, aggressive play\n\n**Stack Size Rules:**\n- **20+ BB:** Standard raising and 3-betting\n- **15-20 BB:** Push/fold and resteal zone\n- **10-15 BB:** Jam or fold only\n- **Under 10 BB:** All-in or fold', followUps: ['What is ICM?', 'How do I play the bubble?', 'What is push/fold strategy?'] },

    { id: 'ps-15', category: 'Tournament Strategy', keywords: ['bubble', 'bubble play', 'near the money', 'bubble factor', 'itm'], patterns: ['how do i play the bubble', 'what is bubble play', 'how does the bubble work', 'what is the bubble factor'], answer: '**Bubble Play** is the phase just before the money in a tournament.\n\n**What Happens:**\n- Players tighten up to avoid busting before the money\n- Big stacks can **exploit** this fear by raising aggressively\n- Short stacks face maximum ICM pressure\n\n**Strategy by Stack Size:**\n- **Big Stack (50+ BB):** Raise wide, put pressure on medium stacks\n- **Medium Stack (20-40 BB):** Play tight, avoid marginal spots\n- **Short Stack (< 15 BB):** Look for spots to shove all-in, avoid slow death\n\n**Bubble Factor:** A mathematical concept showing that chips lost are worth more than chips won. For example, losing an all-in on the bubble might cost you $500 in equity while winning only gains $200.\n\nThe satellite bubble is even more extreme — 1st place and (say) 10th place pay the same, so survival is everything.', followUps: ['What is ICM?', 'Should I fold AK on the bubble?'] },

    // ── Cash Game Strategy ──
    { id: 'ps-16', category: 'Cash Game Strategy', keywords: ['cash game', 'cash game strategy', 'ring game', 'stake selection', 'buy in strategy'], patterns: ['cash game strategy basics', 'how do i play cash games', 'cash game tips', 'how to choose stakes'], answer: '**Cash Game Strategy** focuses on making the most profitable decisions.\n\n**Key Principles:**\n- **Chips = real money** — Every chip has fixed dollar value\n- **Rebuy anytime** — No pressure from increasing blinds\n- **Table selection** — Find the most profitable table\n- **Session length** — Leave when you are not playing your best\n\n**Bankroll Requirements:**\n- **20-30 buy-ins** for your stake (conservative)\n- **50+ buy-ins** if you are taking shots at higher stakes\n\n**Recommended Stakes Progression:**\n1. **Micro** (1/2, 1/3) — Learn fundamentals\n2. **Low** (2/5) — Develop your game\n3. **Mid** (5/10) — Serious competition\n4. **High** (10/20+) — Expert level required', followUps: ['How do I manage my bankroll?', 'Should I play tight or loose?', 'What is table selection?'] },

    // ── Psychology ──
    { id: 'ps-17', category: 'Psychology', keywords: ['tilt', 'mental game', 'emotions', 'control tilt', 'frustration', 'bad beat'], patterns: ['how do i deal with tilt', 'what is tilt', 'how to control emotions', 'how to handle bad beats', 'mental game tips'], answer: '**Tilt** is playing emotionally rather than logically — the #1 bankroll killer.\n\n**Types of Tilt:**\n- **Bad Beat Tilt** — After losing with a strong hand\n- **Downswing Tilt** — Extended losing streak\n- **Winner\'s Tilt** — Overconfidence after big wins\n- **Revenge Tilt** — Trying to get even with a specific player\n\n**How to Manage Tilt:**\n1. **Recognize it** — Self-awareness is step one\n2. **Take a break** — Walk away for 10 minutes\n3. **Breathe** — Deep breathing calms the nervous system\n4. **Set stop-losses** — Decide your max loss before sitting down\n5. **Review sessions** — Analyze decisions, not results\n6. **Bankroll management** — Never play stakes you cannot afford to lose\n\n**Mental Game Priority:** Focus on **decision quality**, not outcomes. A correct fold that \"would have won\" is still a correct fold.', followUps: ['How do I set a stop-loss?', 'How do I deal with variance?'] },

    { id: 'ps-18', category: 'Psychology', keywords: ['variance', 'swings', 'downswing', 'upswing', 'luck', 'standard deviation', 'run bad'], patterns: ['what is variance', 'how do i deal with variance', 'how long can a downswing last', 'is poker luck'], answer: '**Variance** is the natural mathematical fluctuation in poker results.\n\n**Key Facts:**\n- Even the best players have losing months\n- A typical winning player might lose over 50,000+ hand samples\n- Variance is **higher** in tournaments than cash games\n- Proper bankroll management absorbs variance\n\n**How Long Can a Downswing Last?**\n- Cash games: 50,000-200,000 hands\n- Tournaments: Months without a significant cash\n\n**Managing Variance:**\n1. **Bankroll management** — 20-30+ buy-ins minimum\n2. **Volume** — Play enough hands for your edge to show\n3. **Study** — Improve during downswings\n4. **Track results** — Use Bankroll Manager to see long-term trends\n5. **Accept it** — Variance is not personal, it is math', followUps: ['How many buy-ins do I need?', 'How do I track my results?'] },

    // ── PLO ──
    { id: 'ps-19', category: 'Poker Variants', keywords: ['plo', 'pot limit omaha', 'omaha', '4 cards', 'plo strategy'], patterns: ['what is plo', 'how do i play omaha', 'omaha strategy basics', 'what is pot limit omaha'], answer: '**PLO (Pot Limit Omaha)** is a poker variant where each player gets **4 hole cards** instead of 2.\n\n**Key Rules:**\n- Must use **exactly 2** of your 4 hole cards + 3 board cards\n- Betting is **pot-limit** (max bet = pot size)\n- Same hand rankings as Hold\'em\n\n**Strategy Differences from Hold\'em:**\n- **Equities run much closer** — big pairs are less dominant\n- **Nut hands matter more** — non-nut flushes and straights are dangerous\n- **Position is even more important** — more complex decisions\n- **Drawing hands are premium** — double-suited rundowns are strong\n\n**Strong Starting Hands:** AAxx (double-suited), KKQJ, JT98 (suited), AKQx suited', followUps: ['What are the best PLO starting hands?', 'How does pot-limit betting work?'] },

    // ── Geeves Meta ──
    { id: 'ps-20', category: 'Geeves', keywords: ['geeves', 'who are you', 'what are you', 'ai help', 'ask geeves', 'help bot'], patterns: ['who is geeves', 'who are you', 'what is geeves', 'what can you do', 'are you an ai'], answer: 'I am **Geeves**, your AI Help Assistant on Smarter.Poker!\n\n**What I can do:**\n- Answer questions about **every feature** on the platform\n- Explain **poker strategy** concepts (GTO, math, tournaments, cash games)\n- Help you navigate **Club Commander**, **Club Arena**, and the **World Hub**\n- Explain the **Diamond economy**, training tools, and social features\n- Provide **instant** answers without needing to search\n\n**Where to find me:**\n- In every **hamburger menu** across the platform\n- Via the **Live Help** button in the header\n- Press **Cmd+J** (or Ctrl+J) to open the help panel\n\nI am different from **Jarvis** — Jarvis is the elite tactical strategy coach. I am your all-around platform expert!', followUps: ['Who is Jarvis?', 'How do I access training?', 'What features does Smarter.Poker have?'] },

    { id: 'ps-21', category: 'Geeves', keywords: ['jarvis', 'jarvis vs geeves', 'difference', 'ai coach', 'strategy coach'], patterns: ['what is the difference between jarvis and geeves', 'who is jarvis', 'jarvis vs geeves'], answer: '**Jarvis** and **Geeves** are two different AI assistants:\n\n| | Jarvis | Geeves |\n|---|---|---|\n| **Role** | Elite Strategy Coach | Platform Help Expert |\n| **Focus** | Poker hand analysis, solver-level strategy | All platform features, navigation, general poker |\n| **Location** | Training > Jarvis, Personal Assistant | Every hamburger menu, header help button |\n| **Best For** | Deep hand review, range analysis, leak detection | \"How do I...\", feature questions, quick poker tips |\n\n**Use Jarvis** when you need detailed hand analysis or solver-grade strategy advice.\n**Use Geeves** (me!) for everything else — platform help, quick poker questions, and navigation.', followUps: ['How do I access Jarvis?', 'Where is the training hub?'] },
];
