/* Training, Trivia, Diamond Ecosystem Knowledge */
export const TRAINING_ENTRIES = [
    // ── GTO Training Hub ──
    { id: 'tr-1', category: 'Training', keywords: ['training', 'gto trainer', 'gto training', 'training hub', 'learn poker', 'practice'], patterns: ['how do i access training', 'what is gto training', 'how do i practice poker', 'where is the training hub', 'how does training work'], answer: '**GTO Training** is your path to mastering Game Theory Optimal poker strategy.\n\n**Access:** Hub > Training Orb\n\n**Features:**\n- **Scenario Trainer** — Play through pre-built poker situations\n- **Spot Trainer** — Practice specific spots (3-bet pots, river bluffs, etc.)\n- **Range Builder** — Construct and study opening ranges\n- **Preflop Charts** — Reference GTO preflop solutions\n- **Solutions Browser** — Explore full GTO solver outputs\n- **Equity Calculator** — Calculate hand vs. range equity\n- **ICM Calculator** — Tournament equity calculations\n- **Drill Builder** — Create custom practice drills\n- **Hand History Upload** — Import and review your hands\n- **Jarvis AI Coach** — Get strategy feedback from AI\n\nTrack your progress, earn achievements, and climb the leaderboard!', followUps: ['How do I read range charts?', 'What is the spot trainer?', 'How does the equity calculator work?'] },

    // ── Preflop Charts ──
    { id: 'tr-2', category: 'Training', keywords: ['preflop charts', 'opening ranges', 'preflop strategy', 'starting hands', 'open raise'], patterns: ['where are the preflop charts', 'how do i see opening ranges', 'what hands should i open', 'show me preflop ranges'], answer: '**Preflop Charts** display GTO-approved opening ranges for every position.\n\n**How to use:**\n1. Go to Training > Preflop Charts\n2. Select the **position** (UTG, MP, CO, BTN, SB, BB)\n3. Select the **action** (Open, vs 3-bet, etc.)\n4. View the color-coded 13x13 range grid\n\n**Grid Colors:**\n- **Green** — Always play (raise/call)\n- **Yellow** — Mixed strategy (sometimes play)\n- **Red** — Fold\n\nRanges are based on 100bb deep 6-max cash game solutions by default.', followUps: ['What is a mixed strategy?', 'How do ranges change by position?', 'What is 3-betting?'] },

    // ── Range Builder ──
    { id: 'tr-3', category: 'Training', keywords: ['range builder', 'build range', 'hand range', 'range construction', 'create range'], patterns: ['how do i use the range builder', 'how to build a range', 'what is the range builder'], answer: '**Range Builder** lets you construct custom hand ranges visually.\n\n**Features:**\n- Click hands on the 13x13 grid to add/remove them\n- Set frequency percentages for mixed strategies\n- Save ranges for later reference\n- Compare your ranges against GTO solutions\n- Export and share ranges\n\nUse this to study specific spots, prepare game plans, or analyze your own tendencies versus GTO.', followUps: ['How do I compare my range to GTO?', 'What is hand combinatorics?'] },

    // ── Equity Calculator ──
    { id: 'tr-4', category: 'Training', keywords: ['equity calculator', 'equity', 'hand equity', 'calculate equity', 'odds'], patterns: ['how does the equity calculator work', 'how do i calculate equity', 'what is equity'], answer: '**Equity Calculator** computes win probabilities for hands and ranges.\n\n**Usage:**\n1. Go to Training > Equity Calculator\n2. Enter **Hand 1** (e.g., AhKh)\n3. Enter **Hand 2** or a range\n4. Optionally add a **board** (flop/turn/river)\n5. Click Calculate\n\nThe calculator shows percentage equity for each hand, tie probability, and EV breakdowns.\n\n**Example:** AKo vs 22 preflop → AK has ~47% equity (a classic coin flip).', followUps: ['What is equity realization?', 'How do pot odds relate to equity?'] },

    // ── ICM Calculator ──
    { id: 'tr-5', category: 'Training', keywords: ['icm calculator', 'icm', 'independent chip model', 'tournament equity', 'icm pressure'], patterns: ['how does the icm calculator work', 'what is icm', 'how do i calculate icm'], answer: '**ICM (Independent Chip Model)** converts tournament chip stacks into real money equity.\n\n**How it works:**\n1. Enter the **prize pool structure** (1st, 2nd, 3rd, etc.)\n2. Enter each player\'s **chip stack**\n3. The calculator shows each player\'s **dollar equity**\n\n**Key Insight:** In tournaments, chips you lose are worth MORE than chips you gain (due to diminishing returns). This is why ICM creates **bubble pressure** — short stacks near the money should play tighter, and big stacks can exploit this.\n\nICM is critical for final table decisions, deal-making, and satellite strategy.', followUps: ['How does ICM affect bubble play?', 'What is the bubble factor?', 'When should I ignore ICM?'] },

    // ── Solutions Browser ──
    { id: 'tr-6', category: 'Training', keywords: ['solutions browser', 'solver', 'gto solutions', 'solver output', 'solution tree'], patterns: ['what is the solutions browser', 'how do i browse solutions', 'where are gto solutions'], answer: '**Solutions Browser** lets you explore complete GTO solver outputs.\n\n**Features:**\n- Navigate the full decision tree for any spot\n- See exact frequencies for each action (bet/check/raise/fold)\n- View by **position**, **board texture**, and **stack depth**\n- Hand EVs for every combo in your range\n- Mobile-optimized 13x13 strategy matrices\n\nThis is the deepest level of GTO study available — like having a PioSolver subscription built into the platform.', followUps: ['How do I read a strategy matrix?', 'What do the frequencies mean?'] },

    // ── Spot Trainer ──
    { id: 'tr-7', category: 'Training', keywords: ['spot trainer', 'practice spots', 'specific spots', 'drill', 'scenario'], patterns: ['what is the spot trainer', 'how do i practice specific spots', 'how does spot trainer work'], answer: '**Spot Trainer** focuses on specific poker situations:\n\n- **3-Bet Pots** — Practice playing in raised pots\n- **C-Bet Spots** — Continuation betting decisions\n- **River Bluffs** — Bluff vs. value on the river\n- **Multiway Pots** — Navigate 3+ player situations\n- **Short Stack** — Push/fold and resteal spots\n\nEach scenario presents a game state and asks for your action. You get instant feedback comparing your choice to the GTO solution, with explanations.', followUps: ['How is my accuracy scored?', 'Can I create custom scenarios?'] },

    // ── Drill Builder ──
    { id: 'tr-8', category: 'Training', keywords: ['drill builder', 'custom drills', 'build drill', 'training drill'], patterns: ['how do i create a custom drill', 'what is the drill builder', 'how to build a drill'], answer: '**Drill Builder** lets you create custom training sequences.\n\n1. Choose a **game type** (NLH cash, tournament, PLO)\n2. Set **stack depths**, positions, and board textures\n3. Define the **decision points** to practice\n4. Save and share with friends\n\nGreat for focusing on your specific leaks or preparing for a particular game format.', followUps: ['Can I share drills with friends?', 'How do I find my leaks?'] },

    // ── Hand History ──
    { id: 'tr-9', category: 'Training', keywords: ['hand history', 'upload hands', 'import hands', 'review hands', 'hand replay'], patterns: ['how do i upload hand history', 'how to import hands', 'can i review my hands'], answer: '**Hand History Upload** lets you import and analyze your real poker hands.\n\n1. Export hand history from your poker client\n2. Upload the file in Training > Hand History Upload\n3. Browse your hands with filters\n4. Get Jarvis AI analysis on key decisions\n5. See how your play compares to GTO\n\nSupports standard hand history formats from major poker sites.', followUps: ['What formats are supported?', 'How does Jarvis analyze my hands?'] },

    // ── Session Dashboard ──
    { id: 'tr-10', category: 'Training', keywords: ['session dashboard', 'training session', 'session stats', 'practice stats'], patterns: ['what is the session dashboard', 'how do i see my training stats', 'where is session dashboard'], answer: '**Session Dashboard** shows your current training session performance.\n\n- **Accuracy** — Percentage of GTO-correct decisions\n- **Time per decision** — Average decision speed\n- **Spots practiced** — Total hands this session\n- **Streak** — Consecutive correct answers\n- **Session comparison** — Compare to your average\n\nReview after each session to track improvement.', followUps: ['How do I improve my accuracy?', 'What is a good accuracy score?'] },

    // ── Jarvis AI ──
    { id: 'tr-11', category: 'Training', keywords: ['jarvis', 'ai coach', 'personal assistant', 'strategy coach', 'ai analysis'], patterns: ['who is jarvis', 'how do i use jarvis', 'what does jarvis do', 'how does the ai coach work'], answer: '**Jarvis** is your elite AI strategy coach — a tactical intelligence layer powered by advanced AI.\n\n**Capabilities:**\n- **Hand Analysis** — Break down any poker hand decision\n- **Range Construction** — Build optimal ranges for any spot\n- **Leak Detection** — Identify patterns in your play that cost money\n- **Study Plans** — Personalized training recommendations\n- **Sandbox Analysis** — Analyze custom scenarios\n\nJarvis lives at Training > Jarvis or through the Personal Assistant Orb. He gives solver-grade analysis in natural language.\n\n**Note:** Jarvis is the tactical coach. I\'m Geeves — I help with everything else across the platform!', followUps: ['What is the difference between Jarvis and Geeves?', 'How do I access the sandbox?'] },

    // ── Virtual Sandbox ──
    { id: 'tr-12', category: 'Training', keywords: ['sandbox', 'virtual sandbox', 'hand simulator', 'setup hand', 'analyze hand'], patterns: ['what is the sandbox', 'how do i use the sandbox', 'how to set up a hand in sandbox'], answer: '**Virtual Sandbox** lets you set up and analyze any poker scenario.\n\n**Setup:**\n1. Go to Personal Assistant > Sandbox\n2. Set **player count**, **positions**, and **stack sizes**\n3. Deal specific **hole cards** and **board cards**\n4. Set the **pot size** and **betting action**\n5. Click **Analyze** for Jarvis AI breakdown\n\n**Features:**\n- Exploit mode analysis\n- ICM/bubble factor integration\n- Share scenarios via URL\n- Save to Study Replay library\n\nPerfect for post-session hand review or theoretical study.', followUps: ['Can I share a sandbox scenario?', 'What is exploit mode?'] },
];

export const TRIVIA_ENTRIES = [
    // ── Trivia Hub ──
    { id: 'tv-1', category: 'Trivia', keywords: ['trivia', 'trivia hub', 'poker trivia', 'quiz', 'trivia games'], patterns: ['what is trivia', 'how do i play trivia', 'where is the trivia hub', 'what trivia games are there'], answer: '**Trivia Hub** is where you test your poker knowledge against questions.\n\n**Game Modes:**\n- **Cash Game** — Standard Q&A with point scoring\n- **MTT (Tournament)** — Timed rounds with elimination\n- **GTO** — Advanced game-theory questions\n- **ICM** — Tournament equity scenarios\n- **Mixed** — All categories shuffled\n- **PvP Battle** — Head-to-head vs. another player\n- **Endless** — Keep going until you miss\n- **Survival** — Limited lives, see how far you go\n- **Time Attack** — Race against the clock\n\n**Rewards:** Earn diamonds, XP, and climb the trivia leaderboard!', followUps: ['How do I play PvP trivia?', 'What rewards do I get?', 'How does time attack work?'] },

    // ── PvP Battle ──
    { id: 'tv-2', category: 'Trivia', keywords: ['pvp', 'pvp battle', 'versus', 'head to head', 'challenge', 'multiplayer trivia'], patterns: ['how do i play pvp trivia', 'how to challenge a friend', 'what is pvp battle'], answer: '**PvP Battle** lets you challenge another player to a trivia showdown.\n\n**How it works:**\n1. Go to Trivia > PvP\n2. Challenge a friend or get matched randomly\n3. Both players answer the same questions simultaneously\n4. Faster correct answers score more points\n5. Winner earns diamonds and XP\n\n**Features:**\n- Real-time scoring\n- 60-second shot clock per question\n- Streak bonuses for consecutive correct answers\n- Leaderboard ranking', followUps: ['How do I find opponents?', 'What do I win?'] },

    // ── Survival Mode ──
    { id: 'tv-3', category: 'Trivia', keywords: ['survival', 'survival mode', 'lives', 'survive', 'survival game'], patterns: ['how does survival mode work', 'what is survival trivia', 'how many lives do i get'], answer: '**Survival Mode** tests how far you can go with limited lives.\n\n- Start with **3 lives**\n- Each wrong answer costs a life\n- Questions get progressively harder\n- Score multiplier increases as you survive longer\n- High scores are tracked on the leaderboard\n\nPerfect for testing your deep poker knowledge under pressure.', followUps: ['How do I get extra lives?', 'What is my high score?'] },

    // ── Trivia Achievements ──
    { id: 'tv-4', category: 'Trivia', keywords: ['trivia achievements', 'badges', 'trivia rewards', 'unlock'], patterns: ['what trivia achievements are there', 'how do i earn trivia badges', 'what can i unlock in trivia'], answer: '**Trivia Achievements** reward consistent play and mastery:\n\n- **First Blood** — Answer your first question correctly\n- **Sharp Shooter** — 10 correct in a row\n- **Scholar** — Complete 100 questions\n- **Master** — Achieve 90%+ accuracy over 50 questions\n- **Champion** — Win 10 PvP battles\n- **Survivor** — Reach wave 20 in survival mode\n- **Speed Demon** — Complete time attack under 60 seconds\n\nAchievements earn diamonds and appear on your profile.', followUps: ['Where can I see my achievements?', 'How many diamonds do achievements give?'] },
];

export const DIAMOND_ENTRIES = [
    // ── Diamond Store ──
    { id: 'ds-1', category: 'Diamond Store', keywords: ['diamond store', 'buy diamonds', 'diamonds', 'purchase', 'store', 'pricing'], patterns: ['how do i buy diamonds', 'where is the diamond store', 'how much do diamonds cost', 'what are diamonds'], answer: '**Diamonds** are the premium currency of Smarter.Poker.\n\n**How to buy:**\n1. Go to Hub > Diamond Store\n2. Choose a bundle:\n   - **Starter** — 100 diamonds\n   - **Value** — 500 diamonds (best per-diamond price)\n   - **Premium** — 1,000 diamonds\n   - **Elite** — 5,000 diamonds (biggest savings)\n3. Complete checkout via Stripe (secure payment)\n\n**What diamonds buy:**\n- Premium training content\n- Trivia entry fees\n- Diamond Arena tournament buy-ins\n- Avatar upgrades\n- Exclusive features\n\nYou can track orders and view purchase history in the store.', followUps: ['What is the Diamond Arena?', 'Can I earn free diamonds?', 'Where do I see my diamond balance?'] },

    // ── Diamond Balance ──
    { id: 'ds-2', category: 'Diamond Store', keywords: ['diamond balance', 'how many diamonds', 'check balance', 'diamond wallet'], patterns: ['where do i see my diamond balance', 'how many diamonds do i have', 'where is my diamond wallet'], answer: 'Your **diamond balance** is displayed in the header area of every page (top bar near your avatar).\n\nYou can also see it in:\n- **Diamond Store** page\n- **Settings** > Account\n- **Profile** page\n\nDiamonds are earned through:\n- Trivia achievements\n- Training milestones\n- Daily login rewards\n- Purchasing from the store', followUps: ['How do I earn free diamonds?', 'What can I spend diamonds on?'] },

    // ── Diamond Arena ──
    { id: 'ds-3', category: 'Diamond Arena', keywords: ['diamond arena', 'diamond tournament', 'diamond games', 'arena'], patterns: ['what is the diamond arena', 'how do i play in diamond arena', 'how does diamond arena work'], answer: '**Diamond Arena** is a competitive poker tournament platform using diamonds.\n\n**Features:**\n- **Schedule** — View upcoming tournaments with buy-ins and structures\n- **History** — Review past tournament results\n- **Leaderboard** — Season rankings with prizes\n- **Stats** — Your personal tournament statistics\n- **Table Settings** — Customize your playing experience\n\n**How it works:**\n1. Browse the schedule for upcoming events\n2. Register with your diamond buy-in\n3. Play the tournament\n4. Win diamonds based on finishing position\n\nFrom micro buy-ins to high-roller events!', followUps: ['What are the buy-in levels?', 'How do I check the schedule?', 'Is there a leaderboard?'] },

    // ── Diamond Arcade ──
    { id: 'ds-4', category: 'Diamond Arcade', keywords: ['diamond arcade', 'arcade', 'mini games', 'arcade games', 'prizes', 'prize wheel'], patterns: ['what is the diamond arcade', 'how do i play arcade games', 'what prizes can i win', 'how does the prize wheel work'], answer: '**Diamond Arcade** is a collection of fun mini-games and prize opportunities.\n\n**Features:**\n- **Prize Wheel** — Spin to win diamonds and rewards\n- **Achievements** — Unlock badges through gameplay\n- **Leaderboard** — Compete for top arcade scores\n- **Stats** — Track your arcade performance\n- **Winnings** — Review your prize history\n\nThe arcade is a fun way to earn extra diamonds while taking a break from serious study.', followUps: ['How often can I spin the wheel?', 'What are the best prizes?'] },

    // ── VIP Membership ──
    { id: 'ds-5', category: 'Diamond Store', keywords: ['vip', 'membership', 'premium', 'vip benefits', 'subscribe', 'subscription'], patterns: ['what is vip membership', 'what does vip get me', 'how do i become vip', 'what are vip benefits', 'how much is vip'], answer: '**VIP Membership** unlocks the full Smarter.Poker experience.\n\n**VIP Benefits:**\n- Access to **all training content** (no diamond costs)\n- **Premium avatars** and custom uploads\n- **Priority support** from Geeves\n- **Ad-free** experience\n- Monthly **diamond bonus**\n- **Exclusive** VIP-only features and events\n- **Badge** on your profile\n\n**Pricing:**\n- Monthly and annual plans available\n- Powered by Stripe for secure billing\n- Cancel anytime\n\nUpgrade from the Diamond Store or Settings.', followUps: ['Can I cancel anytime?', 'Do I keep my VIP badge if I cancel?'] },
];
