/* ═══════════════════════════════════════════════════════════════════════════
   WORLD HUB & PLATFORM KNOWLEDGE — Expanded
   50+ entries covering every platform page, feature, and common question.
   ═══════════════════════════════════════════════════════════════════════════ */
export const WORLD_HUB_ENTRIES = [
    // ── World Hub Home ──
    { id: 'wh-1', category: 'World Hub', keywords: ['world hub', 'home', 'main page', 'landing', 'orbs', 'dashboard', 'smarter poker', 'what is'], patterns: ['what is world hub', 'what is the world hub', 'how do i get to the hub', 'what is on the home page', 'what is smarter poker', 'what features are available'], answer: '**The World Hub** is your central command center in Smarter.Poker — a complete poker ecosystem.\n\n**All available Orbs (features):**\n- **Training Hub** — GTO scenarios, drills, and strategy mastery\n- **Diamond Store** — Purchase diamonds for premium features\n- **Club Arena** — Online poker rooms and clubs\n- **Club Commander** — Professional poker room management\n- **Bankroll Manager** — Track your poker finances (ORB-08)\n- **Social Media** — Community feed, posts, reels, and stories\n- **Poker Near Me** — Find live games in your area (ORB-04)\n- **Toke Tracker** — Track dealer tips and shift earnings\n- **Personal Assistant** — Jarvis AI coach + Virtual Sandbox\n- **Trivia Hub** — Poker trivia games to earn diamonds\n- **PokerIQ** — Comprehensive training assessment\n- **Video Library** — Poker strategy video collection\n- **News** — Curated poker news from top sources\n- **Events** — Tournament calendar and schedules\n\nEvery Orb is a self-contained world. Tap any one to enter.', followUps: ['What is the diamond economy?', 'How do I get started?', 'What features are free?'] },

    // ── VIP System ──
    { id: 'wh-19', category: 'VIP', keywords: ['vip', 'vip membership', 'upgrade', 'premium', 'subscription', 'vip tiers', 'free vs vip', 'membership'], patterns: ['what is vip membership', 'how do i become vip', 'what does vip unlock', 'what are vip tiers', 'what is the difference between free and vip'], answer: '**VIP Membership** unlocks the full power of Smarter.Poker.\n\n**Membership Tiers:**\n| Tier | Features |\n|------|----------|\n| **Free** | Basic training, limited trivia, social feed access |\n| **Basic** | All free + more training modes, history access |\n| **Pro** | All Basic + advanced analytics, priority support, extended Bankroll history |\n| **Elite** | All Pro + unlimited everything, exclusive events, custom avatar, coaching access |\n\n**Upgrade:** Hub > Diamond Store > Memberships\nOr use the billing section in Settings.\n\nVIP members also earn diamonds faster and access exclusive tournaments.', followUps: ['How much does VIP cost?', 'How do I pay for VIP?', 'What is the diamond economy?'] },

    // ── Diamond Economy ──
    { id: 'wh-20', category: 'Diamond Economy', keywords: ['diamonds', 'diamond economy', 'earn diamonds', 'spend diamonds', 'what are diamonds', 'diamond balance', 'gems'], patterns: ['what are diamonds', 'how do i earn diamonds', 'how do i spend diamonds', 'what is the diamond economy', 'what can i buy with diamonds'], answer: '**Diamonds** are the premium currency of Smarter.Poker.\n\n**Earning Diamonds:**\n- Complete daily training games\n- Win trivia matches\n- Daily login streak bonuses\n- Achieve training milestones\n- Win tournaments\n- Spin the Prize Wheel (daily)\n- VIP membership bonus allocation\n\n**Spending Diamonds:**\n- Premium avatar unlocks\n- Exclusive training content\n- Club Arena entry fees\n- Boost your profile visibility\n- Purchase special cosmetics\n- Enter Diamond Arena tournaments\n\n**Balance:** Tap the diamond icon in the header to see your total.', followUps: ['How do I spin the prize wheel?', 'What is the daily login bonus?', 'Can I gift diamonds?'] },

    // ── Prize Wheel ──
    { id: 'wh-21', category: 'Diamond Economy', keywords: ['prize wheel', 'spin', 'daily spin', 'wheel', 'free spin', 'spin prize'], patterns: ['how does the prize wheel work', 'how do i spin the prize wheel', 'what can i win on the wheel', 'how often can i spin'], answer: '**Prize Wheel** gives you free daily rewards.\n\n**How to spin:**\n1. Find the Prize Wheel on the hub or in Daily Rewards\n2. Tap **Spin** (available once per day)\n3. The wheel lands on a random prize\n\n**Possible prizes:**\n- Diamonds (small to large amounts)\n- VIP trial hours\n- Training session unlock\n- XP bonuses\n- Rare cosmetics (jackpot)\n\nVIP members get bonus spins and better prize odds. Consecutive days without missing increase your streak bonus.', followUps: ['How do I get more spins?', 'What is the best prize?', 'Does VIP improve my spin odds?'] },

    // ── Daily Streak ──
    { id: 'wh-22', category: 'Diamond Economy', keywords: ['daily streak', 'streak', 'login streak', 'consecutive days', 'streak bonus', 'daily bonus'], patterns: ['what is a daily streak', 'how does the streak work', 'what do i get for a streak', 'how do i keep my streak'], answer: '**Daily Streak** rewards you for visiting Smarter.Poker every day.\n\n- Log in on consecutive days to build your streak\n- Day 1: Small diamond bonus\n- Day 7: Medium bonus + special reward\n- Day 30: Large bonus + exclusive item\n- Day 100+: Elite bonuses and recognition\n\n**Missing a day resets your streak** back to Day 1.\n\nThe streak counter appears on your hub and profile. Set a daily reminder to never miss a day!', followUps: ['What is the longest possible streak reward?', 'Does VIP protect my streak?'] },

    // ── Achievements ──
    { id: 'wh-23', category: 'Platform', keywords: ['achievements', 'badges', 'trophies', 'accomplishments', 'milestones', 'rewards'], patterns: ['what are achievements', 'how do i earn badges', 'where do i see my achievements', 'how do achievements work'], answer: '**Achievements** are earned by hitting milestones across the platform.\n\n**Categories:**\n- **Training** — Complete X sessions, reach X% GTO accuracy\n- **Social** — Gain X followers, post X times\n- **Tournament** — Win your first tournament, final table X times\n- **Trivia** — Win X trivia matches, maintain X-day streak\n- **Bankroll** — Log X sessions, profitable for X months straight\n- **Diamond** — Earn X diamonds lifetime\n- **Platform** — Visit every Orb, reach Elite VIP\n\n**Rewards:** Each achievement grants diamonds, XP, and sometimes exclusive cosmetics. View all from Hub > Achievements.', followUps: ['How many achievements are there?', 'What do achievements unlock?'] },

    // ── XP System ──
    { id: 'wh-24', category: 'Platform', keywords: ['xp', 'experience points', 'level', 'leveling up', 'player level', 'rank'], patterns: ['what is xp', 'how do i level up', 'what does leveling up do', 'how is my level calculated'], answer: '**XP (Experience Points)** measure your overall activity and progress on Smarter.Poker.\n\n**Earning XP:**\n- Any activity on the platform (training, trivia, posting, playing)\n- Daily logins\n- Completing achievements\n- Winning tournaments\n\n**Leveling Up:**\n- Higher levels unlock profile decorations and rare achievements\n- Level is displayed on your profile as a badge\n- Some features have minimum level requirements\n\nXP is separate from diamonds — it measures activity, not currency.', followUps: ['What level do I unlock X?', 'How do I earn XP faster?'] },

    // ── Subscription / Billing ──
    { id: 'wh-25', category: 'Account', keywords: ['billing', 'subscription', 'payment', 'stripe', 'charge', 'cancel subscription', 'refund'], patterns: ['how do i manage my subscription', 'how do i cancel vip', 'how is billing handled', 'how do i get a refund'], answer: '**Subscription & Billing:**\n\n**Managing your plan:**\n1. Go to Settings > Billing (or Hub > Diamond Store > My Subscription)\n2. See current plan and renewal date\n3. Upgrade, downgrade, or cancel anytime\n\n**Payment:** Powered by **Stripe** — industry-leading secure payments. Accepts all major credit/debit cards.\n\n**Cancellation:** Cancel anytime. Your VIP access continues until the end of the billing period.\n\n**Refunds:** Contact support within 48 hours of charge for refund consideration.\n\n**Card issues:** Update your payment method from Settings > Billing.', followUps: ['How do I update my credit card?', 'When am I charged?', 'Can I pause my subscription?'] },

    // ── Account Security ──
    { id: 'wh-26', category: 'Account', keywords: ['password', 'security', '2fa', 'two factor', 'account security', 'change password', 'email'], patterns: ['how do i change my password', 'how do i enable 2fa', 'how do i change my email', 'is my account secure'], answer: '**Account Security:**\n\n**Change Password:**\n1. Settings > Account Security > Change Password\n2. Enter current password, then new password twice\n3. Save\n\n**Change Email:**\n- Settings > Account Security > Update Email\n- Verification sent to new email\n\n**Two-Factor Authentication (2FA):**\n- Settings > Account Security > Enable 2FA\n- Scan QR code with authenticator app (Google Authenticator, Authy)\n- Enter 6-digit code to confirm\n\n**Session Management:**\n- See all active sessions\n- Log out from all devices remotely\n\nAll authentication is powered by Supabase with enterprise-grade encryption.', followUps: ['What do I do if my account is hacked?', 'How do I delete my account?'] },

    // ── Profile ──
    { id: 'wh-2', category: 'Profile', keywords: ['profile', 'edit profile', 'username', 'bio', 'avatar', 'profile picture', 'display name'], patterns: ['how do i edit my profile', 'how to change my profile', 'where is my profile', 'how do i change my username', 'how do i change my avatar'], answer: 'To **edit your profile**, tap your avatar in the top-left corner or navigate to **Settings > Profile**.\n\n**Editable fields:**\n- **Display Name** — How others see you\n- **Username** — Your unique @handle (changeable once per 30 days)\n- **Bio** — Up to 150 characters\n- **Avatar** — Choose from the gallery or upload your own (VIP)\n- **Banner Image** — Custom profile header\n- **Location** — Optional\n- **Poker Focus** — Cash, MTT, or mixed\n\nAll changes save in real-time to Supabase and sync across devices instantly.', followUps: ['How do I change my avatar?', 'Where can I see my stats?', 'How do I add friends?'] },

    // ── Avatars ──
    { id: 'wh-3', category: 'Profile', keywords: ['avatar', 'avatars', 'profile picture', 'character', 'change avatar', 'custom avatar', 'avatar gallery'], patterns: ['how do i change my avatar', 'what avatars are available', 'how to get new avatars', 'can i upload my own avatar'], answer: '**Avatars** are your visual identity across Smarter.Poker.\n\n- **Free Avatars** — 20+ default options available to everyone\n- **Premium Avatars** — Unlock with diamonds or VIP membership\n- **Diamond Avatars** — Rare, special editions earned through gameplay\n- **Custom Upload** — Pro and Elite VIP members upload their own image\n- **Animated Avatars** — Elite-tier exclusive animated options\n\n**To change:** Profile > Edit Profile > Change Avatar (or Avatar Gallery from the hub)\n\nYour avatar appears everywhere: hub, social feed, leaderboards, club arena, and trivia.', followUps: ['How do I become VIP?', 'What does Elite VIP unlock?'] },

    // ── Settings ──
    { id: 'wh-4', category: 'Settings', keywords: ['settings', 'preferences', 'notifications', 'privacy', 'account', 'security', 'theme', 'dark mode'], patterns: ['where are my settings', 'how do i change settings', 'how do i manage notifications', 'how to change privacy', 'how do i enable dark mode'], answer: 'Access **Settings** from the hamburger menu (top-right) or your profile page.\n\n**Available sections:**\n- **Profile** — Edit name, bio, avatar, banner\n- **Notifications** — Toggle push, email, and in-app alerts per type\n- **Privacy** — Control who sees your profile, stats, and posts\n- **Account Security** — Password, email, 2FA, active sessions\n- **Billing** — Manage subscription and payment methods\n- **Display** — Theme (auto dark/light based on system)\n- **Accessibility** — Font size, reduced motion\n- **Connected Apps** — Link external accounts\n\nAll settings persist in real-time via Supabase.', followUps: ['How do I turn off notifications?', 'How do I make my profile private?'] },

    // ── Friends ──
    { id: 'wh-5', category: 'Social', keywords: ['friends', 'add friend', 'friend request', 'follow', 'followers', 'following', 'find friends'], patterns: ['how do i add friends', 'how to find friends', 'where are my friends', 'how do i follow someone', 'how to accept a friend request'], answer: '**Friends & Following:**\n\n**Sending a friend request:**\n1. Search for a player by username or display name\n2. Visit their profile\n3. Tap **Add Friend**\n4. They accept → you are connected\n\n**Following (no approval needed):**\n- Tap **Follow** on any public profile\n- Their public content appears in your feed\n\n**Friend benefits:**\n- See each other\'s private posts\n- Direct message access\n- Challenge to PvP trivia\n- See online status\n- Club Arena friend games\n\nFind the **Friends** hub from the hamburger menu or main hub.', followUps: ['How do I send a message?', 'How do I unfriend someone?', 'What is the difference between friends and followers?'] },

    // ── Messenger ──
    { id: 'wh-6', category: 'Social', keywords: ['messenger', 'messages', 'dm', 'direct message', 'chat', 'inbox', 'blocked', 'message requests'], patterns: ['how do i send a message', 'where is messenger', 'how to dm someone', 'how do i use messenger', 'how do i see my messages'], answer: '**Messenger** is the built-in real-time direct messaging system.\n\n**Features:**\n- **1-on-1 chats** — Private conversations with friends\n- **Message Requests** — Messages from non-friends arrive here for approval\n- **Blocked Users** — Manage who cannot contact you\n- **Read Receipts** — See when a message was read\n- **Real-time** — Delivered instantly via Supabase Realtime\n- **Media** — Send images within conversations\n\n**To start a conversation:**\n1. Go to Hub > Messenger (or hamburger menu)\n2. Tap the compose (+) button\n3. Search for the person\n4. Send your first message\n\nYou can also message someone from their profile page.', followUps: ['How do I delete a conversation?', 'Can I block someone?', 'Are messages private?'] },

    // ── Social Media ──
    { id: 'wh-7', category: 'Social', keywords: ['social media', 'feed', 'posts', 'post', 'create post', 'social hub', 'community', 'social page'], patterns: ['how do i create a post', 'what is social media', 'how to post', 'how does the social feed work', 'where is the social page'], answer: '**Social Media** is the community feed where players share content, strategies, and highlights.\n\n**Creating a Post:**\n1. Navigate to Social Media\n2. Tap the compose box at the top\n3. Write content, add images/videos\n4. Set visibility (Public / Friends / Followers)\n5. Tap **Post**\n\n**Feed Features:**\n- Like, comment, and share posts\n- Stories row at the top (24-hour content)\n- Reel clips in a vertical scroll format\n- Filter by: Trending / Latest / Friends-only\n- Explore page for discovering new players\n- Hashtag browsing (#poker, #gto, etc.)', followUps: ['How do I upload a reel?', 'How do I create a social page?', 'What are stories?'] },

    // ── Reels ──
    { id: 'wh-9', category: 'Social', keywords: ['reels', 'video', 'short video', 'upload reel', 'my reels', 'saved reels', 'reel'], patterns: ['how do i upload a reel', 'what are reels', 'how to watch reels', 'how to make a reel', 'where do i see reels'], answer: '**Reels** are short-form video clips (up to 60 seconds), designed for poker highlights and strategy tips.\n\n**Uploading a Reel:**\n1. Navigate to Social Media > Reels tab\n2. Tap the upload / camera button\n3. Select a video from your device\n4. Trim to 60 seconds or less\n5. Add caption, hashtags, and tags\n6. Set visibility and post\n\n**Browsing:**\n- Vertical scrolling feed\n- Like, comment, save, and share\n- Categories: Strategy, Hand Reviews, Funny Moments, Tournament Highlights\n- **My Reels** — Your uploads\n- **Saved Reels** — Your bookmarks', followUps: ['How do I save a reel?', 'Can I delete a reel?', 'How do I get more reel views?'] },

    // ── Notifications ──
    { id: 'wh-10', category: 'Platform', keywords: ['notifications', 'alerts', 'push notifications', 'bell icon', 'notification center', 'turn off notifications'], patterns: ['how do i manage notifications', 'where are my notifications', 'how to turn off notifications', 'how to enable push notifications'], answer: '**Notifications** keep you updated on activity across the platform.\n\n**Types:**\n- **Social** — Likes, comments, friend requests, mentions\n- **Training** — Streak reminders, achievement unlocks, new challenges\n- **Tournament** — Registration confirmations, start times, results, payout processing\n- **System** — Platform updates, maintenance windows, promotions\n- **Messenger** — New direct messages\n\n**Managing:**\n- Tap the bell icon in the header to see recent notifications\n- Settings > Notifications to customize per type:\n  - Toggle push notifications (on/off per type)\n  - Toggle email notifications\n  - Toggle in-app banners\n- Mark all as read in one tap', followUps: ['How do I enable push notifications on iOS?', 'Can I mute specific types?'] },

    // ── Install ──
    { id: 'wh-15', category: 'Platform', keywords: ['install', 'download', 'app', 'pwa', 'add to home screen', 'web app', 'mobile', 'ios', 'android'], patterns: ['how do i install the app', 'how to download smarter poker', 'how do i add to home screen', 'is there a mobile app', 'how do i use on my phone'], answer: '**Smarter.Poker is a Progressive Web App (PWA)** — no app store required.\n\n**Installing on iPhone (iOS Safari):**\n1. Open smarter.poker in Safari\n2. Tap the Share button (square with arrow)\n3. Scroll down and tap **Add to Home Screen**\n4. Tap **Add** — the icon appears on your home screen!\n\n**Installing on Android (Chrome):**\n1. Open smarter.poker in Chrome\n2. Tap the three-dot menu\n3. Tap **Install App** or **Add to Home Screen**\n4. Tap **Install**\n\n**On Desktop:**\nClick the install icon in the address bar (Chrome/Edge)\n\n**Benefits:** Works offline for cached content, push notifications, full-screen mode, automatic updates.', followUps: ['Do push notifications work on iOS?', 'Does it work offline?'] },

    // ── News ──
    { id: 'wh-11', category: 'Platform', keywords: ['news', 'poker news', 'articles', 'news feed', 'sources', 'poker articles', 'news page'], patterns: ['where is the news page', 'how do i read poker news', 'what news sources are available', 'where can i read poker news'], answer: '**News Hub** aggregates the latest poker news from top industry sources.\n\n**Features:**\n- Curated articles from major poker outlets (PokerNews, CardPlayer, PokerStrategy, etc.)\n- Filter by **Source**, **Category**, or **Date**\n- Full article reading in-app\n- Share articles to your social feed\n- Save articles for later\n- Breaking news notifications (if enabled)\n\nAccess from Hub > News Orb. Always up to date with tournament results, industry announcements, and strategy content.', followUps: ['Can I filter by topic?', 'How do I share an article?'] },

    // ── Video Library ──
    { id: 'wh-12', category: 'Platform', keywords: ['video library', 'videos', 'watch', 'poker videos', 'strategy videos', 'training videos'], patterns: ['where is the video library', 'how do i watch videos', 'what videos are available', 'are there training videos'], answer: '**Video Library** is a curated collection of poker strategy and training videos.\n\n**Categories:**\n- Hand Reviews — Expert analysis of interesting hands\n- Tournament Strategy — How to approach MTTs and SNGs\n- GTO Fundamentals — Solver-based strategy explanations\n- Cash Game Tactics — Live and online cash game tips\n- Beginner Series — Complete poker foundations\n- Pro Interviews — Conversations with elite players\n\nVideos are available to all users. VIP members get early access to new content and exclusive series.', followUps: ['Are all videos free?', 'Can I save videos to watch later?'] },

    // ── Events Calendar ──
    { id: 'wh-13', category: 'Platform', keywords: ['events calendar', 'calendar', 'events', 'schedule', 'upcoming events', 'tournament calendar'], patterns: ['where is the events calendar', 'how do i see upcoming events', 'what events are coming up', 'where do i find poker tournaments'], answer: '**Events Calendar** shows all upcoming poker events, tournaments, and special promotions.\n\n**Features:**\n- View by Day, Week, or Month\n- Filter by: Location / Buy-in range / Game type / Online vs live\n- Set personal reminders for any event\n- Synced with Poker Near Me venue data\n- Online Club Arena tournaments integrated\n- Official series (WSOP, WPT, EPT) listed\n\n**Adding to your calendar:**\n- Tap any event > Save Event\n- It appears in your personal events list\n- Reminder notification sent automatically', followUps: ['How do I add my own event?', 'Can I filter by buy-in size?'] },

    // ── Leaderboards ──
    { id: 'wh-14', category: 'Platform', keywords: ['leaderboards', 'rankings', 'top players', 'leaderboard', 'ranking', 'standings', 'top list'], patterns: ['where are the leaderboards', 'how do leaderboards work', 'how do i see my ranking', 'am i on the leaderboard'], answer: '**Leaderboards** rank top performers across every category.\n\n**Categories:**\n- **Training Accuracy** — Highest average GTO decision accuracy\n- **Trivia** — Most diamonds won, longest winning streak\n- **Tournament Wins** — Most victories in Club Arena tournaments\n- **Diamond Arena** — Biggest diamond earners\n- **Social Influence** — Most followers and engagement\n- **Bankroll** — Highest reported win rates (opt-in)\n- **Toke Tracker** — Top earning dealers (opt-in)\n\n**Periods:** Daily, Weekly, Monthly, All-Time\n\n**Rewards:** Top 10 players get diamond bonuses each period. Tap your name to see your full ranking breakdown.', followUps: ['How do I earn more training accuracy?', 'Are leaderboard prizes automatic?'] },

    // ── Marketplace ──
    { id: 'wh-16', category: 'Platform', keywords: ['marketplace', 'buy', 'sell', 'products', 'merch', 'merchandise', 'shop', 'store'], patterns: ['what is the marketplace', 'how do i buy from marketplace', 'what can i buy', 'is there a shop'], answer: '**Marketplace** is your poker gear and digital products hub.\n\n**Available:**\n- Official Smarter.Poker merchandise (apparel, accessories)\n- Club-branded items\n- Digital training tools\n- Poker card protectors, chips sets (partner brands)\n- Coaching session bookings (from approved coaches)\n\n**Payment:** Credit card or diamond balance (for digital items)\n\nAccess from Hub > Marketplace or hamburger menu.', followUps: ['How do I pay?', 'Can I sell my own coaching?'] },

    // ── Social Pages ──
    { id: 'wh-8', category: 'Social', keywords: ['social pages', 'create page', 'business page', 'club page', 'brand page', 'poker club page'], patterns: ['how do i create a social page', 'what are social pages', 'how to make a club page', 'how to create a brand page'], answer: '**Social Pages** are public profiles for clubs, brands, coaches, and organizations.\n\n**Creating a Page:**\n1. Go to Social > My Pages > Create Page\n2. Choose a category: Poker Club / Coaching / Content Creator / Organization\n3. Set name, description, logo, and banner\n4. Add admin team\n5. Start posting!\n\n**Page Features:**\n- **Unlimited followers** (no 5,000 friend limit)\n- Multiple page admins with role management\n- Post analytics: reach, impressions, engagement rate\n- Verification badge (apply after 500 followers)\n- Scheduled posts and content calendar\n- Events and promotions posting', followUps: ['How do I get verified?', 'Can I run ads on my page?'] },

    // ── Help ──
    { id: 'wh-17', category: 'Platform', keywords: ['help', 'support', 'faq', 'contact', 'customer support', 'help page', 'get help', 'bug report'], patterns: ['how do i get help', 'where is customer support', 'how do i contact support', 'is there a help page', 'how do i report a bug'], answer: '**Getting Help:**\n\n1. **Ask Geeves** (that\'s me!) — I know every feature, page, and workflow on Smarter.Poker. Just ask!\n2. **Help Center** — Visit /hub/help for written guides and FAQs\n3. **Email Support** — Contact the team for account-specific issues\n4. **Report a Bug** — Settings > Report a Bug or feedback button\n\n**Common self-service fixes:**\n- Forgotten password: Login page > Forgot Password\n- Billing issue: Settings > Billing\n- Missing diamonds: Check your transaction history\n- App not loading: Clear cache and try again\n\nI can solve most issues instantly — just describe your problem!', followUps: ['How do I reset my password?', 'My diamonds are missing, what do I do?'] },

    // ── Auth ──
    { id: 'wh-18', category: 'Account', keywords: ['login', 'sign up', 'register', 'forgot password', 'reset password', 'sign in', 'account', 'create account', 'new account'], patterns: ['how do i sign up', 'how do i create an account', 'how do i reset my password', 'i forgot my password', 'how do i log in', 'how to register'], answer: '**Account Management:**\n\n**Sign Up:**\n1. Go to smarter.poker\n2. Tap **Sign Up**\n3. Enter email and password (min 8 chars)\n4. Verify your email (check spam if needed)\n5. Complete profile setup\n6. Explore the hub!\n\n**Log In:**\n- Email + password\n- Your session persists for 30 days\n\n**Forgot Password:**\n1. Login page > **Forgot Password**\n2. Enter your email\n3. Check inbox for reset link (valid 1 hour)\n4. Set new password\n5. Log in with new credentials\n\n**Trouble?** Check spam folder. Email addresses are case-sensitive.', followUps: ['How do I enable 2FA?', 'Can I log in with Google?'] },

    // ── Poker IQ ──
    { id: 'wh-27', category: 'Training', keywords: ['pokeriq', 'poker iq', 'iq test', 'poker test', 'skill assessment', 'skill level'], patterns: ['what is pokeriq', 'how does the poker iq test work', 'how do i assess my skill level', 'what is my poker iq'], answer: '**PokerIQ** is your comprehensive poker skill assessment.\n\n- Take a structured test across key skill areas\n- Areas tested: Hand reading, position, pot odds, GTO concepts, tournament strategy\n- Receive a **PokerIQ Score** (0-200)\n- See detailed breakdown by skill area\n- Get a **personalized training plan** based on weak areas\n- Re-test after 30 days to track improvement\n\nYour PokerIQ score is displayed on your profile and is a great tool to guide your study focus.', followUps: ['How long does the PokerIQ test take?', 'Can I retake the test?', 'What score is considered good?'] },

    // ── Personal Assistant / Jarvis ──
    { id: 'wh-28', category: 'Training', keywords: ['jarvis', 'personal assistant', 'ai coach', 'ai advisor', 'strategy advice', 'hand analysis', 'solver'], patterns: ['what is jarvis', 'how do i use the personal assistant', 'how does jarvis work', 'how do i get hand analysis', 'can ai help me study'], answer: '**Jarvis** is your elite AI poker coach — SUPREME-COMMANDER level intelligence.\n\n**Capabilities:**\n- Analyze any poker hand with GTO precision\n- Explain optimal plays and reasoning\n- Generate training scenarios targeting your weak areas\n- Post-game session analysis\n- Range construction advice\n- Spot-specific strategy (tournament bubble, heads-up, etc.)\n\n**Access:**\n- Personal Assistant Orb (hub)\n- Virtual Sandbox for interactive hand analysis\n- After any training game for instant feedback\n\nJarvis uses solver-grade logic to give you pro-level analysis instantly.', followUps: ['How do I set up a hand for Jarvis?', 'What is the Virtual Sandbox?', 'Is Jarvis advice always correct?'] },
];
