/* World Hub & Platform Knowledge */
export const WORLD_HUB_ENTRIES = [
    // ── World Hub Home ──
    { id: 'wh-1', category: 'World Hub', keywords: ['world hub', 'home', 'main page', 'landing', 'orbs', 'dashboard'], patterns: ['what is world hub', 'what is the world hub', 'how do i get to the hub', 'what is on the home page'], answer: '**The World Hub** is your central command center in Smarter.Poker. It displays all available **Orbs** — interactive portals to every feature on the platform. From here you can access:\n\n- **Training Games** — GTO scenarios, trivia, and strategy drills\n- **Diamond Store** — Purchase diamonds for premium features\n- **Club Arena** — Online poker rooms and clubs\n- **Club Commander** — Poker room management system\n- **Bankroll Manager** — Track your poker finances\n- **Social Media** — Community feed, posts, and reels\n- **Poker Near Me** — Find live games in your area\n- **Toke Tracker** — Track dealer tips and earnings\n- **Personal Assistant** — Jarvis AI strategy coach\n\nEach Orb glows and animates — just tap one to enter that world.', followUps: ['How do I customize my hub?', 'What are diamonds used for?', 'How do I access training?'] },

    // ── Profile ──
    { id: 'wh-2', category: 'Profile', keywords: ['profile', 'edit profile', 'username', 'bio', 'avatar', 'profile picture'], patterns: ['how do i edit my profile', 'how to change my profile', 'where is my profile', 'how do i change my username', 'how do i change my avatar'], answer: 'To **edit your profile**, tap your avatar in the top-left corner or navigate to **Settings > Profile**.\n\nYou can change:\n- **Display Name** — How others see you\n- **Username** — Your unique @handle\n- **Bio** — A short description about yourself\n- **Avatar** — Choose from our avatar gallery or upload your own\n- **Banner Image** — Customize your profile header\n\nAll changes save in real-time to Supabase.', followUps: ['How do I change my avatar?', 'Where can I see my stats?', 'How do I add friends?'] },

    // ── Avatars ──
    { id: 'wh-3', category: 'Profile', keywords: ['avatar', 'avatars', 'profile picture', 'character', 'change avatar'], patterns: ['how do i change my avatar', 'what avatars are available', 'how to get new avatars'], answer: '**Avatars** are your visual identity across Smarter.Poker. Access the **Avatar Gallery** from your profile or hub.\n\n- **Free Avatars** — Several default options available to everyone\n- **Premium Avatars** — Unlock with diamonds or VIP membership\n- **Custom Upload** — VIP members can upload their own image\n\nYour avatar appears in the hub, social feed, leaderboards, and club arena.', followUps: ['How do I become VIP?', 'What does VIP unlock?'] },

    // ── Settings ──
    { id: 'wh-4', category: 'Settings', keywords: ['settings', 'preferences', 'notifications', 'privacy', 'account', 'security'], patterns: ['where are my settings', 'how do i change settings', 'how do i manage notifications', 'how to change privacy'], answer: 'Access **Settings** from the hamburger menu or your profile page.\n\nAvailable settings:\n- **Profile** — Edit name, bio, avatar, banner\n- **Notifications** — Toggle push, email, and in-app alerts\n- **Privacy** — Control who sees your profile, stats, and posts\n- **Account Security** — Change password, enable 2FA\n- **Display** — Theme preferences\n- **Connected Accounts** — Link social media\n\nAll settings save automatically.', followUps: ['How do I turn off notifications?', 'How do I delete my account?'] },

    // ── Friends ──
    { id: 'wh-5', category: 'Social', keywords: ['friends', 'add friend', 'friend request', 'follow', 'followers', 'following'], patterns: ['how do i add friends', 'how to find friends', 'where are my friends', 'how do i follow someone'], answer: 'The **Friends** page lets you manage your social connections.\n\n**Adding Friends:**\n1. Search by username or display name\n2. Tap **Add Friend** to send a request\n3. They accept, and you are connected\n\n**Features:**\n- See friends\' online status\n- View their recent activity\n- Challenge them to trivia PvP\n- Send direct messages via Messenger\n\nFind the Friends page in the hub or hamburger menu.', followUps: ['How do I send a message?', 'How do I block someone?'] },

    // ── Messenger ──
    { id: 'wh-6', category: 'Social', keywords: ['messenger', 'messages', 'dm', 'direct message', 'chat', 'inbox', 'blocked'], patterns: ['how do i send a message', 'where is messenger', 'how to dm someone', 'how do i use messenger'], answer: '**Messenger** is the built-in direct messaging system.\n\n**Features:**\n- **1-on-1 chats** with friends\n- **Message requests** from non-friends\n- **Blocked users** management\n- **Read receipts** and timestamps\n- **Real-time** delivery via Supabase\n\n**To send a message:**\n1. Go to Messenger from the hub or hamburger menu\n2. Tap the compose button or select a conversation\n3. Type and send\n\nYou can also message someone directly from their profile.', followUps: ['How do I block someone?', 'How do I delete a conversation?'] },

    // ── Social Media ──
    { id: 'wh-7', category: 'Social', keywords: ['social media', 'feed', 'posts', 'post', 'create post', 'social hub', 'community'], patterns: ['how do i create a post', 'what is social media', 'how to post', 'how does the social feed work'], answer: '**Social Media** is the community feed where players share content.\n\n**Creating a Post:**\n1. Navigate to Social Media\n2. Tap the **Create Post** button at the top\n3. Write your content, add images or videos\n4. Choose visibility (public/friends only)\n5. Tap **Post**\n\n**Feed Features:**\n- Like, comment, and share posts\n- Follow other players\n- View Stories at the top of the feed\n- Filter by trending, latest, or friends\n- Upload and watch **Reels** (short video clips)', followUps: ['How do I upload a reel?', 'How do I create a social page?'] },

    // ── Social Pages ──
    { id: 'wh-8', category: 'Social', keywords: ['social pages', 'create page', 'business page', 'club page', 'brand page'], patterns: ['how do i create a social page', 'what are social pages', 'how to make a club page'], answer: '**Social Pages** are public profiles for clubs, brands, or communities.\n\n**Creating a Page:**\n1. Go to Social Pages from the hub\n2. Tap **Create Page**\n3. Choose a name, category, and description\n4. Upload a logo and banner\n5. Start posting content\n\n**Page Features:**\n- Custom branding and verification\n- Follower count and analytics\n- Post scheduling\n- Multiple admin support\n\nPerfect for poker clubs, training groups, or content creators.', followUps: ['How do I get my page verified?', 'Can I have multiple admins?'] },

    // ── Reels ──
    { id: 'wh-9', category: 'Social', keywords: ['reels', 'video', 'short video', 'upload reel', 'my reels', 'saved reels'], patterns: ['how do i upload a reel', 'what are reels', 'how to watch reels', 'how to make a reel'], answer: '**Reels** are short-form video clips, similar to TikTok or Instagram Reels.\n\n**Uploading a Reel:**\n1. Navigate to Reels from the hub\n2. Tap the upload button\n3. Select a video from your device\n4. Add a caption and tags\n5. Post it\n\n**Features:**\n- Vertical scrolling feed\n- Like, comment, and share\n- **My Reels** — View your uploads\n- **Saved Reels** — Bookmark favorites\n\nGreat for sharing poker highlights, strategy clips, or fun moments.', followUps: ['How do I save a reel?', 'Can I delete a reel?'] },

    // ── Notifications ──
    { id: 'wh-10', category: 'Platform', keywords: ['notifications', 'alerts', 'push notifications', 'bell icon'], patterns: ['how do i manage notifications', 'where are my notifications', 'how to turn off notifications'], answer: '**Notifications** keep you updated on activity across the platform.\n\n**Types:**\n- **Social** — Likes, comments, friend requests\n- **Training** — Streak reminders, achievement unlocks\n- **Tournament** — Registration, start times, results\n- **System** — Updates, maintenance, promotions\n\n**Managing Notifications:**\n- Tap the bell icon in the header\n- Go to Settings > Notifications to customize\n- Toggle push, email, and in-app individually\n- Once dismissed, they won\'t reappear (stored by IP)', followUps: ['How do I enable push notifications?', 'Can I mute specific notification types?'] },

    // ── News ──
    { id: 'wh-11', category: 'Platform', keywords: ['news', 'poker news', 'articles', 'news feed', 'sources'], patterns: ['where is the news page', 'how do i read poker news', 'what news sources are available'], answer: '**News** aggregates the latest poker news from top sources.\n\n- Browse curated articles from major poker outlets\n- Filter by **Sources** to see specific publishers\n- Tap any article to read the full content\n- Share articles to your social feed\n\nStay up to date with tournament results, industry news, and strategy articles all in one place.', followUps: ['Can I add custom news sources?', 'How do I share an article?'] },

    // ── Video Library ──
    { id: 'wh-12', category: 'Platform', keywords: ['video library', 'videos', 'watch', 'poker videos', 'strategy videos'], patterns: ['where is the video library', 'how do i watch videos', 'what videos are available'], answer: '**Video Library** is a collection of poker strategy and training videos.\n\n- Browse by category: strategy, hand reviews, tournaments\n- Watch directly in the app\n- Bookmark favorites for later\n- New content added regularly\n\nPerfect for studying away from the felt.', followUps: ['Are videos free?', 'Can I upload my own videos?'] },

    // ── Events Calendar ──
    { id: 'wh-13', category: 'Platform', keywords: ['events calendar', 'calendar', 'events', 'schedule', 'upcoming events'], patterns: ['where is the events calendar', 'how do i see upcoming events', 'what events are coming up'], answer: '**Events Calendar** shows all upcoming poker events and tournaments.\n\n- View by day, week, or month\n- Filter by location, buy-in, or game type\n- Set reminders for events you want to attend\n- Synced with Poker Near Me venue data\n\nNever miss a tournament series or special event.', followUps: ['How do I set a reminder?', 'How do I add my own event?'] },

    // ── Leaderboards ──
    { id: 'wh-14', category: 'Platform', keywords: ['leaderboards', 'rankings', 'top players', 'leaderboard', 'ranking'], patterns: ['where are the leaderboards', 'how do leaderboards work', 'how do i see my ranking'], answer: '**Leaderboards** track top performers across the platform.\n\n**Categories:**\n- **Training** — Highest GTO accuracy scores\n- **Trivia** — Most points and longest streaks\n- **Diamond Arena** — Tournament performance\n- **Social** — Most followers and engagement\n\nLeaderboards reset on different schedules (daily, weekly, monthly, all-time). Compete for bragging rights and diamond rewards!', followUps: ['How do I climb the leaderboard?', 'Are there rewards for top players?'] },

    // ── Install / PWA ──
    { id: 'wh-15', category: 'Platform', keywords: ['install', 'download', 'app', 'pwa', 'add to home screen', 'web app'], patterns: ['how do i install the app', 'how to download smarter poker', 'how do i add to home screen', 'is there a mobile app'], answer: '**Smarter.Poker is a Progressive Web App (PWA)** — no app store download needed!\n\n**To Install:**\n1. Open smarter.poker in your mobile browser\n2. Tap the **Install** prompt (or "Add to Home Screen")\n3. The app icon appears on your home screen\n4. Launch it like any native app\n\n**Benefits:**\n- Works offline for cached content\n- Push notifications\n- Full-screen experience\n- Automatic updates\n\nAvailable on iOS Safari, Android Chrome, and desktop browsers.', followUps: ['Do I need to create an account?', 'Is it free to use?'] },

    // ── Marketplace ──
    { id: 'wh-16', category: 'Platform', keywords: ['marketplace', 'buy', 'sell', 'products', 'merch', 'merchandise'], patterns: ['what is the marketplace', 'how do i buy from marketplace', 'what can i buy'], answer: '**Marketplace** is where you can browse and purchase poker-related products and merchandise.\n\n- Official Smarter.Poker merch\n- Club-branded items\n- Digital products and tools\n- Browse by category or search\n\nAll transactions are secure and integrated with your account.', followUps: ['How do I pay?', 'Can I sell my own items?'] },

    // ── Help Page ──
    { id: 'wh-17', category: 'Platform', keywords: ['help', 'support', 'faq', 'contact', 'customer support', 'help page'], patterns: ['how do i get help', 'where is customer support', 'how do i contact support', 'is there a help page'], answer: '**Need help?** You have several options:\n\n1. **Ask Geeves** (that\'s me!) — I\'m available in every hamburger menu\n2. **Help Page** — Browse FAQs and guides at /hub/help\n3. **Email Support** — Contact the team directly\n\nI can answer questions about every feature, page, and tool on Smarter.Poker instantly. Just ask!', followUps: ['How do I report a bug?', 'How do I reset my password?'] },

    // ── Auth ──
    { id: 'wh-18', category: 'Account', keywords: ['login', 'sign up', 'register', 'forgot password', 'reset password', 'sign in', 'account'], patterns: ['how do i sign up', 'how do i create an account', 'how do i reset my password', 'i forgot my password', 'how do i log in'], answer: '**Account Management:**\n\n**Sign Up:**\n1. Go to smarter.poker\n2. Tap **Sign Up**\n3. Enter email and create a password\n4. Verify your email\n5. Complete your profile\n\n**Log In:**\n- Use email + password\n- Session persists across visits\n\n**Forgot Password:**\n1. Tap **Forgot Password** on the login page\n2. Enter your email\n3. Check your inbox for a reset link\n4. Create a new password\n\nAll authentication is powered by Supabase with enterprise-grade security.', followUps: ['How do I enable 2FA?', 'Can I change my email?'] },
];
