"""Assemble the shipped intro-v1 art set into the worktree (p4-art).

python3 build.py <worktree>
  * copies each family's mobile + wide files from export/<id>/ to
    public/images/trivia/intro-v1/ (and removes files no longer listed)
  * writes src/config/triviaIntroArt.mjs (generated, framework-free)
  * writes docs/trivia/evidence/p4-art-intro-art-manifest.json (provenance)
"""
import json, os, shutil, sys, hashlib
HERE = os.path.dirname(os.path.abspath(__file__))
ORDER = ['lobby', 'daily', 'arcade', 'history', 'rules', 'pro', 'mtt', 'cash', 'icm', 'gto',
         'endless', 'mixed', 'survival', 'time-attack', 'pvp', 'tournaments']
VERSION = 'intro-v1'
URL = f'/images/trivia/{VERSION}'

def const_name(i): return 'TRIVIA_INTRO_ART_' + i.upper().replace('-', '_')

def srcset(files, fmt):
    return ', '.join(f"{URL}/{f['file']} {f['width']}w" for f in sorted((x for x in files if x['format'] == fmt), key=lambda x: x['width']))

def main(wt):
    out_dir = os.path.join(wt, 'public', 'images', 'trivia', VERSION)
    os.makedirs(out_dir, exist_ok=True)
    recs, keep = {}, set()
    for i in ORDER:
        r = json.load(open(os.path.join(HERE, 'export', i, 'export.json')))
        recs[i] = r
        for c in ('mobile', 'wide'):
            for f in r['crops'][c]['files']:
                keep.add(f['file'])
                shutil.copyfile(os.path.join(HERE, 'export', i, f['file']), os.path.join(out_dir, f['file']))
    for name in os.listdir(out_dir):
        if name not in keep: os.remove(os.path.join(out_dir, name))
    lines = [
        '/**',
        ' * GENERATED by scripts/trivia-art/build.py from the p4-art export records.',
        ' * Do not edit by hand; re-run the pipeline in scripts/trivia-art/.',
        ' *',
        ' * One destination intro master per Trivia family, distinct from that',
        " * family's lobby thumbnail. Each entry is a 16:10 mobile crop and a 12:5",
        ' * wide crop, AVIF + WebP at 640/960/1440, content-hashed file names, and a',
        ' * 32x20 preview painted into the reserved box until the picture decodes.',
        ' * Provenance (prompts, seeds, model, licence, crops, grade, hashes):',
        ' * docs/trivia/evidence/p4-art-intro-art-manifest.json',
        ' */',
        '',
        f"export const TRIVIA_INTRO_ART_VERSION = '{VERSION}';",
        '',
        'const crop = (width, height, avif, webp, src) => Object.freeze({ width, height, avif, webp, src });',
        'const art = (key, preview, mobile, wide) => Object.freeze({ key, preview, mobile, wide });',
        '',
    ]
    for i in ORDER:
        r = recs[i]; m = r['crops']['mobile']['files']; w = r['crops']['wide']['files']
        mf = max((f for f in m if f['format'] == 'webp'), key=lambda f: f['width'])
        wf = max((f for f in w if f['format'] == 'webp'), key=lambda f: f['width'])
        fb = next(f for f in m if f['format'] == 'webp' and f['width'] == 960)
        wfb = next(f for f in w if f['format'] == 'webp' and f['width'] == 960)
        lines += [
            f"export const {const_name(i)} = art(",
            f"    '{i}',",
            f"    '{r['lqip']}',",
            f"    crop({mf['width']}, {mf['height']}, '{srcset(m, 'avif')}', '{srcset(m, 'webp')}', '{URL}/{fb['file']}'),",
            f"    crop({wf['width']}, {wf['height']}, '{srcset(w, 'avif')}', '{srcset(w, 'webp')}', '{URL}/{wfb['file']}'),",
            ');',
            '',
        ]
    lines += ['export const TRIVIA_INTRO_ART = Object.freeze({']
    lines += [f"    '{i}': {const_name(i)}," for i in ORDER]
    lines += ['});', '']
    mod = os.path.join(wt, 'src', 'config', 'triviaIntroArt.mjs')
    open(mod, 'w').write('\n'.join(lines))
    prov = {
        'version': VERSION, 'generated_by': 'scripts/trivia-art (p4-art, Trivia Phase 4)',
        'model': 'Tongyi-MAI/Z-Image-Turbo', 'model_licence': 'Apache-2.0',
        'runner': 'mflux 0.19.2 (MIT) on mlx 0.32.3, Apple M3 Ultra, 1536x1024, default turbo settings',
        'rules': 'text-free, no logos, no real people, no brand marks; essential copy is live HTML',
        'families': {},
    }
    for i in ORDER:
        r = recs[i]
        prov['families'][i] = {
            'seed': r['seed'], 'prompt_sha256': r['prompt_sha256'],
            'prompt': open(os.path.join(HERE, r['prompt_file'])).read(),
            'source_sha256': r['source_sha256'], 'generation': r['generation'],
            'grade': r['grade'], 'dissolve_edges': r['dissolve_edges'], 'shift': r['shift'],
            'encoders': r['encoders'], 'preview_sha256': hashlib.sha256(r['lqip'].encode()).hexdigest(),
            'crops': {c: {'box': r['crops'][c]['box'], 'ratio': r['crops'][c]['ratio'],
                          'files': [{k: f[k] for k in ('file', 'format', 'width', 'height', 'bytes', 'sha256')} for f in r['crops'][c]['files']]}
                      for c in ('mobile', 'wide')},
            'quiet_background': {'method': r['quiet']['method'], 'shipped': False},
        }
    ev = os.path.join(wt, 'docs', 'trivia', 'evidence', 'p4-art-intro-art-manifest.json')
    json.dump(prov, open(ev, 'w'), indent=1)
    tot = sum(f['bytes'] for i in ORDER for c in ('mobile', 'wide') for f in recs[i]['crops'][c]['files'])
    print('families', len(ORDER), 'files', len(keep), 'bytes', tot)

if __name__ == '__main__':
    main(sys.argv[1])
