"""Write src/config/triviaThumbnailPreviews.mjs: a 32px-wide WebP preview of
each lobby card picture (modes-console-v1), painted into the card's picture
well until the real file decodes, so a fast scroll never shows an empty well.

python3 scripts/trivia-art/thumb-previews.py   (run from the repository root)
"""
import base64, io, os, re
from PIL import Image
REG = open('src/config/triviaModeRegistry.mjs').read()
ids = re.findall(r"id: '([a-z-]+)',\s*\n\s*placement: TRIVIA_MODE_PLACEMENT\.MIDDLE", REG)
assert len(ids) == 13, ids
lines = ['/**', ' * GENERATED by scripts/trivia-art/thumb-previews.py. Do not edit by hand.',
         ' * A 32px-wide WebP preview of each lobby card picture, painted into the',
         " * card's picture well (TriviaFrameCard imagePreview) until the file decodes.", ' */',
         'export const TRIVIA_THUMBNAIL_PREVIEWS = Object.freeze({']
for i in ids:
    im = Image.open(f'public/images/trivia/modes-console-v1/{i}.webp').convert('RGB')
    im = im.resize((32, max(1, round(32 * im.height / im.width))), Image.LANCZOS)
    b = io.BytesIO(); im.save(b, 'WEBP', quality=40, method=6)
    lines.append(f"    '{i}': 'data:image/webp;base64,{base64.b64encode(b.getvalue()).decode()}',")
lines += ['});', '']
open('src/config/triviaThumbnailPreviews.mjs', 'w').write('\n'.join(lines))
print(len(ids), os.path.getsize('src/config/triviaThumbnailPreviews.mjs'))
