/**
 * GENERATED by scripts/trivia-art/build.py from the p4-art export records,
 * with the five Phase 8 solo/strategy destinations advanced to intro-v2.
 * Rebuild the Phase 4 set through scripts/trivia-art/; Phase 8 source masters
 * and provenance live in scripts/trivia-art/sources/intro-v2/ and
 * docs/trivia/evidence/p8-core-intro-art-manifest.json.
 *
 * One destination intro master per Trivia family, distinct from that
 * family's lobby thumbnail. Each entry is a 16:10 mobile crop and a 12:5
 * wide crop, AVIF + WebP at 640/960/1440, content-hashed file names, and a
 * 32x20 preview painted into the reserved box until the picture decodes.
 * Provenance (prompts, seeds, model, licence, crops, grade, hashes):
 * docs/trivia/evidence/p4-art-intro-art-manifest.json
 */

export const TRIVIA_INTRO_ART_VERSION = 'intro-v1';
export const TRIVIA_INTRO_ART_PHASE8_VERSION = 'intro-v2';

const crop = (width, height, avif, webp, src) => Object.freeze({ width, height, avif, webp, src });
const art = (key, preview, mobile, wide) => Object.freeze({ key, preview, mobile, wide });

export const TRIVIA_INTRO_ART_LOBBY = art(
    'lobby',
    'data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBQCdASogABQAPu1qrE8ppiQiMBgIATAdiWcAAI91xMEOm3yV0mJ47HFh1baRJoAaicYAAP72iA5hpHpcgGJ8p/c3N4w5naW0JTaCiOWyNM6Hcyg8+F7bq+OmH5eFAw+r4UaKXX7jLDZJyMQXKX5jb1spmpYcUVSof/v0ntb0DY1lJ4F9yUusaQA1mQAA',
    crop(1440, 900, '/images/trivia/intro-v1/lobby-mobile-640.488b645ad4.avif 640w, /images/trivia/intro-v1/lobby-mobile-960.e93f3a9e36.avif 960w, /images/trivia/intro-v1/lobby-mobile-1440.2b613985de.avif 1440w', '/images/trivia/intro-v1/lobby-mobile-640.236fc8cb68.webp 640w, /images/trivia/intro-v1/lobby-mobile-960.268b7127f3.webp 960w, /images/trivia/intro-v1/lobby-mobile-1440.47ad46b16f.webp 1440w', '/images/trivia/intro-v1/lobby-mobile-960.268b7127f3.webp'),
    crop(1440, 600, '/images/trivia/intro-v1/lobby-wide-640.eafaaaabea.avif 640w, /images/trivia/intro-v1/lobby-wide-960.448d84f3a7.avif 960w, /images/trivia/intro-v1/lobby-wide-1440.83ee7c8d68.avif 1440w', '/images/trivia/intro-v1/lobby-wide-640.f7c20a0c85.webp 640w, /images/trivia/intro-v1/lobby-wide-960.d7731bad62.webp 960w, /images/trivia/intro-v1/lobby-wide-1440.7f250e3bf1.webp 1440w', '/images/trivia/intro-v1/lobby-wide-960.d7731bad62.webp'),
);

export const TRIVIA_INTRO_ART_DAILY = art(
    'daily',
    'data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABQBQCdASogABQAPuVcpU2pJSOiMAwBIByJZQAMKwtFRvt5MPsTHcKlBL5DbuAUL2anKsAA/vQrSfjTXNlmAr/Uzp9NxRA3ecyzlRn8pNXgI+FJKhZCGImL89TkgU/MflKNWKj3GyMpSZtxoX9fSV5VzSA2HkjrZ3hsv9henVuaKjGbGYrEzSR7Enj9O2RA1NzHmLwGdJX92O1AKCoGB2GwFTAAtIAA',
    crop(1440, 900, '/images/trivia/intro-v2/daily-mobile-640.1b1f968971.avif 640w, /images/trivia/intro-v2/daily-mobile-960.b144584132.avif 960w, /images/trivia/intro-v2/daily-mobile-1440.a72bab076a.avif 1440w', '/images/trivia/intro-v2/daily-mobile-640.ed6738b5f3.webp 640w, /images/trivia/intro-v2/daily-mobile-960.c306453af0.webp 960w, /images/trivia/intro-v2/daily-mobile-1440.06e3aff161.webp 1440w', '/images/trivia/intro-v2/daily-mobile-960.c306453af0.webp'),
    crop(1440, 600, '/images/trivia/intro-v2/daily-wide-640.dc642bde4c.avif 640w, /images/trivia/intro-v2/daily-wide-960.d25a4e3208.avif 960w, /images/trivia/intro-v2/daily-wide-1440.0f78c2524d.avif 1440w', '/images/trivia/intro-v2/daily-wide-640.c383e3376d.webp 640w, /images/trivia/intro-v2/daily-wide-960.62ae5d5c6e.webp 960w, /images/trivia/intro-v2/daily-wide-1440.7ab0e6aea3.webp 1440w', '/images/trivia/intro-v2/daily-wide-960.62ae5d5c6e.webp'),
);

export const TRIVIA_INTRO_ART_ARCADE = art(
    'arcade',
    'data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBQCdASogABQAPuFaqE2opSQiMAwBEBwJYwDOHExDA1pUAbPuBR6diqbVWM9Un+8lIAD+9WkLmOOm4z9KULFnpqSoTIBrw1h8gknETZZKVk5AlfkdUk0w6THvuL8hMvurGrTUnURjnzQFEV8zpc5WC4iHN8tiVLk8in+DruiqVweUaYClCD5YY2vMKRs9F7dX03Ba3KAAAA==',
    crop(1440, 900, '/images/trivia/intro-v1/arcade-mobile-640.cf2b05bda8.avif 640w, /images/trivia/intro-v1/arcade-mobile-960.c46e8e0509.avif 960w, /images/trivia/intro-v1/arcade-mobile-1440.5af904f282.avif 1440w', '/images/trivia/intro-v1/arcade-mobile-640.a93f692b9f.webp 640w, /images/trivia/intro-v1/arcade-mobile-960.3d3e9a2423.webp 960w, /images/trivia/intro-v1/arcade-mobile-1440.707a7a4ab2.webp 1440w', '/images/trivia/intro-v1/arcade-mobile-960.3d3e9a2423.webp'),
    crop(1440, 600, '/images/trivia/intro-v1/arcade-wide-640.fa7020e527.avif 640w, /images/trivia/intro-v1/arcade-wide-960.60c56e4021.avif 960w, /images/trivia/intro-v1/arcade-wide-1440.2c399612f0.avif 1440w', '/images/trivia/intro-v1/arcade-wide-640.4b6e8bf300.webp 640w, /images/trivia/intro-v1/arcade-wide-960.dffdf0fcc2.webp 960w, /images/trivia/intro-v1/arcade-wide-1440.9dd7f77fc0.webp 1440w', '/images/trivia/intro-v1/arcade-wide-960.dffdf0fcc2.webp'),
);

export const TRIVIA_INTRO_ART_HISTORY = art(
    'history',
    'data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABQBQCdASogABQAPu1gqE2ppaOiMAgBMB2JaQAAW4fjNvwc8ZXfoWtD9XAy98iid4SpCfgA/uxQS/GV+sQ9/BgVc2lyqNA0T6MaYJ78g7bcY4ctSPG6eHs0W7iV0+1RpPGKgCOARL+ZXkrPqioNYAOnurZqMkbkzI46HMh9nBxNEW/6WzMN53Yz6r0pjiVF9rVYZ791km98w4tu5sIz9OmtDHpxVuEAAAA=',
    crop(1440, 900, '/images/trivia/intro-v1/history-mobile-640.93eb77d3d5.avif 640w, /images/trivia/intro-v1/history-mobile-960.74fe6e5e94.avif 960w, /images/trivia/intro-v1/history-mobile-1440.67b1ea7119.avif 1440w', '/images/trivia/intro-v1/history-mobile-640.e63243e723.webp 640w, /images/trivia/intro-v1/history-mobile-960.82a9cbd8a0.webp 960w, /images/trivia/intro-v1/history-mobile-1440.111dd064be.webp 1440w', '/images/trivia/intro-v1/history-mobile-960.82a9cbd8a0.webp'),
    crop(1440, 600, '/images/trivia/intro-v1/history-wide-640.a6f82205c9.avif 640w, /images/trivia/intro-v1/history-wide-960.459d87a128.avif 960w, /images/trivia/intro-v1/history-wide-1440.dcababcda6.avif 1440w', '/images/trivia/intro-v1/history-wide-640.0b9d6e68c3.webp 640w, /images/trivia/intro-v1/history-wide-960.32a23bd73e.webp 960w, /images/trivia/intro-v1/history-wide-1440.82eca45e6b.webp 1440w', '/images/trivia/intro-v1/history-wide-960.32a23bd73e.webp'),
);

export const TRIVIA_INTRO_ART_RULES = art(
    'rules',
    'data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBQCdASogABQAPu1urFEppqQiqAqpMB2JZwDIXDTwK4fEgHai9sVF1+JmOMlv2OboAP70HaA39vDWJG/tFdHWN13iMWC5gq/5bTH7htUEtXk9joygJI90XVxZKbzFKOn3HAx7WPud/e1TbW/6fpWXn74dJa5P4qbmhyRcevgfXsJpAAA=',
    crop(1440, 900, '/images/trivia/intro-v1/rules-mobile-640.9cbf4700cd.avif 640w, /images/trivia/intro-v1/rules-mobile-960.0859d6ded6.avif 960w, /images/trivia/intro-v1/rules-mobile-1440.19b4522c0f.avif 1440w', '/images/trivia/intro-v1/rules-mobile-640.8c9b05e336.webp 640w, /images/trivia/intro-v1/rules-mobile-960.aba03e69a6.webp 960w, /images/trivia/intro-v1/rules-mobile-1440.8a4890a694.webp 1440w', '/images/trivia/intro-v1/rules-mobile-960.aba03e69a6.webp'),
    crop(1440, 600, '/images/trivia/intro-v1/rules-wide-640.d683fe3d43.avif 640w, /images/trivia/intro-v1/rules-wide-960.6ad076e6db.avif 960w, /images/trivia/intro-v1/rules-wide-1440.81f7ccc587.avif 1440w', '/images/trivia/intro-v1/rules-wide-640.0b1c2e2bea.webp 640w, /images/trivia/intro-v1/rules-wide-960.6a748a789e.webp 960w, /images/trivia/intro-v1/rules-wide-1440.953847b046.webp 1440w', '/images/trivia/intro-v1/rules-wide-960.6a748a789e.webp'),
);

export const TRIVIA_INTRO_ART_PRO = art(
    'pro',
    'data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABQBACdASogABQAPu1kqk2ppaQiMAgBMB2JZQDLaYxYwPJccmTrXiZwYE3AAP7qADOI716AxnXrEKwVsq+cggHLAWoeLBJGyCYBfti4h2iCRX6sgMLzHYDQAD1f5Dc4b4zvY95TphT5zVP8s8uSUCaXBOnbA6i0MG+R6lm1rbJI1DbaGMRFLgtpfYl3kw+pCxnvOSOGkdtvOU7CrGYAAA==',
    crop(1440, 900, '/images/trivia/intro-v1/pro-mobile-640.effabf1dd1.avif 640w, /images/trivia/intro-v1/pro-mobile-960.c0de3088b2.avif 960w, /images/trivia/intro-v1/pro-mobile-1440.0e54e6f715.avif 1440w', '/images/trivia/intro-v1/pro-mobile-640.ab0b318b9c.webp 640w, /images/trivia/intro-v1/pro-mobile-960.59cf90e26f.webp 960w, /images/trivia/intro-v1/pro-mobile-1440.bd3a35a618.webp 1440w', '/images/trivia/intro-v1/pro-mobile-960.59cf90e26f.webp'),
    crop(1440, 600, '/images/trivia/intro-v1/pro-wide-640.a489b0ad3d.avif 640w, /images/trivia/intro-v1/pro-wide-960.e8e66b2360.avif 960w, /images/trivia/intro-v1/pro-wide-1440.37560de9dd.avif 1440w', '/images/trivia/intro-v1/pro-wide-640.accf0c4df4.webp 640w, /images/trivia/intro-v1/pro-wide-960.0b71942201.webp 960w, /images/trivia/intro-v1/pro-wide-1440.3f10e88173.webp 1440w', '/images/trivia/intro-v1/pro-wide-960.0b71942201.webp'),
);

export const TRIVIA_INTRO_ART_MTT = art(
    'mtt',
    'data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBQCdASogABQAPu1iqU2ppaOiMAgBMB2JZwDKtywBtBn4a98yhRmoCbtbWStuHeyyIVsAAP7zHSkLFf2iNTopc05Hdz0oo8MOhhbNB0hZKY++wqW0rlQzcN/VazbAThFODuUX0IBTbty349bOWKUJugRLJe92AJSxblLi0gFlfbxz8vzsA1mEM89EumF70GQqPHjrMQz9RoAAAAA=',
    crop(1440, 900, '/images/trivia/intro-v2/mtt-mobile-640.2a23fda015.avif 640w, /images/trivia/intro-v2/mtt-mobile-960.a626d2d59b.avif 960w, /images/trivia/intro-v2/mtt-mobile-1440.4ca07873e8.avif 1440w', '/images/trivia/intro-v2/mtt-mobile-640.97f6462ffd.webp 640w, /images/trivia/intro-v2/mtt-mobile-960.9205486a0a.webp 960w, /images/trivia/intro-v2/mtt-mobile-1440.2362c87940.webp 1440w', '/images/trivia/intro-v2/mtt-mobile-960.9205486a0a.webp'),
    crop(1440, 600, '/images/trivia/intro-v2/mtt-wide-640.884b5f5b9b.avif 640w, /images/trivia/intro-v2/mtt-wide-960.b3712ca0ce.avif 960w, /images/trivia/intro-v2/mtt-wide-1440.9c24371260.avif 1440w', '/images/trivia/intro-v2/mtt-wide-640.e65bf713ca.webp 640w, /images/trivia/intro-v2/mtt-wide-960.a047e79808.webp 960w, /images/trivia/intro-v2/mtt-wide-1440.91fabbea27.webp 1440w', '/images/trivia/intro-v2/mtt-wide-960.a047e79808.webp'),
);

export const TRIVIA_INTRO_ART_CASH = art(
    'cash',
    'data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAADQBQCdASogABQAPu1gq1AppSOisBgIATAdiWUAz6drmRA7Kpx3TV1C/0rD6ggCBRES4/XmHcwAAP73gfJ5dP8dnt90RjpWM3D4fDE59eMnOTLM5riU/eWiWsBD7yOjM3DqtmRX2FfhvUQyrTkgFxQ/0vNJaGzn2GgA6cy4gXij2lm1JxlezvYC8DNLmfIhia2CepRxXGAd9/K9jOzsCZCrxHQjmldYnhM9Gt/5BcNLlUl3FLCrBaLBQ0kAAA==',
    crop(1440, 900, '/images/trivia/intro-v2/cash-mobile-640.8b19e86180.avif 640w, /images/trivia/intro-v2/cash-mobile-960.8a923ae919.avif 960w, /images/trivia/intro-v2/cash-mobile-1440.0d993771fe.avif 1440w', '/images/trivia/intro-v2/cash-mobile-640.9ab2b1eaa0.webp 640w, /images/trivia/intro-v2/cash-mobile-960.6a2c05b670.webp 960w, /images/trivia/intro-v2/cash-mobile-1440.e781fb5e75.webp 1440w', '/images/trivia/intro-v2/cash-mobile-960.6a2c05b670.webp'),
    crop(1440, 600, '/images/trivia/intro-v2/cash-wide-640.c60d80c6cc.avif 640w, /images/trivia/intro-v2/cash-wide-960.039e3e161a.avif 960w, /images/trivia/intro-v2/cash-wide-1440.7e1fb6fbe2.avif 1440w', '/images/trivia/intro-v2/cash-wide-640.bc80780e18.webp 640w, /images/trivia/intro-v2/cash-wide-960.324a307406.webp 960w, /images/trivia/intro-v2/cash-wide-1440.c6c53900fa.webp 1440w', '/images/trivia/intro-v2/cash-wide-960.324a307406.webp'),
);

export const TRIVIA_INTRO_ART_ICM = art(
    'icm',
    'data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAABQBQCdASogABQAPu1iqU2ppaQiMAgBMB2JZQDI2bAlGxqqSbqQlbpfmjazABkYOUitjkAA/vKzT4YMv+TUY7sl2YrCruM0ZQvxFughqsvZpHUfHgtpDCjhBckml3fA90Ylukxuq1Q1vrshLCBeHxuezFxRw3D+T+nYOSel1KZqsqbjou4zWkMRMVtVfgHcfFRs9Uq/Apq7PIYqNUH6UJU6YIk+ep4Zpzh6+cS5go6RLgH607dWLL4q2nJ3dJ9vy97VJPG4Co+AAA==',
    crop(1440, 900, '/images/trivia/intro-v2/icm-mobile-640.c7c8c7837a.avif 640w, /images/trivia/intro-v2/icm-mobile-960.6e8cf78905.avif 960w, /images/trivia/intro-v2/icm-mobile-1440.03ab882ac3.avif 1440w', '/images/trivia/intro-v2/icm-mobile-640.c6696d8acc.webp 640w, /images/trivia/intro-v2/icm-mobile-960.700e61f333.webp 960w, /images/trivia/intro-v2/icm-mobile-1440.4711edbc72.webp 1440w', '/images/trivia/intro-v2/icm-mobile-960.700e61f333.webp'),
    crop(1440, 600, '/images/trivia/intro-v2/icm-wide-640.1cccca5685.avif 640w, /images/trivia/intro-v2/icm-wide-960.7ba107911f.avif 960w, /images/trivia/intro-v2/icm-wide-1440.92de2ab01f.avif 1440w', '/images/trivia/intro-v2/icm-wide-640.bd3572cd4f.webp 640w, /images/trivia/intro-v2/icm-wide-960.ac878d1abe.webp 960w, /images/trivia/intro-v2/icm-wide-1440.832fd35540.webp 1440w', '/images/trivia/intro-v2/icm-wide-960.ac878d1abe.webp'),
);

export const TRIVIA_INTRO_ART_GTO = art(
    'gto',
    'data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADwBACdASogABQAPu1mqk2ppaQiMAgBMB2JZwAIGuPIMNMsvo+8eSsBNYSEYUVnXAAA/vFh3S8dQPkaVGOkAzmiHoUnBTTr9WANn8zAaxRqh29YpqrVAEAw0EQD+mbBW/VMHqB25bH02g3LCHwW5Gmokh4Mxx9ojPcKu5cYTJNt5bZmxpehayUf14vtQ42x7ZLnTNASRfqvvbWfH8sIAA==',
    crop(1440, 900, '/images/trivia/intro-v2/gto-mobile-640.7fb0da9bbc.avif 640w, /images/trivia/intro-v2/gto-mobile-960.9e8647c91f.avif 960w, /images/trivia/intro-v2/gto-mobile-1440.80c3b428a5.avif 1440w', '/images/trivia/intro-v2/gto-mobile-640.b00c72bfba.webp 640w, /images/trivia/intro-v2/gto-mobile-960.40e39db3d4.webp 960w, /images/trivia/intro-v2/gto-mobile-1440.ba0d66c543.webp 1440w', '/images/trivia/intro-v2/gto-mobile-960.40e39db3d4.webp'),
    crop(1440, 600, '/images/trivia/intro-v2/gto-wide-640.c04d761695.avif 640w, /images/trivia/intro-v2/gto-wide-960.37b7f91a18.avif 960w, /images/trivia/intro-v2/gto-wide-1440.b4f2b234e0.avif 1440w', '/images/trivia/intro-v2/gto-wide-640.7ef7c43ec7.webp 640w, /images/trivia/intro-v2/gto-wide-960.bc25f26560.webp 960w, /images/trivia/intro-v2/gto-wide-1440.a651ccb256.webp 1440w', '/images/trivia/intro-v2/gto-wide-960.bc25f26560.webp'),
);

export const TRIVIA_INTRO_ART_ENDLESS = art(
    'endless',
    'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBQCdASogABQAPu1qq08ppiOiMBgIATAdiWcAxNg0cNsccG5MC6d3HNaHxDe/u0wAAP71l4glqVMXtg7wWbjdKSEtgDA8PyrhX/Us1ISgpBrpCTofsbpcycLqMXUvzVUck7VT3Bzkw1orgxO+AVfH8sNq1uf7NeHULgAA',
    crop(1440, 900, '/images/trivia/intro-v1/endless-mobile-640.d596a525c6.avif 640w, /images/trivia/intro-v1/endless-mobile-960.5175682168.avif 960w, /images/trivia/intro-v1/endless-mobile-1440.efa1a0b647.avif 1440w', '/images/trivia/intro-v1/endless-mobile-640.0ce9d4d4e4.webp 640w, /images/trivia/intro-v1/endless-mobile-960.3783177349.webp 960w, /images/trivia/intro-v1/endless-mobile-1440.0bf4247d34.webp 1440w', '/images/trivia/intro-v1/endless-mobile-960.3783177349.webp'),
    crop(1440, 600, '/images/trivia/intro-v1/endless-wide-640.990b7bb3b8.avif 640w, /images/trivia/intro-v1/endless-wide-960.a1e2d3b6ce.avif 960w, /images/trivia/intro-v1/endless-wide-1440.4aed1bfb03.avif 1440w', '/images/trivia/intro-v1/endless-wide-640.8e0aa1be1c.webp 640w, /images/trivia/intro-v1/endless-wide-960.f297d4b121.webp 960w, /images/trivia/intro-v1/endless-wide-1440.d02a5cd4c1.webp 1440w', '/images/trivia/intro-v1/endless-wide-960.f297d4b121.webp'),
);

export const TRIVIA_INTRO_ART_MIXED = art(
    'mixed',
    'data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAACwBQCdASogABQAPu1sq06ppqOiMBgIATAdiWMAyzAIHYAWBbDFADGenFhUSS/EsZcojuW4noAA/vV7yvve85dp8WtNZ0K2lVXVbdRivMQtZAnb/4qW6BNuzC7p0oOBzljHZWVm914oURiEk5DW1BRkDDdCnfwUdjOB0KAk9TweZ+l0ceo7Z6Q7ggbxoCYvnU5b+r1b/qy+3fMioQPBAt5jm4Z52WFvq6Q1ECtbVnPChP1B7Ec3aSPLVs2T6BXc05Tk3n2bhVAAAA==',
    crop(1440, 900, '/images/trivia/intro-v1/mixed-mobile-640.8bf57e0c62.avif 640w, /images/trivia/intro-v1/mixed-mobile-960.b9ab227db3.avif 960w, /images/trivia/intro-v1/mixed-mobile-1440.84a9fd9476.avif 1440w', '/images/trivia/intro-v1/mixed-mobile-640.168b40a408.webp 640w, /images/trivia/intro-v1/mixed-mobile-960.ca7f7b5859.webp 960w, /images/trivia/intro-v1/mixed-mobile-1440.80e435362c.webp 1440w', '/images/trivia/intro-v1/mixed-mobile-960.ca7f7b5859.webp'),
    crop(1440, 600, '/images/trivia/intro-v1/mixed-wide-640.b9e4d8cb69.avif 640w, /images/trivia/intro-v1/mixed-wide-960.821b74c86f.avif 960w, /images/trivia/intro-v1/mixed-wide-1440.3182e7f6d3.avif 1440w', '/images/trivia/intro-v1/mixed-wide-640.7da969748c.webp 640w, /images/trivia/intro-v1/mixed-wide-960.21fa55cc40.webp 960w, /images/trivia/intro-v1/mixed-wide-1440.7698d0692a.webp 1440w', '/images/trivia/intro-v1/mixed-wide-960.21fa55cc40.webp'),
);

export const TRIVIA_INTRO_ART_SURVIVAL = art(
    'survival',
    'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACwBACdASogABQAPu1orVAppaQisBgIATAdiWcAAI9AsolD+K7Ny+otrtgBJ8QAAP72jSnYRALBDZgp3XPff7OhFmZAMgaUruzyBYxJ+g+R8TkqYYE53N/rvOn0shCxD1MPQUn7eSAgekcIey29kVxjppQAAAAA',
    crop(1440, 900, '/images/trivia/intro-v1/survival-mobile-640.d10fd6d6e4.avif 640w, /images/trivia/intro-v1/survival-mobile-960.3cb248744e.avif 960w, /images/trivia/intro-v1/survival-mobile-1440.6cc931f98a.avif 1440w', '/images/trivia/intro-v1/survival-mobile-640.97a41c4199.webp 640w, /images/trivia/intro-v1/survival-mobile-960.2c219d3db8.webp 960w, /images/trivia/intro-v1/survival-mobile-1440.91e2607058.webp 1440w', '/images/trivia/intro-v1/survival-mobile-960.2c219d3db8.webp'),
    crop(1440, 600, '/images/trivia/intro-v1/survival-wide-640.536683cdbe.avif 640w, /images/trivia/intro-v1/survival-wide-960.6443edd1a0.avif 960w, /images/trivia/intro-v1/survival-wide-1440.2e2ba69f68.avif 1440w', '/images/trivia/intro-v1/survival-wide-640.3114e2fa37.webp 640w, /images/trivia/intro-v1/survival-wide-960.10960a8810.webp 960w, /images/trivia/intro-v1/survival-wide-1440.b473f94a85.webp 1440w', '/images/trivia/intro-v1/survival-wide-960.10960a8810.webp'),
);

export const TRIVIA_INTRO_ART_TIME_ATTACK = art(
    'time-attack',
    'data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAAAwBQCdASogABQAPu1oq04ppiQiMAgBMB2JYgDKtYuStWokqA4/6/Z2IwCuUG8KcdG84AD+/dtDSwhEgB5iFeLBrBd76adubac+1o/Ahr87OHl7XGAelztSGqRjmE5gdUeUntFwrNN3X/ow07Ypv2jnSFppat6ZfmPKTephkkgyQQ/qtlfI6pv/innvZk7sX6Rd4MKT6bIhmm1LCV+JwSXuNuy038lHHbFwe4VzCd6uj5eZQyDvl0LkuFV65MAAAAA=',
    crop(1440, 900, '/images/trivia/intro-v1/time-attack-mobile-640.2953700651.avif 640w, /images/trivia/intro-v1/time-attack-mobile-960.e331461f77.avif 960w, /images/trivia/intro-v1/time-attack-mobile-1440.7cccd2eef2.avif 1440w', '/images/trivia/intro-v1/time-attack-mobile-640.cbd510ee75.webp 640w, /images/trivia/intro-v1/time-attack-mobile-960.d72f1554d0.webp 960w, /images/trivia/intro-v1/time-attack-mobile-1440.cf90d3ea8d.webp 1440w', '/images/trivia/intro-v1/time-attack-mobile-960.d72f1554d0.webp'),
    crop(1440, 600, '/images/trivia/intro-v1/time-attack-wide-640.010bce7d38.avif 640w, /images/trivia/intro-v1/time-attack-wide-960.c5c7f54f92.avif 960w, /images/trivia/intro-v1/time-attack-wide-1440.fc488d1885.avif 1440w', '/images/trivia/intro-v1/time-attack-wide-640.d51db0400f.webp 640w, /images/trivia/intro-v1/time-attack-wide-960.9aeab94f8f.webp 960w, /images/trivia/intro-v1/time-attack-wide-1440.5b790d3b76.webp 1440w', '/images/trivia/intro-v1/time-attack-wide-960.9aeab94f8f.webp'),
);

export const TRIVIA_INTRO_ART_PVP = art(
    'pvp',
    'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBQCdASogABQAPuleo02pJSMiMAwBIB0JQBj8sXrb7uni0SRvvagXsLRkQci+IvKgAP70J5oiNeI8ZlC42P86A8vELpY+depWstZaqOMBPfI/k+qKXIUSzOCCYKJPT4U3FSguu4EK9zl3khusk9wEhlW4ufjrlvvWXD44r+sSnkEVGa+GzEveQVgAAA==',
    crop(1440, 900, '/images/trivia/intro-v1/pvp-mobile-640.79b0cf3472.avif 640w, /images/trivia/intro-v1/pvp-mobile-960.94185651e0.avif 960w, /images/trivia/intro-v1/pvp-mobile-1440.feadc91a16.avif 1440w', '/images/trivia/intro-v1/pvp-mobile-640.a2c1a912a9.webp 640w, /images/trivia/intro-v1/pvp-mobile-960.50d703dd72.webp 960w, /images/trivia/intro-v1/pvp-mobile-1440.7cafb3b517.webp 1440w', '/images/trivia/intro-v1/pvp-mobile-960.50d703dd72.webp'),
    crop(1440, 600, '/images/trivia/intro-v1/pvp-wide-640.fc3c950397.avif 640w, /images/trivia/intro-v1/pvp-wide-960.bb8bff3660.avif 960w, /images/trivia/intro-v1/pvp-wide-1440.cc01b2d209.avif 1440w', '/images/trivia/intro-v1/pvp-wide-640.db8329fbc5.webp 640w, /images/trivia/intro-v1/pvp-wide-960.189e51d004.webp 960w, /images/trivia/intro-v1/pvp-wide-1440.d498ba4d0a.webp 1440w', '/images/trivia/intro-v1/pvp-wide-960.189e51d004.webp'),
);

export const TRIVIA_INTRO_ART_TOURNAMENTS = art(
    'tournaments',
    'data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABQBQCdASogABQAPu1kqU2ppaQiMAgBMB2JZwCsITV/+AsJ7oWp1vp5Uop9VA+fXtLvLgAA/vQqjiYwOiAQQ11SWaw8YU434D6fw2hl2BLxl4q7JjXYPcnzylPcA8J2OfAkqX0G5faKQhTGksqs5uO/2BRWkMtDgipnxcBIiRj06CIolPMZ+59l37B9jfElgfsySPPdJZfAAA==',
    crop(1440, 900, '/images/trivia/intro-v1/tournaments-mobile-640.4b38067c35.avif 640w, /images/trivia/intro-v1/tournaments-mobile-960.328c6d1e34.avif 960w, /images/trivia/intro-v1/tournaments-mobile-1440.eb61215464.avif 1440w', '/images/trivia/intro-v1/tournaments-mobile-640.18e260a6f5.webp 640w, /images/trivia/intro-v1/tournaments-mobile-960.2aca9899ec.webp 960w, /images/trivia/intro-v1/tournaments-mobile-1440.546b837004.webp 1440w', '/images/trivia/intro-v1/tournaments-mobile-960.2aca9899ec.webp'),
    crop(1440, 600, '/images/trivia/intro-v1/tournaments-wide-640.bb471ae789.avif 640w, /images/trivia/intro-v1/tournaments-wide-960.484873ac3c.avif 960w, /images/trivia/intro-v1/tournaments-wide-1440.7f1101a101.avif 1440w', '/images/trivia/intro-v1/tournaments-wide-640.68fbc865d9.webp 640w, /images/trivia/intro-v1/tournaments-wide-960.8f0d0b3a1b.webp 960w, /images/trivia/intro-v1/tournaments-wide-1440.baf0144f9f.webp 1440w', '/images/trivia/intro-v1/tournaments-wide-960.8f0d0b3a1b.webp'),
);

export const TRIVIA_INTRO_ART = Object.freeze({
    'lobby': TRIVIA_INTRO_ART_LOBBY,
    'daily': TRIVIA_INTRO_ART_DAILY,
    'arcade': TRIVIA_INTRO_ART_ARCADE,
    'history': TRIVIA_INTRO_ART_HISTORY,
    'rules': TRIVIA_INTRO_ART_RULES,
    'pro': TRIVIA_INTRO_ART_PRO,
    'mtt': TRIVIA_INTRO_ART_MTT,
    'cash': TRIVIA_INTRO_ART_CASH,
    'icm': TRIVIA_INTRO_ART_ICM,
    'gto': TRIVIA_INTRO_ART_GTO,
    'endless': TRIVIA_INTRO_ART_ENDLESS,
    'mixed': TRIVIA_INTRO_ART_MIXED,
    'survival': TRIVIA_INTRO_ART_SURVIVAL,
    'time-attack': TRIVIA_INTRO_ART_TIME_ATTACK,
    'pvp': TRIVIA_INTRO_ART_PVP,
    'tournaments': TRIVIA_INTRO_ART_TOURNAMENTS,
});
