/**
 * GTO EXPLANATION ENDPOINT (DETERMINISTIC — Operation Grok-Sweep)
 * ═══════════════════════════════════════════════════════════════════════════
 * Returns the rich "EngineExplanation" payload consumed by FeedbackCard.tsx
 * and other clients (mobile, legacy training arena).
 *
 * Routing:
 *   • PIO / CHART (or any question with gtoFrequencies present) → deterministic
 *     templates (no LLM call). Generated by src/lib/explanationTemplates.js.
 *   • SCENARIO (psychology / mental-game) → grok-3-mini fallback. We keep an
 *     LLM here because there is no solver math for these questions.
 *
 * Caching:
 *   • Reads/writes grok_explanation_cache. Cache is keyed by
 *     md5(question + heroPos + heroHand + board + action + villainPos + correctAnswer).
 *   • Caching deterministic responses still wins (avoids re-doing the template
 *     build, and keeps the response shape stable across deploys).
 *
 * Auth + rate-limit (preserved exactly):
 *   • JWT required (Bearer); rejected with 401 on missing/invalid.
 *   • LIMITS.write applied to mutating verbs.
 *
 * Cost note: prior to this refactor every cold cache miss issued a grok-3 call
 * (~$0.005–$0.012). After this refactor only SCENARIO questions hit grok-3-mini
 * (~$0.0002), and PIO/CHART are free.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { getGrokClient } from '../../../src/lib/grokClient';
import { createClient } from '../../../src/lib/supabaseServerClient';
import crypto from 'crypto';
import { applyRateLimit, LIMITS } from '../../../src/lib/apiRateLimit';
import { withTiming } from '../../../src/utils/trainingApiUtils';
import { reportApiError } from '../../../src/lib/sentryWrap';
import { buildExplainAnswerPayload } from '../../../src/lib/explanationTemplates';
import { getServerUserWithFallback } from '../../../src/lib/serverAuth';

// ── Lazy Supabase getter (SSG-safe) ─────────────────────────────
let _supabase = null;
function getSupabase() {
    if (!_supabase) {
        _supabase = createClient(
            process.env.NEXT_PUBLIC_SUPABASE_URL,
            process.env.SUPABASE_SERVICE_ROLE_KEY
        );
    }
    return _supabase;
}

// Generate a hash key for the scenario (for cache lookup)
function generateCacheKey(question, correctAnswer) {
    const scenario = question.scenario || {};
    const keyData = JSON.stringify({
        q: question.question,
        heroPos: scenario.heroPosition,
        heroHand: scenario.heroHand,
        board: scenario.board,
        action: scenario.action,
        villainPos: scenario.villainPosition,
        correctAnswer
    });
    return crypto.createHash('md5').update(keyData).digest('hex');
}

// Determine whether this question has solver math → deterministic path.
// SCENARIO questions and any question explicitly typed PSYCHOLOGY take the
// LLM path (grok-3-mini). Everything else uses templates.
function hasSolverData(question, gtoFrequencies) {
    if (!question) return false;
    const type = (question.type || '').toUpperCase();
    if (type === 'SCENARIO') return false;
    if (question.scenario?.isPsychology) return false;
    const freqs = gtoFrequencies || question.gtoFrequencies;
    if (freqs && typeof freqs === 'object' && Object.keys(freqs).length > 0) return true;
    if (type === 'PIO' || type === 'CHART') return true;
    return false;
}

export default async function handler(req, res) {
  try {
      withTiming(res);
      if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(req.method)) {
          if (!applyRateLimit(req, res, LIMITS.write)) return;
      }

      if (req.method !== 'POST') {
          return res.status(405).json({ success: false, error: 'Method not allowed' });
      }

      // Body size guard (50KB max)
      const bodySize = JSON.stringify(req.body || {}).length;
      if (bodySize > 51200) {
          return res.status(413).json({ success: false, error: 'Request body too large' });
      }

      // Prevent caching of personalized responses at the CDN layer
      res.setHeader('Cache-Control', 'no-store');

      // ── Auth: verify JWT (prevent unauthenticated AI API abuse) ──
      const supabase = getSupabase();
      const { user, error: authErr } = await getServerUserWithFallback(req, supabase);
      if (!user) {
          if (authErr === 'No token') return res.status(401).json({ success: false, error: 'Auth required' });
          return res.status(401).json({ success: false, error: 'Invalid token' });
      }

      const {
          question,           // The original question object
          userAnswer,         // What the user selected
          correctAnswer,      // The correct answer
          wasCorrect,         // Boolean
          gameId,             // Game context
          level,              // Difficulty level (used by SCENARIO LLM tone)
          gtoFrequencies,     // Solver frequencies { actionCode: pct }
          classification,     // 'BEST' | 'CORRECT' | 'INACCURACY' | 'WRONG' | 'BLUNDER'
          evLoss,             // Numeric EV loss in BB
      } = req.body;

      if (!question || !userAnswer || !correctAnswer) {
          return res.status(400).json({ success: false, error: 'Missing required fields' });
      }

      const cacheKey = generateCacheKey(question, correctAnswer);

      try {
          // CHECK CACHE FIRST (cache stays in front of both branches)
          const { data: cached } = await supabase
              .from('grok_explanation_cache')
              .select('explanation, was_correct')
              .eq('cache_key', cacheKey)
              .eq('was_correct', wasCorrect)
              .maybeSingle();

          if (cached?.explanation) {
              return res.status(200).json({
                  success: true,
                  explanation: cached.explanation,
                  wasCorrect,
                  generatedBy: 'cache',
                  cached: true
              });
          }

          // ════════════════════════════════════════════════════════════════
          // BRANCH A — Deterministic (PIO / CHART / any question with freqs)
          // ════════════════════════════════════════════════════════════════
          if (hasSolverData(question, gtoFrequencies)) {
              const explanation = buildExplainAnswerPayload({
                  question,
                  userAnswer,
                  correctAnswer,
                  wasCorrect,
                  classification,
                  evLoss,
                  gtoFrequencies,
              });

              // Cache the deterministic payload — even though generation is
              // free, caching saves the Supabase round-trip + JSON build cost on
              // repeat keys.
              supabase
                  .from('grok_explanation_cache')
                  .upsert({
                      cache_key: cacheKey,
                      was_correct: wasCorrect,
                      question_hash: cacheKey,
                      game_id: gameId,
                      explanation,
                      hit_count: 1,
                      created_at: new Date().toISOString(),
                  }, { onConflict: 'cache_key,was_correct' })
                  .then(() => console.debug(`[Explain] Cached deterministic ${cacheKey.slice(0, 8)}…`))
                  .catch(e => console.warn('[Explain] Cache save failed:', e?.message || e));

              return res.status(200).json({
                  success: true,
                  explanation,
                  wasCorrect,
                  generatedBy: 'deterministic',
                  cached: false,
              });
          }

          // ════════════════════════════════════════════════════════════════
          // BRANCH B — SCENARIO / Psychology fallback (grok-3-mini)
          // No solver math exists for these questions; the LLM is the only
          // sensible source for tilt / mental-game / table-image coaching.
          // ════════════════════════════════════════════════════════════════
          const grok = getGrokClient();
          const scenario = question.scenario || {};

          // Level-appropriate tone (preserved from the prior implementation)
          const levelNum = parseInt(level, 10) || 1;
          let coachingTone;
          if (levelNum <= 3) {
              coachingTone =
                  'Use simple language. Avoid heavy jargon. Focus on the one key concept.';
          } else if (levelNum <= 6) {
              coachingTone =
                  'Use intermediate poker terminology. Reference ranges, equity, and discipline.';
          } else {
              coachingTone =
                  'Use advanced terminology. Reference variance, ICM, mental-game leaks, and tilt control.';
          }

          const prompt = `You are an elite poker MENTAL-GAME coach.
A student just ${wasCorrect ? 'CORRECTLY' : 'INCORRECTLY'} answered a psychology / mental-game scenario.

QUESTION: ${question.question || ''}
SCENARIO CONTEXT: ${scenario.context || scenario.title || 'Mental-game spot'}

USER'S ANSWER: ${userAnswer}
CORRECT ANSWER: ${correctAnswer}
RESULT: ${wasCorrect ? '✓ CORRECT': '✕ INCORRECT'}

COACHING TONE: ${coachingTone}

Provide your analysis in this EXACT JSON format (no markdown):
{
  "headline": "3–6 word headline about the psychological concept",
  "shortExplanation": "One sentence capturing the core mental-game insight",
  "deepDive": {
    "equityAnalysis": "How does this scenario affect decision-quality / EV indirectly?",
    "rangeConsiderations": "What mental-game habits / frames apply here?",
    "evCalculation": "Long-run cost of this leak (in sessions, sleep, focus, dollars)",
    "boardTexture": "What environmental cues should the student notice next time?"
  },
  "keyTakeaway": "The #1 actionable principle to remember",
  "similarSpots": "1–2 similar mental-game scenarios where this same concept applies",
  "mixedStrategyNote": "",
  "confidence": ${wasCorrect ? '0.9' : '0.7'}
}

Be specific to THIS scenario. Avoid generic advice.`;

          const response = await grok.chat.completions.create({
              model: 'grok-3-mini', // ← was grok-3 (Operation Grok-Sweep)
              messages: [{ role: 'user', content: prompt }],
              temperature: 0.7,
              max_tokens: 600,
          }, { signal: AbortSignal.timeout(15000) });

          const content = response.choices[0]?.message?.content || '';
          const jsonMatch = content.match(/\{[\s\S]*\}/);

          if (jsonMatch) {
              const explanation = JSON.parse(jsonMatch[0]);

              // Save SCENARIO response to cache
              supabase
                  .from('grok_explanation_cache')
                  .upsert({
                      cache_key: cacheKey,
                      was_correct: wasCorrect,
                      question_hash: cacheKey,
                      game_id: gameId,
                      explanation,
                      hit_count: 1,
                      created_at: new Date().toISOString(),
                  }, { onConflict: 'cache_key,was_correct' })
                  .then(() => console.debug(`[Explain] Cached scenario ${cacheKey.slice(0, 8)}…`))
                  .catch(e => console.warn('[Explain] Cache save failed:', e?.message || e));

              return res.status(200).json({
                  success: true,
                  explanation,
                  wasCorrect,
                  generatedBy: 'grok-3-mini',
                  cached: false,
              });
          }

          // JSON-extraction fallback for SCENARIO branch
          return res.status(200).json({
              success: true,
              explanation: {
                  headline: wasCorrect ? 'Strong mental game.' : 'Mental-game leak.',
                  shortExplanation: content.slice(0, 200) || 'Review the optimal mental-game response for this scenario.',
                  deepDive: null,
                  keyTakeaway: wasCorrect
                      ? 'Your mental-game habit here is solid — keep reinforcing it.'
                      : 'Identify the trigger and rehearse the optimal response.',
                  confidence: 0.5,
              },
              wasCorrect,
              generatedBy: 'grok-3-mini-fallback',
              cached: false,
          });

      } catch (error) {
          console.warn('[Explain] Error:', error?.message || error);

          // Graceful fallback — guarantee the frontend always gets a renderable shape.
          return res.status(200).json({
              success: true,
              explanation: {
                  headline: wasCorrect ? 'Correct.' : 'Suboptimal.',
                  shortExplanation:
                      question?.explanation ||
                      'Review the solver-approved play for this spot.',
                  deepDive: {
                      equityAnalysis: 'Equity profile not available for this node.',
                      rangeConsiderations: 'Standard balanced ranges apply.',
                      evCalculation: 'Exact EV not reported.',
                      boardTexture: 'Texture not provided.',
                  },
                  keyTakeaway: wasCorrect
                      ? 'You made the GTO-optimal decision.'
                      : 'The solver recommends a different action here.',
                  similarSpots: 'Drill this exact node in the GTO Trainer.',
                  mixedStrategyNote: '',
                  confidence: 0.3,
              },
              wasCorrect,
              generatedBy: 'fallback',
              cached: false,
          });
      }

  } catch (err) {
      try { reportApiError(err, req); } catch (_sentryErr) { console.warn('[App] Handled exception:', _sentryErr?.message || _sentryErr); }
    console.warn('[API Error]', err);
    if (!res.headersSent) return res.status(500).json({ success: false, error: 'Internal server error' });
  }
}
