/**
 * 📢 TRAINING SOCIAL SHARE API
 * ═══════════════════════════════════════════════════════════════════════════
 * Share achievements, milestones, and accomplishments to the social feed
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { createClient } from '@supabase/supabase-js';
import { applyRateLimit, LIMITS } from '../../../src/lib/apiRateLimit';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

// Share type templates
const SHARE_TEMPLATES = {
    achievement: {
        generateContent: (data) =>
            `🏅 I just unlocked the "${data.name}" achievement in GTO Training! ${data.description || ''}`,
        postType: 'achievement'
    },
    challenge: {
        generateContent: (data) =>
            `🎯 I completed the ${data.challengeType} challenge: "${data.name}"! +${data.diamonds}💎`,
        postType: 'challenge'
    },
    streak: {
        generateContent: (data) =>
            `🔥 ${data.days}-day GTO Training streak! I'm on fire! ${data.days >= 30 ? '👑' : data.days >= 14 ? '⚡' : '💪'}`,
        postType: 'milestone'
    },
    perfect_round: {
        generateContent: (data) =>
            `💎 Perfect Round! 100% accuracy on "${data.gameName}"! That's ${data.totalPerfect} perfect rounds total!`,
        postType: 'accomplishment'
    },
    leaderboard: {
        generateContent: (data) =>
            `🏆 I reached #${data.rank} on the ${data.period} GTO Training leaderboard!`,
        postType: 'milestone'
    },
    session_complete: {
        generateContent: (data) =>
            `📚 Just completed a training session on "${data.gameName}" with ${data.accuracy}% accuracy!`,
        postType: 'update'
    }
};

export default async function handler(req, res) {
  if (['POST','PUT','PATCH','DELETE'].includes(req.method)) {
    if (!applyRateLimit(req, res, LIMITS.write)) return;
  }

    // Require JWT auth for write operations
    if (req.method !== 'GET') {
        const _token = req.headers.authorization?.replace('Bearer ', '');
        if (!_token) return res.status(401).json({ error: 'Authentication required' });
        const { data: { user: _authUser }, error: _authErr } = await supabase.auth.getUser(_token);
        if (_authErr || !_authUser) return res.status(401).json({ error: 'Invalid token' });
        if (req.body) req.body.userId = _authUser.id;
    }

    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    const supabase = createClient(supabaseUrl, supabaseKey);

    const {
        userId,
        shareType,  // 'achievement', 'challenge', 'streak', 'perfect_round', 'leaderboard', 'session_complete'
        data,       // Relevant data for the share type
        customMessage // Optional user override
    } = req.body;

    if (!userId || !shareType) {
        return res.status(400).json({ error: 'userId and shareType required' });
    }

    const template = SHARE_TEMPLATES[shareType];
    if (!template) {
        return res.status(400).json({ error: `Invalid shareType: ${shareType}` });
    }

    try {
        // Generate content from template or use custom message
        const content = customMessage || template.generateContent(data);

        // Create unique ID for the post
        const postId = `training-${shareType}-${userId}-${Date.now()}`;

        // Get user profile for the post
        const { data: profile } = await supabase
            .from('profiles')
            .select('username, avatar_url, display_name')
            .eq('id', userId)
            .single();

        // Create the social post
        const { data: post, error } = await supabase
            .from('social_posts')
            .insert({
                id: postId,
                user_id: userId,
                content,
                type: 'training_share',
                metadata: {
                    shareType,
                    postType: template.postType,
                    trainingData: data,
                    autoGenerated: !customMessage
                }
            })
            .select()
            .single();

        if (error) {
            console.error('[TrainingShare] Insert error:', error);

            // If social_posts doesn't exist, just log success
            if (error.code === '42P01') {
                return res.status(200).json({
                    success: true,
                    message: 'Share logged (social feed table not available)',
                    content
                });
            }

            throw error;
        }

        return res.status(200).json({
            success: true,
            postId: post?.id || postId,
            content,
            shareType,
            message: 'Successfully shared to your feed!'
        });

    } catch (error) {
        console.error('[TrainingShare] Error:', error.message);
        return res.status(500).json({ error: 'Failed to share' });
    }
}
