/**
 * TRAINING SOCIAL SHARE API
 *
 * Only explicitly user-authored text may be published through this legacy
 * route. Browser-provided achievement, challenge, streak, leaderboard, and
 * session statistics are not trusted to generate a verified accomplishment.
 */

import { createClient } from '../../../src/lib/supabaseServerClient';
import { applyRateLimit, LIMITS } from '../../../src/lib/apiRateLimit';
import { withTiming } from '../../../src/utils/trainingApiUtils';
import { reportApiError } from '../../../src/lib/sentryWrap';
import { getServerUserWithFallback } from '../../../src/lib/serverAuth';

let _supabase = null;
function getSupabase() {
    if (!_supabase) {
        _supabase = createClient(
            process.env.NEXT_PUBLIC_SUPABASE_URL,
            process.env.SUPABASE_SERVICE_ROLE_KEY
        );
    }
    return _supabase;
}

export default async function handler(req, res) {
  try {
      withTiming(res);
      if (req.method !== 'POST') {
          return res.status(405).json({ success: false, error: 'Method not allowed' });
      }
      if (!applyRateLimit(req, res, LIMITS.write)) return;

      const bodySize = JSON.stringify(req.body || {}).length;
      if (bodySize > 10240) {
          return res.status(413).json({ success: false, error: 'Request body too large' });
      }

      const customMessage = typeof req.body?.customMessage === 'string'
          ? req.body.customMessage.trim()
          : '';
      if (!customMessage) {
          return res.status(410).json({
              success: false,
              error: 'Verified Training accomplishments require server-authoritative share data.',
              code: 'TRAINING_SHARE_SERVER_AUTHORITY_REQUIRED',
          });
      }
      if (customMessage.length > 2000 || customMessage.includes('\u0000')) {
          return res.status(400).json({ success: false, error: 'Custom message must be 1-2000 valid characters' });
      }

      const supabase = getSupabase();
      const { user, error: authErr } = await getServerUserWithFallback(req, supabase);
      if (!user) {
          if (authErr === 'No token') return res.status(401).json({ success: false, error: 'Authentication required' });
          return res.status(401).json({ success: false, error: 'Invalid token' });
      }

      const postId = `training-custom-${user.id}-${Date.now()}`;
      const { data: post, error } = await supabase
          .from('social_posts')
          .insert({
              id: postId,
              author_id: user.id,
              content: customMessage,
              content_type: 'training_share',
              metadata: {
                  shareType: 'custom',
                  postType: 'update',
                  autoGenerated: false,
              },
          })
          .select('id')
          .maybeSingle();

      if (error) {
          console.warn('[TrainingShare] Insert error:', error.message);
          return res.status(500).json({ success: false, error: 'Failed to share' });
      }

      return res.status(200).json({
          success: true,
          postId: post?.id || postId,
          content: customMessage,
          shareType: 'custom',
          message: 'Successfully shared to your feed!',
      });
  } catch (err) {
      try { reportApiError(err, req); } catch (_sentryErr) { console.warn('[App] Handled exception:', _sentryErr?.message || _sentryErr); }
      console.warn('[API Error]', err);
      if (!res.headersSent) return res.status(500).json({ success: false, error: 'Internal server error' });
  }
}
