/**
 * THE MINT -- platform issuance and retirement API
 *
 * GET  /api/horses/mint?section=overview
 * GET  /api/horses/mint?section=ledger&asset=&action=&limit=&offset=
 * GET  /api/horses/mint?section=targets                 (clubs + unions, with balances)
 * GET  /api/horses/mint?section=player_search&q=<text>  (diamond recipients)
 * POST /api/horses/mint  { action, asset, target, targetId, amount, reason, opId }
 *
 * WHY THIS ROUTE EXISTS (added 2026-09-02)
 *
 * `fn_ca_mint` had been in the database since the issuance-reserve work and had
 * never once been called -- `ca_op_claims` held zero rows for it. There was no
 * route and no panel, so the only way to create supply was a hand-written
 * migration, which CLAUDE.md section 10.6 forbids by name. This is the surface
 * that makes the authorized path the easy path.
 *
 * DAN'S LAW ON DESTINATIONS (2026-09-02, verbatim): "chips sent to clubs or
 * unions go directly into every club or union wallet. chips never get sent to
 * individual users only diamonds can do that."
 *
 * So the shape below is not a UI convenience, it is the rule:
 *   chips    -> club treasury | union bank
 *   diamonds -> an individual player
 * The route refuses anything else BEFORE the RPC, and the RPC refuses it again.
 * Two gates, because the first one is javascript and the second one is not.
 *
 * WHY THE SERVICE ROLE
 *
 * Every read here is blocked from the browser by RLS -- an account with
 * profiles.role='admin' reads zero of 1501 club_members and zero
 * chip_transactions, because the policies are scoped to club staff rather than
 * platform staff (see the header of club-arena-admin.js, which was written
 * after that exact failure rendered "0 members" for every club). So the gate is
 * `requireAdmin` in this file and the queries run with the service key. Do not
 * move them back into the browser.
 *
 * IDEMPOTENCY IS THE CALLER'S JOB AND THE PANEL DOES IT
 *
 * `opId` is generated by the browser BEFORE the operator presses the button and
 * sent unchanged on every retry. `fn_ca_mint` claims that key, and a replay
 * returns the ORIGINAL result with `replayed: true` instead of minting a second
 * time. A double-click cannot double the money. If the client omits it we mint
 * nothing -- we do not invent a key here, because a key invented per-request is
 * not an idempotency key at all.
 */
import { getServerUserWithFallback } from '../../../src/lib/serverAuth';
import { createClient } from '../../../src/lib/supabaseServerClient';
import { applyRateLimit, LIMITS } from '../../../src/lib/apiRateLimit';
import { reportApiError } from '../../../src/lib/sentryWrap';

let _supabase = null;
function getSupabase() {
  if (!_supabase) {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://kuklfnapbkmacvwxktbh.supabase.co';
    const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
    _supabase = createClient(url, key);
  }
  return _supabase;
}

const ADMIN_ROLES = ['admin', 'superadmin', 'god'];
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** The single-operation ceilings the RPC also enforces. Mirrored so the panel
 *  can say no without a round trip; the database still has the last word. */
const CAPS = { chips: 1000000000, diamonds: 10000000 };

/** Dan's law, expressed as data. `chips` never reaches a person. */
const ALLOWED_TARGETS = { chips: ['club', 'union'], diamonds: ['player'] };

const LEDGER_FIELDS =
  'id, op_id, action, asset, holder_type, holder_id, holder_label, amount, ' +
  'balance_before, balance_after, supply_after, reason, performed_by, ' +
  'performed_by_label, created_at, chip_ledger_id, diamond_tx_id';

const LEDGER_PAGE_MAX = 200;

/**
 * PostgREST `.or()` takes a comma-separated filter STRING, so an unescaped
 * comma, parenthesis or dot in user input does not "inject SQL" but does
 * rewrite the filter tree. Strip everything structural to that grammar.
 */
function sanitizeSearch(raw) {
  return String(raw || '')
    .replace(/[,()*\\%.]/g, ' ')
    .trim()
    .slice(0, 60);
}

async function requireAdmin(req, res) {
  const token = req.headers.authorization?.replace('Bearer ', '');
  if (!token) {
    res.status(401).json({ success: false, error: 'Authorization required' });
    return null;
  }
  const { user, error: authErr } = await getServerUserWithFallback(req, getSupabase());
  if (authErr || !user) {
    res.status(401).json({ success: false, error: 'Invalid token' });
    return null;
  }
  const { data: profile } = await getSupabase()
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .maybeSingle();
  if (!profile || !ADMIN_ROLES.includes(profile.role)) {
    res.status(403).json({ success: false, error: 'Admin access required' });
    return null;
  }
  return user;
}

// -- READS -------------------------------------------------------------------

/**
 * Supply and circulation. `fn_ca_mint_overview` reports issued totals from the
 * Mint journal and circulating totals from the live balances SEPARATELY and on
 * purpose: the platform has ~172M chips in member wallets that predate the Mint
 * entirely, so "issued" and "circulating" are not supposed to match yet and a
 * panel that reconciled them silently would be lying.
 */
async function sectionOverview() {
  const db = getSupabase();
  const [{ data: totals, error: totalsErr }, { data: recent }] = await Promise.all([
    db.rpc('fn_ca_mint_overview'),
    db.from('ca_mint_ledger').select(LEDGER_FIELDS).order('created_at', { ascending: false }).limit(10),
  ]);

  if (totalsErr) throw totalsErr;
  return { totals: totals || null, recent: recent || [] };
}

async function sectionLedger(query) {
  const db = getSupabase();
  const limit = Math.min(Number(query.limit) || 50, LEDGER_PAGE_MAX);
  const offset = Math.max(Number(query.offset) || 0, 0);

  let q = db
    .from('ca_mint_ledger')
    .select(LEDGER_FIELDS, { count: 'exact' })
    .order('created_at', { ascending: false })
    .range(offset, offset + limit - 1);

  if (query.asset === 'chips' || query.asset === 'diamonds') q = q.eq('asset', query.asset);
  if (query.action === 'mint' || query.action === 'burn') q = q.eq('action', query.action);
  if (UUID_RE.test(String(query.holderId || ''))) q = q.eq('holder_id', query.holderId);

  const { data, error, count } = await q;
  if (error) throw error;
  return { entries: data || [], total: count ?? 0, limit, offset };
}

/**
 * Everything chips can legally be issued to, with its CURRENT balance, so the
 * operator sees what a club holds before deciding what to add to it. Union
 * balances live in union_wallets rather than on the union row, and a union that
 * has never held chips has no wallet row at all -- that is not an error, it is
 * a zero, and fn_ca_mint creates the row on first issuance.
 */
async function sectionTargets() {
  const db = getSupabase();
  const [{ data: clubs, error: clubErr }, { data: unions, error: unionErr }, { data: wallets }] =
    await Promise.all([
      db.from('clubs').select('id, name, club_id, code, status, chip_treasury').order('name'),
      db.from('unions').select('id, name, code, union_code').order('name'),
      db.from('union_wallets').select('union_id, chip_balance'),
    ]);

  if (clubErr) throw clubErr;
  if (unionErr) throw unionErr;

  const walletByUnion = {};
  for (const w of wallets || []) walletByUnion[w.union_id] = Number(w.chip_balance) || 0;

  return {
    clubs: (clubs || []).map((c) => ({
      id: c.id,
      label: c.name,
      code: c.club_id || c.code || null,
      status: c.status || null,
      balance: Number(c.chip_treasury) || 0,
    })),
    unions: (unions || []).map((u) => ({
      id: u.id,
      label: u.name,
      code: u.union_code || u.code || null,
      balance: walletByUnion[u.id] || 0,
    })),
  };
}

/**
 * Diamond recipients. Horses are NOT filtered out: CLAUDE.md section 10.5 is a
 * hard law and a horse is a player, so if the operator wants to grant one
 * diamonds the panel does not get an opinion about it. `is_horse` is surfaced
 * as a BADGE so the operator can see what they are picking -- identification,
 * which the law explicitly still allows.
 */
async function sectionPlayerSearch(query) {
  const term = sanitizeSearch(query.q);
  if (term.length < 2) return { players: [] };

  const db = getSupabase();
  let q = db
    .from('profiles')
    .select('id, username, display_name, full_name, player_number, diamonds, is_horse, avatar_url')
    .limit(25);

  // A bare number is almost always a player_number, which is how staff refer to
  // an account out loud.
  if (/^\d+$/.test(term)) {
    q = q.eq('player_number', Number(term));
  } else {
    q = q.or(`username.ilike.%${term}%,display_name.ilike.%${term}%,full_name.ilike.%${term}%`);
  }

  const { data, error } = await q;
  if (error) throw error;

  return {
    players: (data || []).map((p) => ({
      id: p.id,
      label: p.display_name || p.username || p.full_name || `${String(p.id).slice(0, 8)}...`,
      username: p.username || null,
      playerNumber: p.player_number ?? null,
      balance: Number(p.diamonds) || 0,
      isHorse: Boolean(p.is_horse),
      avatarUrl: p.avatar_url || null,
    })),
  };
}

// -- WRITE -------------------------------------------------------------------

/**
 * Validate before the round trip. Every rule here is also enforced inside the
 * RPC -- this layer exists to give the operator a sentence they can act on
 * instead of a snake_case reason code, not to be the only thing standing
 * between a typo and the money.
 */
function validateIssuance(body) {
  const action = String(body.action || '').toLowerCase();
  const asset = String(body.asset || '').toLowerCase();
  const target = String(body.target || '').toLowerCase();
  const reason = String(body.reason || '').trim();
  const opId = String(body.opId || '').trim();
  const amount = Number(body.amount);

  if (action !== 'mint' && action !== 'burn') {
    return { error: 'Action must be mint or burn.' };
  }
  if (!CAPS[asset]) {
    return { error: 'Asset must be chips or diamonds.' };
  }
  if (!ALLOWED_TARGETS[asset].includes(target)) {
    return {
      error:
        asset === 'chips'
          ? 'Chips are issued to a club treasury or a union bank only, never to an individual.'
          : 'Diamonds are issued to an individual player only, never to a club or union.',
    };
  }
  if (!UUID_RE.test(String(body.targetId || ''))) {
    return { error: 'Pick a valid destination.' };
  }
  if (!Number.isFinite(amount) || amount <= 0) {
    return { error: 'Amount must be a positive number.' };
  }
  if (Math.round(amount * 100) !== amount * 100) {
    return { error: 'Amount cannot be finer than two decimal places.' };
  }
  if (asset === 'diamonds' && !Number.isInteger(amount)) {
    return { error: 'Diamonds are whole numbers.' };
  }
  if (amount > CAPS[asset]) {
    return { error: `That is over the single-operation cap of ${CAPS[asset].toLocaleString()}.` };
  }
  if (reason.length < 10) {
    return { error: 'Write a real reason. It is the only explanation anyone auditing this will have.' };
  }
  if (!opId) {
    return { error: 'Missing idempotency key. Reload the panel and try again.' };
  }

  return { action, asset, target, targetId: body.targetId, amount, reason, opId };
}

/**
 * Reason codes the database returns, in plain English. Anything not listed is
 * passed through verbatim rather than swallowed -- an unrecognised refusal is
 * information, and hiding it behind "something went wrong" is how a money bug
 * survives a week.
 */
const REASON_TEXT = {
  the_mint_is_admin_only: 'The Mint is restricted to platform admins.',
  asset_must_be_chips_or_diamonds: 'Asset must be chips or diamonds.',
  chips_are_issued_to_a_club_or_union_wallet_only:
    'Chips are issued to a club treasury or a union bank only.',
  chips_are_retired_from_a_club_or_union_wallet_only:
    'Chips are retired from a club treasury or a union bank only.',
  diamonds_are_issued_to_an_individual_player_only:
    'Diamonds are issued to an individual player only.',
  diamonds_are_retired_from_an_individual_player_only:
    'Diamonds are retired from an individual player only.',
  target_required: 'Pick a destination.',
  amount_must_be_positive_to_two_decimals: 'Amount must be positive, to at most two decimals.',
  diamonds_are_whole_numbers: 'Diamonds are whole numbers.',
  amount_over_the_single_mint_cap: 'That is over the single-operation cap.',
  issuance_needs_a_real_reason: 'Issuance needs a reason of at least ten characters.',
  retirement_needs_a_real_reason: 'Retirement needs a reason of at least ten characters.',
  idempotency_key_required: 'Missing idempotency key. Reload the panel and try again.',
  player_not_found: 'No player with that id.',
  club_not_found: 'No club with that id.',
  union_not_found: 'No union with that id.',
  union_wallet_not_found: 'That union has no chip wallet yet, so there is nothing to retire.',
  that_would_take_the_balance_below_zero: 'That is more than the player holds.',
  that_would_take_the_treasury_below_zero: 'That is more than the club treasury holds.',
  that_would_take_the_union_bank_below_zero: 'That is more than the union bank holds.',
};

async function handleIssuance(req, res, user) {
  const parsed = validateIssuance(req.body || {});
  if (parsed.error) {
    return res.status(400).json({ success: false, error: parsed.error });
  }

  const { action, asset, target, targetId, amount, reason, opId } = parsed;
  const db = getSupabase();

  // fn_ca_mint takes a destination; fn_ca_burn takes a source. Same six values,
  // opposite direction, and the parameter names say which way the chips move.
  const { data, error } =
    action === 'mint'
      ? await db.rpc('fn_ca_mint', {
          p_asset: asset,
          p_destination: target,
          p_target_id: targetId,
          p_amount: amount,
          p_reason: reason,
          p_op_id: opId,
        })
      : await db.rpc('fn_ca_burn', {
          p_asset: asset,
          p_source: target,
          p_target_id: targetId,
          p_amount: amount,
          p_reason: reason,
          p_op_id: opId,
        });

  if (error) throw error;

  if (!data || data.ok !== true) {
    const code = data?.reason || 'unknown';
    return res.status(400).json({
      success: false,
      error: REASON_TEXT[code] || `The Mint refused this: ${code}`,
      reason: code,
      detail: data || null,
    });
  }

  return res.status(200).json({ success: true, result: data, performedBy: user.id });
}

// -- HANDLER -----------------------------------------------------------------

export default async function handler(req, res) {
  try {
    if (req.method === 'GET') {
      if (!applyRateLimit(req, res, LIMITS.read)) return;
      const user = await requireAdmin(req, res);
      if (!user) return;

      const section = String(req.query.section || 'overview');
      let payload;
      if (section === 'overview') payload = await sectionOverview();
      else if (section === 'ledger') payload = await sectionLedger(req.query);
      else if (section === 'targets') payload = await sectionTargets();
      else if (section === 'player_search') payload = await sectionPlayerSearch(req.query);
      else return res.status(400).json({ success: false, error: 'Unknown section' });

      return res.status(200).json({ success: true, ...payload });
    }

    if (req.method === 'POST') {
      // Financial limit, not the write limit: 20/min is far more than a human
      // operator needs and far less than a runaway client can do damage with.
      if (!applyRateLimit(req, res, LIMITS.financial)) return;
      const user = await requireAdmin(req, res);
      if (!user) return;
      return await handleIssuance(req, res, user);
    }

    res.setHeader('Allow', 'GET, POST');
    return res.status(405).json({ success: false, error: 'Method not allowed' });
  } catch (err) {
    reportApiError(err, req, { route: '/api/horses/mint' });
    return res.status(500).json({ success: false, error: err?.message || 'The Mint is unavailable' });
  }
}
