/**
 * THE MINT - platform issuance and retirement API
 *
 * GET  /api/horses/mint?section=overview
 * GET  /api/horses/mint?section=ledger&asset=&action=&origin=&holderId=&limit=&offset=
 * GET  /api/horses/mint?section=targets                 (clubs + unions, with balances)
 * GET  /api/horses/mint?section=player_search&q=<text>  (diamond recipients)
 * POST /api/horses/mint  { action, asset, target, targetId, amount, reason, opId }
 *
 * PHASE 1 NOTE (2026-09-02). Rebuilt onto src/lib/horses/operatorRoute.js:
 * money.read on GET, money.write on POST, and a DURABLE rate limit of 20 write
 * operations a minute per operator. The in-memory limiter this route used
 * before is per lambda instance, so on Vercel the effective ceiling was
 * 20 x instances - which is not a ceiling at all on the one route that creates
 * money. Three further fixes: the amount is parsed with money2dp so
 * 0.07 / 0.29 / 1.15 are accepted (the old float comparison refused them), the
 * ledger pages properly, and no database error text can reach the browser.
 *
 * WHY THIS ROUTE EXISTS (added 2026-09-02)
 *
 * `fn_ca_mint` had been in the database since the issuance-reserve work and had
 * never once been called - `ca_op_claims` held zero rows for it. There was no
 * route and no panel, so the only way to create supply was a hand-written
 * migration, which CLAUDE.md section 10.6 forbids by name. This is the surface
 * that makes the authorized path the easy path.
 *
 * DAN'S LAW ON DESTINATIONS (2026-09-02, verbatim): "chips sent to clubs or
 * unions go directly into every club or union wallet. chips never get sent to
 * individual users only diamonds can do that."
 *
 * So the shape below is not a UI convenience, it is the rule:
 *   chips    -> club treasury | union bank
 *   diamonds -> an individual player
 * The route refuses anything else BEFORE the RPC, and the RPC refuses it again.
 * Two gates, because the first one is javascript and the second one is not.
 *
 * WHY THE SERVICE ROLE
 *
 * Every read here is blocked from the browser by RLS - an account with
 * profiles.role='admin' reads zero of 1501 club_members and zero
 * chip_transactions, because the policies are scoped to club staff rather than
 * platform staff (see the header of club-arena-admin.js, which was written
 * after that exact failure rendered "0 members" for every club). The wrapper's
 * service-role client is the only client this route ever sees. Do not move
 * these queries back into the browser.
 *
 * IDEMPOTENCY IS THE CALLER'S JOB AND THE PANEL DOES IT
 *
 * `opId` is generated by the browser BEFORE the operator presses the button and
 * sent unchanged on every retry. `fn_ca_mint` claims that key, and a replay
 * returns the ORIGINAL result with `replayed: true` instead of minting a second
 * time. A double-click cannot double the money. If the client omits it we mint
 * nothing - we do not invent a key here, because a key invented per-request is
 * not an idempotency key at all.
 *
 * PHASE 2 (2026-09-03): MAKER-CHECKER
 *
 * `requireApproval` runs BEFORE fn_ca_mint / fn_ca_burn and
 * `markApprovalExecuted` runs after the chips have moved. With
 * ca_operator_policy.approvals_enabled false - which is the default and the
 * state of production today - the call records an auto_approved row and returns
 * required:false, so this route behaves exactly as it did before. When Dan turns
 * approvals on, an operation at or over the threshold returns 202 with
 * { success: true, pending: true, approvalId, status, message } and touches no
 * money at all.
 *
 * The approval row carries the SAME opId, which is what makes an approved
 * request execute exactly once: the key the approval was raised under is the key
 * fn_ca_mint claims when it finally runs.
 */
import { withOperatorRoute } from '../../../src/lib/horses/operatorRoute.js';
import { PERMISSIONS } from '../../../src/lib/horses/permissions.js';
import { ApiError, badRequest } from '../../../src/lib/horses/apiEnvelope.js';
import { auditOperatorAction } from '../../../src/lib/horses/operatorAudit.js';
import {
  requireApproval,
  markApprovalExecuted,
  approvalPendingResponse,
} from '../../../src/lib/horses/approvals.js';
import { paging, runPaged } from '../../../src/lib/horses/paged.js';
import {
  pageFor,
  readByIds,
  shapeList,
  shapeUnknownTotal,
  sourceCollector,
} from '../../../src/lib/horses/listShape.js';
import { uuid, enumOf, money2dp, text, searchTerm } from '../../../src/lib/horses/validate.js';

/** Sanity ceilings for the pre-flight check only. The real caps live in
 *  ca_mint_policy (10,000,000 chips / 1,000,000 diamonds per operation by
 *  default, plus a rolling 24h ceiling) and fn_ca_mint refuses over them with
 *  a reason code this route translates; the database has the last word. */
const CAPS = { chips: 1000000000, diamonds: 10000000 };

/** Dan's law, expressed as data. `chips` never reaches a person. */
const ALLOWED_TARGETS = { chips: ['club', 'union'], diamonds: ['player'] };

const SECTIONS = ['overview', 'ledger', 'targets', 'player_search'];

const LEDGER_FIELDS =
  'id, op_id, action, asset, holder_type, holder_id, holder_label, amount, ' +
  'balance_before, balance_after, supply_after, reason, performed_by, ' +
  'performed_by_label, created_at, chip_ledger_id, diamond_tx_id, origin';

/** Where a register row came from (ca_mint_ledger.origin, generated from
 *  the op id in 20260904194036_the_mint_hardened). The panel filters on it. */
const ORIGINS = ['operator', 'journal', 'baseline', 'diamond-mint', 'opening-grant', 'restoration', 'seed', 'deletion'];

/** Restored to the original 200 (addendum item 10): the journal is rendered
 *  without a pager on first load, and 50 rows of it is half a screen. */
const LEDGER_PAGE = { defaultLimit: 200, max: 500 };
/** The destination pickers need every club and union, not a 50-row page, so
 *  this section pages with a deliberately large default and says `truncated`
 *  the moment the list does not fit. 500 is the contract ceiling. */
const TARGET_PAGE = { defaultLimit: 500, max: 500 };
const PLAYER_PAGE = { defaultLimit: 25, max: 50 };

// -- READS -------------------------------------------------------------------

/**
 * Supply and circulation. Until 2026-09-04 18:34 UTC "issued" and
 * "circulating" were not supposed to match: ~172M chips in member wallets
 * predated the Mint. The opening baseline (chip standard Phase 3.1) sized the
 * register to the supply meter at that instant, and since then the register
 * FOLLOWS the journal (a constraint trigger registers every issuance leg at
 * commit), so they are supposed to match, and `fn_ca_mint_overview` says
 * whether they do: `reconciliation` (register net as of the meter's
 * snapshot, meter total, difference, unexplained drift since the baseline,
 * `balanced`), `issuance` (since the baseline and in 24h), `policy` (the
 * caps in ca_mint_policy with 24h headroom) and `by_origin`. Passed through
 * whole; the old keys are still there (add, never rename).
 */
async function sectionOverview(db, requestId) {
  const c = sourceCollector({ requestId, route: 'horses.mint' });
  const [{ data: totals, error: totalsErr }, recentRes] = await Promise.all([
    db.rpc('fn_ca_mint_overview'),
    db.from('ca_mint_ledger').select(LEDGER_FIELDS).order('created_at', { ascending: false }).limit(10),
  ]);

  if (totalsErr) {
    console.error(`[horses.mint] ${requestId} fn_ca_mint_overview failed:`, totalsErr.message);
    throw new ApiError(503, 'The Mint Overview Is Unavailable', 'mint_overview_unavailable');
  }
  // The recent-operations read used to discard its error, so a broken read
  // rendered as "no recent operations" on the one panel whose job is to show
  // that money moved.
  c.check('ca_mint_ledger_recent', recentRes);
  return { totals: totals || null, recent: recentRes.data || [], failedSources: c.list() };
}

/** Contract item 5: the journal pages, and says how many rows there are. */
async function sectionLedger(db, query) {
  const page = paging(query, LEDGER_PAGE);

  let q = db
    .from('ca_mint_ledger')
    .select(LEDGER_FIELDS, { count: 'exact' })
    .order('created_at', { ascending: false });

  const asset = enumOf(query.asset, ['chips', 'diamonds']);
  if (asset) q = q.eq('asset', asset);
  const action = enumOf(query.action, ['mint', 'burn']);
  if (action) q = q.eq('action', action);
  const holderId = uuid(query.holderId);
  if (holderId) q = q.eq('holder_id', holderId);
  const origin = enumOf(query.origin, ORIGINS);
  if (origin) q = q.eq('origin', origin);

  const result = await runPaged(q, page);
  if (result.error) {
    console.error('[horses.mint] ledger read failed:', result.error.message);
    throw new ApiError(503, 'The Mint Journal Is Unavailable', 'mint_ledger_unavailable');
  }

  const shaped = shapeList(result, page);
  // `entries` is what the console renders today. Added to, never renamed.
  return { ...shaped, entries: shaped.rows };
}

/**
 * Everything chips can legally be issued to, with its CURRENT balance, so the
 * operator sees what a club holds before deciding what to add to it. Union
 * balances live in union_wallets rather than on the union row, and a union that
 * has never held chips has no wallet row at all - that is not an error, it is
 * a zero, and fn_ca_mint creates the row on first issuance.
 */
async function sectionTargets(db, query, requestId) {
  // Independently pageable, so the club list can be advanced without dragging
  // the union list along with it.
  const clubsPage = pageFor(query, 'clubs', TARGET_PAGE);
  const unionsPage = pageFor(query, 'unions', TARGET_PAGE);

  const [clubsRes, unionsRes] = await Promise.all([
    runPaged(
      db
        .from('clubs')
        .select('id, name, club_id, code, status, chip_treasury', { count: 'exact' })
        .order('name'),
      clubsPage
    ),
    runPaged(
      db.from('unions').select('id, name, code, union_code', { count: 'exact' }).order('name'),
      unionsPage
    ),
  ]);

  if (clubsRes.error || unionsRes.error) {
    console.error(
      `[horses.mint] ${requestId} targets read failed:`,
      clubsRes.error?.message || unionsRes.error?.message
    );
    throw new ApiError(503, 'The Destination List Is Unavailable', 'mint_targets_unavailable');
  }

  // Wallets FOR THE UNIONS ON THE PAGE. It used to be a flat `.limit(1000)`
  // with no relation to the page at all, so past the first thousand wallets
  // every union on screen showed a balance of 0 while holding chips.
  const unionIds = (unionsRes.data || []).map((u) => u.id);
  const walletsRead = await readByIds(db, unionIds, (part) =>
    db.from('union_wallets').select('union_id, chip_balance').in('union_id', part)
  );
  if (walletsRead.error) {
    console.error(`[horses.mint] ${requestId} union_wallets read failed:`, walletsRead.error.message);
  }

  const walletByUnion = {};
  for (const w of walletsRead.rows) walletByUnion[w.union_id] = Number(w.chip_balance) || 0;

  const clubs = (clubsRes.data || []).map((c) => ({
    id: c.id,
    label: c.name,
    code: c.club_id || c.code || null,
    status: c.status || null,
    balance: Number(c.chip_treasury) || 0,
  }));
  const unions = (unionsRes.data || []).map((u) => ({
    id: u.id,
    label: u.name,
    code: u.union_code || u.code || null,
    balance: walletByUnion[u.id] || 0,
  }));

  const clubPage = shapeList(clubsRes, clubsPage, clubs);
  const unionPage = shapeList(unionsRes, unionsPage, unions);

  return {
    clubs,
    unions,
    pages: { clubs: clubPage, unions: unionPage },
    limit: clubsPage.limit,
    offset: clubsPage.offset,
    clubTotal: clubPage.total,
    unionTotal: unionPage.total,
    walletBalancesAvailable: !walletsRead.error,
    // Explicit rather than implied: a picker missing the club the operator
    // wants is indistinguishable from that club not existing.
    truncated: clubPage.truncated || unionPage.truncated,
  };
}

/**
 * Diamond recipients. Horses are NOT filtered out: CLAUDE.md section 10.5 is a
 * hard law and a horse is a player, so if the operator wants to grant one
 * diamonds the panel does not get an opinion about it. `is_horse` is surfaced
 * as a BADGE so the operator can see what they are picking - identification,
 * which the law explicitly still allows.
 */
async function sectionPlayerSearch(db, query, requestId) {
  const page = paging(query, PLAYER_PAGE);
  const term = searchTerm(query.q, { max: 60 });
  if (!term || term.length < 2) {
    return {
      players: [],
      rows: [],
      total: 0,
      limit: page.limit,
      offset: page.offset,
      hasMore: false,
      truncated: false,
    };
  }

  // NO COUNT (addendum item 10). The Phase 1 rebuild put `count: 'exact'`
  // behind three LEADING-wildcard ilike filters on `profiles`, so every
  // keystroke in the recipient box paid for a full scan plus a sort. The
  // original was a bare `.limit(25)`. `total` is null and the pager takes Next
  // from `hasMore`.
  let q = db
    .from('profiles')
    .select('id, username, display_name, full_name, player_number, diamonds, is_horse, avatar_url')
    .order('player_number', { ascending: true });

  // A bare number is almost always a player_number, which is how staff refer to
  // an account out loud.
  if (/^\d+$/.test(term)) {
    q = q.eq('player_number', Number(term));
  } else {
    q = q.or(`username.ilike.%${term}%,display_name.ilike.%${term}%,full_name.ilike.%${term}%`);
  }

  const result = await runPaged(q, page);
  if (result.error) {
    console.error(`[horses.mint] ${requestId} player search failed:`, result.error.message);
    throw new ApiError(503, 'Player Search Is Unavailable', 'mint_player_search_unavailable');
  }

  const players = (result.data || []).map((p) => ({
    id: p.id,
    label: p.display_name || p.username || p.full_name || `${String(p.id).slice(0, 8)}...`,
    username: p.username || null,
    playerNumber: p.player_number ?? null,
    balance: Number(p.diamonds) || 0,
    isHorse: Boolean(p.is_horse),
    avatarUrl: p.avatar_url || null,
  }));

  const shaped = shapeUnknownTotal(players, page, { countMode: 'none' });
  return { ...shaped, players };
}

// -- WRITE -------------------------------------------------------------------

/**
 * Validate before the round trip. Every rule here is also enforced inside the
 * RPC - this layer exists to give the operator a sentence they can act on
 * instead of a snake_case reason code, not to be the only thing standing
 * between a typo and the money.
 */
export function validateIssuance(body) {
  const action = enumOf(String(body.action || '').toLowerCase(), ['mint', 'burn']);
  if (!action) throw badRequest('Action Must Be Mint Or Burn');

  const asset = enumOf(String(body.asset || '').toLowerCase(), ['chips', 'diamonds']);
  if (!asset) throw badRequest('Asset Must Be Chips Or Diamonds');

  const target = enumOf(String(body.target || '').toLowerCase(), ALLOWED_TARGETS[asset]);
  if (!target) {
    throw badRequest(
      asset === 'chips'
        ? 'Chips Are Issued To A Club Treasury Or A Union Bank Only, Never To An Individual'
        : 'Diamonds Are Issued To An Individual Player Only, Never To A Club Or Union'
    );
  }

  const targetId = uuid(body.targetId);
  if (!targetId) throw badRequest('Pick A Valid Destination');

  // Parsed from the STRING, so 0.07 and 1.15 survive. The old check compared
  // the rounded cent value against the raw float product, and 0.07 * 100 is
  // 7.000000000000001 in IEEE 754, so legitimate two-decimal amounts were
  // refused as "finer than two decimal places".
  const amount = money2dp(body.amount);
  if (amount === null) throw badRequest('Amount Must Be Positive, To At Most Two Decimals');
  if (asset === 'diamonds' && !Number.isInteger(amount)) throw badRequest('Diamonds Are Whole Numbers');
  if (amount > CAPS[asset]) {
    throw badRequest(`That Is Over The Single-Operation Cap Of ${CAPS[asset].toLocaleString()}`);
  }

  const reason = text(body.reason, { min: 10, max: 500 });
  if (!reason) {
    throw badRequest(
      'Write A Real Reason Of At Least Ten Characters. It Is The Only Explanation Anyone Auditing This Will Have'
    );
  }

  const opId = text(body.opId, { min: 1, max: 200 });
  if (!opId) throw badRequest('Missing Idempotency Key. Reload The Panel And Try Again');

  return { action, asset, target, targetId, amount, reason, opId };
}

/**
 * Reason codes the database returns, in plain English. A code that is NOT on
 * this list becomes a 409 "Mint Refused" carrying the code, because an
 * unrecognised refusal is information - but the raw database sentence behind it
 * never reaches the browser.
 */
const REASON_TEXT = {
  the_mint_is_admin_only: 'The Mint Is Restricted To Platform Admins.',
  asset_must_be_chips_or_diamonds: 'Asset Must Be Chips Or Diamonds.',
  chips_are_issued_to_a_club_or_union_wallet_only:
    'Chips Are Issued To A Club Treasury Or A Union Bank Only.',
  chips_are_retired_from_a_club_or_union_wallet_only:
    'Chips Are Retired From A Club Treasury Or A Union Bank Only.',
  diamonds_are_issued_to_an_individual_player_only:
    'Diamonds Are Issued To An Individual Player Only.',
  diamonds_are_retired_from_an_individual_player_only:
    'Diamonds Are Retired From An Individual Player Only.',
  target_required: 'Pick A Destination.',
  amount_must_be_positive_to_two_decimals: 'Amount Must Be Positive, To At Most Two Decimals.',
  diamonds_are_whole_numbers: 'Diamonds Are Whole Numbers.',
  amount_over_the_single_mint_cap: 'That Is Over The Single-Operation Cap In The Issuance Policy.',
  over_the_rolling_24h_issuance_ceiling:
    'That Would Take The Last 24 Hours Over The Rolling Issuance Ceiling. Raise The Policy With A Reason First.',
  issuance_needs_a_real_reason: 'Issuance Needs A Reason Of At Least Ten Characters.',
  retirement_needs_a_real_reason: 'Retirement Needs A Reason Of At Least Ten Characters.',
  idempotency_key_required: 'Missing Idempotency Key. Reload The Panel And Try Again.',
  player_not_found: 'No Player With That Id.',
  club_not_found: 'No Club With That Id.',
  union_not_found: 'No Union With That Id.',
  union_wallet_not_found: 'That Union Has No Chip Wallet Yet, So There Is Nothing To Retire.',
  that_would_take_the_balance_below_zero: 'That Is More Than The Player Holds.',
  that_would_take_the_treasury_below_zero: 'That Is More Than The Club Treasury Holds.',
  that_would_take_the_union_bank_below_zero: 'That Is More Than The Union Bank Holds.',
};

async function handleIssuance(db, op, req, res, body) {
  const { action, asset, target, targetId, amount, reason, opId } = validateIssuance(body);

  // PHASE 2 MAKER-CHECKER. This runs BEFORE the money RPC and never after it.
  //
  // With approvals off (the default, and the state of production today) it
  // records an auto_approved row and returns required:false, so this route
  // behaves exactly as it did yesterday - PHASE2-CONTRACTS.md section 0.
  //
  // The approval row carries THE SAME opId the RPC claims. That is the whole
  // exactly-once story: the browser generates opId once, it travels on the
  // approval, and when the approved request is finally executed fn_ca_mint
  // claims that same key. A request that is approved, retried, and approved
  // again still mints once.
  const approval = await requireApproval(op, req, {
    kind: action === 'mint' ? 'mint' : 'burn',
    amount,
    asset,
    targetType: target,
    targetId,
    reason,
    opId,
    payload: { action, asset, target, targetId, amount, reason, opId },
  });

  if (approval.required) {
    // 202, and NOT ONE CHIP MOVES. The audit row is filed here rather than
    // after the RPC because from the operator's point of view this request did
    // happen; it is simply waiting.
    await auditOperatorAction(op, req, {
      action: 'mint.request_approval',
      targetType: target,
      targetId,
      before: { status: 'none' },
      after: { status: approval.status, approval_id: approval.approvalId },
      details: { operation: action, asset, amount, reason, opId, threshold: approval.threshold },
    });
    return approvalPendingResponse(res, approval, {
      requestId: op.requestId,
      message:
        action === 'mint'
          ? 'Sent For Approval. Another Operator Must Approve This Issuance Before Any Chips Are Created'
          : 'Sent For Approval. Another Operator Must Approve This Retirement Before Any Chips Are Removed',
    });
  }

  // fn_ca_mint takes a destination; fn_ca_burn takes a source. Same six values,
  // opposite direction, and the parameter names say which way the chips move.
  const { data, error } =
    action === 'mint'
      ? await db.rpc('fn_ca_mint', {
          p_asset: asset,
          p_destination: target,
          p_target_id: targetId,
          p_amount: amount,
          p_reason: reason,
          p_op_id: opId,
        })
      : await db.rpc('fn_ca_burn', {
          p_asset: asset,
          p_source: target,
          p_target_id: targetId,
          p_amount: amount,
          p_reason: reason,
          p_op_id: opId,
        });

  if (error) {
    // The raw sentence is a Postgres string: table names, constraint names,
    // SQL fragments. It is logged under the request id and never returned.
    console.error(`[horses.mint] ${action} rpc failed:`, error.message);
    // The trail reads the same through either door (re-verification L-11):
    // operator-admin.executeApproval records `failed` for the same outcome,
    // and the SQL treats a failed row as a fresh request, so the operator can
    // retry. markApprovalExecuted never throws.
    await markApprovalExecuted(op, approval.approvalId, { ok: false, error: 'mint_unavailable' }, { status: 'failed' });
    throw new ApiError(503, 'The Mint Is Unavailable', 'mint_unavailable');
  }

  if (!data || data.ok !== true) {
    const code = typeof data?.reason === 'string' ? data.reason : 'mint_refused';
    // Record the refusal on the approval row before answering (L-11), so an
    // auto_approved or approved row does not sit with no result while the
    // same request through execute_approval would read `failed`.
    await markApprovalExecuted(op, approval.approvalId, { ok: false, error: code }, { status: 'failed' });
    if (REASON_TEXT[code]) throw new ApiError(400, REASON_TEXT[code], code);
    // THE CODE GOES IN THE MESSAGE. The console shows `err.message` and nothing
    // else, so a bare "Mint Refused" tells the operator that the money did not
    // move and refuses to say why. The reason code is a fixed server-side enum
    // out of fn_ca_mint, not database text: an unrecognised refusal is
    // information, and hiding it behind a generic sentence is how a money bug
    // survives a week.
    throw new ApiError(409, `Mint Refused: ${code}`, code);
  }

  // The money has moved. Close the approval row out. markApprovalExecuted never
  // throws for the same reason auditOperatorAction never does: telling an
  // operator a completed mint failed is how a mint happens twice.
  //
  // ITS ANSWER IS READ (re-verification M-4). `refused: true` means
  // fn_ca_operator_mark_executed would not close the row - the loudest signal
  // this system has, because it means chips moved against a row nobody
  // approved (the H-2 shape). It goes into the audit row as
  // `mark_executed_refused`, `trail_closed` says whether the row is closed,
  // and the response carries `trailClosed` so the operator sees it too.
  const mark = await markApprovalExecuted(op, approval.approvalId, {
    ok: true,
    ledger_id: data.ledger_id ?? null,
    balance_after: data.balance_after ?? null,
    supply_after: data.supply_after ?? null,
    replayed: data.replayed === true,
  });
  const trailClosed = mark.ok === true;
  // The approval's status AFTER execution, not the pre-execution one the
  // request returned: executed when the row closed, failed-to-close otherwise,
  // and unrecorded when there was no row to close.
  const approvalStatusAfter = !approval.approvalId
    ? approval.status
    : trailClosed
      ? 'executed'
      : approval.status;

  await auditOperatorAction(op, req, {
    action: action === 'mint' ? 'mint.issue' : 'mint.retire',
    targetType: target,
    targetId,
    before: {
      balance_before: data.balance_before ?? null,
      supply_before: data.supply_before ?? null,
    },
    after: {
      balance_after: data.balance_after ?? null,
      supply_after: data.supply_after ?? null,
      replayed: data.replayed === true,
    },
    details: {
      asset,
      target,
      amount,
      reason,
      opId,
      ledgerId: data.ledger_id ?? null,
      approvalId: approval.approvalId,
      approvalStatus: approvalStatusAfter,
      approvalStatusBefore: approval.status,
      approvalBlockedReason: approval.blockedReason,
      trail_closed: trailClosed,
      mark_executed_refused: mark.refused === true,
      mark_executed_reason: mark.reason ?? null,
    },
  });

  return {
    result: data,
    performedBy: op.user.id,
    approvalId: approval.approvalId,
    // `approvalStatus` is the status the request was released under, as it
    // always was (add, never rename); `approvalStatusAfter` is the row after
    // this execution, and `trailClosed` is whether it closed.
    approvalStatus: approval.status,
    approvalStatusAfter,
    trailClosed,
  };
}

export const spec = {
  name: 'horses.mint',
  methods: ['GET', 'POST'],
  permission: { GET: PERMISSIONS.MONEY_READ, POST: PERMISSIONS.MONEY_WRITE },
  limit: { GET: 'read', POST: 'financial' },
  // Durable, not in-memory: the money route is the one place where "per lambda
  // instance" is not a limit at all.
  durable: { POST: { max: 20, windowSeconds: 60 } },
};

export async function handle({ req, res, op, db, body, query, method, requestId }) {
  if (method === 'POST') return handleIssuance(db, op, req, res, body);

  const section = enumOf(String(query.section || 'overview'), SECTIONS);
  if (!section) throw badRequest('Unknown Section');

  if (section === 'overview') return sectionOverview(db, requestId);
  if (section === 'ledger') return sectionLedger(db, query);
  if (section === 'targets') return sectionTargets(db, query, requestId);
  return sectionPlayerSearch(db, query, requestId);
}

export default withOperatorRoute(spec, handle);
