const path = require('path');
require('dotenv').config({ path: path.join(process.cwd(), '.env.local') });
const { createClient } = require('@supabase/supabase-js');
const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

const RULE_QUESTIONS = [
    { category: 'rule_knowledge', difficulty: 'easy', question: 'In Texas Hold\'em, how many hole cards does each player receive?', options: ['1', '2', '3', '4'], correct_index: 1, explanation: 'Each player is dealt exactly 2 hole cards face down in Texas Hold\'em.' },
    { category: 'rule_knowledge', difficulty: 'easy', question: 'How many community cards are dealt on the flop?', options: ['1', '2', '3', '5'], correct_index: 2, explanation: 'The flop consists of 3 community cards dealt face up.' },
    { category: 'rule_knowledge', difficulty: 'easy', question: 'What is the best possible hand in poker?', options: ['Four of a Kind', 'Full House', 'Royal Flush', 'Straight Flush'], correct_index: 2, explanation: 'A Royal Flush (A-K-Q-J-10 of the same suit) is the highest possible hand.' },
    { category: 'rule_knowledge', difficulty: 'easy', question: 'In Hold\'em, which position acts first after the flop?', options: ['Button', 'Small Blind', 'Big Blind', 'Under the Gun'], correct_index: 1, explanation: 'The small blind (or first remaining player left of the dealer) acts first post-flop.' },
    { category: 'rule_knowledge', difficulty: 'easy', question: 'What does "all-in" mean in poker?', options: ['Folding your hand', 'Betting all your chips', 'Calling any bet', 'Raising the maximum'], correct_index: 1, explanation: 'Going all-in means wagering all of your remaining chips.' },
    { category: 'rule_knowledge', difficulty: 'medium', question: 'Which hand beats a flush?', options: ['Straight', 'Three of a Kind', 'Full House', 'Two Pair'], correct_index: 2, explanation: 'A Full House (three of a kind + pair) beats a Flush in standard poker hand rankings.' },
    { category: 'rule_knowledge', difficulty: 'medium', question: 'In a standard deck, how many cards are there?', options: ['48', '50', '52', '54'], correct_index: 2, explanation: 'A standard deck contains 52 cards (13 ranks × 4 suits).' },
    { category: 'rule_knowledge', difficulty: 'medium', question: 'What is the minimum number of players needed for a Texas Hold\'em game?', options: ['2', '3', '4', '5'], correct_index: 0, explanation: 'Texas Hold\'em can be played heads-up with just 2 players.' },
    { category: 'rule_knowledge', difficulty: 'medium', question: 'In a tournament, what happens when a player runs out of chips?', options: ['They rebuy automatically', 'They are eliminated', 'They get a loan', 'They sit out until the next hand'], correct_index: 1, explanation: 'In a freeze-out tournament, losing all chips means elimination.' },
    { category: 'rule_knowledge', difficulty: 'medium', question: 'What is a "kicker" in poker?', options: ['A special card that breaks ties', 'The highest unpaired card used to break ties', 'A wild card', 'The dealer\'s card'], correct_index: 1, explanation: 'A kicker is the highest card not part of a made hand, used to break ties between similar hands.' },
    { category: 'rule_knowledge', difficulty: 'medium', question: 'How many betting rounds are there in Texas Hold\'em?', options: ['2', '3', '4', '5'], correct_index: 2, explanation: 'There are 4 betting rounds: pre-flop, flop, turn, and river.' },
    { category: 'rule_knowledge', difficulty: 'medium', question: 'What does the "button" represent in poker?', options: ['The best seat', 'The dealer position', 'The biggest bet', 'The chip leader'], correct_index: 1, explanation: 'The button indicates the dealer position and determines the order of play.' },
    { category: 'rule_knowledge', difficulty: 'medium', question: 'What is a "blind" in poker?', options: ['A forced bet posted before cards are dealt', 'A bluff', 'Playing without looking at cards', 'A side bet'], correct_index: 0, explanation: 'Blinds are forced bets that ensure action in every hand. Small blind and big blind are posted before the deal.' },
    { category: 'rule_knowledge', difficulty: 'hard', question: 'In a tournament with rebuys, when does the rebuy period typically end?', options: ['After the first hand', 'After the first level', 'After a specified number of levels', 'When half the players are eliminated'], correct_index: 2, explanation: 'Rebuy periods typically last for a specified number of levels, usually the first 3-6 levels.' },
    { category: 'rule_knowledge', difficulty: 'hard', question: 'What is the "one-chip rule" in poker tournaments?', options: ['Each player starts with one chip', 'A single chip put in the pot without announcing raise is a call', 'Only one chip can be bet at a time', 'Chips cannot be stacked more than one high'], correct_index: 1, explanation: 'Under the one-chip rule, if a player puts a single chip into the pot without verbalizing "raise", it is considered a call.' },
    { category: 'rule_knowledge', difficulty: 'hard', question: 'In Pot-Limit Omaha, how many hole cards must be used to make a hand?', options: ['Any number', 'Exactly 1', 'Exactly 2', 'At least 2'], correct_index: 2, explanation: 'In Omaha, players MUST use exactly 2 of their 4 hole cards and exactly 3 community cards.' },
    { category: 'rule_knowledge', difficulty: 'hard', question: 'What happens if two players have identical hands at showdown?', options: ['The player who bet first wins', 'The pot is split equally', 'The player with better position wins', 'Another card is dealt'], correct_index: 1, explanation: 'If two or more players have identical hands, the pot is split equally between them.' },
    { category: 'rule_knowledge', difficulty: 'medium', question: 'What is "string betting" in live poker?', options: ['Betting with string chips', 'Adding chips to a bet in multiple motions without announcing', 'Betting on every street', 'Tying chips together'], correct_index: 1, explanation: 'A string bet occurs when a player places chips in the pot in multiple motions without verbally declaring the raise amount first.' },
    { category: 'rule_knowledge', difficulty: 'easy', question: 'Which hand is higher: a straight or three of a kind?', options: ['Three of a Kind', 'Straight', 'They are equal', 'Depends on the cards'], correct_index: 1, explanation: 'A Straight beats Three of a Kind in standard poker hand rankings.' },
    { category: 'rule_knowledge', difficulty: 'easy', question: 'What does "fold" mean in poker?', options: ['Match the current bet', 'Raise the bet', 'Give up your hand and leave the pot', 'Show your cards'], correct_index: 2, explanation: 'Folding means surrendering your hand and forfeiting any chips already in the pot.' },
    { category: 'rule_knowledge', difficulty: 'medium', question: 'What is a "side pot" in poker?', options: ['An extra pot for spectators', 'A pot created when a player goes all-in and others continue betting', 'A pot for the dealer', 'A bonus pot at the end of the night'], correct_index: 1, explanation: 'A side pot is created when one player goes all-in and the remaining players continue betting. The all-in player can only win the main pot.' },
    { category: 'rule_knowledge', difficulty: 'hard', question: 'In NLHE, what is the minimum legal raise amount?', options: ['Any amount above the current bet', 'At least the size of the previous bet or raise', 'Double the big blind', 'At least 3x the big blind'], correct_index: 1, explanation: 'The minimum raise must be at least equal to the previous bet or raise. For example, if the big blind is $10 and someone raises to $30, the minimum re-raise is to $50 ($30 + $20 raise increment).' },
    { category: 'rule_knowledge', difficulty: 'medium', question: 'What is a "misdeal" in poker?', options: ['When the dealer deals the wrong number of cards', 'Any procedural error requiring the hand to be re-dealt', 'When a player sees another\'s cards', 'When the deck runs out of cards'], correct_index: 1, explanation: 'A misdeal is a procedural error in dealing (exposed cards, wrong number dealt, etc.) that requires the hand to be voided and re-dealt.' },
];

const TOURNAMENT_QUESTIONS = [
    { category: 'tournament_facts', difficulty: 'medium', question: 'What is ICM in tournament poker?', options: ['Independent Chip Model', 'International Card Masters', 'Increasing Chip Multiplier', 'Initial Card Movement'], correct_index: 0, explanation: 'ICM (Independent Chip Model) converts tournament chip stacks into monetary equity.' },
    { category: 'tournament_facts', difficulty: 'easy', question: 'What does "on the bubble" mean in a poker tournament?', options: ['Being the chip leader', 'Being one elimination away from the money', 'Starting a new level', 'Having the fewest chips'], correct_index: 1, explanation: 'The "bubble" is when one more elimination will put remaining players in the money.' },
    { category: 'tournament_facts', difficulty: 'medium', question: 'What is a "satellite" tournament?', options: ['A small tournament offering entry to a bigger event', 'A tournament played via satellite link', 'A tournament with no rebuys', 'A heads-up format tournament'], correct_index: 0, explanation: 'Satellites are smaller tournaments where the prize is entry into a bigger, more expensive tournament.' },
    { category: 'tournament_facts', difficulty: 'hard', question: 'What is a "freezeout" tournament format?', options: ['Players get only one buy-in with no rebuys or add-ons', 'A tournament played in cold weather', 'A format where blinds don\'t increase', 'A tournament with unlimited rebuys'], correct_index: 0, explanation: 'In a freezeout, once you lose all your chips you are eliminated — no rebuys or add-ons allowed.' },
    { category: 'tournament_facts', difficulty: 'medium', question: 'What does "final table" mean in a tournament?', options: ['The first table to play', 'The last remaining table of players', 'The table with the most chips', 'A special exhibition table'], correct_index: 1, explanation: 'The final table is the last table of players remaining in a tournament, typically the last 9 players.' },
    { category: 'tournament_facts', difficulty: 'easy', question: 'What is a "bounty" tournament?', options: ['A tournament with a fixed prize', 'A tournament where you earn a prize for each player you eliminate', 'A tournament for new players', 'A tournament with no entry fee'], correct_index: 1, explanation: 'In bounty tournaments, each player has a bounty on their head. When you eliminate them, you win their bounty prize.' },
    { category: 'tournament_facts', difficulty: 'hard', question: 'In MTTs, what is "chip EV" vs "$EV"?', options: ['They are the same thing', 'Chip EV considers tournament equity while $EV does not', 'Chip EV ignores payout structure while $EV accounts for it', '$EV is always higher than chip EV'], correct_index: 2, explanation: 'Chip EV (cEV) evaluates decisions purely by chip accumulation. $EV considers the tournament payout structure and ICM implications.' },
    { category: 'tournament_facts', difficulty: 'medium', question: 'What is a "turbo" tournament?', options: ['A tournament that starts immediately', 'A tournament with faster blind level increases', 'A tournament for fast players only', 'A tournament with no time limits'], correct_index: 1, explanation: 'Turbo tournaments have shorter blind level intervals (typically 5-6 minutes vs 15-20 minutes in regular tournaments).' },
    { category: 'tournament_facts', difficulty: 'easy', question: 'What are "antes" in a tournament?', options: ['Side bets', 'Forced bets all players pay before each hand', 'The first cards dealt', 'Extra prizes'], correct_index: 1, explanation: 'Antes are small forced bets every player must contribute before each hand, typically introduced at later blind levels.' },
    { category: 'tournament_facts', difficulty: 'medium', question: 'What is a "chop" in a tournament?', options: ['Splitting remaining prize pool among final players by agreement', 'Cutting the deck', 'Eliminating a player', 'Removing antes from play'], correct_index: 0, explanation: 'A chop (or deal) is when remaining players agree to divide the remaining prize pool rather than play to completion.' },
    { category: 'tournament_facts', difficulty: 'hard', question: 'What is "pay jump" consideration in tournament strategy?', options: ['Moving up in stakes', 'The difference in prize money between finishing positions affecting decisions', 'Skipping a blind level', 'Getting paid after each round'], correct_index: 1, explanation: 'Pay jumps refer to the significant increases in prize money between finishing positions, which influence ICM-aware decisions at final tables.' },
    { category: 'tournament_facts', difficulty: 'medium', question: 'What does "registration closes" mean in an MTT?', options: ['The tournament is full', 'Late registration period ended — no more entries allowed', 'Cards are being shuffled', 'The starting stacks are set'], correct_index: 1, explanation: 'Registration closing means the late registration window has ended and no more players can enter or re-enter the tournament.' },
];

const POKER_HISTORY_QUESTIONS = [
    { category: 'poker_history', difficulty: 'easy', question: 'Who won the first WSOP Main Event in 1970?', options: ['Johnny Moss', 'Doyle Brunson', 'Stu Ungar', 'Amarillo Slim'], correct_index: 0, explanation: 'Johnny Moss was voted the best poker player by his peers to win the first WSOP Main Event in 1970.' },
    { category: 'poker_history', difficulty: 'medium', question: 'What online poker site did Chris Moneymaker qualify through to win the 2003 WSOP?', options: ['Full Tilt', 'PartyPoker', 'PokerStars', '888poker'], correct_index: 2, explanation: 'Chris Moneymaker qualified through a $39 satellite on PokerStars to win the $2.5 million first prize at the 2003 WSOP.' },
    { category: 'poker_history', difficulty: 'hard', question: 'What was the buy-in for the first WSOP Main Event in 1970?', options: ['$500', '$5,000', '$10,000', 'There was no fixed buy-in'], correct_index: 3, explanation: 'The first WSOP in 1970 had no specific buy-in. It was an invitational event where players voted on the best player.' },
    { category: 'poker_history', difficulty: 'medium', question: 'Which player is known as the "Godfather of Poker"?', options: ['Johnny Moss', 'Doyle Brunson', 'Stu Ungar', 'Jack Binion'], correct_index: 1, explanation: 'Doyle Brunson is widely known as the Godfather of Poker due to his pioneering influence on the game.' },
    { category: 'poker_history', difficulty: 'easy', question: 'What day is known as "Black Friday" in online poker?', options: ['April 15, 2011', 'November 25, 2011', 'January 1, 2010', 'December 31, 2012'], correct_index: 0, explanation: 'April 15, 2011 (Black Friday) saw the DOJ seize domains of major online poker sites including PokerStars, Full Tilt, and Absolute Poker.' },
    { category: 'poker_history', difficulty: 'medium', question: 'Who was the youngest WSOP Main Event winner?', options: ['Phil Hellmuth', 'Peter Eastgate', 'Joe Cada', 'Daniel Negreanu'], correct_index: 2, explanation: 'Joe Cada won the 2009 WSOP Main Event at age 21, making him the youngest winner at that time.' },
];

const PLAYER_PROFILE_QUESTIONS = [
    { category: 'player_profiles', difficulty: 'easy', question: 'Which player has the most WSOP bracelets of all time?', options: ['Phil Ivey', 'Phil Hellmuth', 'Doyle Brunson', 'Daniel Negreanu'], correct_index: 1, explanation: 'Phil Hellmuth holds the all-time record with 17 WSOP bracelets.' },
    { category: 'player_profiles', difficulty: 'medium', question: 'Which player is nicknamed "Kid Poker"?', options: ['Phil Ivey', 'Phil Hellmuth', 'Daniel Negreanu', 'Tom Dwan'], correct_index: 2, explanation: 'Daniel Negreanu earned the nickname "Kid Poker" for his youthful appearance when he first appeared in poker.' },
    { category: 'player_profiles', difficulty: 'medium', question: 'Who is known as "durrrr" in online poker?', options: ['Phil Galfond', 'Tom Dwan', 'Viktor Blom', 'Doug Polk'], correct_index: 1, explanation: 'Tom Dwan is famous for his online alias "durrrr" and his high-stakes play.' },
    { category: 'player_profiles', difficulty: 'hard', question: 'Which player won 3 WSOP Main Events, the only person to do so?', options: ['Phil Hellmuth', 'Johnny Moss', 'Stu Ungar', 'Doyle Brunson'], correct_index: 2, explanation: 'Stu Ungar won the WSOP Main Event in 1980, 1981, and 1997 — the only player to win it three times.' },
    { category: 'player_profiles', difficulty: 'easy', question: 'Who wrote the poker strategy book "Super/System"?', options: ['Mike Caro', 'David Sklansky', 'Doyle Brunson', 'Dan Harrington'], correct_index: 2, explanation: 'Doyle Brunson authored "Super/System" in 1979, considered one of the most influential poker strategy books ever written.' },
    { category: 'player_profiles', difficulty: 'medium', question: 'Which female poker player has the most live tournament earnings?', options: ['Vanessa Selbst', 'Kristen Bicknell', 'Jennifer Harman', 'Liv Boeree'], correct_index: 0, explanation: 'Vanessa Selbst is the all-time female leader in poker tournament earnings with over $11 million in live tournament winnings.' },
];

(async () => {
    const allQuestions = [...RULE_QUESTIONS, ...TOURNAMENT_QUESTIONS, ...POKER_HISTORY_QUESTIONS, ...PLAYER_PROFILE_QUESTIONS];

    console.log(`Seeding ${allQuestions.length} questions across 4 categories...`);

    const { data, error } = await sb.from('trivia_questions').insert(allQuestions).select('id, category');

    if (error) {
        console.log('ERROR:', error.message);
        process.exit(1);
    }

    // Count by category
    const cats = {};
    data.forEach(q => { cats[q.category] = (cats[q.category] || 0) + 1; });
    Object.entries(cats).forEach(([cat, count]) => {
        console.log(`  ✅ ${cat}: ${count} questions inserted`);
    });
    console.log(`  TOTAL: ${data.length} questions seeded successfully`);

    process.exit(0);
})();
