#!/usr/bin/env python3
"""Database contract tests for the PokerAtlas atomic venue-ingest migration."""

import json
import shutil
import socket
import subprocess
import tempfile
import unittest
import uuid
from datetime import datetime, timezone
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
MIGRATION_MATCHES = sorted(
    (PROJECT_ROOT / 'supabase' / 'migrations').glob('*_pokeratlas_atomic_venue_ingest.sql')
)
if len(MIGRATION_MATCHES) != 1:
    raise RuntimeError(
        f'expected exactly one PokerAtlas atomic-ingest migration, found {MIGRATION_MATCHES}'
    )
MIGRATION = MIGRATION_MATCHES[0]


def _postgres_program(name):
    """Prefer a complete PostgreSQL server bundle over client-only libpq links."""
    found = shutil.which(name)
    if found and (name not in {'initdb', 'pg_ctl'} or (Path(found).resolve().parent / 'postgres').exists()):
        return found
    candidates = []
    for base in (Path('/opt/homebrew/opt'), Path('/usr/local/opt')):
        candidates.extend(sorted(base.glob(f'postgresql*/bin/{name}'), reverse=True))
    return str(candidates[0]) if candidates else None


class PokerAtlasAtomicIngestDatabaseTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.initdb = _postgres_program('initdb')
        cls.pg_ctl = _postgres_program('pg_ctl')
        cls.psql = _postgres_program('psql')
        if not all((cls.initdb, cls.pg_ctl, cls.psql)):
            raise unittest.SkipTest('PostgreSQL initdb, pg_ctl, and psql are required')

        cls.tempdir = tempfile.TemporaryDirectory(prefix='pa-atomic-pg-')
        cls.data_dir = Path(cls.tempdir.name) / 'data'
        with socket.socket() as listener:
            listener.bind(('127.0.0.1', 0))
            cls.port = listener.getsockname()[1]

        initialized = subprocess.run(
            [cls.initdb, '-D', str(cls.data_dir), '-A', 'trust', '-U', 'postgres', '--no-locale'],
            text=True,
            capture_output=True,
        )
        if initialized.returncode:
            cls.tempdir.cleanup()
            raise RuntimeError(initialized.stderr or initialized.stdout)

        started = subprocess.run(
            [
                cls.pg_ctl,
                '-D', str(cls.data_dir),
                '-l', str(Path(cls.tempdir.name) / 'postgres.log'),
                '-o', f'-F -p {cls.port} -h 127.0.0.1',
                '-w', 'start',
            ],
            text=True,
            capture_output=True,
        )
        if started.returncode:
            cls.tempdir.cleanup()
            raise RuntimeError(started.stderr or started.stdout)

        cls._sql('postgres', "CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;")

    @classmethod
    def tearDownClass(cls):
        if getattr(cls, 'pg_ctl', None) and getattr(cls, 'data_dir', None):
            subprocess.run(
                [cls.pg_ctl, '-D', str(cls.data_dir), '-m', 'fast', '-w', 'stop'],
                text=True,
                capture_output=True,
            )
        if getattr(cls, 'tempdir', None):
            cls.tempdir.cleanup()

    @classmethod
    def _psql_command(cls, database, *extra):
        return [
            cls.psql,
            '-X',
            '-h', '127.0.0.1',
            '-p', str(cls.port),
            '-U', 'postgres',
            '-d', database,
            '-v', 'ON_ERROR_STOP=1',
            *extra,
        ]

    @classmethod
    def _sql(cls, database, sql, *, check=True):
        completed = subprocess.run(
            cls._psql_command(database, '-At', '-c', sql),
            text=True,
            capture_output=True,
        )
        if check and completed.returncode:
            raise AssertionError(completed.stderr or completed.stdout)
        return completed

    def setUp(self):
        self.database = f'pa_atomic_{uuid.uuid4().hex[:12]}'
        self._sql('postgres', f'CREATE DATABASE {self.database}')
        self._install_fixture()

    def _install_fixture(self):
        fixture = r'''
          CREATE TABLE public.poker_venues (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL,
            address text,
            city text NOT NULL,
            state text NOT NULL,
            country text,
            zip text,
            phone text,
            website text,
            latitude double precision,
            longitude double precision,
            slug text,
            pokeratlas_slug text,
            pokeratlas_url text,
            data_quality text,
            scrape_url text,
            scrape_html_hash text,
            scrape_timestamp timestamptz,
            scrape_source text,
            scrape_batch_id uuid,
            scrape_status text,
            canonical_venue_id integer REFERENCES public.poker_venues(id),
            is_active boolean NOT NULL DEFAULT true,
            is_suppressed boolean NOT NULL DEFAULT false,
            retired_at timestamptz,
            retired_by uuid,
            retired_reason text,
            location_integrity_revision timestamptz NOT NULL DEFAULT now()
          );

          CREATE TABLE public.data_audit_log (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            table_name text NOT NULL,
            record_id text NOT NULL,
            action text NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE', 'ROLLBACK', 'FLAG')),
            old_data jsonb,
            new_data jsonb,
            scrape_proof jsonb,
            batch_id uuid,
            agent_id text,
            created_at timestamptz DEFAULT now()
          );

          CREATE TABLE public.venue_duplicate_retirement_log (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            retired_venue_id integer NOT NULL REFERENCES public.poker_venues(id) ON DELETE RESTRICT,
            canonical_venue_id integer NOT NULL REFERENCES public.poker_venues(id) ON DELETE RESTRICT,
            actor_id uuid,
            reason text NOT NULL CHECK (char_length(reason) BETWEEN 12 AND 500),
            before_record jsonb NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now(),
            CHECK (retired_venue_id <> canonical_venue_id)
          );

          CREATE TABLE public.venue_location_integrity_state (
            venue_id integer PRIMARY KEY REFERENCES public.poker_venues(id) ON DELETE CASCADE,
            marker text NOT NULL
          );

          INSERT INTO public.poker_venues (
            id, name, city, state, country, is_active, is_suppressed,
            data_quality, scrape_status, canonical_venue_id, retired_at,
            retired_by, retired_reason, pokeratlas_slug
          ) VALUES
            (1878, 'Harrah''s Cherokee', 'Cherokee', 'NC', 'US', true, false,
             'scraped_verified', 'complete', NULL, NULL, NULL, NULL,
             'harrahs-cherokee-cherokee'),
            (2912, 'Club Montmartre', 'Paris', 'Paris', 'US', true, false,
             'scraped_verified', 'no_data', NULL, NULL, NULL, NULL,
             'club-montmartre-paris'),
            (3428, 'Harrahs Cherokee', 'Cherokee', 'NC', 'US', true, true,
             'unverified', 'no_data', NULL, NULL, NULL, NULL,
             'harrahs-cherokee-cherokee');

          INSERT INTO public.venue_location_integrity_state (venue_id, marker)
          VALUES (3428, 'preserve-me');
        '''
        self._sql(self.database, fixture)

    def _apply_migration(self, *, check=True):
        completed = subprocess.run(
            self._psql_command(self.database, '-f', str(MIGRATION)),
            text=True,
            capture_output=True,
        )
        if check and completed.returncode:
            raise AssertionError(completed.stderr or completed.stdout)
        return completed

    @staticmethod
    def _payload(slug, batch_id, **overrides):
        row = {
            'name': 'Atomic Test Room',
            'address': '100 Main Street',
            'city': 'Austin',
            'state': 'TX',
            'country': 'US',
            'slug': slug,
            'pokeratlas_slug': slug,
            'pokeratlas_url': f'https://www.pokeratlas.com/poker-room/{slug}',
            'data_quality': 'scraped_verified',
            'scrape_url': f'https://www.pokeratlas.com/poker-room/{slug}',
            'scrape_html_hash': 'a' * 64,
            'scrape_timestamp': datetime.now(timezone.utc).isoformat(),
            'scrape_source': 'pokeratlas',
            'scrape_batch_id': batch_id,
            'scrape_status': 'ready',
        }
        row.update(overrides)
        return row

    def _rpc_sql(self, rows, batch_id):
        payload = json.dumps(rows, separators=(',', ':')).replace("'", "''")
        return (
            "SELECT public.fn_pokeratlas_ingest_venues("
            f"'{payload}'::jsonb, '{batch_id}'::uuid)::text"
        )

    def _rpc(self, rows, batch_id, *, check=True):
        completed = self._sql(
            self.database,
            self._rpc_sql(rows, batch_id),
            check=check,
        )
        if completed.returncode:
            return completed
        return json.loads(completed.stdout.strip().splitlines()[-1])

    def test_migration_retires_exact_alias_and_preserves_redirect_and_audit(self):
        self._apply_migration()

        row = self._sql(
            self.database,
            """
              SELECT canonical_venue_id, is_active, is_suppressed,
                     retired_at IS NOT NULL, retired_by IS NULL,
                     pokeratlas_slug
                FROM public.poker_venues
               WHERE id = 3428
            """,
        ).stdout.strip()
        self.assertEqual(
            row,
            '1878|f|t|t|t|harrahs-cherokee-cherokee',
        )
        audit = self._sql(
            self.database,
            """
              SELECT retired_venue_id, canonical_venue_id, actor_id IS NULL,
                     before_record ->> 'name'
                FROM public.venue_duplicate_retirement_log
            """,
        ).stdout.strip()
        self.assertEqual(audit, '3428|1878|t|Harrahs Cherokee')
        non_us = self._sql(
            self.database,
            """
              SELECT canonical_venue_id IS NULL, is_active, is_suppressed,
                     retired_at IS NOT NULL, retired_by IS NULL,
                     pokeratlas_slug
                FROM public.poker_venues
               WHERE id = 2912
            """,
        ).stdout.strip()
        self.assertEqual(non_us, 't|f|t|t|t|club-montmartre-paris')
        non_us_audit = self._sql(
            self.database,
            """
              SELECT action, old_data ->> 'country', new_data ->> 'is_active',
                     scrape_proof ->> 'finding', scrape_proof ->> 'canonical_venue_id'
                FROM public.data_audit_log
               WHERE table_name = 'poker_venues'
                 AND record_id = '2912'
            """,
        ).stdout.strip()
        self.assertEqual(non_us_audit, 'UPDATE|US|false|non_us_location|')
        integrity = self._sql(
            self.database,
            "SELECT marker FROM public.venue_location_integrity_state WHERE venue_id = 3428",
        ).stdout.strip()
        self.assertEqual(integrity, 'preserve-me')

        predicate = self._sql(
            self.database,
            """
              SELECT pg_get_expr(i.indpred, i.indrelid)
                FROM pg_index i
               WHERE i.indexrelid =
                 'public.uq_poker_venues_pokeratlas_slug_normalized_canonical'::regclass
            """,
        ).stdout.strip()
        self.assertIn('canonical_venue_id IS NULL', predicate)

        batch_id = str(uuid.uuid4())
        resolved = self._rpc(
            [self._payload('harrahs-cherokee-cherokee', batch_id)],
            batch_id,
        )
        self.assertEqual(resolved['inserted_count'], 0)
        self.assertEqual(resolved['venues'], [{
            'id': 1878,
            'pokeratlas_slug': 'harrahs-cherokee-cherokee',
            'canonical_venue_id': None,
        }])

    def test_migration_aborts_and_rolls_back_when_known_snapshot_drifts(self):
        self._sql(
            self.database,
            "UPDATE public.poker_venues SET data_quality = 'reviewed' WHERE id = 3428",
        )
        failed = self._apply_migration(check=False)
        self.assertNotEqual(failed.returncode, 0)
        self.assertIn('suppressed venue 3428 no longer matches', failed.stderr)

        unchanged = self._sql(
            self.database,
            "SELECT canonical_venue_id IS NULL, retired_at IS NULL FROM public.poker_venues WHERE id = 3428",
        ).stdout.strip()
        self.assertEqual(unchanged, 't|t')
        self.assertEqual(
            self._sql(self.database, 'SELECT count(*) FROM public.venue_duplicate_retirement_log').stdout.strip(),
            '0',
        )
        self.assertEqual(
            self._sql(
                self.database,
                "SELECT to_regclass('public.uq_poker_venues_pokeratlas_slug_normalized_canonical') IS NULL",
            ).stdout.strip(),
            't',
        )

    def test_migration_aborts_if_non_us_tombstone_snapshot_drifts(self):
        self._sql(
            self.database,
            "UPDATE public.poker_venues SET country = 'FR' WHERE id = 2912",
        )
        failed = self._apply_migration(check=False)
        self.assertNotEqual(failed.returncode, 0)
        self.assertIn('non-US venue 2912 no longer matches', failed.stderr)
        self.assertEqual(
            self._sql(
                self.database,
                "SELECT is_active, is_suppressed, retired_at IS NULL FROM public.poker_venues WHERE id = 2912",
            ).stdout.strip(),
            't|f|t',
        )
        self.assertEqual(
            self._sql(self.database, 'SELECT count(*) FROM public.data_audit_log').stdout.strip(),
            '0',
        )

    def test_migration_refuses_to_overwrite_a_preexisting_rpc(self):
        self._sql(
            self.database,
            """
              CREATE FUNCTION public.fn_pokeratlas_ingest_venues(jsonb, uuid)
              RETURNS jsonb LANGUAGE sql AS $$ SELECT '{}'::jsonb $$
            """,
        )
        failed = self._apply_migration(check=False)
        self.assertNotEqual(failed.returncode, 0)
        self.assertIn('migration-owned PokerAtlas ingest RPC already exists', failed.stderr)
        self.assertEqual(
            self._sql(
                self.database,
                "SELECT public.fn_pokeratlas_ingest_venues('[]'::jsonb, gen_random_uuid())::text",
            ).stdout.strip(),
            '{}',
        )

    def test_suppressed_canonical_identity_fails_the_batch(self):
        self._apply_migration()
        self._sql(
            self.database,
            """
              INSERT INTO public.poker_venues (
                name, city, state, country, pokeratlas_slug, is_active, is_suppressed
              ) VALUES (
                'Suppressed Room', 'Austin', 'TX', 'US', 'suppressed-room', false, true
              )
            """,
        )
        batch_id = str(uuid.uuid4())
        failed = self._rpc(
            [self._payload('suppressed-room', batch_id)],
            batch_id,
            check=False,
        )
        self.assertNotEqual(failed.returncode, 0)
        self.assertIn('only 0/1 PokerAtlas identities resolved', failed.stderr)
        self.assertEqual(
            self._sql(
                self.database,
                f"SELECT count(*) FROM public.data_audit_log WHERE id = '{batch_id}'::uuid",
            ).stdout.strip(),
            '0',
        )

    def test_invalid_member_rolls_back_the_entire_rpc_batch(self):
        self._apply_migration()
        batch_id = str(uuid.uuid4())
        rows = [
            self._payload('valid-room', batch_id),
            self._payload('foreign-room', batch_id, state='ON', country='CA'),
        ]
        before_count = self._sql(
            self.database,
            'SELECT count(*) FROM public.poker_venues',
        ).stdout.strip()
        failed = self._rpc(rows, batch_id, check=False)
        self.assertNotEqual(failed.returncode, 0)
        self.assertIn('verified US country is required', failed.stderr)
        self.assertEqual(
            self._sql(self.database, 'SELECT count(*) FROM public.poker_venues').stdout.strip(),
            before_count,
        )
        self.assertEqual(
            self._sql(
                self.database,
                f"SELECT count(*) FROM public.data_audit_log WHERE id = '{batch_id}'::uuid",
            ).stdout.strip(),
            '0',
        )

    def test_rpc_rejects_noncanonical_full_state_names(self):
        self._apply_migration()
        batch_id = str(uuid.uuid4())
        failed = self._rpc(
            [self._payload('full-state-room', batch_id, state='North Carolina')],
            batch_id,
            check=False,
        )
        self.assertNotEqual(failed.returncode, 0)
        self.assertIn('canonical two-letter US state is required', failed.stderr)
        self.assertEqual(
            self._sql(
                self.database,
                "SELECT count(*) FROM public.poker_venues WHERE pokeratlas_slug = 'full-state-room'",
            ).stdout.strip(),
            '0',
        )

    def test_replay_is_idempotent_and_rejects_changed_batch_contract(self):
        self._apply_migration()
        batch_id = str(uuid.uuid4())
        rows = [self._payload('replay-room', batch_id)]
        first = self._rpc(rows, batch_id)
        second = self._rpc(rows, batch_id)
        self.assertEqual(first['inserted_count'], 1)
        self.assertEqual(second['inserted_count'], 0)
        self.assertEqual(second['existing_count'], 1)
        self.assertEqual(
            self._sql(
                self.database,
                f"SELECT count(*) FROM public.data_audit_log WHERE id = '{batch_id}'::uuid",
            ).stdout.strip(),
            '1',
        )

        changed = [dict(rows[0], address='999 Changed Street')]
        failed = self._rpc(changed, batch_id, check=False)
        self.assertNotEqual(failed.returncode, 0)
        self.assertIn('batch id was already used for a different audit contract', failed.stderr)
        stored_address = self._sql(
            self.database,
            "SELECT address FROM public.poker_venues WHERE pokeratlas_slug = 'replay-room' AND canonical_venue_id IS NULL",
        ).stdout.strip()
        self.assertEqual(stored_address, '100 Main Street')

    def test_concurrent_batches_create_one_canonical_identity(self):
        self._apply_migration()
        self._sql(
            self.database,
            r'''
              CREATE FUNCTION public.test_delay_pokeratlas_insert()
              RETURNS trigger LANGUAGE plpgsql AS $$
              BEGIN
                IF NEW.pokeratlas_slug = 'concurrent-room' THEN
                  PERFORM pg_sleep(0.5);
                END IF;
                RETURN NEW;
              END
              $$;
              CREATE TRIGGER test_delay_pokeratlas_insert
                BEFORE INSERT ON public.poker_venues
                FOR EACH ROW EXECUTE FUNCTION public.test_delay_pokeratlas_insert();
            ''',
        )
        first_batch = str(uuid.uuid4())
        second_batch = str(uuid.uuid4())
        commands = [
            self._psql_command(
                self.database,
                '-At',
                '-c',
                self._rpc_sql([self._payload('concurrent-room', first_batch)], first_batch),
            ),
            self._psql_command(
                self.database,
                '-At',
                '-c',
                self._rpc_sql([self._payload('concurrent-room', second_batch)], second_batch),
            ),
        ]
        processes = [
            subprocess.Popen(command, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            for command in commands
        ]
        completed = [process.communicate(timeout=15) for process in processes]
        for process, (stdout, stderr) in zip(processes, completed):
            self.assertEqual(process.returncode, 0, stderr or stdout)
        results = [json.loads(stdout.strip().splitlines()[-1]) for stdout, _ in completed]
        self.assertEqual(sorted(result['inserted_count'] for result in results), [0, 1])
        self.assertEqual(sorted(result['existing_count'] for result in results), [0, 1])
        self.assertEqual(
            self._sql(
                self.database,
                """
                  SELECT count(*)
                    FROM public.poker_venues
                   WHERE lower(btrim(pokeratlas_slug)) = 'concurrent-room'
                     AND canonical_venue_id IS NULL
                """,
            ).stdout.strip(),
            '1',
        )
        self.assertEqual(
            self._sql(
                self.database,
                f"SELECT count(*) FROM public.data_audit_log WHERE id IN ('{first_batch}'::uuid, '{second_batch}'::uuid)",
            ).stdout.strip(),
            '2',
        )


if __name__ == '__main__':
    unittest.main()
