import React, { useCallback, useEffect, useRef, useState } from 'react';
import { eventBus, EventType } from '../../engine/EventBus';
import { T, num, when } from '../../lib/horsesAdminTokens';
import { hasPermission } from './operatorPermissions';
import DataTable from './DataTable';
import pageStyles from '../../../pages/horses/horses.module.css';
import panelStyles from './legacyPanels.module.css';

const styles = { ...pageStyles, ...panelStyles };

export default function GeevesPanel({ authFetch, showNotification, permissions }) {
  const [analytics, setAnalytics] = useState({ summary: null, questions: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [marking, setMarking] = useState(null);
  const loadSequence = useRef(0); const markSequence = useRef(0);
  const canWrite = hasPermission(permissions, 'moderation.write');
  const load = useCallback(async () => { const seq = ++loadSequence.current; setLoading(true); setError(''); try { const [summary, missed] = await Promise.all([authFetch('/api/geeves/analytics?action=summary'), authFetch('/api/geeves/analytics?action=top_missed').catch(() => ({ questions: [] }))]); if (seq === loadSequence.current) setAnalytics({ summary: summary.summary || null, questions: missed.questions || [] }); } catch (cause) { if (seq === loadSequence.current) setError(cause?.message || 'Geeves Analytics Could Not Be Read'); } finally { if (seq === loadSequence.current) setLoading(false); } }, [authFetch]);
  useEffect(() => { load(); return () => { loadSequence.current += 1; markSequence.current += 1; }; }, [load]);
  useEffect(() => {
    const missed = eventBus.on(EventType.GEEVES_QUESTION_MISSED, (event) => { const { question, page } = event.payload || {}; if (!question) return; setAnalytics((current) => { const found = current.questions.find((row) => row.question === question); return { ...current, questions: found ? current.questions.map((row) => row.question === question ? { ...row, asked_count: (row.asked_count || 1) + 1, last_asked: new Date().toISOString() } : row) : [{ id: `live-${Date.now()}`, question, page: page || null, asked_count: 1, last_asked: new Date().toISOString(), grok_answer: null }, ...current.questions] }; }); });
    const kb = eventBus.on(EventType.GEEVES_KB_UPDATED, (event) => { const id = event.payload?.questionId; if (id) setAnalytics((current) => ({ ...current, questions: current.questions.filter((row) => row.id !== id) })); });
    return () => { missed(); kb(); };
  }, []);
  const mark = async (id, addedToKB) => { if (!canWrite) return; if (String(id).startsWith('live-')) { showNotification?.('This Question Is Still Arriving. Refresh, Then Mark It.', 'info'); return; } const seq = ++markSequence.current; setMarking(id); try { await authFetch('/api/geeves/analytics', { method: 'POST', body: JSON.stringify({ action: 'resolve', questionId: id, addedToKB }) }); if (seq !== markSequence.current) return; setAnalytics((current) => ({ ...current, questions: current.questions.filter((row) => row.id !== id) })); showNotification?.(addedToKB ? 'Marked As Added To KB' : 'Marked As Resolved'); } catch (cause) { if (seq === markSequence.current) showNotification?.(cause.message, 'error'); } finally { if (seq === markSequence.current) setMarking(null); } };
  return <div className={styles.statsView}><div className={styles.panelHeading}><div><h2>Geeves Knowledge Base</h2><p>Questions That Fell Through To Grok. Add Them To The KB To Make Geeves Smarter.</p></div><button className={styles.actionBtn} onClick={load} disabled={loading}>{loading ? 'Loading' : 'Refresh'}</button></div>{!canWrite ? <div className={styles.warnBanner}>Moderation Write Permission Is Required To Resolve Questions.</div> : null}{error ? <div className={styles.errorState} role="alert">Geeves Analytics Unavailable: {error}<button className={styles.actionBtn} onClick={load}>Retry</button></div> : <>{analytics.summary ? <div className={styles.kpiGrid}>{[['Missed This Week', analytics.summary.missedThisWeek, T.danger], ['Resolved This Week', analytics.summary.resolvedThisWeek, T.accent], ['Total Added To KB', analytics.summary.totalAddedToKB, T.accent], ['Cache Answers Served', analytics.summary.cacheAnswersServedThisWeek, T.warn], ['Avg Cache Rating', analytics.summary.avgCacheRating ? `${analytics.summary.avgCacheRating} / 5` : null, T.info]].map(([label, value, color]) => <div className={styles.kpi} key={label}><div className={styles.kpiValue} style={{ color }}>{typeof value === 'string' ? value : num(value)}</div><div className={styles.kpiLabel}>{label}</div></div>)}</div> : null}<DataTable caption="Questions Requiring Knowledge-Base Review" loading={loading} loadingLabel="Loading Geeves Analytics" empty="No Unanswered Questions. Geeves Is Handling Everything Locally." rows={analytics.questions} columns={[
    { key: 'question', header: 'Question', render: (row) => <div>{row.question}{row.grok_answer ? <details><summary>View Grok Answer</summary><div>{row.grok_answer}</div></details> : null}</div> }, { key: 'page', header: 'Page', render: (row) => row.page ? row.page.replace('/hub/', '') : '-' }, { key: 'asked', header: 'Asked', render: (row) => num(row.asked_count) }, { key: 'last', header: 'Last Asked', render: (row) => when(row.last_asked) }, { key: 'actions', header: 'Actions', render: (row) => <div><button className={styles.filterBtn} onClick={() => mark(row.id, true)} disabled={!canWrite || marking === row.id}>{marking === row.id ? 'Saving' : 'Added To KB'}</button><button className={styles.filterBtn} onClick={() => mark(row.id, false)} disabled={!canWrite || marking === row.id}>Dismiss</button></div> },
  ]} /></>}</div>;
}
