import React, { useCallback, useEffect, useRef, useState } from 'react';
import { T, num, when } from '../../lib/horsesAdminTokens';
import { hasPermission } from './operatorPermissions';
import Modal from './Modal';
import pageStyles from '../../../pages/horses/horses.module.css';
import panelStyles from './legacyPanels.module.css';

const styles = { ...pageStyles, ...panelStyles };

const EMPTY = { code: '', description: '', type: 'signup_bonus', value: 100, maxUses: '', expiresAt: '' };
function localInput(value) { if (!value) return ''; const date = new Date(value); if (Number.isNaN(date.getTime())) return ''; const pad = (n) => String(n).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
function iso(value) { if (!value) return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date.toISOString(); }

export default function PromoPanel({ authFetch, showNotification, permissions }) {
  const [codes, setCodes] = useState([]); const [types, setTypes] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [creating, setCreating] = useState(false); const [form, setForm] = useState(EMPTY); const [editing, setEditing] = useState(null); const [edit, setEdit] = useState(null); const [saving, setSaving] = useState(false);
  const alive = useRef(true); const loadSequence = useRef(0);
  const canWrite = hasPermission(permissions, 'promo.write');
  const load = useCallback(async () => { const seq = ++loadSequence.current; setLoading(true); setError(''); try { const body = await authFetch('/api/promo/admin-promo-codes'); if (seq !== loadSequence.current || !alive.current) return; setCodes(body.codes || body.rows || []); if (Array.isArray(body.rewardTypes)) setTypes(body.rewardTypes); } catch (cause) { if (seq === loadSequence.current && alive.current) setError(cause?.message || 'Promo Codes Could Not Be Read'); } finally { if (seq === loadSequence.current && alive.current) setLoading(false); } }, [authFetch]);
  useEffect(() => { alive.current = true; load(); return () => { alive.current = false; loadSequence.current += 1; }; }, [load]);
  const create = async (event) => { event.preventDefault(); if (!canWrite) return; setCreating(true); try { const body = await authFetch('/api/promo/admin-promo-codes', { method: 'POST', body: JSON.stringify({ ...form, maxUses: form.maxUses ? Number(form.maxUses) : null, expiresAt: iso(form.expiresAt) }) }); showNotification?.(`Promo Code ${body.code?.code || ''} Created`.trim()); setForm(EMPTY); load(); window.dispatchEvent(new CustomEvent('promo-codes-updated')); } catch (cause) { showNotification?.(cause.message, 'error'); } finally { setCreating(false); } };
  const beginEdit = (row) => { setEditing(row); setEdit({ code: row.code || '', description: row.description || '', reward_type: row.reward_type || row.type || 'signup_bonus', reward_value: row.reward_value ?? row.value ?? 0, max_uses: row.max_uses ?? '', expires_at: localInput(row.expires_at) }); };
  const save = async (event) => { event.preventDefault(); if (!canWrite || !editing) return; setSaving(true); try { const body = { id: editing.id, code: edit.code, description: edit.description, reward_type: edit.reward_type, reward_value: Number(edit.reward_value), max_uses: edit.max_uses === '' ? null : Number(edit.max_uses), expires_at: iso(edit.expires_at) }; await authFetch('/api/promo/admin-promo-codes', { method: 'PATCH', body: JSON.stringify(body) }); showNotification?.(`Promo Code ${body.code} Saved`); setEditing(null); setEdit(null); load(); } catch (cause) { showNotification?.(cause.message, 'error'); } finally { setSaving(false); } };
  const toggle = async (row) => { if (!canWrite) return; try { await authFetch('/api/promo/admin-promo-codes', { method: 'PATCH', body: JSON.stringify({ id: row.id, is_active: !row.is_active }) }); showNotification?.(`Code ${row.is_active ? 'Deactivated' : 'Activated'}`); load(); } catch (cause) { showNotification?.(cause.message, 'error'); } };
  const copy = async (row) => { try { await navigator.clipboard.writeText(row.code); showNotification?.(`Copied ${row.code}`); } catch { showNotification?.('Clipboard Unavailable In This Browser', 'error'); } };
  return <div className={styles.statsView}><h2>Promo Code Manager</h2>{!canWrite ? <div className={styles.warnBanner}>Promo Write Permission Is Required To Create Or Change Codes.</div> : null}<div className={styles.statsOverview}><div className={styles.statCardLarge}><span className={styles.statNumber}>{num(codes.length)}</span><span className={styles.statLabel}>Total Codes</span></div><div className={styles.statCardLarge}><span className={styles.statNumber}>{num(codes.filter((row) => row.is_active).length)}</span><span className={styles.statLabel}>Active</span></div><div className={styles.statCardLarge}><span className={styles.statNumber}>{num(codes.reduce((sum, row) => sum + (Number(row.redemption_count ?? row.current_uses ?? row.times_used) || 0), 0))}</span><span className={styles.statLabel}>Total Redemptions</span></div></div><section className={styles.contentBreakdown}><h3>Create New Promo Code</h3><form onSubmit={create}><div className={styles.formRow}><div className={styles.formGroup}><label htmlFor="promo-code">Code (Blank Auto-Generates)</label><input id="promo-code" maxLength={20} value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, '') })} /></div><div className={styles.formGroup}><label htmlFor="promo-desc">Description</label><input id="promo-desc" required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></div></div><div className={styles.formRow}><div className={styles.formGroup}><label htmlFor="promo-type">Type</label><select id="promo-type" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}>{(types.length ? types : ['signup_bonus','diamonds','vip_days']).map((type) => <option value={type} key={type}>{type.replace(/_/g, ' ')}</option>)}</select></div><div className={styles.formGroup}><label htmlFor="promo-value">Value</label><input id="promo-value" type="number" min="1" max="10000" required value={form.value} onChange={(event) => setForm({ ...form, value: Number(event.target.value) || 0 })} /></div></div><div className={styles.formRow}><div className={styles.formGroup}><label htmlFor="promo-max">Max Uses (Blank Is Unlimited)</label><input id="promo-max" type="number" min="1" value={form.maxUses} onChange={(event) => setForm({ ...form, maxUses: event.target.value })} /></div><div className={styles.formGroup}><label htmlFor="promo-exp">Expires At (Optional)</label><input id="promo-exp" type="datetime-local" value={form.expiresAt} onChange={(event) => setForm({ ...form, expiresAt: event.target.value })} /></div></div><button className={styles.btnSubmit} disabled={!canWrite || creating}>{creating ? 'Creating' : 'Create Promo Code'}</button></form></section>
    <section className={styles.contentBreakdown}><div className={styles.panelHeading}><h3>All Promo Codes <span className={styles.countPill}>{num(codes.length)}</span></h3><button className={styles.actionBtn} onClick={load} disabled={loading}>Refresh</button></div>{error ? <div className={styles.errorState} role="alert">Promo Codes Unavailable: {error}</div> : loading ? <div className={styles.loadingSpinner}>Loading Codes</div> : !codes.length ? <div className={styles.emptyState}>No Promo Codes Yet. Create One Above.</div> : <div className={styles.tableWrapper}><table className={styles.table}><thead><tr><th scope="col">Code</th><th scope="col">Type</th><th scope="col">Value</th><th scope="col">Uses</th><th scope="col">Expires</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody>{codes.map((row) => <tr key={row.id}><td><strong>{row.code}</strong><div>{row.description}</div></td><td>{row.reward_type || row.type || 'Unknown'}</td><td>{num(row.reward_value ?? row.value)}</td><td>{num(row.redemption_count ?? row.current_uses ?? row.times_used)}{row.max_uses ? ` / ${num(row.max_uses)}` : ' / Unlimited'}</td><td>{row.expires_at ? when(row.expires_at) : 'Never'}</td><td style={{ color: row.is_active ? T.accent : T.muted }}>{row.is_active ? 'Active' : 'Inactive'}</td><td><button className={styles.filterBtn} onClick={() => copy(row)}>Copy</button><button className={styles.filterBtn} disabled={!canWrite} onClick={() => beginEdit(row)}>Edit</button><button className={styles.filterBtn} disabled={!canWrite} onClick={() => toggle(row)}>{row.is_active ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div>}</section>
    {editing && edit ? <Modal title={`Edit ${editing.code}`} onClose={() => { setEditing(null); setEdit(null); }} sticky={saving} blockEscape={saving} wide><form onSubmit={save}><div className={styles.formRow}><div className={styles.formGroup}><label htmlFor="pe-code">Code</label><input id="pe-code" required maxLength={20} value={edit.code} onChange={(event) => setEdit({ ...edit, code: event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, '') })} /></div><div className={styles.formGroup}><label htmlFor="pe-type">Type</label><select id="pe-type" value={edit.reward_type} onChange={(event) => setEdit({ ...edit, reward_type: event.target.value })}>{(types.length ? types : [edit.reward_type]).map((type) => <option key={type} value={type}>{type.replace(/_/g, ' ')}</option>)}</select></div></div><div className={styles.formGroup}><label htmlFor="pe-desc">Description</label><input id="pe-desc" value={edit.description} onChange={(event) => setEdit({ ...edit, description: event.target.value })} /></div><div className={styles.formRow}><div className={styles.formGroup}><label htmlFor="pe-value">Value</label><input id="pe-value" type="number" min="0" max="10000" required value={edit.reward_value} onChange={(event) => setEdit({ ...edit, reward_value: event.target.value })} /></div><div className={styles.formGroup}><label htmlFor="pe-max">Max Uses</label><input id="pe-max" type="number" min="1" value={edit.max_uses} onChange={(event) => setEdit({ ...edit, max_uses: event.target.value })} /></div></div><div className={styles.formGroup}><label htmlFor="pe-exp">Expires At</label><input id="pe-exp" type="datetime-local" value={edit.expires_at} onChange={(event) => setEdit({ ...edit, expires_at: event.target.value })} /></div><div className={styles.formActions}><button type="button" className={styles.btnCancel} onClick={() => { setEditing(null); setEdit(null); }}>Cancel</button><button className={styles.btnSubmit} disabled={saving}>{saving ? 'Saving' : 'Save Changes'}</button></div></form></Modal> : null}
  </div>;
}
