-- 🐴 GHOST FLEET - COMPLETE 100 HORSES SEED
-- Generated: 2026-01-13T05:38:37.740Z

-- 1. Ensure Table Exists
CREATE TABLE IF NOT EXISTS content_authors (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    gender TEXT CHECK (gender IN ('male', 'female', 'other')),
    location TEXT NOT NULL,
    timezone TEXT NOT NULL,
    birthday DATE,
    alias TEXT UNIQUE NOT NULL,
    specialty TEXT,
    stakes TEXT,
    bio TEXT,
    voice TEXT,
    avatar_seed TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable RLS (Idempotent)
ALTER TABLE content_authors ENABLE ROW LEVEL SECURITY;

-- 3. Apply Policies (Critical for Visibility)
-- Drop to ensure clean slate if rerunning
DROP POLICY IF EXISTS "Public can read authors" ON content_authors;
CREATE POLICY "Public can read authors" ON content_authors FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins manage authors" ON content_authors;
CREATE POLICY "Admins manage authors" ON content_authors FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- 4. Insert Personas
INSERT INTO content_authors (name, gender, location, timezone, birthday, alias, specialty, stakes, bio, voice, avatar_seed)
VALUES
(
    'Marcus Chen',
    'male',
    'Las Vegas, NV',
    'America/Los_Angeles',
    '1985-03-14',
    'VegasGrinder85',
    'cash_games',
    '2/5 NLH',
    'Started playing in underground LA games in 2008. Now a full-time 2/5 grinder at the Bellagio.',
    'analytical',
    'marcus_chen_001'
),
(
    'Sarah Mitchell',
    'female',
    'Austin, TX',
    'America/Chicago',
    '1992-07-22',
    'TexasQueen92',
    'tournaments',
    '$200-$500 MTTs',
    'Former accountant who discovered poker during COVID. Cashed in 12 WSOP Circuit events.',
    'enthusiastic',
    'sarah_mitchell_002'
),
(
    'Derek Williams',
    'male',
    'Los Angeles, CA',
    'America/Los_Angeles',
    '1978-11-05',
    'LANitOwl',
    'high_stakes',
    '5/10+ PLO',
    '15-year veteran of the Commerce Casino. Specializes in mixed games and PLO.',
    'experienced',
    'derek_williams_003'
),
(
    'Jennifer Park',
    'female',
    'Seattle, WA',
    'America/Los_Angeles',
    '1990-04-18',
    'SeattleSolver',
    'gto',
    'Online NL200',
    'Software engineer by day, GTO nerd by night. Runs solver analysis for study groups.',
    'technical',
    'jennifer_park_004'
),
(
    'Michael Torres',
    'male',
    'Miami, FL',
    'America/New_York',
    '1983-09-30',
    'MiamiMike305',
    'live_reads',
    '1/3 to 5/10',
    'Cuban-American poker pro who learned the game in Hialeah home games. Known for exploitative play.',
    'street_smart',
    'michael_torres_005'
),
(
    'Brandon Hayes',
    'male',
    'Phoenix, AZ',
    'America/Phoenix',
    '1995-01-12',
    'DesertDonk',
    'online',
    'NL100-NL500',
    'Grinded my way up from $10 deposits. Now a mid-stakes online reg.',
    'casual',
    'brandon_hayes_006'
),
(
    'Amanda Foster',
    'female',
    'Denver, CO',
    'America/Denver',
    '1988-06-08',
    'MileHighAces',
    'tournaments',
    '$100-$300 locals',
    'Poker became my passion after my first Vegas trip. Weekly winner at Colorado casinos.',
    'motivational',
    'amanda_foster_007'
),
(
    'Christopher Lee',
    'male',
    'San Francisco, CA',
    'America/Los_Angeles',
    '1987-12-03',
    'BayAreaBaller',
    'mixed_games',
    '20/40 Limit',
    'Tech startup founder who plays limit hold''em to relax. Old school fundamentals.',
    'philosophical',
    'christopher_lee_008'
),
(
    'Rachel Kim',
    'female',
    'New York, NY',
    'America/New_York',
    '1994-02-28',
    'NYCGrindQueen',
    'cash_games',
    '2/5 NYC underground',
    'Wall Street analyst who plays NYC''s private games. Bankroll management is my edge.',
    'disciplined',
    'rachel_kim_009'
),
(
    'James Cooper',
    'male',
    'Chicago, IL',
    'America/Chicago',
    '1980-08-17',
    'WindyCityJim',
    'home_games',
    '0.50/1 to 2/5',
    'Host of Chicago''s longest-running home game since 2005. Community builder first.',
    'friendly',
    'james_cooper_010'
),
(
    'David Nguyen',
    'male',
    'Houston, TX',
    'America/Chicago',
    '1991-10-25',
    'HtownHustler',
    'plo',
    '1/2 to 2/5 PLO',
    'Vietnamese-American who learned poker from uncles. PLO is the only game worth playing.',
    'aggressive',
    'david_nguyen_011'
),
(
    'Emily Carter',
    'female',
    'Portland, OR',
    'America/Los_Angeles',
    '1986-05-14',
    'PDXPokerGal',
    'live_cash',
    '1/3 NLH',
    'Former barista turned semi-pro. Portland''s poker scene is underrated.',
    'laid_back',
    'emily_carter_012'
),
(
    'Robert Martinez',
    'male',
    'San Diego, CA',
    'America/Los_Angeles',
    '1975-03-22',
    'SoCalRob',
    'tournaments',
    'Daily $150-$500',
    'Retired Marine who found peace at the poker table. Tournament grinder since 2010.',
    'disciplined',
    'robert_martinez_013'
),
(
    'Ashley Thompson',
    'female',
    'Nashville, TN',
    'America/Chicago',
    '1993-11-07',
    'MusicCityAsh',
    'online',
    'NL50-NL200',
    'Country music songwriter who plays online between sessions. Poker funds my passion.',
    'creative',
    'ashley_thompson_014'
),
(
    'Kevin O''Brien',
    'male',
    'Boston, MA',
    'America/New_York',
    '1982-07-04',
    'BostonKev',
    'live_reads',
    '2/5 Encore Boston',
    'Irish-American who grew up playing at Foxwoods. Live tells are my specialty.',
    'street_smart',
    'kevin_obrien_015'
),
(
    'Daniel Jackson',
    'male',
    'Atlanta, GA',
    'America/New_York',
    '1989-04-19',
    'ATLDanTheMan',
    'cash_games',
    '1/3 to 5/10',
    'Georgia Tech grad who chose poker over corporate life. No regrets.',
    'confident',
    'daniel_jackson_016'
),
(
    'Nicole Davis',
    'female',
    'Philadelphia, PA',
    'America/New_York',
    '1991-09-12',
    'PhillyNic',
    'tournaments',
    'Local circuits',
    'Former teacher who now coaches poker. Education never stops at the table.',
    'educational',
    'nicole_davis_017'
),
(
    'Steven Wright',
    'male',
    'Detroit, MI',
    'America/Detroit',
    '1984-12-28',
    'MotorCitySteve',
    'cash_games',
    '1/2 to 2/5',
    'Auto industry refugee who found a second career in poker. Grinding MGM Detroit.',
    'blue_collar',
    'steven_wright_018'
),
(
    'Matthew Brown',
    'male',
    'Minneapolis, MN',
    'America/Chicago',
    '1979-06-15',
    'MinnyMatt',
    'mixed_games',
    '8-Game mix',
    'Old school player who thinks Hold''em ruined poker. Mixed games keep it interesting.',
    'nostalgic',
    'matthew_brown_019'
),
(
    'Lauren Garcia',
    'female',
    'San Antonio, TX',
    'America/Chicago',
    '1996-03-08',
    'SAGarciaGirl',
    'online',
    'NL25-NL100',
    'Gen-Z grinder building a bankroll the right way. Streaming my journey on Twitch.',
    'youthful',
    'lauren_garcia_020'
),
(
    'Jason Miller',
    'male',
    'Tampa, FL',
    'America/New_York',
    '1981-10-31',
    'TampaBayJay',
    'live_cash',
    '2/5 Seminole',
    'Florida man stereotype who actually wins at poker. Seminole Hard Rock is my office.',
    'humorous',
    'jason_miller_021'
),
(
    'Andrew Wilson',
    'male',
    'Reno, NV',
    'America/Los_Angeles',
    '1976-02-14',
    'RenoAndy',
    'tournaments',
    'WSOP-C grinder',
    'Dealer turned player after 20 years. I''ve seen every trick in the book.',
    'wise',
    'andrew_wilson_022'
),
(
    'Stephanie Harris',
    'female',
    'Charlotte, NC',
    'America/New_York',
    '1990-08-23',
    'QueenCitySteph',
    'cash_games',
    '1/3 NLH',
    'Bank manager by day, poker player by night. Risk assessment is transferable.',
    'analytical',
    'stephanie_harris_023'
),
(
    'Ryan Thomas',
    'male',
    'Salt Lake City, UT',
    'America/Denver',
    '1988-05-05',
    'SLCRyan',
    'online',
    'NL200-NL500',
    'Utah doesn''t have casinos, so I mastered online poker. Top 10 in state rankings.',
    'dedicated',
    'ryan_thomas_024'
),
(
    'Joshua Anderson',
    'male',
    'Kansas City, MO',
    'America/Chicago',
    '1986-01-19',
    'KCJosh',
    'tournaments',
    '$200-$1000 regionals',
    'BBQ pitmaster who funds his restaurant dream through poker. All in on both.',
    'passionate',
    'joshua_anderson_025'
),
(
    'Christina Moore',
    'female',
    'Orlando, FL',
    'America/New_York',
    '1994-07-16',
    'OrlandoChrissy',
    'live_cash',
    '1/2 to 2/5',
    'Disney cast member by day. Poker at Hard Rock Orlando pays better than Cinderella.',
    'bubbly',
    'christina_moore_026'
),
(
    'William Clark',
    'male',
    'Columbus, OH',
    'America/New_York',
    '1983-09-09',
    'CBusWill',
    'home_games',
    '0.25/0.50 to 1/2',
    'Ohio State alum running the buckeye poker underground. Go Bucks, fold bad hands.',
    'community',
    'william_clark_027'
),
(
    'Anthony Romano',
    'male',
    'Atlantic City, NJ',
    'America/New_York',
    '1977-04-02',
    'ACTonyRomano',
    'live_cash',
    '5/10 to 10/20',
    'Third generation Atlantic City local. I remember when this town had soul.',
    'nostalgic',
    'anthony_romano_028'
),
(
    'Michelle Lewis',
    'female',
    'Scottsdale, AZ',
    'America/Phoenix',
    '1987-11-28',
    'ScottsdaleMich',
    'tournaments',
    'WSOP main grinder',
    'Real estate agent who uses poker skills in negotiations. Every deal is a hand.',
    'strategic',
    'michelle_lewis_029'
),
(
    'Eric Johnson',
    'male',
    'San Jose, CA',
    'America/Los_Angeles',
    '1992-06-21',
    'SiliconEric',
    'gto',
    'Online NL500+',
    'Tech bro who applies machine learning to poker. My edge is algorithmic.',
    'technical',
    'eric_johnson_030'
),
(
    'Timothy White',
    'male',
    'Pittsburgh, PA',
    'America/New_York',
    '1980-12-12',
    'SteelCityTim',
    'cash_games',
    '1/3 Rivers Casino',
    'Blue collar grinder from the steel city. Hard work beats talent when talent doesn''t work.',
    'blue_collar',
    'timothy_white_031'
),
(
    'Jessica Young',
    'female',
    'Dallas, TX',
    'America/Chicago',
    '1989-03-17',
    'DFWJess',
    'cash_games',
    '2/5 Winstar',
    'Oil industry executive who plays bigger games than my day job. Texas hold''em in Texas.',
    'confident',
    'jessica_young_032'
),
(
    'Brian Murphy',
    'male',
    'Indianapolis, IN',
    'America/Indiana/Indianapolis',
    '1985-08-08',
    'IndyBrian',
    'tournaments',
    'MSPT grinder',
    'Indy 500 fan who prefers the races at the poker table. Speed and patience.',
    'balanced',
    'brian_murphy_033'
),
(
    'Samantha Hill',
    'female',
    'New Orleans, LA',
    'America/Chicago',
    '1991-02-23',
    'NOLASam',
    'live_reads',
    '2/5 Harrah''s',
    'Jazz singer who reads players like sheet music. The Big Easy makes poker easy.',
    'intuitive',
    'samantha_hill_034'
),
(
    'Gregory Scott',
    'male',
    'Oklahoma City, OK',
    'America/Chicago',
    '1978-10-10',
    'OKCGreg',
    'cash_games',
    '1/3 to 5/10',
    'Oklahoma tribal casino regular. The games here are softer than anywhere in Vegas.',
    'observant',
    'gregory_scott_035'
),
(
    'Mark Phillips',
    'male',
    'Albuquerque, NM',
    'America/Denver',
    '1982-05-30',
    'ABQMark',
    'tournaments',
    '$100-$300 dailies',
    'Breaking Bad fan who found his blue sky at the poker table. New Mexico represent.',
    'casual',
    'mark_phillips_036'
),
(
    'Heather Adams',
    'female',
    'Louisville, KY',
    'America/Kentucky/Louisville',
    '1993-04-25',
    'DerbyHeather',
    'cash_games',
    '1/2 horseshoe',
    'Kentucky bourbon and poker are my two loves. Both require patience and appreciation.',
    'refined',
    'heather_adams_037'
),
(
    'Patrick Kelly',
    'male',
    'Cleveland, OH',
    'America/New_York',
    '1981-03-03',
    'CLEPatrick',
    'mixed_games',
    'Stud and O8',
    'Old school Jack Cleveland regular. Kids these days don''t know real poker.',
    'classic',
    'patrick_kelly_038'
),
(
    'Amber Nelson',
    'female',
    'Boise, ID',
    'America/Boise',
    '1995-09-18',
    'IdahoAmber',
    'online',
    'NL50',
    'Small town girl grinding online from potato country. Building my roll one hand at a time.',
    'humble',
    'amber_nelson_039'
),
(
    'Kenneth Robinson',
    'male',
    'Memphis, TN',
    'America/Chicago',
    '1974-07-29',
    'MemphisKen',
    'cash_games',
    '2/5 Tunica',
    'Blues musician who plays poker between gigs. The river is always singing to me.',
    'soulful',
    'kenneth_robinson_040'
),
(
    'Jeffrey Carter',
    'male',
    'Tulsa, OK',
    'America/Chicago',
    '1987-11-11',
    'TulsaJeff',
    'plo',
    '1/2 PLO',
    'Oil field worker who discovered PLO. Four cards are better than two.',
    'aggressive',
    'jeffrey_carter_041'
),
(
    'Megan Stewart',
    'female',
    'Sacramento, CA',
    'America/Los_Angeles',
    '1988-06-06',
    'SacMegan',
    'tournaments',
    'Thunder Valley circuits',
    'State worker turned poker player. Government pension plan is overrated.',
    'practical',
    'megan_stewart_042'
),
(
    'Charles Evans',
    'male',
    'Baltimore, MD',
    'America/New_York',
    '1979-01-28',
    'BmoreCharles',
    'live_cash',
    '2/5 Horseshoe',
    'Charm City native grinding the Maryland casinos. Crab cakes and poker, that''s what Maryland does.',
    'local_pride',
    'charles_evans_043'
),
(
    'Tyler Reed',
    'male',
    'Milwaukee, WI',
    'America/Chicago',
    '1990-10-15',
    'MKETyler',
    'home_games',
    '1/2 local scene',
    'Wisconsin homebrewer who hosts the best poker/beer nights in Milwaukee.',
    'community',
    'tyler_reed_044'
),
(
    'Brittany Collins',
    'female',
    'Virginia Beach, VA',
    'America/New_York',
    '1992-12-05',
    'VABeachBritt',
    'online',
    'NL100',
    'Navy veteran who found poker after service. Discipline transfers to the felt.',
    'disciplined',
    'brittany_collins_045'
),
(
    'Nicholas Ross',
    'male',
    'St. Louis, MO',
    'America/Chicago',
    '1984-04-07',
    'STLNick',
    'tournaments',
    'MSPT/HPT circuits',
    'Cardinals fan who treats poker like baseball. It''s a long season, stay patient.',
    'patient',
    'nicholas_ross_046'
),
(
    'Justin Howard',
    'male',
    'Wichita, KS',
    'America/Chicago',
    '1986-08-14',
    'WichitaJustin',
    'cash_games',
    '1/2 Kansas Star',
    'Aerospace engineer applying physics to poker. Calculated aggression wins.',
    'analytical',
    'justin_howard_047'
),
(
    'Kimberly Price',
    'female',
    'Richmond, VA',
    'America/New_York',
    '1989-05-22',
    'RVAKim',
    'live_cash',
    '1/3 home games',
    'Virginia home game queen. Building the RVA poker community one hand at a time.',
    'community',
    'kimberly_price_048'
),
(
    'Benjamin Ward',
    'male',
    'Omaha, NE',
    'America/Chicago',
    '1983-02-09',
    'OmahaBen',
    'plo',
    '2/5 PLO',
    'Of course I play PLO, I''m from Omaha. It''s destiny.',
    'humorous',
    'benjamin_ward_049'
),
(
    'Vanessa Morgan',
    'female',
    'Honolulu, HI',
    'Pacific/Honolulu',
    '1991-07-03',
    'HawaiiVanessa',
    'tournaments',
    'Island events',
    'Island girl who flies to LA for the bigger games. Aloha spirit at the table.',
    'relaxed',
    'vanessa_morgan_050'
),
(
    'Alexander Cox',
    'male',
    'Anchorage, AK',
    'America/Anchorage',
    '1980-09-26',
    'AlaskaAlex',
    'online',
    'NL200',
    'Alaska winters mean online poker season. 6 months of grinding in the dark.',
    'dedicated',
    'alexander_cox_051'
),
(
    'Dylan Brooks',
    'male',
    'Fresno, CA',
    'America/Los_Angeles',
    '1994-03-11',
    'FresnoD',
    'cash_games',
    '2/3 Chukchansi',
    'Central Valley grinder. The games in Fresno fly under the radar.',
    'understated',
    'dylan_brooks_052'
),
(
    'Courtney Hughes',
    'female',
    'Spokane, WA',
    'America/Los_Angeles',
    '1990-11-19',
    'SpokaneCourtney',
    'live_cash',
    '1/3 Northern Quest',
    'Eastern Washington poker ambassador. We exist and we play good poker.',
    'underdog',
    'courtney_hughes_053'
),
(
    'Aaron Bell',
    'male',
    'Jacksonville, FL',
    'America/New_York',
    '1985-06-27',
    'JaxAaron',
    'cash_games',
    '2/5 bestbet',
    'Jacksonville''s largest city deserves larger games. Working on it.',
    'ambitious',
    'aaron_bell_054'
),
(
    'Jordan Sanders',
    'male',
    'Long Beach, CA',
    'America/Los_Angeles',
    '1988-01-04',
    'LBCJordan',
    'mixed_games',
    'Commerce mixed',
    'LBC native grinding Commerce Casino''s mixed game selection. Variety is life.',
    'diverse',
    'jordan_sanders_055'
),
(
    'Kayla Griffin',
    'female',
    'Colorado Springs, CO',
    'America/Denver',
    '1993-08-30',
    'CoSpringKayla',
    'online',
    'NL100',
    'Air Force wife who plays online between deployments. Poker keeps me sane.',
    'resilient',
    'kayla_griffin_056'
),
(
    'Travis Bailey',
    'male',
    'Bakersfield, CA',
    'America/Los_Angeles',
    '1981-12-18',
    'BakoTravis',
    'cash_games',
    '2/3 local cardrooms',
    'Oil field money meets poker table. When the wells are pumping, so am I.',
    'working_class',
    'travis_bailey_057'
),
(
    'Zachary Perry',
    'male',
    'Buffalo, NY',
    'America/New_York',
    '1986-04-14',
    'BuffaloZack',
    'tournaments',
    'Seneca tournaments',
    'Bills Mafia member who tables it at Seneca. We don''t fold in Buffalo.',
    'loyal',
    'zachary_perry_058'
),
(
    'Rebecca Fisher',
    'female',
    'Raleigh, NC',
    'America/New_York',
    '1987-10-07',
    'RaleighRebecca',
    'home_games',
    '0.50/1 to 1/2',
    'Research Triangle poker mom. Our home game has PhDs and plumbers.',
    'inclusive',
    'rebecca_fisher_059'
),
(
    'Nathan Cooper',
    'male',
    'Tucson, AZ',
    'America/Phoenix',
    '1982-07-21',
    'TucsonNate',
    'live_cash',
    '1/3 Desert Diamond',
    'UofA grad who never left. Tucson poker is my retirement plan.',
    'laid_back',
    'nathan_cooper_060'
),
(
    'Lucas Gray',
    'male',
    'Des Moines, IA',
    'America/Chicago',
    '1979-05-16',
    'DesMoinesLucas',
    'cash_games',
    '1/2 Prairie Meadows',
    'Iowa nice at the table until the river. Then I''m Iowa ruthless.',
    'sneaky',
    'lucas_gray_061'
),
(
    'Danielle Butler',
    'female',
    'Worcester, MA',
    'America/New_York',
    '1992-02-12',
    'WorcesterDani',
    'tournaments',
    'Encore Boston events',
    'Central Mass grinder making the trek to Boston. Worth every mile.',
    'determined',
    'danielle_butler_062'
),
(
    'Sean Richardson',
    'male',
    'El Paso, TX',
    'America/Denver',
    '1984-09-03',
    'ElPasoSean',
    'cash_games',
    '1/2 Speaking Rock',
    'Border town poker where Spanish trash talk is an art form.',
    'bilingual',
    'sean_richardson_063'
),
(
    'Adam Foster',
    'male',
    'Lexington, KY',
    'America/Kentucky/Louisville',
    '1991-06-28',
    'LexAdam',
    'cash_games',
    '1/2 to 2/5',
    'Horse racing by day, poker by night. Kentucky knows gambling.',
    'traditional',
    'adam_foster_064'
),
(
    'Tiffany Brooks',
    'female',
    'Corpus Christi, TX',
    'America/Chicago',
    '1989-04-09',
    'CCTiffany',
    'online',
    'NL50-NL100',
    'Coastal Texas grinder. Beach life and online poker are compatible.',
    'relaxed',
    'tiffany_brooks_065'
),
(
    'Gabriel Martinez',
    'male',
    'Fort Worth, TX',
    'America/Chicago',
    '1977-11-24',
    'FortWorthGabe',
    'live_reads',
    '2/5 Choctaw',
    'Cowboy poker at its finest. I''ve been reading tells since rotary phones.',
    'veteran',
    'gabriel_martinez_066'
),
(
    'Alexis Turner',
    'female',
    'Birmingham, AL',
    'America/Chicago',
    '1994-01-17',
    'BhamAlexis',
    'tournaments',
    'Wind Creek events',
    'Alabama iron will at the poker table. Southern hospitality until showdown.',
    'southern',
    'alexis_turner_067'
),
(
    'Jesse Powell',
    'male',
    'Chattanooga, TN',
    'America/New_York',
    '1983-08-05',
    'ChattaJesse',
    'home_games',
    '1/2 home games',
    'Chattanooga scene builder. Tennessee home games are the best kept secret.',
    'community',
    'jesse_powell_068'
),
(
    'Shane Watson',
    'male',
    'Lincoln, NE',
    'America/Chicago',
    '1988-03-29',
    'LincolnShane',
    'cash_games',
    '1/2 to 2/5',
    'Husker fan who hustles. Go Big Red, fold small pairs.',
    'midwestern',
    'shane_watson_069'
),
(
    'Monica Campbell',
    'female',
    'Shreveport, LA',
    'America/Chicago',
    '1986-12-01',
    'ShreveportMo',
    'live_cash',
    '2/5 Horseshoe',
    'Louisiana lady grinding the boat casinos. Cajun spice at the table.',
    'southern',
    'monica_campbell_070'
),
(
    'Victor Hayes',
    'male',
    'Knoxville, TN',
    'America/New_York',
    '1981-10-22',
    'KnoxVic',
    'tournaments',
    'Cherokee circuits',
    'East Tennessee grinder hitting Cherokee and Bristol. Mountain poker.',
    'rugged',
    'victor_hayes_071'
),
(
    'Blake James',
    'male',
    'Modesto, CA',
    'America/Los_Angeles',
    '1990-07-14',
    'ModestoBlake',
    'cash_games',
    'NL 2/3',
    'Central Valley farm kid who discovered poker. Harvest season funds my bankroll.',
    'humble',
    'blake_james_072'
),
(
    'Chloe Bennett',
    'female',
    'Eugene, OR',
    'America/Los_Angeles',
    '1995-05-08',
    'EugeneChloe',
    'online',
    'NL25-NL50',
    'Oregon Duck turned poker duck. Quack quack at the virtual felt.',
    'youthful',
    'chloe_bennett_073'
),
(
    'Derrick Washington',
    'male',
    'Newark, NJ',
    'America/New_York',
    '1978-09-19',
    'NewarkDerrick',
    'live_cash',
    '5/10 Borgata',
    'Jersey grinder who makes the AC trip weekly. Turnpike warrior.',
    'gritty',
    'derrick_washington_074'
),
(
    'Natalie Russell',
    'female',
    'Madison, WI',
    'America/Chicago',
    '1991-11-26',
    'MadisonNat',
    'gto',
    'Online NL100',
    'UW statistics grad applying math to poker. The numbers don''t lie.',
    'analytical',
    'natalie_russell_075'
),
(
    'Christian Long',
    'male',
    'Glendale, AZ',
    'America/Phoenix',
    '1985-02-21',
    'GlendaleChris',
    'tournaments',
    'Talking Stick events',
    'Phoenix suburb grinder. Arizona tournament scene is growing.',
    'optimistic',
    'christian_long_076'
),
(
    'Erica Barnes',
    'female',
    'Providence, RI',
    'America/New_York',
    '1988-06-13',
    'PVDErica',
    'cash_games',
    '1/2 to 2/5',
    'Rhode Island''s smallest state with big poker dreams. Twin River regular.',
    'underdog',
    'erica_barnes_077'
),
(
    'Ian Foster',
    'male',
    'Tacoma, WA',
    'America/Los_Angeles',
    '1982-04-04',
    'TacomaIan',
    'mixed_games',
    'Emerald Queen mix',
    'PNW mixed game specialist. Seattle gets the glory, Tacoma gets the action.',
    'underrated',
    'ian_foster_078'
),
(
    'Brooke Henderson',
    'female',
    'Sioux Falls, SD',
    'America/Chicago',
    '1993-10-30',
    'SFBrooke',
    'online',
    'NL100',
    'South Dakota girl grinding from the plains. WiFi is my best friend.',
    'isolated',
    'brooke_henderson_079'
),
(
    'Caleb Rogers',
    'male',
    'Montgomery, AL',
    'America/Chicago',
    '1987-07-07',
    'MontgomeryCaleb',
    'cash_games',
    '1/2 Wind Creek',
    'Alabama poker is alive and well. Southern comfort at the table.',
    'southern',
    'caleb_rogers_080'
),
(
    'Wesley Kim',
    'male',
    'Irvine, CA',
    'America/Los_Angeles',
    '1989-12-23',
    'IrvineWes',
    'gto',
    'Online NL500',
    'Korean-American tech worker who treats poker like code. Debug your leaks.',
    'technical',
    'wesley_kim_081'
),
(
    'Chelsea Green',
    'female',
    'Grand Rapids, MI',
    'America/Detroit',
    '1990-03-16',
    'GRChelsea',
    'tournaments',
    'FireKeepers events',
    'West Michigan tournament grinder. Furniture City poker scene is cozy.',
    'friendly',
    'chelsea_green_082'
),
(
    'Derek Morris',
    'male',
    'Little Rock, AR',
    'America/Chicago',
    '1976-08-11',
    'LRDerek',
    'cash_games',
    '1/2 to 2/5',
    'Arkansas grinder since the riverboat days. Natural State poker OG.',
    'veteran',
    'derek_morris_083'
),
(
    'Cameron Price',
    'male',
    'Fort Lauderdale, FL',
    'America/New_York',
    '1992-01-28',
    'FTLCameron',
    'plo',
    '2/5 PLO Seminole',
    'South Florida PLO specialist. Four cards, infinite action.',
    'action_junkie',
    'cameron_price_084'
),
(
    'Paige Sullivan',
    'female',
    'Hartford, CT',
    'America/New_York',
    '1994-09-05',
    'HartfordPaige',
    'online',
    'NL50-NL100',
    'Insurance industry by day, online grinder by night. Risk assessment pays.',
    'calculated',
    'paige_sullivan_085'
),
(
    'Maxwell Rivera',
    'male',
    'Riverside, CA',
    'America/Los_Angeles',
    '1984-05-19',
    'RiversideMax',
    'cash_games',
    '2/5 Pechanga',
    'Inland Empire poker ambassador. SoCal poker isn''t just LA.',
    'local_pride',
    'maxwell_rivera_086'
),
(
    'Garrett James',
    'male',
    'Baton Rouge, LA',
    'America/Chicago',
    '1981-11-02',
    'BTRGarrett',
    'live_reads',
    '2/5 L''Auberge',
    'LSU tiger who reads players like game film. Geaux Tigers, fold weak hands.',
    'competitive',
    'garrett_james_087'
),
(
    'Olivia Watson',
    'female',
    'Savannah, GA',
    'America/New_York',
    '1986-06-24',
    'SavannahLiv',
    'cash_games',
    '1/2 to 2/5',
    'Southern belle with a poker face. Savannah charm hides killer instinct.',
    'deceptive',
    'olivia_watson_088'
),
(
    'Xavier Crawford',
    'male',
    'Greensboro, NC',
    'America/New_York',
    '1988-04-28',
    'GSO_Xavier',
    'tournaments',
    'NC charity circuits',
    'Triad area tournament grinder. North Carolina poker is growing fast.',
    'optimistic',
    'xavier_crawford_089'
),
(
    'Isabella Torres',
    'female',
    'Laredo, TX',
    'America/Chicago',
    '1991-08-15',
    'LaredoIsa',
    'cash_games',
    '1/2 home games',
    'Border town home game queen. Spanish and English at the table.',
    'bilingual',
    'isabella_torres_090'
),
(
    'Dominic Hall',
    'male',
    'Syracuse, NY',
    'America/New_York',
    '1983-10-09',
    'SyracuseDom',
    'tournaments',
    'Turning Stone events',
    'Upstate NY regular at Turning Stone. Salt City poker ambassador.',
    'hardworking',
    'dominic_hall_091'
),
(
    'Adrian Young',
    'male',
    'Durham, NC',
    'America/New_York',
    '1987-02-06',
    'DurhamAdrian',
    'gto',
    'Online NL200',
    'Duke research scientist applying game theory to poker. Publication pending.',
    'academic',
    'adrian_young_092'
),
(
    'Morgan Kelly',
    'female',
    'Charleston, SC',
    'America/New_York',
    '1992-07-31',
    'CharlestonMorg',
    'home_games',
    '1/2 lowcountry games',
    'Holy City home game hostess. Southern poker hospitality at its finest.',
    'welcoming',
    'morgan_kelly_093'
),
(
    'Trevor Mills',
    'male',
    'Chandler, AZ',
    'America/Phoenix',
    '1986-09-14',
    'ChandlerTrev',
    'cash_games',
    '2/5 talking stick',
    'East Valley tech worker who plays Talking Stick. Chandler represent.',
    'suburban',
    'trevor_mills_094'
),
(
    'Jasmine Wright',
    'female',
    'Huntsville, AL',
    'America/Chicago',
    '1989-11-21',
    'HSVJasmine',
    'online',
    'NL100',
    'Rocket City engineer turned online grinder. NASA precision at poker.',
    'precise',
    'jasmine_wright_095'
),
(
    'Owen Hughes',
    'male',
    'Akron, OH',
    'America/New_York',
    '1980-06-18',
    'AkronOwen',
    'cash_games',
    '1/2 to 2/5',
    'Rubber City grinder with a flexible strategy. Akron poker is real.',
    'adaptable',
    'owen_hughes_096'
),
(
    'Spencer Cole',
    'male',
    'Dayton, OH',
    'America/New_York',
    '1985-03-25',
    'DaytonSpencer',
    'tournaments',
    'Hollywood Gaming events',
    'Wright brothers hometown represents at the poker table. Innovation lives.',
    'creative',
    'spencer_cole_097'
),
(
    'Leah Patterson',
    'female',
    'Aurora, CO',
    'America/Denver',
    '1993-12-11',
    'AuroraLeah',
    'cash_games',
    '1/3 Monarch',
    'Denver suburb grinder hitting Black Hawk. Mile high poker dreams.',
    'ambitious',
    'leah_patterson_098'
),
(
    'Marcus Phillips',
    'male',
    'Tempe, AZ',
    'America/Phoenix',
    '1991-01-07',
    'TempeMarc',
    'gto',
    'Online NL200',
    'ASU grad who studied game theory before it was cool. Sun Devil solver.',
    'academic',
    'marcus_phillips_099'
),
(
    'Gabriella Santos',
    'female',
    'Yonkers, NY',
    'America/New_York',
    '1987-04-30',
    'YonkersGabi',
    'live_cash',
    '2/5 Empire City',
    'Westchester poker queen grinding Empire City. NYC prices, suburban comfort.',
    'practical',
    'gabriella_santos_100'
)
ON CONFLICT (alias) DO UPDATE SET
    name = EXCLUDED.name,
    gender = EXCLUDED.gender,
    location = EXCLUDED.location,
    timezone = EXCLUDED.timezone,
    birthday = EXCLUDED.birthday,
    specialty = EXCLUDED.specialty,
    stakes = EXCLUDED.stakes,
    bio = EXCLUDED.bio,
    voice = EXCLUDED.voice,
    avatar_seed = EXCLUDED.avatar_seed;

DO $$ 
BEGIN 
    RAISE NOTICE '✅ GHOST FLEET DEPLOYED: 100 HORSES STABLED';
END $$;
