-- =====================================================================
-- 20261007052243_activate_training_solver_m1_bounded_canary.sql
-- =====================================================================
-- TIER:        3
-- AUTHOR:      Smarter.Poker Phase 6 controller
-- AFFECTS:     training_solver_provenance_authority,
--              training_solver_bounded_canary_targets,
--              training_solver_ingest_scopes; fn_training_solver_scope_transition_guard_v1 (function + DML)
-- IRREVERSIBLE: yes (old authority retirement; qualified recovery holds NEW only)
--
-- WHY:
--   Install the exact reviewed M1 authority tuple and two reserved warehouse
--   identities required by the cash-002 continuation cohort. Evidence and the
--   literal contract live in the dated Phase 6 M1 bounded-canary audit files.
--
-- HOW (high level):
--   - Fail closed unless prerequisite objects and exact target identities exist.
--   - Insert one checksum-sealed authority and exactly two canary targets.
--   - Move only the exact M1 tuple from held to bounded_canary for partition 2/0.
--   - Assert that exactly one bounded scope is active before commit.
-- =====================================================================
-- Generated by build_m1_bounded_canary.py from one reviewed packet.
-- Literal M1 held -> target install -> bounded-canary activation only.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';
DO $m1_guard_preimage$
BEGIN
  IF md5(pg_catalog.pg_get_functiondef('public.fn_training_solver_scope_transition_guard_v1()'::regprocedure))
       IS DISTINCT FROM '5080a6fb62d078a04931e3389dda5942' THEN
    RAISE EXCEPTION 'TRAINING_M1_SCOPE_GUARD_PREIMAGE_MISMATCH';
  END IF;
END;
$m1_guard_preimage$;
CREATE OR REPLACE FUNCTION public.fn_training_solver_scope_transition_guard_v1()
RETURNS trigger
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  v_parent_count integer;
  v_child_count integer;
  v_target_count integer;
  v_lineage_valid boolean;
BEGIN
  IF NEW.admission_mode = 'held' AND NEW.partition_count IS NULL AND NEW.partition_index IS NULL
     AND ROW(NEW.machine_id, NEW.solver_version, NEW.solver_binary_checksum, NEW.pipeline_commit, NEW.manifest_version, NEW.manifest_checksum)
       IS NOT DISTINCT FROM ROW(OLD.machine_id, OLD.solver_version, OLD.solver_binary_checksum, OLD.pipeline_commit, OLD.manifest_version, OLD.manifest_checksum)
     AND NEW.machine_id = 'M1' AND NEW.solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)' AND NEW.solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb' AND NEW.manifest_version = '5'
     AND ((NEW.pipeline_commit = '1ccf3907cf3298e24609eb6fbd903023d91dbddf' AND NEW.manifest_checksum = 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8')
       OR (NEW.pipeline_commit = '002cb37bbd89df86f4cc054fcf370f794b14f413' AND NEW.manifest_checksum = '3115537d7169913cac08db6a40797af7b516e33d1e4faa8d51310704aaf58a25')) THEN
    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('training-solver-ingest-scope:M1', 0));
    RETURN NEW;
  END IF;
  IF OLD.admission_mode IS DISTINCT FROM 'held'
     OR NEW.machine_id IS DISTINCT FROM OLD.machine_id
     OR NEW.solver_version IS DISTINCT FROM OLD.solver_version
     OR NEW.solver_binary_checksum IS DISTINCT FROM OLD.solver_binary_checksum
     OR NEW.pipeline_commit IS DISTINCT FROM OLD.pipeline_commit
     OR NEW.manifest_version IS DISTINCT FROM OLD.manifest_version
     OR NEW.manifest_checksum IS DISTINCT FROM OLD.manifest_checksum
     OR NEW.admission_mode NOT IN ('backlog', 'bounded_canary') THEN
    RAISE EXCEPTION USING
      ERRCODE = '55000', MESSAGE = 'TRAINING_SOLVER_INGEST_SCOPE_IMMUTABLE';
  END IF;

  -- Serialize activation per physical worker. M1 and M2 intentionally use
  -- independent advisory keys, so either machine may run while the other does.
  -- Both backlog and bounded-canary transitions take this lock; otherwise two
  -- concurrent held->active transactions could each miss the other.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'training-solver-ingest-scope:' || OLD.machine_id,
      0
    )
  );

  IF EXISTS (
    SELECT 1
    FROM public.training_solver_ingest_scopes other_scope
    JOIN public.training_solver_provenance_authority other_authority
      USING (
        machine_id, solver_version, solver_binary_checksum, pipeline_commit,
        manifest_version, manifest_checksum
      )
    WHERE other_scope.machine_id = OLD.machine_id
      AND other_scope.admission_mode IN ('backlog', 'bounded_canary')
      AND other_authority.retired_at IS NULL
      AND (
        other_scope.solver_version IS DISTINCT FROM OLD.solver_version
        OR other_scope.solver_binary_checksum IS DISTINCT FROM
          OLD.solver_binary_checksum
        OR other_scope.pipeline_commit IS DISTINCT FROM OLD.pipeline_commit
        OR other_scope.manifest_version IS DISTINCT FROM OLD.manifest_version
        OR other_scope.manifest_checksum IS DISTINCT FROM OLD.manifest_checksum
      )
  ) THEN
    RAISE EXCEPTION USING
      ERRCODE = '55000',
      MESSAGE = 'TRAINING_SOLVER_MACHINE_INGEST_SCOPE_ALREADY_ACTIVE';
  END IF;

  SELECT count(*), count(*) FILTER (WHERE target.target_role = 'parent'),
         count(*) FILTER (WHERE target.target_role = 'child')
  INTO v_target_count, v_parent_count, v_child_count
  FROM public.training_solver_bounded_canary_targets target
  WHERE target.machine_id = OLD.machine_id
    AND target.solver_version = OLD.solver_version
    AND target.solver_binary_checksum = OLD.solver_binary_checksum
    AND target.pipeline_commit = OLD.pipeline_commit
    AND target.manifest_version = OLD.manifest_version
    AND target.manifest_checksum = OLD.manifest_checksum;

  IF (NEW.admission_mode = 'backlog' AND v_target_count <> 0)
     OR (NEW.admission_mode = 'bounded_canary'
         AND (v_target_count <> 2 OR v_parent_count <> 1 OR v_child_count <> 1)) THEN
    RAISE EXCEPTION USING
      ERRCODE = '23514', MESSAGE = 'TRAINING_SOLVER_INGEST_SCOPE_TARGET_SET_INVALID';
  END IF;
  IF NEW.admission_mode = 'bounded_canary' THEN
    SELECT
      left(child.scenario_hash, char_length('turn_' || parent.scenario_hash)) =
        'turn_' || parent.scenario_hash
      AND char_length(child.scenario_hash) =
        char_length('turn_' || parent.scenario_hash) + 2
      AND right(child.scenario_hash, 2) ~ '^[2-9TJQKA][cdhs]$'
      AND starts_with(child.node, parent.node || ':')
      AND child.hero_position = parent.hero_position
    INTO v_lineage_valid
    FROM public.training_solver_bounded_canary_targets parent
    JOIN public.training_solver_bounded_canary_targets child
      ON child.machine_id = parent.machine_id
     AND child.solver_version = parent.solver_version
     AND child.solver_binary_checksum = parent.solver_binary_checksum
     AND child.pipeline_commit = parent.pipeline_commit
     AND child.manifest_version = parent.manifest_version
     AND child.manifest_checksum = parent.manifest_checksum
     AND child.target_role = 'child'
    WHERE parent.machine_id = OLD.machine_id
      AND parent.solver_version = OLD.solver_version
      AND parent.solver_binary_checksum = OLD.solver_binary_checksum
      AND parent.pipeline_commit = OLD.pipeline_commit
      AND parent.manifest_version = OLD.manifest_version
      AND parent.manifest_checksum = OLD.manifest_checksum
      AND parent.target_role = 'parent';
    IF v_lineage_valid IS DISTINCT FROM true THEN
      RAISE EXCEPTION USING
        ERRCODE = '23514', MESSAGE = 'TRAINING_SOLVER_CANARY_LINEAGE_INVALID';
    END IF;
  END IF;
  RETURN NEW;
END;
$function$;

-- Serialize with the actual maintained M1 activation guard, not a new lock.
SELECT pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('training-solver-ingest-scope:M1', 0));
LOCK TABLE public.training_solver_worker_receipts IN SHARE MODE;
DO $m1_pin_transition$
DECLARE v_count integer;
BEGIN
  PERFORM 1 FROM public.training_solver_provenance_authority WHERE machine_id = 'M1' AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)' AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb' AND pipeline_commit = '1ccf3907cf3298e24609eb6fbd903023d91dbddf' AND manifest_version = '5' AND manifest_checksum = 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8' FOR UPDATE;
  PERFORM 1 FROM public.training_solver_ingest_scopes WHERE machine_id = 'M1' AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)' AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb' AND pipeline_commit = '1ccf3907cf3298e24609eb6fbd903023d91dbddf' AND manifest_version = '5' AND manifest_checksum = 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8' FOR UPDATE;
  IF (SELECT count(*) FROM public.training_solver_provenance_authority WHERE machine_id = 'M1' AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)' AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb' AND pipeline_commit = '1ccf3907cf3298e24609eb6fbd903023d91dbddf' AND manifest_version = '5' AND manifest_checksum = 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8' AND retired_at IS NULL) <> 1
     OR (SELECT count(*) FROM public.training_solver_ingest_scopes WHERE machine_id = 'M1' AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)' AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb' AND pipeline_commit = '1ccf3907cf3298e24609eb6fbd903023d91dbddf' AND manifest_version = '5' AND manifest_checksum = 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8' AND admission_mode = 'bounded_canary' AND partition_count = 2 AND partition_index = 0) <> 1 THEN
    RAISE EXCEPTION 'TRAINING_M1_OLD_PIN_NOT_EXACT_ACTIVE';
  END IF;
  IF EXISTS (SELECT 1 FROM public.training_solver_worker_receipts WHERE machine_id = 'M1' AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)' AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb' AND pipeline_commit = '1ccf3907cf3298e24609eb6fbd903023d91dbddf' AND manifest_version = '5' AND manifest_checksum = 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8') THEN
    RAISE EXCEPTION 'TRAINING_M1_OLD_PIN_HAS_RECEIPTS';
  END IF;
  UPDATE public.training_solver_provenance_authority SET retired_at = clock_timestamp() WHERE machine_id = 'M1' AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)' AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb' AND pipeline_commit = '1ccf3907cf3298e24609eb6fbd903023d91dbddf' AND manifest_version = '5' AND manifest_checksum = 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8' AND retired_at IS NULL;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  IF v_count <> 1 THEN RAISE EXCEPTION 'TRAINING_M1_RETIRE_COUNT'; END IF;
  UPDATE public.training_solver_ingest_scopes SET admission_mode = 'held', partition_count = NULL, partition_index = NULL,
    configured_at = clock_timestamp(), configured_by = 'phase6-pio38-incompatible-old-pin-retirement' WHERE machine_id = 'M1' AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)' AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb' AND pipeline_commit = '1ccf3907cf3298e24609eb6fbd903023d91dbddf' AND manifest_version = '5' AND manifest_checksum = 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8';
  GET DIAGNOSTICS v_count = ROW_COUNT;
  IF v_count <> 1 THEN RAISE EXCEPTION 'TRAINING_M1_OLD_HOLD_COUNT'; END IF;
END;
$m1_pin_transition$;





DO $phase6_m1_prerequisites$
BEGIN
  IF to_regclass('public.training_solver_provenance_authority') IS NULL
     OR to_regclass('public.training_solver_ingest_scopes') IS NULL
     OR to_regclass('public.training_solver_bounded_canary_targets') IS NULL
     OR to_regclass('public.solved_spots_gold') IS NULL
     OR NOT EXISTS (
       SELECT 1
       FROM pg_catalog.pg_attribute attribute_row
       WHERE attribute_row.attrelid =
         to_regclass('public.solved_spots_gold')
         AND attribute_row.attname = 'strategy_matrix_v2'
         AND attribute_row.attnum > 0
         AND NOT attribute_row.attisdropped
     ) THEN
    RAISE EXCEPTION 'TRAINING_SOLVER_M1_CANARY_PREREQUISITE_MISSING';
  END IF;
END;
$phase6_m1_prerequisites$;

DO $phase6_m1_target_identity$
BEGIN
  IF (
    SELECT count(*)
    FROM public.solved_spots_gold artifact
    WHERE artifact.id = '2d7b403c-e4d3-4c20-bff8-ed5db7ecb50a'::uuid
      AND artifact.scenario_hash = 'hu_cash_BTN_100bb_2c4c7c'
      AND artifact.street = 'flop'
      AND artifact.game_type = 'hu_cash'
      AND artifact.stack_depth = 100
      AND artifact.strategy_matrix_v2 ->> 'node' = 'r:0:c'
      AND artifact.strategy_matrix_v2 ->> 'position' = 'BTN'
  ) <> 1 THEN
    RAISE EXCEPTION 'TRAINING_SOLVER_M1_CANARY_PARENT_IDENTITY_MISMATCH';
  END IF;
  IF (
    SELECT count(*)
    FROM public.solved_spots_gold artifact
    WHERE artifact.id = '21d75135-faa8-4c0d-acbe-91b55c98daf0'::uuid
      AND artifact.scenario_hash = 'turn_hu_cash_BTN_100bb_2c4c7c2d'
      AND artifact.street = 'turn'
      AND artifact.game_type = 'hu_cash'
      AND artifact.stack_depth = 100
      AND artifact.strategy_matrix_v2 ->> 'node' = 'r:0:c:b412:c:2d:c'
      AND artifact.strategy_matrix_v2 ->> 'position' = 'BTN'
  ) <> 1 THEN
    RAISE EXCEPTION 'TRAINING_SOLVER_M1_CANARY_CHILD_IDENTITY_MISMATCH';
  END IF;
END;
$phase6_m1_target_identity$;

INSERT INTO public.training_solver_provenance_authority (
  machine_id, solver_version, solver_binary_checksum, pipeline_commit,
  manifest_version, manifest_checksum, source_combo_order_sha256,
  training_game_contracts_sha256, manifest_contracts, approved_by
) VALUES (
  'M1', 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)', 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb', '002cb37bbd89df86f4cc054fcf370f794b14f413', '5', '3115537d7169913cac08db6a40797af7b516e33d1e4faa8d51310704aaf58a25',
  '7d1e445d2a9fe34d416ea41adf7f2df2c4319c49141b389be5eb3d6cb2d9618a', '5dc75c9f5dad99b71ea7e84db4c4ced9acfb51078d2fdcd019b802509a94c4a3', '[{"accuracy_fraction":0.005,"eff_chips":9750,"game_type":"hu_cash","ip_player":"BTN","ip_range_checksum":"6255165643c516cc03605773a76bcd43f38ee63d50d4013e296df5e1f6c616cc","oop_player":"BB","oop_range_checksum":"9dbfd7dff86d7502e20acacc8a89d593342287a771acd00b99eca9e0b513148d","pot_chips":550,"rake":"0.05 10","range_combo_order":"card=rank*4+suit; combo=b*(b-1)/2+a; 2c2d=0..AhAs=1325","source_combo_order_sha256":"7d1e445d2a9fe34d416ea41adf7f2df2c4319c49141b389be5eb3d6cb2d9618a","stack_depth":100,"streets":["flop","turn"],"tree_geometry":"srp_parameterized_four_action_v3"}]'::jsonb, 'Smarter.Poker Phase 6 controller Pio 3.8 compatibility correction 2026-10-07'
);

INSERT INTO public.training_solver_bounded_canary_targets (
  machine_id, solver_version, solver_binary_checksum, pipeline_commit,
  manifest_version, manifest_checksum, target_role, artifact_id,
  scenario_hash, street, node, hero_position, approved_by
) VALUES
  ('M1', 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)', 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb', '002cb37bbd89df86f4cc054fcf370f794b14f413', '5', '3115537d7169913cac08db6a40797af7b516e33d1e4faa8d51310704aaf58a25', 'parent', '2d7b403c-e4d3-4c20-bff8-ed5db7ecb50a', 'hu_cash_BTN_100bb_2c4c7c', 'flop', 'r:0:c', 'BTN', 'Smarter.Poker Phase 6 controller Pio 3.8 compatibility correction 2026-10-07'),
  ('M1', 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)', 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb', '002cb37bbd89df86f4cc054fcf370f794b14f413', '5', '3115537d7169913cac08db6a40797af7b516e33d1e4faa8d51310704aaf58a25', 'child', '21d75135-faa8-4c0d-acbe-91b55c98daf0', 'turn_hu_cash_BTN_100bb_2c4c7c2d', 'turn', 'r:0:c:b412:c:2d:c', 'BTN', 'Smarter.Poker Phase 6 controller Pio 3.8 compatibility correction 2026-10-07');

DO $phase6_m1_single_active_scope$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.training_solver_ingest_scopes other_scope
    JOIN public.training_solver_provenance_authority other_authority
      USING (
        machine_id, solver_version, solver_binary_checksum, pipeline_commit,
        manifest_version, manifest_checksum
      )
    WHERE other_scope.machine_id = 'M1'
      AND other_scope.admission_mode IN ('backlog', 'bounded_canary')
      AND other_authority.retired_at IS NULL
      AND (
        other_scope.solver_version IS DISTINCT FROM 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)'
        OR other_scope.solver_binary_checksum IS DISTINCT FROM 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb'
        OR other_scope.pipeline_commit IS DISTINCT FROM '002cb37bbd89df86f4cc054fcf370f794b14f413'
        OR other_scope.manifest_version IS DISTINCT FROM '5'
        OR other_scope.manifest_checksum IS DISTINCT FROM '3115537d7169913cac08db6a40797af7b516e33d1e4faa8d51310704aaf58a25'
      )
  ) THEN
    RAISE EXCEPTION 'TRAINING_SOLVER_MACHINE_INGEST_SCOPE_ALREADY_ACTIVE';
  END IF;
END;
$phase6_m1_single_active_scope$;

UPDATE public.training_solver_ingest_scopes
SET admission_mode = 'bounded_canary',
    partition_count = 2,
    partition_index = 0,
    configured_at = clock_timestamp(),
    configured_by = 'Smarter.Poker Phase 6 controller Pio 3.8 compatibility correction 2026-10-07'
WHERE machine_id = 'M1'
    AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)'
    AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb'
    AND pipeline_commit = '002cb37bbd89df86f4cc054fcf370f794b14f413'
    AND manifest_version = '5'
    AND manifest_checksum = '3115537d7169913cac08db6a40797af7b516e33d1e4faa8d51310704aaf58a25'
  AND admission_mode = 'held';

DO $phase6_m1_activation_assertion$
BEGIN
  IF (SELECT count(*)
      FROM public.training_solver_ingest_scopes
      WHERE machine_id = 'M1'
    AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)'
    AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb'
    AND pipeline_commit = '002cb37bbd89df86f4cc054fcf370f794b14f413'
    AND manifest_version = '5'
    AND manifest_checksum = '3115537d7169913cac08db6a40797af7b516e33d1e4faa8d51310704aaf58a25'
        AND admission_mode = 'bounded_canary'
        AND partition_count = 2
        AND partition_index = 0) <> 1 THEN
    RAISE EXCEPTION 'M1 bounded canary approval did not activate exactly one scope';
  END IF;
END;
$phase6_m1_activation_assertion$;

COMMIT;

-- ROLLBACK / RECOVERY: execute only to hold NEW; old retirement is permanent.
-- BEGIN;
-- SELECT pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('training-solver-ingest-scope:M1', 0));
-- DO $m1_hold_new$
-- BEGIN
--  IF (SELECT count(*) FROM public.training_solver_provenance_authority WHERE machine_id = 'M1' AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)' AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb' AND pipeline_commit = '1ccf3907cf3298e24609eb6fbd903023d91dbddf' AND manifest_version = '5' AND manifest_checksum = 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8' AND retired_at IS NOT NULL) <> 1 THEN
--    RAISE EXCEPTION 'TRAINING_M1_OLD_PIN_RETIREMENT_REQUIRED';
--  END IF;
--  IF (SELECT count(*) FROM public.training_solver_ingest_scopes WHERE machine_id = 'M1' AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)' AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb' AND pipeline_commit = '002cb37bbd89df86f4cc054fcf370f794b14f413' AND manifest_version = '5' AND manifest_checksum = '3115537d7169913cac08db6a40797af7b516e33d1e4faa8d51310704aaf58a25') <> 1 THEN
--    RAISE EXCEPTION 'TRAINING_M1_NEW_PIN_REQUIRED';
--  END IF;
--  UPDATE public.training_solver_ingest_scopes SET admission_mode = 'held', partition_count = NULL, partition_index = NULL,
--  configured_at = clock_timestamp(), configured_by = 'phase6-hold-new-pin-only' WHERE machine_id = 'M1' AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)' AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb' AND pipeline_commit = '002cb37bbd89df86f4cc054fcf370f794b14f413' AND manifest_version = '5' AND manifest_checksum = '3115537d7169913cac08db6a40797af7b516e33d1e4faa8d51310704aaf58a25';
-- END;
-- $m1_hold_new$;
-- COMMIT;
