-- ═══════════════════════════════════════════════════════════════════════════
-- 2026-08-15 — sp_refresh_pending_families() was taking the poker platform
-- down. FIXED by removing the need for the scan entirely.
--
-- THE PROBLEM
--
-- pg_cron job 39 ran `select sp_refresh_pending_families()` every 10 minutes.
-- The function full-scans solved_spots_gold (62 GB, 8.1M rows) to count rows
-- where strategy_matrix_v2 IS NULL, grouped by (game_type, stack_depth), into
-- sp_pending_family_cache. It is a dashboard metric.
--
-- Over 24h: 144 runs, avg 53.1s, max 128.0s, and 69 of them FAILED.
-- While running, `select id from tables limit 1` took 12-25 SECONDS. The poker
-- engine's dealing loop hit its Supabase timeout and dealing stopped:
-- ZERO hands platform-wide 20:55-21:01 UTC.
--
-- WHY IT FAILED 48% OF THE TIME
--
-- Cluster statement_timeout is 120s (configuration file). The scan takes
-- 53-128s. It straddled the limit, so roughly half the runs were killed —
-- burning two minutes of database capacity to accomplish nothing.
--
-- WHY THE OBVIOUS FIX DID NOT WORK
--
-- The natural fix is a partial index on (game_type, stack_depth) WHERE
-- strategy_matrix_v2 IS NULL. (An index for this predicate already exists —
-- idx_ssg_v2_pending — but it leads with `street`, so it cannot serve the
-- GROUP BY and the planner sequentially scans every time.)
--
-- Building the correct index was attempted and THIS INSTANCE CANNOT DO IT.
-- CREATE INDEX CONCURRENTLY on a 62 GB table under production load caused a
-- POSTGRES SERVER RESTART. Do not retry it on this instance without first
-- sizing up or taking a real maintenance window.
--
-- THE FIX THAT SHIPPED
--
-- The counter is a pure aggregate over a predicate, so every change to it is
-- knowable at write time. Statement-level triggers with transition tables
-- maintain sp_pending_family_cache incrementally: one small GROUP BY over the
-- CHANGED rows per statement, instead of a scan of all 8.1M rows every 10
-- minutes. Bulk solver writes cost one aggregate over the batch.
--
--   sp_pending_family_apply_delta(jsonb)  -- applies a per-family delta
--   sp_pending_family_tg()                -- computes the delta, branches on TG_OP
--   sp_pending_family_ins / _upd / _del   -- statement-level triggers
--
-- The trigger is EXCEPTION-GUARDED. solved_spots_gold is on the GTO solver's
-- write path and a counter being briefly wrong is far preferable to blocking
-- solver writes. Drift is corrected by the reconciliation scan, which now runs
-- ONCE DAILY off-peak (09:17 UTC) instead of every 10 minutes, and which now
-- has a function-scoped 15-minute statement_timeout so it can no longer fail
-- against the cluster's 120s cap.
--
-- VERIFIED before shipping, in rolled-back transactions against the live table:
--   insert 3 rows (2 pending, 1 solved)      -> counter = 2      PASS
--   solve one spot                            -> counter = 2->2   PASS
--   bulk-solve remaining in one statement     -> family removed   PASS
--   re-open (set strategy_matrix_v2 = null)   -> counter = 2      PASS
--   delete pending rows                       -> family removed   PASS
--   no test rows or cache entries leaked                          PASS
--
-- RESULT: DB latency 25s -> 0.14s, engine liveness ok, 0 stalled tables,
-- hands flowing at 21-40/min with no gaps.
--
-- Applied live via Supabase migrations:
--   sp_pending_family_incremental_maintenance
--   sp_pending_family_tg_per_operation
--   select cron.alter_job(39, schedule => '17 9 * * *');
--   select cron.alter_job(1,  active   => false);  -- arena-log-archival-nightly
--                                                  -- called a function that has
--                                                  -- never existed
-- ═══════════════════════════════════════════════════════════════════════════

-- STILL WORTH DOING when there is capacity — the daily reconciliation scan
-- would become fast, and it is the safety net for the incremental counter:
--
--   create index concurrently if not exists idx_ssg_pending_family
--     on public.solved_spots_gold (game_type, stack_depth)
--     where strategy_matrix_v2 is null;
--
-- Must run OUTSIDE a transaction (so not via the Supabase SQL editor or MCP,
-- both of which wrap and roll back at their 60s timeout), and with
-- statement_timeout raised above the cluster's 120s. It also needs enough
-- instance headroom not to restart the server — see above.
--
-- A cancelled or collided build leaves an INVALID 0-byte stub which blocks
-- later attempts because CREATE INDEX IF NOT EXISTS matches on name:
--   select indisvalid from pg_index i join pg_class c on c.oid=i.indexrelid
--    where c.relname='idx_ssg_pending_family';
--   drop index if exists public.idx_ssg_pending_family;
