-- Index the multi-street lookup on solved_spots_gold.
--
-- WHY
-- ---
-- pages/api/training/next-street.js -> DeterministicGTOEngine.queryNextStreet
-- runs two queries shaped like:
--
--   game_type = ? AND stack_depth = ? AND street = ?
--   AND scenario_hash ILIKE '%<board>%'
--
-- scenario_hash is '{street}_{game_type}_{position}_{stack}bb_{board}', so the
-- board sits at the END of the string and the match needs a leading wildcard.
-- That makes idx_god_mode_hash (plain btree on scenario_hash) unusable, and a
-- prefix rewrite does not help either -- the column's collation is not C, so
-- LIKE 'turn_cash_%' is not accepted as an index condition (measured: the
-- planner ignored it and fell back to a bitmap scan of the 1.89M 'cash' rows).
--
-- The three existing single-column indexes are individually too weak, so the
-- planner chose a full sequential scan of all 8,053,212 rows / 59 GB:
--
--   Limit  (cost=1000.00..497566.86 rows=2 width=66)
--     ->  Gather
--           ->  Parallel Seq Scan on solved_spots_gold  (cost=0.00..496566.66)
--                 Filter: ((scenario_hash ~~* '%tc3sac%') AND (game_type = 'cash')
--                          AND (stack_depth = 100) AND (street = 'turn'))
--
-- Measured on production: one /api/training/next-street call took 17,361 ms,
-- against a worst case of 4,315 ms for every other /api/training/* endpoint.
-- That is the ~15-second dead table a player stares at between the flop and
-- the turn of a multi-street hand.
--
-- SELECTIVITY (from pg_stats)
-- ---------------------------
--   game_type='cash'   0.1513
--   stack_depth=100    0.0216
--   street='turn'      0.3913
--   product           ~0.00128  ->  ~10,300 candidate rows, a ~780x reduction.
--
-- scenario_hash is the trailing column so the ILIKE recheck is evaluated
-- against the index tuple rather than costing a heap fetch per candidate; only
-- the handful of rows that actually match pay to read the wide strategy_matrix.
--
-- RESULT (measured after the build)
-- ---------------------------------
-- Miss case (board not present):
--   Limit  (cost=0.56..11551.69 rows=1) (actual time=1.563..1.563 rows=0)
--     ->  Index Scan using idx_ssg_next_street on solved_spots_gold
--           Index Cond: (game_type='cash' AND stack_depth=100 AND street='turn')
--           Buffers: shared hit=1 read=3
--   Execution Time: 1.671 ms          (from 17,361 ms)
--
-- Hit case (game_type='6max_cash', stack_depth=100, street='turn',
-- scenario_hash ilike '%2h8s7c9c%'):
--   Index Only Scan using idx_ssg_next_street
--   Rows Removed by Filter: 2477, Heap Fetches: 2478
--   Execution Time: 379.021 ms        (from 17,361 ms)
--
-- The hit case is ~45x better but not as good as the miss case, and the reason
-- is visible in the plan: Heap Fetches equals the rows scanned, so the
-- visibility map has no all-visible bits for these pages yet. A VACUUM of the
-- table would turn this into a true index-only scan and take the remaining
-- ~380 ms with it. It is deliberately NOT done here -- vacuuming 59 GB is a
-- large I/O event that wants a quiet window, and 379 ms is already well inside
-- the arena's 450 ms dealing-indicator gate, so the player never sees it.
--
-- HOW THIS WAS APPLIED
-- --------------------
-- The Supabase MCP connection times out at 60s and rolls its transaction back,
-- which discarded a first in-band attempt at 28% of the table scan. The build
-- was therefore driven by a ONE-SHOT pg_cron job that ran it in a background
-- worker independent of the client session, guarded by pg_try_advisory_lock so
-- repeat firings were no-ops, and unscheduled the moment the index existed:
--
--   select cron.schedule('build_idx_ssg_next_street', '* * * * *', $job$ ... $job$);
--   -- poll pg_stat_progress_create_index
--   select cron.unschedule('build_idx_ssg_next_street');
--
-- READ THIS BEFORE COPYING THE ABOVE. As written it does not work, and it
-- fails SILENTLY -- it looks like a slow build rather than a broken one.
--
-- A pg_cron job inherits the role's statement_timeout, which is 120 seconds
-- here. A CREATE INDEX over 349,801 blocks takes far longer than that, so every
-- firing was killed at the two-minute mark and the next firing restarted the
-- scan FROM ZERO. Polling pg_stat_progress_create_index looks like progress
-- because each fresh attempt climbs again; the giveaway is that the block count
-- goes BACKWARDS between polls (observed: 160043, then 56107). The truth is in
-- cron.job_run_details, which had seven consecutive
-- "canceling statement due to statement timeout" rows, each exactly ~2 minutes
-- long. This thrashed for ~15 minutes and made zero net progress while burning
-- continuous I/O.
--
-- The job body must therefore raise its own limits before the DDL:
--
--   select set_config('statement_timeout','0',false),
--          set_config('lock_timeout','0',false),
--          set_config('idle_in_transaction_session_timeout','0',false),
--          set_config('maintenance_work_mem','1GB',false);
--   -- then the pg_try_advisory_lock-guarded DO block containing CREATE INDEX
--
-- With that prefix the build ran to completion in one firing: 593 MB.
-- Cleanup is cron.unschedule plus pg_cancel_backend on any workers left over
-- from the killed attempts (they do not always exit with the job).
--
-- This is NOT a standing pg_cron job and does not conflict with CLAUDE.md
-- section 11 (which governs scheduled APPLICATION triggers, all of which go
-- through Open Claw). It was scaffolding for a single DDL build and no longer
-- exists -- verified with
-- `select jobid, jobname from cron.job where jobname like '%idx_ssg%'` -> [].
-- This file is the auditable record of the resulting schema.
CREATE INDEX IF NOT EXISTS idx_ssg_next_street
    ON public.solved_spots_gold (game_type, stack_depth, street, scenario_hash);
