-- VENUES SQL (53 unique venues from PokerAtlas)
INSERT INTO poker_venues (name, city, state, venue_type, is_featured, trust_score, is_active)
VALUES
('Venetian Las Vegas', 'Las Vegas', 'NV', 'card_room', false, 4.0, true),
('Borgata Hotel Casino & Spa', 'Atlantic City', 'NJ', 'casino', false, 4.0, true),
('FireKeepers Casino', 'Battle Creek', 'MI', 'casino', false, 4.0, true),
('Viking Social Poker Club', 'Steubenville', 'OH', 'poker_club', false, 4.0, true),
('Silverado Franklin Casino', 'Deadwood', 'SD', 'casino', false, 4.0, true),
('Wynn Las Vegas', 'Las Vegas', 'NV', 'card_room', false, 4.0, true),
('Seminole Hard Rock Hollywood', 'Ft. Lauderdale', 'FL', 'casino', false, 4.0, true),
('Commerce Casino', 'Los Angeles', 'CA', 'casino', false, 4.0, true),
('Choctaw Casino Durant', 'Durant', 'OK', 'casino', false, 4.0, true),
('Beau Rivage Resort & Casino', 'Biloxi', 'MS', 'casino', false, 4.0, true),
('Sycuan Casino', 'El Cajon', 'CA', 'casino', false, 4.0, true),
('Thunder Valley Casino', 'Lincoln', 'CA', 'casino', false, 4.0, true),
('House of Kings Card Club', 'El Paso', 'TX', 'poker_club', false, 4.0, true),
('Bally''s Black Hawk Casino', 'Black Hawk', 'CO', 'casino', false, 4.0, true),
('Orange City Racing & Card Club', 'Orange City', 'FL', 'poker_club', false, 4.0, true),
('Texas Card House Houston', 'Houston', 'TX', 'card_room', false, 4.0, true),
('Live! Casino Philadelphia', 'Philadelphia', 'PA', 'casino', false, 4.0, true),
('TGT Poker & Racebook', 'Tampa', 'FL', 'card_room', false, 4.0, true),
('Lodge Card Club Austin', 'Round Rock', 'TX', 'poker_club', false, 4.0, true),
('Maryland Live! Casino at Arundel Mills', 'Hanover', 'MD', 'casino', false, 4.0, true),
('Harrah''s Pompano Beach', 'Pompano Beach', 'FL', 'casino', false, 4.0, true),
('Hard Rock Tulsa', 'Catoosa', 'OK', 'casino', false, 4.0, true),
('Seminole Hard Rock Tampa', 'Tampa', 'FL', 'casino', false, 4.0, true),
('Running Aces Casino & Racetrack', 'Forest Lake', 'MN', 'casino', false, 4.0, true),
('Hard Rock Hotel & Casino Bristol', 'Bristol', 'VA', 'casino', false, 4.0, true),
('Horseshoe Casino Tunica', 'Robinsonville', 'MS', 'casino', false, 4.0, true),
('Portland Meadows', 'Portland', 'OR', 'card_room', false, 4.0, true),
('Hard Rock Casino Cincinnati', 'Cincinnati', 'OH', 'casino', false, 4.0, true),
('Talking Stick Resort', 'Scottsdale', 'AZ', 'casino', false, 4.0, true),
('Aria Casino', 'Las Vegas', 'NV', 'casino', false, 4.0, true),
('Daytona Beach Racing and Card Club', 'Daytona Beach', 'FL', 'poker_club', false, 4.0, true),
('Caesars Virginia', 'Danville', 'VA', 'card_room', false, 4.0, true),
('Canterbury Park', 'Shakopee', 'MN', 'card_room', false, 4.0, true),
('Champions Club', 'Houston', 'TX', 'poker_club', false, 4.0, true),
('bestbet Jacksonville', 'Jacksonville', 'FL', 'card_room', false, 4.0, true),
('Mohegan Sun', 'Uncasville', 'CT', 'card_room', false, 4.0, true),
('JACK Cleveland Casino', 'Cleveland', 'OH', 'casino', false, 4.0, true),
('MGM National Harbor', 'Oxon Hill', 'MD', 'card_room', false, 4.0, true),
('Harrah''s Cherokee', 'Cherokee', 'NC', 'casino', false, 4.0, true),
('Potawatomi Hotel & Casino', 'Milwaukee', 'WI', 'casino', false, 4.0, true),
('Downstream Casino', 'Quapaw', 'OK', 'casino', false, 4.0, true),
('Horseshoe Baltimore', 'Baltimore', 'MD', 'casino', false, 4.0, true),
('Bay 101 Casino', 'San Jose', 'CA', 'casino', false, 4.0, true),
('Horseshoe Casino Hammond', 'Hammond', 'IN', 'casino', false, 4.0, true),
('Grand Falls Casino Resort', 'Larchwood', 'IA', 'casino', false, 4.0, true),
('Turning Stone Casino', 'Verona', 'NY', 'casino', false, 4.0, true),
('Riverside Casino', 'Riverside', 'IA', 'casino', false, 4.0, true),
('Horseshoe Las Vegas', 'Las Vegas', 'NV', 'casino', false, 4.0, true),
('One-Eyed Jacks', 'Sarasota', 'FL', 'card_room', false, 4.0, true),
('Grand Victoria Casino', 'Elgin', 'IL', 'casino', false, 4.0, true),
('Caesars Republic Lake Tahoe', 'Stateline', 'NV', 'card_room', false, 4.0, true),
('South Point Casino', 'Las Vegas', 'NV', 'casino', false, 4.0, true),
('Caesars New Orleans', 'New Orleans', 'LA', 'card_room', false, 4.0, true)
ON CONFLICT (name, city, state) DO NOTHING;

