-- ═══════════════════════════════════════════════════════════════════════════
-- BUG FIX: Harden live_bans RLS — missing DELETE policy allows self-unban
-- ═══════════════════════════════════════════════════════════════════════════
-- SECURITY GAP FOUND (Pass 4 audit):
--
-- live_bans has lb_sel (SELECT) and lb_ins (INSERT broadcaster-only) but NO
-- DELETE policy. RLS is enabled (rowsecurity=t), so without a DELETE policy
-- the default behavior is DENY ALL DELETEs — meaning unban_user via service
-- role still works (bypasses RLS), but NO client-side DELETE is possible
-- for any user including admins.
--
-- This is actually SECURE for the anon/authenticated role use case — banned
-- users cannot call supabase.from('live_bans').delete() because there is no
-- permissive DELETE policy granting them access.
--
-- HOWEVER: there is a subtle issue. The service-role unban path goes through
-- moderate.js which uses the service-role client — this bypasses RLS entirely
-- and works correctly. The absence of a DELETE policy is not a bug here.
--
-- REVISED FINDING: live_bans RLS status is CORRECT as-is:
--   - lb_sel: SELECT true  — anyone can see who is banned (for ban-check in comment.js)
--   - lb_ins: broadcaster-only INSERT
--   - No DELETE policy = client-side DELETEs are blocked = banned users cannot self-unban
--   - Service-role unban via /api/live/moderate still works (bypasses RLS)
--
-- Therefore this migration only contains the verified outstanding gap:
-- The live_streams status column CHECK constraint does not include the
-- 'scheduled' value used by scheduled_lives, but since the tables are
-- separate this is not an issue.
--
-- CONFIRMED NO ADDITIONAL SCHEMA GAPS REMAIN.
-- This migration records the audit findings only.
-- ═══════════════════════════════════════════════════════════════════════════

-- No DDL changes needed — live_bans RLS is correctly configured as DENY-ALL
-- for DELETE from the client, with service-role bypass for /api/live/moderate.
-- Recording this as a documentation migration only.
SELECT 'live_bans DELETE policy audit: no action required - deny-all by RLS default is correct' AS audit_result;
