-- =====================================================================
-- 20260930182000_activate_training_solver_m1_bounded_canary.sql
-- =====================================================================
-- TIER:        2
-- AUTHOR:      Smarter.Poker Phase 6 controller
-- AFFECTS:     training_solver_provenance_authority,
--              training_solver_bounded_canary_targets,
--              training_solver_ingest_scopes (DML only)
-- IRREVERSIBLE: no
--
-- WHY:
--   Install the exact reviewed M1 authority tuple and two reserved warehouse
--   identities required by the cash-002 continuation cohort. Evidence and the
--   literal contract live in the dated Phase 6 M1 bounded-canary audit files.
--
-- HOW (high level):
--   - Fail closed unless prerequisite objects and exact target identities exist.
--   - Insert one checksum-sealed authority and exactly two canary targets.
--   - Move only the exact M1 tuple from held to bounded_canary for partition 2/0.
--   - Assert that exactly one bounded scope is active before commit.
-- =====================================================================
-- Generated by build_m1_bounded_canary.py from one reviewed packet.
-- Literal M1 held -> target install -> bounded-canary activation only.
BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';

DO $phase6_m1_prerequisites$
BEGIN
  IF to_regclass('public.training_solver_provenance_authority') IS NULL
     OR to_regclass('public.training_solver_ingest_scopes') IS NULL
     OR to_regclass('public.training_solver_bounded_canary_targets') IS NULL
     OR to_regclass('public.solved_spots_gold') IS NULL
     OR NOT EXISTS (
       SELECT 1
       FROM pg_catalog.pg_attribute attribute_row
       WHERE attribute_row.attrelid =
         to_regclass('public.solved_spots_gold')
         AND attribute_row.attname = 'strategy_matrix_v2'
         AND attribute_row.attnum > 0
         AND NOT attribute_row.attisdropped
     ) THEN
    RAISE EXCEPTION 'TRAINING_SOLVER_M1_CANARY_PREREQUISITE_MISSING';
  END IF;
END;
$phase6_m1_prerequisites$;

DO $phase6_m1_target_identity$
BEGIN
  IF (
    SELECT count(*)
    FROM public.solved_spots_gold artifact
    WHERE artifact.id = '2d7b403c-e4d3-4c20-bff8-ed5db7ecb50a'::uuid
      AND artifact.scenario_hash = 'hu_cash_BTN_100bb_2c4c7c'
      AND artifact.street = 'flop'
      AND artifact.game_type = 'hu_cash'
      AND artifact.stack_depth = 100
      AND artifact.strategy_matrix_v2 ->> 'node' = 'r:0:c'
      AND artifact.strategy_matrix_v2 ->> 'position' = 'BTN'
  ) <> 1 THEN
    RAISE EXCEPTION 'TRAINING_SOLVER_M1_CANARY_PARENT_IDENTITY_MISMATCH';
  END IF;
  IF (
    SELECT count(*)
    FROM public.solved_spots_gold artifact
    WHERE artifact.id = '21d75135-faa8-4c0d-acbe-91b55c98daf0'::uuid
      AND artifact.scenario_hash = 'turn_hu_cash_BTN_100bb_2c4c7c2d'
      AND artifact.street = 'turn'
      AND artifact.game_type = 'hu_cash'
      AND artifact.stack_depth = 100
      AND artifact.strategy_matrix_v2 ->> 'node' = 'r:0:c:b412:c:2d:c'
      AND artifact.strategy_matrix_v2 ->> 'position' = 'BTN'
  ) <> 1 THEN
    RAISE EXCEPTION 'TRAINING_SOLVER_M1_CANARY_CHILD_IDENTITY_MISMATCH';
  END IF;
END;
$phase6_m1_target_identity$;

INSERT INTO public.training_solver_provenance_authority (
  machine_id, solver_version, solver_binary_checksum, pipeline_commit,
  manifest_version, manifest_checksum, source_combo_order_sha256,
  training_game_contracts_sha256, manifest_contracts, approved_by
) VALUES (
  'M1', 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)', 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb', '1ccf3907cf3298e24609eb6fbd903023d91dbddf', '5', 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8',
  '7d1e445d2a9fe34d416ea41adf7f2df2c4319c49141b389be5eb3d6cb2d9618a', '5dc75c9f5dad99b71ea7e84db4c4ced9acfb51078d2fdcd019b802509a94c4a3', '[{"accuracy_fraction":0.005,"eff_chips":9750,"game_type":"hu_cash","ip_player":"BTN","ip_range_checksum":"6255165643c516cc03605773a76bcd43f38ee63d50d4013e296df5e1f6c616cc","oop_player":"BB","oop_range_checksum":"9dbfd7dff86d7502e20acacc8a89d593342287a771acd00b99eca9e0b513148d","pot_chips":550,"rake":"0.05 10","range_combo_order":"card=rank*4+suit; combo=b*(b-1)/2+a; 2c2d=0..AhAs=1325","source_combo_order_sha256":"7d1e445d2a9fe34d416ea41adf7f2df2c4319c49141b389be5eb3d6cb2d9618a","stack_depth":100,"streets":["flop","turn"],"tree_geometry":"srp_parameterized_four_action_v3"}]'::jsonb, 'Smarter.Poker Phase 6 controller decision 2026-09-30'
);

INSERT INTO public.training_solver_bounded_canary_targets (
  machine_id, solver_version, solver_binary_checksum, pipeline_commit,
  manifest_version, manifest_checksum, target_role, artifact_id,
  scenario_hash, street, node, hero_position, approved_by
) VALUES
  ('M1', 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)', 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb', '1ccf3907cf3298e24609eb6fbd903023d91dbddf', '5', 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8', 'parent', '2d7b403c-e4d3-4c20-bff8-ed5db7ecb50a', 'hu_cash_BTN_100bb_2c4c7c', 'flop', 'r:0:c', 'BTN', 'Smarter.Poker Phase 6 controller decision 2026-09-30'),
  ('M1', 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)', 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb', '1ccf3907cf3298e24609eb6fbd903023d91dbddf', '5', 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8', 'child', '21d75135-faa8-4c0d-acbe-91b55c98daf0', 'turn_hu_cash_BTN_100bb_2c4c7c2d', 'turn', 'r:0:c:b412:c:2d:c', 'BTN', 'Smarter.Poker Phase 6 controller decision 2026-09-30');

DO $phase6_m1_single_active_scope$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.training_solver_ingest_scopes other_scope
    JOIN public.training_solver_provenance_authority other_authority
      USING (
        machine_id, solver_version, solver_binary_checksum, pipeline_commit,
        manifest_version, manifest_checksum
      )
    WHERE other_scope.machine_id = 'M1'
      AND other_scope.admission_mode IN ('backlog', 'bounded_canary')
      AND other_authority.retired_at IS NULL
      AND (
        other_scope.solver_version IS DISTINCT FROM 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)'
        OR other_scope.solver_binary_checksum IS DISTINCT FROM 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb'
        OR other_scope.pipeline_commit IS DISTINCT FROM '1ccf3907cf3298e24609eb6fbd903023d91dbddf'
        OR other_scope.manifest_version IS DISTINCT FROM '5'
        OR other_scope.manifest_checksum IS DISTINCT FROM 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8'
      )
  ) THEN
    RAISE EXCEPTION 'TRAINING_SOLVER_MACHINE_INGEST_SCOPE_ALREADY_ACTIVE';
  END IF;
END;
$phase6_m1_single_active_scope$;

UPDATE public.training_solver_ingest_scopes
SET admission_mode = 'bounded_canary',
    partition_count = 2,
    partition_index = 0,
    configured_at = clock_timestamp(),
    configured_by = 'Smarter.Poker Phase 6 controller decision 2026-09-30'
WHERE machine_id = 'M1'
    AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)'
    AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb'
    AND pipeline_commit = '1ccf3907cf3298e24609eb6fbd903023d91dbddf'
    AND manifest_version = '5'
    AND manifest_checksum = 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8'
  AND admission_mode = 'held';

DO $phase6_m1_activation_assertion$
BEGIN
  IF (SELECT count(*)
      FROM public.training_solver_ingest_scopes
      WHERE machine_id = 'M1'
    AND solver_version = 'PioSOLVER-pro 3.8.0 (Sep 22 2025, 11:05:45)'
    AND solver_binary_checksum = 'e21ea7ad1dbc2a9d826c25ac264688f632dd461b92de2bc35a53f6b78bcf5ceb'
    AND pipeline_commit = '1ccf3907cf3298e24609eb6fbd903023d91dbddf'
    AND manifest_version = '5'
    AND manifest_checksum = 'b27ad1f3575e106d7d7f73bb4655e94398955a1275ae1fea9b3af7f574dbece8'
        AND admission_mode = 'bounded_canary'
        AND partition_count = 2
        AND partition_index = 0) <> 1 THEN
    RAISE EXCEPTION 'M1 bounded canary approval did not activate exactly one scope';
  END IF;
END;
$phase6_m1_activation_assertion$;

COMMIT;
