-- 1. Add the new column (added directly to production earlier, making it idempotent)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS use_avatar_as_profile_pic BOOLEAN DEFAULT false;

-- 2. Grant SELECT privileges to anon and authenticated for the new column (and arena_avatar_url)
GRANT SELECT (use_avatar_as_profile_pic, arena_avatar_url) ON public.profiles TO anon, authenticated;

-- 3. Grant UPDATE to authenticated so users can actually toggle it
GRANT UPDATE (use_avatar_as_profile_pic) ON public.profiles TO authenticated;

-- 4. Restore anon SELECT privileges for all SAFE_PROFILE_COLUMNS (in case column-level REVOKE wiped table-level SELECT)
GRANT SELECT (id, full_name, display_name, first_name, last_name, username, bio, city, state, alias, avatar_url, role, status, is_vip, is_horse, is_admin, is_online, player_number, diamonds, diamond_balance, diamond_multiplier, level, tier, skill_tier, login_streak, streak_days, settings, preferences, social_page_id, favorite_venue, home_poker_club, referred_by, friends_count, hendon_total_cashes, hendon_total_earnings, email_verified, phone_verified, onboarding_complete, last_login, last_login_date, last_seen, created_at, updated_at, training_view_mode, last_trivia_date, trivia_streak, trivia_high_score, total_hands_played, notification_token, referral_code, horse_status, horse_profile, sounds_enabled, vibrations_enabled, show_stack_bb, birth_year, favorite_hand_type, card_back_preference, country, website, twitter, instagram, hendon_url, favorite_game, favorite_hand, home_casino, cover_photo_url, favorite_hand_plo, app_settings, display_name_preference, cover_photo_position, tiktok, telegram, birthday, hendon_biggest_cash, use_real_name, streak_count, access_tier, vip_tier, vip_expires_at, last_active, poker_near_me_preferences, can_review, deleted_reviews_count, kyc_status, kyc_provider, kyc_inquiry_id, kyc_completed_at, kyc_rejection_reason, age_verified, age_verified_at, jurisdiction_country, mfa_required, hub_preferences, friend_preferences, store_preferences, messenger_preferences, reels_preferences, over_18_attested_at, jurisdiction_region, jurisdiction_acknowledged_at, home_games_onboarded_at, social_profile_completed) ON public.profiles TO anon;
