-- ═══════════════════════════════════════════════════════════════════════════
-- SMARTER.POKER — COMBINED PENDING MIGRATIONS
-- Generated: 2026-03-08 (Phase 14)
-- ═══════════════════════════════════════════════════════════════════════════
-- Run this in Supabase SQL Editor:
--   Dashboard → SQL Editor → + New query → paste → Run
--
-- These migrations cover Phases 9-13:
--   • Performance indexes and RPCs
--   • Grinder settings
--   • Multi-day tournaments  
--   • Sandbox quiz / bookmarks
--   • Daily challenge
--   • Sandbox enhancement suite
--   • BBJ config + union leave requests
--   • Diamond arena events
--   • Realtime publication on all 70+ tables
--   • Geeves missed questions
--   • Hand ID tracking
--   • Hierarchy gaps (union → club → agent → player)
--   • Sandbox wave 2 tables
--   • Union applications
--   • Union wallets + rakeback_periods realtime
-- ═══════════════════════════════════════════════════════════════════════════



-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260305213232_perf_indexes_and_rpcs.sql
-- ════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- PERFORMANCE MIGRATION: Indexes + Atomic Counter RPCs
-- Generated by optimization audit — Phase 4
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Atomic counter RPCs ───────────────────────────────────────────────────
-- Replaces read-then-update N+1 patterns for likes/comments/shares

CREATE OR REPLACE FUNCTION increment_post_count(p_post_id UUID, p_field TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF p_field = 'like_count' THEN
    UPDATE social_posts SET like_count = like_count + 1 WHERE id = p_post_id;
  ELSIF p_field = 'comment_count' THEN
    UPDATE social_posts SET comment_count = comment_count + 1 WHERE id = p_post_id;
  ELSIF p_field = 'share_count' THEN
    UPDATE social_posts SET share_count = share_count + 1 WHERE id = p_post_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION decrement_post_count(p_post_id UUID, p_field TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF p_field = 'like_count' THEN
    UPDATE social_posts SET like_count = GREATEST(like_count - 1, 0) WHERE id = p_post_id;
  ELSIF p_field = 'comment_count' THEN
    UPDATE social_posts SET comment_count = GREATEST(comment_count - 1, 0) WHERE id = p_post_id;
  ELSIF p_field = 'share_count' THEN
    UPDATE social_posts SET share_count = GREATEST(share_count - 1, 0) WHERE id = p_post_id;
  END IF;
END;
$$;

-- ── social_posts indexes ──────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_social_posts_user_id
  ON social_posts(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_posts_created_at
  ON social_posts(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_posts_club_page
  ON social_posts(club_page_id, created_at DESC)
  WHERE club_page_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_social_posts_post_type
  ON social_posts(post_type, created_at DESC)
  WHERE post_type IS NOT NULL;

-- ── social_interactions indexes ───────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_social_interactions_post_user
  ON social_interactions(post_id, user_id, interaction_type);

CREATE INDEX IF NOT EXISTS idx_social_interactions_user
  ON social_interactions(user_id, created_at DESC);

-- ── social_comments indexes ───────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_social_comments_post_id
  ON social_comments(post_id, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_social_comments_user_id
  ON social_comments(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_comments_parent
  ON social_comments(parent_id)
  WHERE parent_id IS NOT NULL;

-- ── profiles indexes ──────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_profiles_username
  ON profiles(username)
  WHERE username IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_profiles_updated_at
  ON profiles(updated_at DESC);

-- ── notifications indexes ─────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
  ON notifications(user_id, is_read, created_at DESC)
  WHERE is_read = false;

CREATE INDEX IF NOT EXISTS idx_notifications_user_all
  ON notifications(user_id, created_at DESC);

-- ── commander_sessions indexes ────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_commander_sessions_venue_date
  ON commander_sessions(venue_id, session_date DESC);

CREATE INDEX IF NOT EXISTS idx_commander_sessions_active
  ON commander_sessions(venue_id, is_active)
  WHERE is_active = true;

-- ── club_arena indexes ────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_club_memberships_user
  ON club_memberships(user_id, status);

CREATE INDEX IF NOT EXISTS idx_club_memberships_club
  ON club_memberships(club_id, status);

CREATE INDEX IF NOT EXISTS idx_chip_transactions_user
  ON chip_transactions(user_id, created_at DESC)
  WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_chip_transactions_club
  ON chip_transactions(club_id, created_at DESC);

-- ── bankroll indexes ──────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_bankroll_sessions_user
  ON bankroll_sessions(user_id, played_at DESC);

CREATE INDEX IF NOT EXISTS idx_bankroll_sessions_user_year
  ON bankroll_sessions(user_id, EXTRACT(YEAR FROM played_at));

-- ── stories indexes ───────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_stories_user_active
  ON stories(user_id, expires_at)
  WHERE expires_at > NOW();

CREATE INDEX IF NOT EXISTS idx_stories_expires
  ON stories(expires_at)
  WHERE expires_at IS NOT NULL;



-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260306_add_grinder_settings.sql
-- ════════════════════════════════════════════════════════════════════════

-- Add Grinder Settings configuration to the content_settings table
ALTER TABLE content_settings 
ADD COLUMN IF NOT EXISTS grinder_max_tables integer DEFAULT 4,
ADD COLUMN IF NOT EXISTS grinder_daily_hours integer DEFAULT 16,
ADD COLUMN IF NOT EXISTS grinder_starting_chips integer DEFAULT 10000,
ADD COLUMN IF NOT EXISTS grinder_ai_model text DEFAULT 'gpt-4o';


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260307_multi_day_tournaments.sql
-- ════════════════════════════════════════════════════════════════════════

-- =====================================================
-- MULTI-DAY TOURNAMENT FLIGHTS SCHEMA
-- =====================================================
-- Adds multi-day flight support to commander_tournaments
-- Enables: Day 1A/1B/1C flights, bag-and-tag chip counts,
-- parent-child tournament linking, and resume scheduling
-- =====================================================

-- Multi-day flag and day tracking
ALTER TABLE commander_tournaments
  ADD COLUMN IF NOT EXISTS is_multi_day BOOLEAN DEFAULT false;

ALTER TABLE commander_tournaments
  ADD COLUMN IF NOT EXISTS total_days INTEGER DEFAULT 1;

ALTER TABLE commander_tournaments
  ADD COLUMN IF NOT EXISTS current_day INTEGER DEFAULT 1;

-- Flight label (e.g., 'Day 1A', 'Day 1B', 'Day 2 Final')
ALTER TABLE commander_tournaments
  ADD COLUMN IF NOT EXISTS flight_label TEXT;

-- Parent tournament link: child flights reference the parent event
ALTER TABLE commander_tournaments
  ADD COLUMN IF NOT EXISTS parent_tournament_id UUID REFERENCES commander_tournaments(id) ON DELETE SET NULL;

-- Bag-and-tag: end-of-day chip counts stored as JSONB array
-- Format: [{ entry_id, player_name, chip_count, table_number, seat_number, bagged_at }]
ALTER TABLE commander_tournaments
  ADD COLUMN IF NOT EXISTS day_end_chip_counts JSONB DEFAULT '[]';

-- Resume time: when the next day/flight is scheduled to start
ALTER TABLE commander_tournaments
  ADD COLUMN IF NOT EXISTS resume_time TIMESTAMPTZ;

-- Index for parent tournament lookups (flights under a parent)
CREATE INDEX IF NOT EXISTS idx_commander_tournaments_parent
  ON commander_tournaments(parent_tournament_id) WHERE parent_tournament_id IS NOT NULL;

-- Add 'bagged' to tournament entry status for end-of-day
-- (players who bagged chips for the next day)
ALTER TABLE commander_tournament_entries
  DROP CONSTRAINT IF EXISTS commander_tournament_entries_status_check;

ALTER TABLE commander_tournament_entries
  ADD CONSTRAINT commander_tournament_entries_status_check
  CHECK (status IN ('registered', 'seated', 'active', 'eliminated', 'winner', 'bagged'));

-- Tournament reminder tracking table
CREATE TABLE IF NOT EXISTS tournament_reminders_sent (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tournament_id UUID NOT NULL,
  user_id UUID NOT NULL,
  reminder_type TEXT NOT NULL CHECK (reminder_type IN ('24h', '1h', 'flight_resume', 'starting_now')),
  sent_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(tournament_id, user_id, reminder_type)
);

ALTER TABLE tournament_reminders_sent ENABLE ROW LEVEL SECURITY;

CREATE POLICY reminders_select ON tournament_reminders_sent
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY reminders_insert ON tournament_reminders_sent
  FOR INSERT WITH CHECK (true);

-- Add to realtime publication for live updates
ALTER PUBLICATION supabase_realtime ADD TABLE tournament_reminders_sent;


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260307_sandbox_quiz_weekly_bookmarks.sql
-- ════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Migration: Create 3 missing tables for Sandbox Quiz + Weekly Spots + GTO Bookmarks
-- Date: March 7, 2026
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. sandbox_quiz_results — "What Would You Do?" quiz answers for leaderboard
CREATE TABLE IF NOT EXISTS sandbox_quiz_results (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    scenario_hash TEXT NOT NULL,
    user_action TEXT NOT NULL,
    correct_action TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sandbox_quiz_results_user ON sandbox_quiz_results(user_id);
CREATE INDEX IF NOT EXISTS idx_sandbox_quiz_results_created ON sandbox_quiz_results(created_at DESC);

ALTER TABLE sandbox_quiz_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own quiz results" ON sandbox_quiz_results
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can read own quiz results" ON sandbox_quiz_results
    FOR SELECT USING (auth.uid() = user_id);

-- Service role can read all for leaderboard aggregation
CREATE POLICY "Service role reads all quiz results" ON sandbox_quiz_results
    FOR SELECT USING (auth.role() = 'service_role');


-- 2. sandbox_weekly_spots — Admin-curated weekly challenge scenarios
CREATE TABLE IF NOT EXISTS sandbox_weekly_spots (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    week_start DATE NOT NULL,
    scenario_json JSONB NOT NULL,
    correct_action TEXT,
    description TEXT,
    difficulty TEXT DEFAULT 'intermediate',
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sandbox_weekly_spots_week ON sandbox_weekly_spots(week_start DESC);

ALTER TABLE sandbox_weekly_spots ENABLE ROW LEVEL SECURITY;

-- Everyone can read weekly spots (public content)
CREATE POLICY "Public read weekly spots" ON sandbox_weekly_spots
    FOR SELECT USING (true);

-- Only service role can manage weekly spots
CREATE POLICY "Service role manages weekly spots" ON sandbox_weekly_spots
    FOR ALL USING (auth.role() = 'service_role');


-- 3. solution_bookmarks — GTO Solutions bookmarks
CREATE TABLE IF NOT EXISTS solution_bookmarks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    spot_id TEXT,
    scenario_hash TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_solution_bookmarks_user ON solution_bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_solution_bookmarks_hash ON solution_bookmarks(user_id, scenario_hash);

ALTER TABLE solution_bookmarks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own bookmarks" ON solution_bookmarks
    FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Service role manages all bookmarks" ON solution_bookmarks
    FOR ALL USING (auth.role() = 'service_role');


-- ═══════════════════════════════════════════════════════════════════════════
-- Verification: Count tables to confirm creation
-- ═══════════════════════════════════════════════════════════════════════════
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'public'
AND table_name IN ('sandbox_quiz_results', 'sandbox_weekly_spots', 'solution_bookmarks');


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260308094344_daily_challenge.sql
-- ════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Phase 24: Daily GTO Challenge Tables
-- training_questions: Pool of solver-verified GTO spots for daily selection
-- training_daily_challenge: Records per-user daily challenge completions
-- ═══════════════════════════════════════════════════════════════════════════

-- 1) training_questions — GTO question pool for hand-of-the-day
CREATE TABLE IF NOT EXISTS training_questions (
    id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    scenario_text   TEXT NOT NULL DEFAULT 'What is the GTO play?',
    hero_hand       TEXT,
    hero_position   TEXT,
    board_cards     JSONB DEFAULT '[]'::jsonb,
    street          TEXT DEFAULT 'flop',
    correct_answer  TEXT NOT NULL DEFAULT 'Call',
    options         JSONB DEFAULT '["Fold","Call","Raise","All-In"]'::jsonb,
    gto_action      TEXT,
    gto_explanation TEXT,
    action_breakdown JSONB,
    gto_frequencies  JSONB,
    difficulty      INTEGER DEFAULT 1,
    game_type       TEXT DEFAULT 'cash',
    stack_depth     INTEGER DEFAULT 100,
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- 2) training_daily_challenge — user completion records
CREATE TABLE IF NOT EXISTS training_daily_challenge (
    id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id         UUID NOT NULL,
    daily_id        TEXT NOT NULL,
    score           INTEGER DEFAULT 0,
    ev_loss         REAL DEFAULT 0,
    completed_at    TIMESTAMPTZ DEFAULT now(),
    UNIQUE(user_id, daily_id)
);

-- Enable RLS
ALTER TABLE training_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE training_daily_challenge ENABLE ROW LEVEL SECURITY;

-- RLS for training_questions: anyone can read
CREATE POLICY "Anyone can read training_questions" ON training_questions
    FOR SELECT USING (true);

-- RLS for training_daily_challenge: users manage their own records
CREATE POLICY "Users manage own daily challenge" ON training_daily_challenge
    FOR ALL USING (true);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_daily_challenge_user ON training_daily_challenge(user_id);
CREATE INDEX IF NOT EXISTS idx_daily_challenge_daily_id ON training_daily_challenge(daily_id);
CREATE INDEX IF NOT EXISTS idx_training_questions_game ON training_questions(game_type);

-- Seed 20 starter questions for the daily challenge pool
INSERT INTO training_questions (scenario_text, hero_hand, hero_position, board_cards, street, correct_answer, options, gto_action, gto_explanation, action_breakdown, difficulty, game_type, stack_depth) VALUES
('Hero opens BTN, BB 3-bets. Board: Ks 9h 4d. BB checks. What is the GTO play?', 'AQo', 'BTN', '["Ks","9h","4d"]', 'flop', 'Bet 33%', '["Check","Bet 33%","Bet 75%","All-In"]', 'Bet 33%', 'With overcards and a backdoor straight draw, a small c-bet is preferred at high frequency to maintain aggression and deny equity.', '{"Check": 22, "Bet 33%": 55, "Bet 75%": 18, "All-In": 5}', 2, 'cash', 100),
('Hero in BB facing a CO open. Board: 7s 6s 2h. CO bets 33%. What is the GTO play?', 'Ts9s', 'BB', '["7s","6s","2h"]', 'flop', 'Call', '["Fold","Call","Raise","All-In"]', 'Call', 'With a flush draw and open-ended straight draw, calling is the highest frequency play. We have excellent implied odds and equity to continue.', '{"Fold": 5, "Call": 68, "Raise": 24, "All-In": 3}', 2, 'cash', 100),
('SB vs BB single raised pot. Board: Ah Kd 3c. SB (hero) to act. What is the GTO play?', 'QJo', 'SB', '["Ah","Kd","3c"]', 'flop', 'Bet 33%', '["Check","Bet 33%","Bet 75%","Bet 125%"]', 'Bet 33%', 'On this ace-high board as the preflop aggressor, we c-bet small at high frequency. Our range advantage on AK-high textures supports this strategy.', '{"Check": 20, "Bet 33%": 62, "Bet 75%": 15, "Bet 125%": 3}', 1, 'cash', 100),
('CO opens, BTN 3-bets, CO calls. Board: Jd Tc 5h. BTN (hero) to act. What is the GTO play?', 'AKs', 'BTN', '["Jd","Tc","5h"]', 'flop', 'Bet 75%', '["Check","Bet 33%","Bet 75%","All-In"]', 'Bet 75%', 'As the 3-bettor with two overcards and a gutshot, we bet large on this connected board. Our range crushing advantage on JT5 supports 75% sizing.', '{"Check": 15, "Bet 33%": 12, "Bet 75%": 65, "All-In": 8}', 3, 'cash', 100),
('UTG opens, HJ calls, CO folds, BTN folds, SB folds, BB (hero) calls. Board: 8s 7s 3d. UTG bets 50%. HJ folds. What is the GTO play?', '9s8d', 'BB', '["8s","7s","3d"]', 'flop', 'Call', '["Fold","Call","Raise","All-In"]', 'Call', 'Mid pair with a gutshot and backdoor flush draw. Against UTG range on this board, calling is the GTO play to protect our check-calling range.', '{"Fold": 12, "Call": 63, "Raise": 22, "All-In": 3}', 2, 'cash', 100),
('BTN opens, SB 3-bets, BB folds, BTN (hero) calls. Board: Qh 9c 6d. SB bets 33%. What is the GTO play?', 'JTs', 'BTN', '["Qh","9c","6d"]', 'flop', 'Call', '["Fold","Call","Raise","All-In"]', 'Call', 'With an open-ended straight draw on a queen-high board against the 3-bettor, calling is the highest frequency play. We have 8 clean outs and position.', '{"Fold": 10, "Call": 72, "Raise": 16, "All-In": 2}', 2, 'cash', 100),
('BB defends vs CO open. Board: Ad 8c 2s. CO bets 33%. BB (hero) to act. What is the GTO play?', 'KQo', 'BB', '["Ad","8c","2s"]', 'flop', 'Fold', '["Fold","Call","Raise","All-In"]', 'Fold', 'On an ace-high dry board without connecting, KQ has very little equity against the continuation bet range. The solver folds this at high frequency.', '{"Fold": 72, "Call": 25, "Raise": 3, "All-In": 0}', 1, 'cash', 100),
('HJ opens, CO 3-bets, HJ (hero) calls. Board: Ks Td 7c. CO bets 55%. What is the GTO play?', 'AsAh', 'HJ', '["Ks","Td","7c"]', 'flop', 'Call', '["Fold","Call","Raise","All-In"]', 'Call', 'With an overpair, we have a strong hand but should mostly call. Raising would narrow us to very strong hands and fold out worse hands that give us value.', '{"Fold": 2, "Call": 75, "Raise": 20, "All-In": 3}', 2, 'cash', 100),
('MP opens, BB (hero) defends. Board: 6s 5s 4h. MP bets 66%. What is the GTO play?', 'As7s', 'BB', '["6s","5s","4h"]', 'flop', 'Raise', '["Fold","Call","Raise","All-In"]', 'Raise', 'With a flush draw, overcard, and open-ended straight draw, this is the perfect hand to raise on the wet board. We have massive equity and fold equity.', '{"Fold": 3, "Call": 28, "Raise": 60, "All-In": 9}', 3, 'cash', 100),
('SB opens, BB (hero) 3-bets, SB calls. Board: Qc Jh 2c. BB to act. What is the GTO play?', 'AcKc', 'BB', '["Qc","Jh","2c"]', 'flop', 'Bet 33%', '["Check","Bet 33%","Bet 75%","Bet 125%"]', 'Bet 33%', 'As the 3-bettor with a nut flush draw and two overcards, we c-bet small. This board favors our range and a small sizing builds the pot with our equity.', '{"Check": 15, "Bet 33%": 55, "Bet 75%": 25, "Bet 125%": 5}', 2, 'cash', 100),
('BTN opens, SB folds, BB (hero) calls. Turn: Js 9c 4d 2h. BB checks, BTN bets 66%. What is the GTO play?', 'JdTd', 'BB', '["Js","9c","4d","2h"]', 'turn', 'Call', '["Fold","Call","Raise","All-In"]', 'Call', 'With top pair good kicker on a dry turn runout, calling is the standard play. Our hand is too strong to fold and doesn''t benefit from raising.', '{"Fold": 5, "Call": 80, "Raise": 13, "All-In": 2}', 2, 'cash', 100),
('CO opens, BTN 3-bets, blinds fold, CO (hero) calls. River: Kh Qd 8c 5s 3h. CO checks, BTN bets 75%. What is the GTO play?', 'AhAs', 'CO', '["Kh","Qd","8c","5s","3h"]', 'river', 'Call', '["Fold","Call","Raise","All-In"]', 'Call', 'Aces are a strong bluff catcher on this runout. The solver calls here at high frequency because we beat all bluffs and many value bets.', '{"Fold": 15, "Call": 70, "Raise": 12, "All-In": 3}', 3, 'cash', 100),
('UTG opens, everyone folds to BB (hero). Board: Th 7h 3s. UTG bets 33%. What is the GTO play?', '5h4h', 'BB', '["Th","7h","3s"]', 'flop', 'Call', '["Fold","Call","Raise","All-In"]', 'Call', 'With a flush draw, we have implied odds to continue. Calling keeps our range wide and allows us to realize our equity on later streets.', '{"Fold": 15, "Call": 62, "Raise": 20, "All-In": 3}', 1, 'cash', 100),
('BTN opens, BB (hero) defends. Turn: As Ks 8d 6c. BB checks, BTN bets 50%. What is the GTO play?', '9s8s', 'BB', '["As","Ks","8d","6c"]', 'turn', 'Call', '["Fold","Call","Raise","All-In"]', 'Call', 'Second pair with a flush draw gives us enough equity to continue. We have outs to a flush and can potentially improve to trips or two pair.', '{"Fold": 20, "Call": 65, "Raise": 12, "All-In": 3}', 2, 'cash', 100),
('SB vs BB battle. Board: 9h 8c 4s 2d. SB (hero) checks turn. BB bets 75%. What is the GTO play?', 'TdTs', 'SB', '["9h","8c","4s","2d"]', 'turn', 'Call', '["Fold","Call","Raise","All-In"]', 'Call', 'Overpair on a relatively dry board facing a turn probe. We''re ahead of most of BB''s range and should call to keep their bluffs in.', '{"Fold": 8, "Call": 72, "Raise": 17, "All-In": 3}', 2, 'cash', 100),
('25BB effective in MTT. UTG shoves. Folds to BB (hero). What is the GTO play?', 'ATo', 'BB', '[]', 'preflop', 'Call', '["Fold","Call"]', 'Call', 'At 25BB effective, ATo is a clear call against a UTG shove in a tournament. We have sufficient equity against the shoving range and pot odds.', '{"Fold": 28, "Call": 72}', 3, 'mtt', 25),
('15BB effective in MTT. CO shoves. BTN folds. SB folds. BB (hero) to act. What is the GTO play?', 'KJs', 'BB', '[]', 'preflop', 'Call', '["Fold","Call"]', 'Call', 'KJs is a profitable call against CO shove range at 15BB. We have strong equity with suited broadway cards and correct pot odds.', '{"Fold": 22, "Call": 78}', 2, 'mtt', 15),
('Bubble of 45-man SNG. 6 left, 5 paid. BTN (hero) has 12BB. SB has 8BB. BB has 20BB. What is the GTO play?', '77', 'BTN', '[]', 'preflop', 'All-In', '["Fold","Raise","All-In"]', 'All-In', 'Pocket sevens is a strong shove at 12BB on the bubble. We have fold equity against the blinds and strong equity when called.', '{"Fold": 10, "Raise": 5, "All-In": 85}', 3, 'mtt', 12),
('Final table of MTT. 4 left. CO (hero) has 30BB. What is the GTO play?', 'A5s', 'CO', '[]', 'preflop', 'Raise', '["Fold","Raise","All-In"]', 'Raise', 'A5 suited is a standard open from CO at 30BB deep. We have a suited ace with wheel potential and nut flush potential. Min-raise is preferred.', '{"Fold": 15, "Raise": 78, "All-In": 7}', 2, 'mtt', 30),
('HU in MTT. 20BB effective. SB (hero) on BTN. What is the GTO play?', 'K2o', 'SB', '[]', 'preflop', 'Raise', '["Fold","Raise","All-In"]', 'Raise', 'Heads-up at 20BB, K2o is a clear raise from the button/SB. Our range should be very wide HU and king-high has sufficient equity.', '{"Fold": 12, "Raise": 80, "All-In": 8}', 1, 'mtt', 20);


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260308095555_sandbox_enhancement_suite.sql
-- ════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════
-- Sandbox Templates Table
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS sandbox_templates (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  scenario_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sandbox_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own templates"
  ON sandbox_templates FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own templates"
  ON sandbox_templates FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own templates"
  ON sandbox_templates FOR DELETE
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_sandbox_templates_user ON sandbox_templates(user_id);

-- ═══════════════════════════════════════════════════════════════
-- Sandbox Analytics Table (Leak Tracker)
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS sandbox_analytics (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  position TEXT NOT NULL DEFAULT 'BTN',
  street TEXT NOT NULL DEFAULT 'preflop',
  game_type TEXT NOT NULL DEFAULT 'cash',
  action_taken TEXT,
  is_correct BOOLEAN,
  hand_strength TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sandbox_analytics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own analytics"
  ON sandbox_analytics FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own analytics"
  ON sandbox_analytics FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_sandbox_analytics_user ON sandbox_analytics(user_id);
CREATE INDEX IF NOT EXISTS idx_sandbox_analytics_created ON sandbox_analytics(user_id, created_at DESC);


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260308_bbj_config_and_leave_requests.sql
-- ════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Migration: BBJ club-level config + Union Leave Requests
-- Run in Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. Add bbj_enabled column to clubs ─────────────────────────────────────
-- NULL = use platform default (enabled for eligible stakes/variants)
-- TRUE = explicitly enabled
-- FALSE = explicitly disabled for this club
ALTER TABLE public.clubs
  ADD COLUMN IF NOT EXISTS bbj_enabled BOOLEAN DEFAULT NULL;

COMMENT ON COLUMN public.clubs.bbj_enabled IS
  'Club-level BBJ override. NULL = platform default (on), FALSE = disabled, TRUE = explicitly on.';

-- ── 2. Create union_leave_requests table ────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.union_leave_requests (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  union_id            UUID NOT NULL REFERENCES public.unions(id) ON DELETE CASCADE,
  club_id             UUID NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
  requester_user_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  club_name           TEXT NOT NULL,
  club_code           INTEGER,
  reason              TEXT,
  status              TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'approved', 'denied')),
  requested_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_by         UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at         TIMESTAMPTZ,
  UNIQUE (club_id, status) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_union_leave_requests_union_id    ON public.union_leave_requests(union_id);
CREATE INDEX IF NOT EXISTS idx_union_leave_requests_club_id     ON public.union_leave_requests(club_id);
CREATE INDEX IF NOT EXISTS idx_union_leave_requests_status      ON public.union_leave_requests(status);
CREATE INDEX IF NOT EXISTS idx_union_leave_requests_requested   ON public.union_leave_requests(requested_at DESC);

-- ── 3. RLS for union_leave_requests ─────────────────────────────────────────
ALTER TABLE public.union_leave_requests ENABLE ROW LEVEL SECURITY;

-- Club owner can view their own leave requests
CREATE POLICY "club_owner_view_leave_requests"
  ON public.union_leave_requests FOR SELECT
  USING (
    requester_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.clubs
      WHERE id = club_id AND owner_id = auth.uid()
    )
  );

-- Club owner can insert leave request for their club
CREATE POLICY "club_owner_insert_leave_request"
  ON public.union_leave_requests FOR INSERT
  WITH CHECK (
    requester_user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.clubs
      WHERE id = club_id AND owner_id = auth.uid()
    )
  );

-- Platform admin can view all leave requests
CREATE POLICY "platform_admin_view_leave_requests"
  ON public.union_leave_requests FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role IN ('admin', 'superadmin')
    )
  );

-- Platform admin can update (approve/deny) leave requests
CREATE POLICY "platform_admin_update_leave_requests"
  ON public.union_leave_requests FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role IN ('admin', 'superadmin')
    )
  );

-- ── 4. Add to realtime publication ──────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND tablename = 'union_leave_requests'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.union_leave_requests;
  END IF;
END $$;


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260308_diamond_arena_events.sql
-- ════════════════════════════════════════════════════════════════════════

-- ================================================================
-- MIGRATION: diamond_arena_events table for arcade game sessions
-- Tracks game starts, completions, wins, losses for analytics + audit
-- Date: 2026-03-08
-- ================================================================

CREATE TABLE IF NOT EXISTS public.diamond_arena_events (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    event_type      TEXT NOT NULL CHECK (event_type IN ('game_start', 'game_complete', 'duel_start', 'duel_complete', 'jackpot_win')),
    game_type       TEXT,                           -- 'hand-snap', 'board-nuts', etc.
    score           INTEGER DEFAULT 0,
    correct_count   INTEGER DEFAULT 0,
    total_questions INTEGER DEFAULT 0,
    time_spent_ms   INTEGER DEFAULT 0,
    won             BOOLEAN DEFAULT FALSE,
    prize_awarded   INTEGER DEFAULT 0,              -- diamonds awarded on win
    entry_fee       INTEGER DEFAULT 0,              -- diamonds spent to play
    diamonds_delta  INTEGER DEFAULT 0,              -- net change (prize - fee)
    status          TEXT DEFAULT 'completed' CHECK (status IN ('active', 'completed', 'abandoned')),
    metadata        JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_diamond_arena_events_user ON public.diamond_arena_events (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_diamond_arena_events_type ON public.diamond_arena_events (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_diamond_arena_events_game ON public.diamond_arena_events (game_type, created_at DESC);

-- RLS
ALTER TABLE public.diamond_arena_events ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'diamond_arena_events' AND policyname = 'Users can view own events'
    ) THEN
        CREATE POLICY "Users can view own events" ON public.diamond_arena_events
            FOR SELECT USING (auth.uid() = user_id);
    END IF;
END $$;

-- Service role can insert on behalf of users (API routes)
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'diamond_arena_events' AND policyname = 'Service role can insert events'
    ) THEN
        CREATE POLICY "Service role can insert events" ON public.diamond_arena_events
            FOR INSERT WITH CHECK (true);
    END IF;
END $$;

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS public.diamond_arena_events;

-- ================================================================
-- diamond_arena_scores: leaderboard aggregates (if not already created)
-- ================================================================
CREATE TABLE IF NOT EXISTS public.diamond_arena_scores (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    game_type       TEXT NOT NULL,
    high_score      INTEGER DEFAULT 0,
    total_wins      INTEGER DEFAULT 0,
    total_games     INTEGER DEFAULT 0,
    total_earned    INTEGER DEFAULT 0,               -- lifetime diamonds won
    best_streak     INTEGER DEFAULT 0,
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, game_type)
);

CREATE INDEX IF NOT EXISTS idx_diamond_arena_scores_game ON public.diamond_arena_scores (game_type, total_wins DESC);
ALTER TABLE public.diamond_arena_scores ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'diamond_arena_scores' AND policyname = 'Scores are public'
    ) THEN
        CREATE POLICY "Scores are public" ON public.diamond_arena_scores FOR SELECT USING (true);
    END IF;
END $$;

ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS public.diamond_arena_scores;


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260308_enable_realtime_all_tables.sql
-- ════════════════════════════════════════════════════════════════════════

-- ================================================================
-- MIGRATION: Enable Supabase Realtime for all subscribed tables
-- Run in Supabase SQL Editor: Dashboard > SQL Editor > New Query
-- Date: 2026-03-08
-- ================================================================
-- These tables have active postgres_changes subscriptions in the
-- frontend codebase. They must be added to the supabase_realtime
-- publication so the DB change events are broadcast.
-- ================================================================

-- Core Club Arena tables
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS agents;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS cashout_requests;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS chip_transactions;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS club_members;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS club_shop_items;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS club_shop_purchases;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS club_tournaments;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS clubs;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS tables;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS settlement_periods;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS tournament_registrations;

-- Union tables
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS unions;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS union_admins;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS union_clubs;

-- Arcade
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS arcade_duel_queue;

-- Profiles
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS profiles;

-- Commander tables
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_checkins;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_club_announcements;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_comp_balances;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_comp_transactions;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_dealer_rotations;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_games;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_home_games;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_home_groups;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_home_members;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_home_rsvps;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_members;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_player_stats;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_promotions;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_service_requests;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_staff_shifts;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_table_sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commander_waitlist;

-- Social & Messaging
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS conversations;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS follows;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS friendships;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS social_interactions;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS social_page_posts;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS social_pages;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS social_posts;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS social_reels;

-- Bankroll
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS bankroll_ledger;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS bankroll_trips;

-- Training / Trivia / Games
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS daily_trivia_plays;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS diamond_arena_events;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS diamond_arena_scores;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS hand_histories;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS jarvis_training_sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS memory_game_sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS memory_leaderboards;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS orders;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS training_streaks;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS trivia_scores;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS trivia_streaks;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS trivia_survival_runs;

-- ================================================================
-- RLS POLICIES: Ensure all realtime-enabled tables allow the
-- authenticated user to see their own rows via SELECT policies.
-- These are additive (IF NOT EXISTS guards).
-- ================================================================

-- club_members: users can see their own membership
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'club_members' AND policyname = 'Members can read own club memberships'
  ) THEN
    CREATE POLICY "Members can read own club memberships" ON club_members
      FOR SELECT USING (auth.uid() = user_id);
  END IF;
END $$;

-- agents: agents can read own row
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'agents' AND policyname = 'Agents can read own agent row'
  ) THEN
    CREATE POLICY "Agents can read own agent row" ON agents
      FOR SELECT USING (auth.uid() = user_id);
  END IF;
END $$;

-- cashout_requests: users can see own requests
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'cashout_requests' AND policyname = 'Users can read own cashout requests'
  ) THEN
    CREATE POLICY "Users can read own cashout requests" ON cashout_requests
      FOR SELECT USING (auth.uid() = user_id);
  END IF;
END $$;

-- tournament_registrations: users can see own registrations
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'tournament_registrations' AND policyname = 'Users can read own tournament registrations'
  ) THEN
    CREATE POLICY "Users can read own tournament registrations" ON tournament_registrations
      FOR SELECT USING (auth.uid() = user_id);
  END IF;
END $$;

-- ================================================================
-- PERFORMANCE: Indexes for realtime filter columns
-- Supabase realtime filters hit the DB on every change event.
-- These indexes prevent seq scans on filtered subscriptions.
-- ================================================================

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agents_club_user ON agents (club_id, user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cashout_requests_club ON cashout_requests (club_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_chip_transactions_club ON chip_transactions (club_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_tournament_regs_user ON tournament_registrations (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_tournament_regs_tournament ON tournament_registrations (tournament_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_settlement_periods_club ON settlement_periods (club_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_union_clubs_union ON union_clubs (union_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_union_admins_union ON union_admins (union_id);


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260308_geeves_missed_questions.sql
-- ════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Geeves Auto-Learning System — Full SQL Package
-- Run this in Supabase SQL Editor (or via CLI)
-- Includes: table, indexes, RLS, and 2 RPCs used by chat.js
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. Table ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS geeves_missed_questions (
  id            BIGSERIAL    PRIMARY KEY,
  question      TEXT         NOT NULL,
  question_hash TEXT         NOT NULL,
  page          TEXT,
  asked_count   INT          NOT NULL DEFAULT 1,
  first_asked   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  last_asked    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  resolved      BOOLEAN      NOT NULL DEFAULT FALSE,
  added_to_kb   BOOLEAN      NOT NULL DEFAULT FALSE,
  grok_answer   TEXT,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Unique on hash for ON CONFLICT upsert
CREATE UNIQUE INDEX IF NOT EXISTS geeves_mq_hash_idx
  ON geeves_missed_questions (question_hash);

-- Speed up top-missed queries (analytics dashboard)
CREATE INDEX IF NOT EXISTS geeves_mq_count_idx
  ON geeves_missed_questions (asked_count DESC, resolved)
  WHERE resolved = FALSE;

-- ── 2. RLS ────────────────────────────────────────────────────────────────
ALTER TABLE geeves_missed_questions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service_role_only" ON geeves_missed_questions;
CREATE POLICY "service_role_only" ON geeves_missed_questions
  USING (false) WITH CHECK (false);

-- ── 3. RPC: geeves_upsert_missed_question ─────────────────────────────────
-- Primary function called from chat.js Step 4.
-- Inserts on first ask, increments asked_count on repeat asks.
-- Security: SECURITY DEFINER so service_role can bypass RLS.
CREATE OR REPLACE FUNCTION geeves_upsert_missed_question(
  p_question   TEXT,
  p_hash       TEXT,
  p_page       TEXT     DEFAULT NULL,
  p_grok_answer TEXT    DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO geeves_missed_questions
    (question, question_hash, page, grok_answer, asked_count, first_asked, last_asked)
  VALUES
    (p_question, p_hash, p_page, LEFT(p_grok_answer, 2000), 1, now(), now())
  ON CONFLICT (question_hash) DO UPDATE
    SET asked_count = geeves_missed_questions.asked_count + 1,
        last_asked  = now(),
        -- Update grok_answer only if we have a newer one (not null)
        grok_answer = COALESCE(LEFT(EXCLUDED.grok_answer, 2000), geeves_missed_questions.grok_answer),
        page        = COALESCE(EXCLUDED.page, geeves_missed_questions.page);
END;
$$;

-- ── 4. RPC: geeves_increment_missed_count ─────────────────────────────────
-- Fallback function: called when INSERT returns a 23505 conflict
-- and the primary RPC wasn't available yet.
CREATE OR REPLACE FUNCTION geeves_increment_missed_count(
  p_hash        TEXT,
  p_grok_answer TEXT    DEFAULT NULL,
  p_page        TEXT    DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE geeves_missed_questions
  SET asked_count = asked_count + 1,
      last_asked  = now(),
      grok_answer = COALESCE(LEFT(p_grok_answer, 2000), grok_answer),
      page        = COALESCE(p_page, page)
  WHERE question_hash = p_hash;
END;
$$;

-- ── 5. Grant execute to service_role ──────────────────────────────────────
GRANT EXECUTE ON FUNCTION geeves_upsert_missed_question TO service_role;
GRANT EXECUTE ON FUNCTION geeves_increment_missed_count TO service_role;


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260308_hand_id_and_tracking.sql
-- ════════════════════════════════════════════════════════════════════════

-- ================================================================
-- HAND ID SYSTEM + FULL TRACKING
--
-- 1. Global hand ID sequence (SP-XXXXXXX)
-- 2. global_hand_id + is_tournament on rake_records
-- 3. player_bbj_contributions on union_bbj_ledger
-- 4. Updated record_rake() — adds global_hand_id + per-player BBJ
-- 5. record_tournament_buyin_rake() — per-player at registration
-- ================================================================

-- ─────────────────────────────────────────────────────────────
-- 1. GLOBAL HAND ID SEQUENCE
--    Every hand across all clubs/tables gets a unique integer.
--    Display format: SP-0001234567 (10-digit, zero-padded)
-- ─────────────────────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS hand_id_seq
  START WITH 1000000
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 100;   -- Pre-allocate 100 IDs to reduce round-trip latency

COMMENT ON SEQUENCE hand_id_seq IS
  'Global sequential hand ID. Every rake-recorded hand gets a unique integer. Display as SP-XXXXXXXXXX.';

-- ─────────────────────────────────────────────────────────────
-- 2. ADD COLUMNS TO rake_records
-- ─────────────────────────────────────────────────────────────
DO $$
BEGIN
  -- Global unique sequential hand number
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'rake_records' AND column_name = 'global_hand_id'
  ) THEN
    ALTER TABLE rake_records
      ADD COLUMN global_hand_id BIGINT DEFAULT nextval('hand_id_seq');
    COMMENT ON COLUMN rake_records.global_hand_id IS
      'Globally unique sequential hand ID from hand_id_seq. Used in display as SP-XXXXXXXXXX.';
  END IF;

  -- Tournament flag
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'rake_records' AND column_name = 'is_tournament'
  ) THEN
    ALTER TABLE rake_records
      ADD COLUMN is_tournament BOOLEAN NOT NULL DEFAULT false;
    COMMENT ON COLUMN rake_records.is_tournament IS
      'True when this record is for tournament buy-in rake (not a cash game hand).';
  END IF;

  -- Tournament ID (NULL for cash game hands)
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'rake_records' AND column_name = 'tournament_id'
  ) THEN
    ALTER TABLE rake_records
      ADD COLUMN tournament_id UUID REFERENCES club_tournaments(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_rake_records_global_hand ON rake_records(global_hand_id);
CREATE INDEX IF NOT EXISTS idx_rake_records_tournament ON rake_records(tournament_id) WHERE tournament_id IS NOT NULL;

-- ─────────────────────────────────────────────────────────────
-- 3. ADD player_bbj_contributions TO union_bbj_ledger
--    Tracks each dealt player's share of the BBJ drop per hand.
--    Format: {"user_id": amount, ...}  (same dealt-method split)
-- ─────────────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'union_bbj_ledger' AND column_name = 'player_contributions'
  ) THEN
    ALTER TABLE union_bbj_ledger
      ADD COLUMN player_contributions JSONB DEFAULT NULL;
    COMMENT ON COLUMN union_bbj_ledger.player_contributions IS
      'Per-player BBJ contribution amounts for this hand. Dealt-method split: bbj_amount / num_dealt_players per player. Format: {"user_id": amount}';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'union_bbj_ledger' AND column_name = 'num_players'
  ) THEN
    ALTER TABLE union_bbj_ledger
      ADD COLUMN num_players INTEGER DEFAULT NULL;
    COMMENT ON COLUMN union_bbj_ledger.num_players IS
      'Number of players dealt into the hand that generated this BBJ contribution.';
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────
-- 4. REPLACE record_rake() — adds global_hand_id + BBJ player tracking
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION record_rake(
  p_hand_id TEXT,
  p_club_id UUID,
  p_table_id UUID,
  p_rake_amount NUMERIC,
  p_pot_size NUMERIC,
  p_num_players INTEGER,
  p_bbj_contribution NUMERIC DEFAULT 0,
  p_dealt_player_ids UUID[] DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_club RECORD;
  v_union_settings JSONB;
  v_union_id UUID;
  v_union_share NUMERIC;
  v_club_share NUMERIC;
  v_rake_id UUID;
  v_global_hand_id BIGINT;
  v_player_contributions JSONB := '{}'::JSONB;
  v_bbj_player_contributions JSONB := '{}'::JSONB;
  v_per_player_rake NUMERIC;
  v_per_player_bbj NUMERIC;
  v_player_id UUID;
  -- BBJ split
  v_bbj_main_pct NUMERIC;
  v_bbj_backup_pct NUMERIC;
  v_bbj_promo_pct NUMERIC;
  v_bbj_main NUMERIC := 0;
  v_bbj_backup NUMERIC := 0;
  v_bbj_promo NUMERIC := 0;
  v_new_main NUMERIC;
  v_new_backup NUMERIC;
  v_new_promo NUMERIC;
BEGIN
  IF p_rake_amount <= 0 AND COALESCE(p_bbj_contribution, 0) <= 0 THEN
    RETURN jsonb_build_object('success', true, 'rake', 0, 'note', 'No rake taken');
  END IF;

  -- Assign global sequential hand ID
  v_global_hand_id := nextval('hand_id_seq');

  -- Get club + union info
  SELECT c.*, uc.union_id,
    COALESCE(u.settings, '{}'::JSONB) AS union_settings
  INTO v_club
  FROM clubs c
  LEFT JOIN union_clubs uc ON uc.club_id = c.id
  LEFT JOIN unions u ON u.id = uc.union_id
  WHERE c.id = p_club_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Club not found');
  END IF;

  v_union_id := v_club.union_id;
  v_union_settings := v_club.union_settings;

  -- ══════════════════════════════════════════════════════════
  -- DEALT METHOD: Split rake equally among all dealt players
  -- Cash games: rake / num_players dealt
  -- Tournament: 100% per registering player (handled by record_tournament_buyin_rake)
  -- ══════════════════════════════════════════════════════════
  IF p_dealt_player_ids IS NOT NULL AND array_length(p_dealt_player_ids, 1) > 0 AND p_rake_amount > 0 THEN
    v_per_player_rake := ROUND(p_rake_amount / array_length(p_dealt_player_ids, 1), 4);
    FOREACH v_player_id IN ARRAY p_dealt_player_ids LOOP
      v_player_contributions := v_player_contributions || jsonb_build_object(v_player_id::TEXT, v_per_player_rake);
    END LOOP;
  ELSIF p_num_players > 0 AND p_rake_amount > 0 THEN
    v_per_player_rake := ROUND(p_rake_amount / p_num_players, 4);
  END IF;

  -- ══════════════════════════════════════════════════════════
  -- BBJ PLAYER ATTRIBUTION (Dealt Method)
  -- Each dealt player gets credited with their proportional share
  -- of the BBJ drop for that hand.
  -- ══════════════════════════════════════════════════════════
  IF COALESCE(p_bbj_contribution, 0) > 0 THEN
    IF p_dealt_player_ids IS NOT NULL AND array_length(p_dealt_player_ids, 1) > 0 THEN
      v_per_player_bbj := ROUND(p_bbj_contribution / array_length(p_dealt_player_ids, 1), 4);
      FOREACH v_player_id IN ARRAY p_dealt_player_ids LOOP
        v_bbj_player_contributions := v_bbj_player_contributions
          || jsonb_build_object(v_player_id::TEXT, v_per_player_bbj);
      END LOOP;
    ELSIF p_num_players > 0 THEN
      v_per_player_bbj := ROUND(p_bbj_contribution / p_num_players, 4);
    END IF;
  END IF;

  -- ══════════════════════════════════════════════════════════
  -- ROUTING:
  --   Union club  → 100% rake + 100% BBJ → UNION
  --   Standalone  → 100% rake + 100% BBJ → CLUB
  -- ══════════════════════════════════════════════════════════
  IF v_union_id IS NOT NULL THEN
    v_union_share := p_rake_amount;
    v_club_share := 0;

    IF COALESCE(p_bbj_contribution, 0) > 0 THEN
      v_bbj_main_pct := COALESCE((v_union_settings->>'bbj_main_pct')::NUMERIC, 40);
      v_bbj_backup_pct := COALESCE((v_union_settings->>'bbj_backup_pct')::NUMERIC, 30);
      v_bbj_promo_pct := COALESCE((v_union_settings->>'bbj_promo_pct')::NUMERIC, 30);

      IF v_bbj_main_pct + v_bbj_backup_pct + v_bbj_promo_pct != 100 THEN
        v_bbj_main_pct := 40; v_bbj_backup_pct := 30; v_bbj_promo_pct := 30;
      END IF;

      v_bbj_main := ROUND(p_bbj_contribution * (v_bbj_main_pct / 100.0), 2);
      v_bbj_backup := ROUND(p_bbj_contribution * (v_bbj_backup_pct / 100.0), 2);
      v_bbj_promo := p_bbj_contribution - v_bbj_main - v_bbj_backup;
    END IF;

    UPDATE unions SET
      total_rake = COALESCE(total_rake, 0) + p_rake_amount,
      main_bbj_balance = COALESCE(main_bbj_balance, 0) + v_bbj_main,
      backup_bbj_balance = COALESCE(backup_bbj_balance, 0) + v_bbj_backup,
      promo_fund_balance = COALESCE(promo_fund_balance, 0) + v_bbj_promo,
      updated_at = NOW()
    WHERE id = v_union_id
    RETURNING main_bbj_balance, backup_bbj_balance, promo_fund_balance
    INTO v_new_main, v_new_backup, v_new_promo;

    IF COALESCE(p_bbj_contribution, 0) > 0 THEN
      INSERT INTO union_bbj_ledger (
        union_id, club_id, hand_id, entry_type,
        main_amount, backup_amount, promo_amount,
        main_balance_after, backup_balance_after, promo_balance_after,
        player_contributions,
        num_players,
        note
      ) VALUES (
        v_union_id, p_club_id, p_hand_id, 'contribution',
        v_bbj_main, v_bbj_backup, v_bbj_promo,
        v_new_main, v_new_backup, v_new_promo,
        CASE WHEN v_bbj_player_contributions != '{}'::JSONB
          THEN v_bbj_player_contributions ELSE NULL END,
        COALESCE(array_length(p_dealt_player_ids, 1), p_num_players),
        'BBJ drop from hand — per-player contributions tracked'
      );
    END IF;

  ELSE
    v_union_share := 0;
    v_club_share := p_rake_amount + COALESCE(p_bbj_contribution, 0);
  END IF;

  -- ══════════════════════════════════════════════════════════
  -- INSERT rake_record with global_hand_id
  -- ══════════════════════════════════════════════════════════
  INSERT INTO rake_records (
    club_id, table_id, hand_id, global_hand_id, rake_amount, pot_size,
    num_players, bbj_contribution, player_contributions, is_tournament
  ) VALUES (
    p_club_id, p_table_id, p_hand_id,
    v_global_hand_id,
    p_rake_amount, p_pot_size,
    COALESCE(array_length(p_dealt_player_ids, 1), p_num_players),
    COALESCE(p_bbj_contribution, 0),
    CASE WHEN v_player_contributions != '{}'::JSONB THEN v_player_contributions ELSE NULL END,
    false
  ) RETURNING id INTO v_rake_id;

  UPDATE clubs SET
    chip_treasury = COALESCE(chip_treasury, 0) + v_club_share,
    total_rake = COALESCE(total_rake, 0) + p_rake_amount,
    hands_played = COALESCE(hands_played, 0) + 1,
    updated_at = NOW()
  WHERE id = p_club_id;

  INSERT INTO club_transactions (club_id, transaction_type, amount, description, reference_id, metadata)
  VALUES (p_club_id, 'rake', v_club_share,
    CASE WHEN v_union_id IS NOT NULL THEN 'Rake collected (routed to union)' ELSE 'Rake from hand' END,
    v_rake_id,
    jsonb_build_object(
      'hand_id', p_hand_id,
      'global_hand_id', v_global_hand_id,
      'total_rake', p_rake_amount,
      'routed_to', CASE WHEN v_union_id IS NOT NULL THEN 'union' ELSE 'club' END,
      'union_id', v_union_id,
      'union_share', v_union_share,
      'club_share', v_club_share,
      'bbj', COALESCE(p_bbj_contribution, 0),
      'bbj_main', v_bbj_main,
      'bbj_backup', v_bbj_backup,
      'bbj_promo', v_bbj_promo,
      'num_dealt', COALESCE(array_length(p_dealt_player_ids, 1), p_num_players),
      'per_player_rake', v_per_player_rake,
      'per_player_bbj', v_per_player_bbj
    ));

  RETURN jsonb_build_object(
    'success', true,
    'rake_id', v_rake_id,
    'global_hand_id', v_global_hand_id,
    'total_rake', p_rake_amount,
    'routed_to', CASE WHEN v_union_id IS NOT NULL THEN 'union' ELSE 'club' END,
    'club_share', v_club_share,
    'union_share', v_union_share,
    'bbj_contribution', COALESCE(p_bbj_contribution, 0),
    'bbj_main', v_bbj_main,
    'bbj_backup', v_bbj_backup,
    'bbj_promo', v_bbj_promo,
    'per_player_rake', v_per_player_rake,
    'per_player_bbj', v_per_player_bbj,
    'num_dealt', COALESCE(array_length(p_dealt_player_ids, 1), p_num_players),
    'player_contributions', v_player_contributions,
    'player_bbj_contributions', v_bbj_player_contributions
  );
END;
$$;

-- ─────────────────────────────────────────────────────────────
-- 5. record_tournament_buyin_rake()
--    Called at each player registration.
--    100% of buyinFee is credited as that player's rake generated.
--    Flows through union routing + cascading agent commissions.
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION record_tournament_buyin_rake(
  p_tournament_id UUID,
  p_club_id UUID,
  p_player_user_id UUID,
  p_buyin_fee NUMERIC,            -- The rake/fee portion of the buy-in
  p_buyin_amount NUMERIC,         -- The full buy-in (for context)
  p_tournament_name TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_club RECORD;
  v_union_id UUID;
  v_union_settings JSONB;
  v_union_share NUMERIC;
  v_club_share NUMERIC;
  v_rake_id UUID;
  v_global_hand_id BIGINT;
  v_hand_id TEXT;
  v_bbj_main_pct NUMERIC;
  v_bbj_backup_pct NUMERIC;
  v_bbj_promo_pct NUMERIC;
BEGIN
  IF p_buyin_fee <= 0 THEN
    RETURN jsonb_build_object('success', true, 'note', 'No fee to record');
  END IF;

  -- Generate unique global ID for this registration event
  v_global_hand_id := nextval('hand_id_seq');
  v_hand_id := 'TOURN-' || p_tournament_id::TEXT || '-REG-' || p_player_user_id::TEXT;

  -- Get club + union info
  SELECT c.*, uc.union_id,
    COALESCE(u.settings, '{}'::JSONB) AS union_settings
  INTO v_club
  FROM clubs c
  LEFT JOIN union_clubs uc ON uc.club_id = c.id
  LEFT JOIN unions u ON u.id = uc.union_id
  WHERE c.id = p_club_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Club not found');
  END IF;

  v_union_id := v_club.union_id;
  v_union_settings := v_club.union_settings;

  -- Route 100% of tournament fee to union (or club if standalone)
  IF v_union_id IS NOT NULL THEN
    v_union_share := p_buyin_fee;
    v_club_share := 0;

    UPDATE unions SET
      total_rake = COALESCE(total_rake, 0) + p_buyin_fee,
      updated_at = NOW()
    WHERE id = v_union_id;
  ELSE
    v_union_share := 0;
    v_club_share := p_buyin_fee;

    UPDATE clubs SET
      chip_treasury = COALESCE(chip_treasury, 0) + v_club_share,
      total_rake = COALESCE(total_rake, 0) + p_buyin_fee,
      updated_at = NOW()
    WHERE id = p_club_id;
  END IF;

  -- Record in rake_records: 100% attributed to this single player
  INSERT INTO rake_records (
    club_id, hand_id, global_hand_id, rake_amount, pot_size,
    num_players, bbj_contribution, player_contributions,
    is_tournament, tournament_id
  ) VALUES (
    p_club_id, v_hand_id, v_global_hand_id, p_buyin_fee, p_buyin_amount,
    1, 0,
    -- 100% attributed to this player
    jsonb_build_object(p_player_user_id::TEXT, p_buyin_fee),
    true,
    p_tournament_id
  ) RETURNING id INTO v_rake_id;

  -- Log club transaction
  INSERT INTO club_transactions (club_id, transaction_type, amount, description, reference_id, metadata)
  VALUES (p_club_id, 'rake', v_club_share,
    COALESCE(p_tournament_name, 'Tournament') || ' — registration fee (rake)',
    v_rake_id,
    jsonb_build_object(
      'tournament_id', p_tournament_id,
      'player_id', p_player_user_id,
      'buyin_fee', p_buyin_fee,
      'buyin_amount', p_buyin_amount,
      'global_hand_id', v_global_hand_id,
      'routed_to', CASE WHEN v_union_id IS NOT NULL THEN 'union' ELSE 'club' END,
      'union_id', v_union_id
    ));

  RETURN jsonb_build_object(
    'success', true,
    'rake_id', v_rake_id,
    'global_hand_id', v_global_hand_id,
    'buyin_fee', p_buyin_fee,
    'routed_to', CASE WHEN v_union_id IS NOT NULL THEN 'union' ELSE 'club' END,
    'union_share', v_union_share,
    'club_share', v_club_share,
    'player_id', p_player_user_id,
    'tournament_id', p_tournament_id
  );
END;
$$;

-- Lock down new RPCs to service role only
REVOKE ALL ON FUNCTION record_tournament_buyin_rake(UUID, UUID, UUID, NUMERIC, NUMERIC, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION record_tournament_buyin_rake(UUID, UUID, UUID, NUMERIC, NUMERIC, TEXT) FROM anon;
REVOKE ALL ON FUNCTION record_tournament_buyin_rake(UUID, UUID, UUID, NUMERIC, NUMERIC, TEXT) FROM authenticated;
GRANT EXECUTE ON FUNCTION record_tournament_buyin_rake(UUID, UUID, UUID, NUMERIC, NUMERIC, TEXT) TO service_role;

SELECT 'Hand ID sequence + BBJ player tracking + tournament rake attribution installed' AS result;


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260308_hierarchy_gaps.sql
-- ════════════════════════════════════════════════════════════════════════

-- ============================================================
-- CLUB ARENA HIERARCHY GAPS — 2026-03-08
-- Adds: commission_history table,
--       fn_increment_club_member_count RPC,
--       fn_increment_agent_player_count RPC
--
-- NOTE: Agent referral codes are profiles.player_number (existing).
-- No separate invite_code column needed on agents table.
-- ============================================================

-- ── 2. commission_history table ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.commission_history (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id     UUID NOT NULL REFERENCES public.agents(id) ON DELETE CASCADE,
  club_id      UUID NOT NULL,
  period_id    UUID,                   -- references settlement_periods(id) if available
  rake_amount  BIGINT NOT NULL DEFAULT 0,
  commission   BIGINT NOT NULL DEFAULT 0,
  commission_rate NUMERIC(5,4) NOT NULL DEFAULT 0,
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_commission_history_agent
  ON public.commission_history (agent_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_commission_history_club
  ON public.commission_history (club_id, created_at DESC);

ALTER TABLE public.commission_history ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'commission_history' AND policyname = 'Agents can read own commission history'
  ) THEN
    CREATE POLICY "Agents can read own commission history"
      ON public.commission_history FOR SELECT
      USING (
        agent_id IN (
          SELECT id FROM public.agents WHERE user_id = auth.uid()
        )
      );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'commission_history' AND policyname = 'Club owners and union admins can read commission history'
  ) THEN
    CREATE POLICY "Club owners and union admins can read commission history"
      ON public.commission_history FOR SELECT
      USING (
        club_id IN (
          SELECT id FROM public.clubs WHERE owner_id = auth.uid()
        )
        OR club_id IN (
          SELECT c.id FROM public.clubs c
          JOIN public.union_admins ua ON ua.union_id = c.union_id
          WHERE ua.user_id = auth.uid()
        )
      );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'commission_history' AND policyname = 'Service role can insert commission history'
  ) THEN
    CREATE POLICY "Service role can insert commission history"
      ON public.commission_history FOR INSERT
      WITH CHECK (true);
  END IF;
END $$;

-- ── 3. fn_increment_club_member_count RPC ───────────────────
-- Atomic member count increment — avoids stale-read race conditions
CREATE OR REPLACE FUNCTION public.fn_increment_club_member_count(p_club_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.clubs
  SET member_count = COALESCE(member_count, 0) + 1
  WHERE id = p_club_id;
END;
$$;

-- ── 4. fn_increment_agent_player_count RPC ──────────────────
-- Atomic active_player_count + total_players increment for an agent
CREATE OR REPLACE FUNCTION public.fn_increment_agent_player_count(
  p_agent_user_id UUID,
  p_club_id       UUID
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.agents
  SET
    active_player_count = COALESCE(active_player_count, 0) + 1,
    total_players       = COALESCE(total_players, 0) + 1
  WHERE user_id = p_agent_user_id
    AND club_id = p_club_id;
END;
$$;

-- ── 4. Add commission_history to realtime ───────────────────
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['commission_history'] LOOP
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = t
      ) THEN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE %I', t);
      END IF;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END $$;


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260308_sandbox_wave2_tables.sql
-- ════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════
-- SANDBOX WAVE 2 TABLES
-- Supports: Coach Mode Results, Equity History, Session Logs
-- Date: 2026-03-08
-- ═══════════════════════════════════════════════════════════════

-- ── Coach Mode Results ──────────────────────────────────────────────────────
-- Persists every Socratic coach mode evaluation: what the user picked,
-- what GTO recommended, and the EV delta
CREATE TABLE IF NOT EXISTS sandbox_coach_results (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id       UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id    UUID REFERENCES sandbox_sessions(id) ON DELETE SET NULL,
  hero_hand     TEXT NOT NULL,
  hero_position TEXT,
  street        TEXT,
  board         TEXT,
  user_pick     TEXT NOT NULL,           -- action user chose
  gto_action    TEXT,                    -- GTO optimal action label
  is_correct    BOOLEAN,                 -- user_pick == gto_action
  ev_delta      NUMERIC(8,4),            -- EV difference (negative = leak)
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sandbox_coach_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own coach results"
  ON sandbox_coach_results FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own coach results"
  ON sandbox_coach_results FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_coach_results_user ON sandbox_coach_results(user_id);
CREATE INDEX IF NOT EXISTS idx_coach_results_correct ON sandbox_coach_results(user_id, is_correct);
CREATE INDEX IF NOT EXISTS idx_coach_results_created ON sandbox_coach_results(user_id, created_at DESC);


-- ── Equity History ──────────────────────────────────────────────────────────
-- Tracks hero equity at each street for multi-street equity graph rendering
-- (client-side EquityGraph reads from state, this table enables cross-session replay)
CREATE TABLE IF NOT EXISTS sandbox_equity_history (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id       UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id    UUID REFERENCES sandbox_sessions(id) ON DELETE CASCADE,
  hero_hand     TEXT NOT NULL,
  villain_range TEXT,
  street        TEXT NOT NULL,           -- 'preflop','flop','turn','river'
  equity_pct    NUMERIC(6,3),            -- hero win equity 0-100
  ev_hero       NUMERIC(8,4),            -- hero EV at this street
  board_cards   TEXT,                    -- space-separated card list
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sandbox_equity_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own equity history"
  ON sandbox_equity_history FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own equity history"
  ON sandbox_equity_history FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_eq_history_user ON sandbox_equity_history(user_id);
CREATE INDEX IF NOT EXISTS idx_eq_history_session ON sandbox_equity_history(session_id);


-- ── User Coach Accuracy Aggregate View ─────────────────────────────────────
-- Real-time accuracy stats for the coach mode — used by Leak Finder page
CREATE OR REPLACE VIEW sandbox_coach_accuracy AS
SELECT
  user_id,
  COUNT(*)                                          AS total_hands,
  COUNT(*) FILTER (WHERE is_correct = true)         AS correct_count,
  COUNT(*) FILTER (WHERE is_correct = false)        AS incorrect_count,
  ROUND(
    100.0 * COUNT(*) FILTER (WHERE is_correct = true) / NULLIF(COUNT(*), 0),
    1
  )                                                 AS accuracy_pct,
  AVG(CASE WHEN is_correct = false THEN ABS(ev_delta) END) AS avg_leak_ev
FROM sandbox_coach_results
GROUP BY user_id;


-- ── Realtime enabled for live badge updates ─────────────────────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE sandbox_coach_results;
ALTER PUBLICATION supabase_realtime ADD TABLE sandbox_equity_history;


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260308_union_applications.sql
-- ════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- UNION APPLICATIONS TABLE
-- ═══════════════════════════════════════════════════════════════════════════
-- Allows club owners to apply to join the Midway Union.
-- Platform admins (admin/superadmin role) review, approve, or reject.
-- Approving auto-integrates the club into the union via union_clubs + clubs.union_id.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.union_applications (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  union_id          UUID        NOT NULL REFERENCES public.unions(id) ON DELETE CASCADE,
  club_id           UUID        NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
  applicant_user_id UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Snapshot at time of application (denormalized for display without joins)
  club_name         TEXT        NOT NULL,
  club_code         INTEGER,
  member_count      INTEGER     DEFAULT 0,

  -- Optional message from club owner to union admin
  message           TEXT,

  -- Lifecycle
  status            TEXT        NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'approved', 'rejected')),
  applied_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_by       UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at       TIMESTAMPTZ,
  review_note       TEXT,

  -- Prevent duplicate pending applications for the same club+union
  UNIQUE (union_id, club_id, status) DEFERRABLE INITIALLY DEFERRED
);

-- Index for fast lookup by club owner (checking own status)
CREATE INDEX IF NOT EXISTS idx_union_applications_club_id
  ON public.union_applications (club_id, applied_at DESC);

-- Index for admin list view (all pending across all unions)
CREATE INDEX IF NOT EXISTS idx_union_applications_status
  ON public.union_applications (status, applied_at DESC);

-- ─── ROW-LEVEL SECURITY ─────────────────────────────────────────────────────
ALTER TABLE public.union_applications ENABLE ROW LEVEL SECURITY;

-- Club owners can see their own club's applications
CREATE POLICY "club_owner_can_view_own_applications"
  ON public.union_applications
  FOR SELECT
  USING (
    applicant_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.clubs
      WHERE id = union_applications.club_id
        AND owner_id = auth.uid()
    )
  );

-- Club owners can insert (apply) — further auth is enforced at API level
CREATE POLICY "club_owner_can_apply"
  ON public.union_applications
  FOR INSERT
  WITH CHECK (applicant_user_id = auth.uid());

-- Platform admins can see and update all applications (via service role in API)
-- The API uses service role key, so RLS is bypassed server-side. 
-- These policies are for any future direct-Supabase access by admins.
CREATE POLICY "admin_can_view_all_applications"
  ON public.union_applications
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid()
        AND role IN ('admin', 'superadmin')
    )
  );

CREATE POLICY "admin_can_update_applications"
  ON public.union_applications
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid()
        AND role IN ('admin', 'superadmin')
    )
  );

-- ─── REALTIME ────────────────────────────────────────────────────────────────
-- Add to realtime so the horses admin dashboard can get live notifications
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND tablename = 'union_applications'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.union_applications;
  END IF;
END $$;


-- ════════════════════════════════════════════════════════════════════════
-- FILE: 20260308_union_wallets.sql
-- ════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Migration: Union Wallet System
-- 4 wallets on the unions table:
--   chip_balance  — general/operational wallet for sending chips to clubs
--   rake_wallet   — rake collected from clubs each settlement period
--   bbj_wallet    — BBJ contributions routed here from club settlements
--   promo_wallet  — promotional fund pool
-- Run in Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE public.unions
  ADD COLUMN IF NOT EXISTS chip_balance   NUMERIC(20,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rake_wallet    NUMERIC(20,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bbj_wallet     NUMERIC(20,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS promo_wallet   NUMERIC(20,4) NOT NULL DEFAULT 0;

COMMENT ON COLUMN public.unions.chip_balance  IS 'General-purpose chip balance. Union can send chips to clubs from here.';
COMMENT ON COLUMN public.unions.rake_wallet   IS 'Cumulative rake collected from all member clubs each settlement cycle.';
COMMENT ON COLUMN public.unions.bbj_wallet    IS 'BBJ pool contributions routed here from club-level settlements.';
COMMENT ON COLUMN public.unions.promo_wallet  IS 'Promo fund balance for union-level promotional chip distributions.';

-- ── Safe increment/decrement RPCs ──────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.fn_union_credit_wallet(
  p_union_id   UUID,
  p_wallet     TEXT,   -- 'chip_balance' | 'rake_wallet' | 'bbj_wallet' | 'promo_wallet'
  p_amount     NUMERIC
) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF p_amount <= 0 THEN RAISE EXCEPTION 'amount must be positive'; END IF;
  IF p_wallet NOT IN ('chip_balance','rake_wallet','bbj_wallet','promo_wallet') THEN
    RAISE EXCEPTION 'invalid wallet name: %', p_wallet;
  END IF;
  EXECUTE format(
    'UPDATE public.unions SET %I = %I + $1 WHERE id = $2',
    p_wallet, p_wallet
  ) USING p_amount, p_union_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_union_debit_wallet(
  p_union_id   UUID,
  p_wallet     TEXT,
  p_amount     NUMERIC
) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_bal NUMERIC;
BEGIN
  IF p_amount <= 0 THEN RAISE EXCEPTION 'amount must be positive'; END IF;
  IF p_wallet NOT IN ('chip_balance','rake_wallet','bbj_wallet','promo_wallet') THEN
    RAISE EXCEPTION 'invalid wallet name: %', p_wallet;
  END IF;
  EXECUTE format(
    'SELECT %I FROM public.unions WHERE id = $1 FOR UPDATE',
    p_wallet
  ) INTO v_bal USING p_union_id;
  IF v_bal < p_amount THEN
    RAISE EXCEPTION 'insufficient union % balance (have %, need %)', p_wallet, v_bal, p_amount;
  END IF;
  EXECUTE format(
    'UPDATE public.unions SET %I = %I - $1 WHERE id = $2',
    p_wallet, p_wallet
  ) USING p_amount, p_union_id;
END;
$$;

-- ── union_wallet_transactions ledger ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.union_wallet_transactions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  union_id        UUID NOT NULL REFERENCES public.unions(id) ON DELETE CASCADE,
  wallet          TEXT NOT NULL CHECK (wallet IN ('chip_balance','rake_wallet','bbj_wallet','promo_wallet')),
  direction       TEXT NOT NULL CHECK (direction IN ('credit','debit')),
  amount          NUMERIC(20,4) NOT NULL CHECK (amount > 0),
  balance_after   NUMERIC(20,4),
  tx_type         TEXT NOT NULL, -- 'settlement_hold','rakeback_distribution','manual_transfer','bbj_contribution','promo_distribution'
  club_id         UUID REFERENCES public.clubs(id) ON DELETE SET NULL,
  period_id       UUID,
  notes           TEXT,
  created_by      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_uwt_union_id    ON public.union_wallet_transactions(union_id);
CREATE INDEX IF NOT EXISTS idx_uwt_wallet      ON public.union_wallet_transactions(wallet);
CREATE INDEX IF NOT EXISTS idx_uwt_created_at  ON public.union_wallet_transactions(created_at DESC);

ALTER TABLE public.union_wallet_transactions ENABLE ROW LEVEL SECURITY;

-- Union admins can view their union's transactions
CREATE POLICY "union_admin_view_wallet_txns"
  ON public.union_wallet_transactions FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.union_admins
      WHERE union_id = union_wallet_transactions.union_id
        AND user_id = auth.uid()
    )
  );

-- Platform admins can view all
CREATE POLICY "platform_admin_view_wallet_txns"
  ON public.union_wallet_transactions FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role IN ('admin','superadmin')
    )
  );

-- Add to realtime
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'union_wallet_transactions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.union_wallet_transactions;
  END IF;
END $$;


-- ═══════════════════════════════════════════════════════════════════════════
-- PHASE 14 ADDITION: rakeback_periods + union_wallet_transactions realtime
-- ═══════════════════════════════════════════════════════════════════════════
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS rakeback_periods;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS union_wallet_transactions;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commission_history;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS commission_records;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS union_leave_requests;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS sandbox_coach_results;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS sandbox_equity_history;
ALTER PUBLICATION supabase_realtime ADD TABLE IF NOT EXISTS geeves_missed_questions;
