// Settings Page Styles — extracted for bundle splitting
const styles = {
    container: {
        minHeight: '100vh', paddingBottom: 70, width: '100%', maxWidth: '100vw', overflowX: 'hidden', boxSizing: 'border-box',
        background: '#0a1628',
        fontFamily: 'Inter, -apple-system, sans-serif',
        position: 'relative',
    },
    bgGrid: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundImage: `
            linear-gradient(rgba(136, 136, 136, 0.02) 1px, transparent 1px),
            linear-gradient(90deg, rgba(136, 136, 136, 0.02) 1px, transparent 1px)
        `,
        backgroundSize: '60px 60px',
        pointerEvents: 'none',
    },
    header: {},
    backButton: {},
    pageTitle: {
        fontFamily: 'Rajdhani, sans-serif',
        fontSize: 24,
        fontWeight: 700,
        color: '#fff',
    },

    layout: {
        display: 'flex',
        minHeight: 'calc(100vh - 80px)',
    },
    sidebar: {
        width: 240,
        padding: 20,
        borderRight: '1px solid rgba(255, 255, 255, 0.1)',
        background: 'rgba(0, 0, 0, 0.2)',
    },
    sidebarItem: {
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        width: '100%',
        padding: '12px 16px',
        background: 'transparent',
        border: 'none',
        borderRadius: 8,
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 14,
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        marginBottom: 4,
        textAlign: 'left',
    },
    sidebarItemActive: {
        background: 'rgba(0, 212, 255, 0.15)',
        color: '#00D4FF',
    },

    sidebarDivider: {
        height: 1,
        background: 'rgba(255, 255, 255, 0.1)',
        margin: '16px 0',
    },
    logoutButton: {
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        width: '100%',
        padding: '12px 16px',
        background: 'transparent',
        border: 'none',
        borderRadius: 8,
        color: '#ff4757',
        fontSize: 14,
        cursor: 'pointer',
        textAlign: 'left',
    },
    content: {
        flex: 1,
        padding: '24px 40px',
        overflowY: 'auto',
    },
    section: {},
    settingGroup: {
        marginBottom: 24,
    },
    groupTitle: {
        fontSize: 16,
        fontWeight: 600,
        color: '#fff',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 24,
        fontWeight: 700,
        color: '#fff',
        marginBottom: 24,
    },
    card: {
        background: 'rgba(255, 255, 255, 0.05)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        borderRadius: 16,
        padding: 24,
        marginBottom: 24,
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: 600,
        color: '#fff',
        marginBottom: 16,
    },
    settingRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '16px 0',
        borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
    },
    settingInfo: {
        display: 'flex',
        flexDirection: 'column',
        gap: 4,
    },
    settingLabel: {
        fontSize: 15,
        fontWeight: 500,
        color: '#fff',
    },
    settingDesc: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.5)',
    },
    toggle: {
        width: 48,
        height: 28,
        borderRadius: 14,
        border: 'none',
        cursor: 'pointer',
        position: 'relative',
        transition: 'all 0.2s ease',
    },
    toggleKnob: {
        width: 22,
        height: 22,
        borderRadius: '50%',
        background: '#fff',
        position: 'absolute',
        top: 3,
        left: 3,
        transition: 'transform 0.2s ease',
    },
    select: {
        padding: '10px 16px',
        background: 'rgba(0, 0, 0, 0.3)',
        border: '1px solid rgba(255, 255, 255, 0.2)',
        borderRadius: 8,
        color: '#fff',
        fontSize: 14,
        cursor: 'pointer',
        minWidth: 150,
    },
    profileRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 16,
    },
    profileAvatar: {},
    profileInfo: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: 4,
    },
    profileName: {
        fontSize: 18,
        fontWeight: 600,
        color: '#fff',
    },
    profileEmail: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.6)',
    },
    editButton: {
        padding: '10px 20px',
        background: 'rgba(0, 212, 255, 0.15)',
        border: '1px solid rgba(0, 212, 255, 0.3)',
        borderRadius: 8,
        color: '#00D4FF',
        fontSize: 14,
        fontWeight: 500,
        cursor: 'pointer',
    },
    secondaryButton: {
        display: 'block',
        width: '100%',
        padding: '12px 16px',
        background: 'rgba(255, 255, 255, 0.05)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        borderRadius: 8,
        color: '#fff',
        fontSize: 14,
        cursor: 'pointer',
        marginBottom: 8,
        textAlign: 'left',
    },
    dataRow: {},
    dataTitle: {},
    dataDesc: {},
    exportButton: {
        padding: '8px 20px',
        background: 'rgba(0, 212, 255, 0.15)',
        border: '1px solid rgba(0, 212, 255, 0.3)',
        borderRadius: 6,
        color: '#00D4FF',
        fontSize: 13,
        fontWeight: 500,
        cursor: 'pointer',
    },
    dangerCard: {},
    dangerTitle: {},
    dangerDesc: {},
    dangerButton: {},
    // New styles for added sections
    slider: {
        flex: 1,
        margin: '0 16px',
        accentColor: '#00D4FF',
    },
    volumeLabel: {
        minWidth: '50px',
        textAlign: 'right',
        fontSize: 14,
        color: '#00D4FF',
        fontWeight: 600,
    },
    infoText: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.7)',
        lineHeight: 1.6,
        marginBottom: 16,
    },
    helperText: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.5)',
        marginTop: 12,
        fontStyle: 'italic',
    },
    linkButton: {
        padding: '12px 24px',
        background: 'rgba(0, 212, 255, 0.15)',
        border: '1px solid rgba(0, 212, 255, 0.3)',
        borderRadius: 8,
        color: '#00D4FF',
        fontSize: 14,
        fontWeight: 600,
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    infoList: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.7)',
        lineHeight: 1.8,
        paddingLeft: 24,
        margin: 0,
    },
    vipBadge: {},
    vipIcon: {},
    vipTitle: {},
    vipSubtitle: {},
    dangerZone: {
        background: 'rgba(255, 71, 87, 0.05)',
        border: '1px solid rgba(255, 71, 87, 0.2)',
        borderRadius: 16,
        padding: 24,
    },
    warningBox: {
        display: 'flex',
        gap: 16,
        padding: 20,
        background: 'rgba(255, 165, 0, 0.1)',
        border: '1px solid rgba(255, 165, 0, 0.3)',
        borderRadius: 12,
        marginBottom: 24,
    },
    warningIcon: {
        fontSize: 32,
    },
    warningTitle: {
        fontSize: 18,
        fontWeight: 600,
        color: '#FFA500',
        marginBottom: 8,
    },
    warningText: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.7)',
        lineHeight: 1.6,
    },
    deleteButton: {
        padding: '14px 28px',
        background: '#ff4757',
        border: 'none',
        borderRadius: 8,
        color: '#fff',
        fontSize: 15,
        fontWeight: 700,
        cursor: 'pointer',
        marginTop: 24,
        transition: 'all 0.2s',
    },
    // ── Billing Styles ──
    billingStatCard: {},
    transactionRow: {},
    billingOrderCard: {},
};

export default styles;
