/**
 * A PDF W-2G IS READ, BECAUSE THAT IS HOW A CASINO SENDS ONE.
 *
 * Until 2026-09-09 DealerVault's handleFileSelect sent images to the reader
 * and PDFs nowhere at all: anything non-image went straight to the upload
 * form and analyzeDocument never ran. The file uploaded, it stored, and every
 * field on it was typed in by hand.
 *
 * Casinos email W-2Gs as PDFs. It is the most common way a player receives
 * one, and it was the one input the reader ignored completely.
 *
 * TEXT FIRST. A W-2G generated by a payer's system has a text layer: the
 * numbers are IN the file, exactly, and pdf.js hands them over with no
 * recognition step and therefore no recognition errors. Rasterising that and
 * running OCR over it would be slower and strictly worse. Only a scan or a
 * photograph inside a PDF wrapper needs the engine.
 *
 * Both paths verified in a real browser against real PDFs:
 *   text pdf     source=text  confidence 100  -> tax / w2 / 2026 / 2140.00
 *   scanned pdf  source=ocr   confidence 94   -> tax / w2 / 2026 / 2140.00
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { isPdf, PDFJS_VERSION } from '../src/lib/docscan/pdfText.mjs';
import { VERSION as COPIED_VERSION, OUT_DIR } from '../scripts/copy-pdfjs-assets.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');
const code = (rel) => read(rel)
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:])\/\/.*$/gm, '$1');

// ---------------------------------------------------------------------------
// A PDF REACHES THE READER AT ALL
// ---------------------------------------------------------------------------

test('choosing a PDF starts a read instead of going straight to the form', () => {
    const vault = code('src/components/bankroll/DealerVault.jsx');
    assert.match(vault, /if \(isPdf\(file\)\) analyzeDocument\(file\)/, 'a PDF was never read before this');
    // And the image path is untouched.
    assert.match(vault, /if \(file\.type\.startsWith\('image\/'\)\)/);
});

test('the reader is given the file, not a data url it cannot use', () => {
    const vault = code('src/components/bankroll/DealerVault.jsx');
    assert.match(vault, /read = await readPdf\(input, \{ onProgress/);
    assert.match(vault, /if \(isPdf\(input\)\) \{/, 'the branch is on the input, not on a flag set elsewhere');
    // The image path still downscales and still uses the OCR engine.
    assert.match(vault, /downscaleForOcr\(full, 1600, 0\.85\)/);
    assert.match(vault, /readText\(forOcr/);
});

test('a PDF is recognised by type or by name', () => {
    assert.equal(isPdf({ type: 'application/pdf' }), true);
    assert.equal(isPdf({ type: 'APPLICATION/PDF' }), true);
    assert.equal(isPdf({ name: 'w2g-2026.PDF' }), true, 'some browsers send an empty type');
    assert.equal(isPdf({ type: 'image/jpeg', name: 'receipt.jpg' }), false);
    for (const junk of [null, undefined, {}, '', 0]) assert.equal(isPdf(junk), false);
});

// ---------------------------------------------------------------------------
// TEXT BEFORE PIXELS
// ---------------------------------------------------------------------------

test('a text layer is used directly, with no recognition step', () => {
    const pdf = code('src/lib/docscan/pdfText.mjs');
    assert.match(pdf, /const text = joinTextContent\(await page\.getTextContent\(\)\)/);
    assert.match(pdf, /if \(text\.length >= MIN_TEXT_CHARS\)/);
    assert.match(pdf, /source: 'text', pages: doc\.numPages/);
    assert.match(pdf, /confidence: 100/, 'exact text has nothing to be unsure about');
    // The OCR call must come AFTER, so it is genuinely the fallback.
    assert.ok(
        pdf.indexOf('getTextContent()') < pdf.indexOf('readText(canvas'),
        'text extraction must be tried before rasterising',
    );
});

test('a page with no text layer is rasterised and read by the same engine', () => {
    const pdf = code('src/lib/docscan/pdfText.mjs');
    assert.match(pdf, /await readText\(canvas, \{ onProgress: options\.onProgress \}\)/);
    assert.match(pdf, /source: 'ocr'/);
    // A transparent page background renders BLACK on a fresh canvas, which
    // hides every letter on the form.
    assert.match(pdf, /ctx\.fillStyle = '#ffffff'/);
    assert.match(pdf, /ctx\.fillRect\(0, 0, canvas\.width, canvas\.height\)/);
});

test('lines survive the text layer, because the parser reads line by line', () => {
    // pdf.js hands back positioned fragments, not lines. Joining them without
    // looking at the baseline gives one long line, and every label-and-amount
    // rule in the parser works on a line.
    const pdf = code('src/lib/docscan/pdfText.mjs');
    assert.match(pdf, /item\.transform\[5\]|transform\[5\]/, 'the baseline decides where a line ends');
    assert.match(pdf, /item\.hasEOL/);
});

// ---------------------------------------------------------------------------
// STILL OUR OWN ORIGIN, STILL CODE SPLIT
// ---------------------------------------------------------------------------

test('pdf.js runs from our own origin, never the CDN it defaults to', () => {
    const pdf = code('src/lib/docscan/pdfText.mjs');
    assert.match(pdf, /GlobalWorkerOptions\.workerPort = new Worker\(PDFJS_WORKER_URL, \{ type: 'module' \}\)/,
        'the worker must be ours, and module-typed: a classic worker cannot parse its first import');
    assert.match(pdf, /export const PDFJS_WORKER_URL = `\/pdfjs\/\$\{PDFJS_VERSION\}\/pdf\.worker\.min\.mjs`/);
    assert.doesNotMatch(pdf, /cdnjs|jsdelivr|unpkg|cdn\./i);
    assert.doesNotMatch(pdf, /workerSrc\s*=\s*['"`]https?:/);
    // The webpack idiom does not work for a bare specifier and the build says
    // so. Pinned here so nobody "simplifies" it back into a red build.
    assert.doesNotMatch(pdf, /new URL\('pdfjs-dist/, 'webpack cannot resolve a package specifier inside new URL()');
});

test('the worker version the code asks for is the one the build writes', () => {
    const pdf = code('src/lib/docscan/pdfText.mjs');
    const declared = pdf.match(/export const PDFJS_VERSION = '([\d.]+)'/);
    assert.ok(declared, 'the version must be a constant, not buried in a string');
    const installed = JSON.parse(read('node_modules/pdfjs-dist/package.json')).version;
    assert.equal(declared[1], installed, 'a drift here is a 404 for the worker');
    assert.equal(PDFJS_VERSION, COPIED_VERSION, 'and the copy script must agree');
    assert.equal(OUT_DIR, `public/pdfjs/${PDFJS_VERSION}`);
});

test('the worker is served immutable, like the OCR engine', () => {
    const vercel = JSON.parse(read('vercel.json'));
    const rule = vercel.headers.find((h) => h.source === '/pdfjs/(.*)');
    assert.ok(rule, 'without this Vercel serves it max-age=0, must-revalidate');
    const cc = rule.headers.find((h) => /^cache-control$/i.test(h.key));
    assert.match(cc.value, /\bimmutable\b/);
    // And generated by the build that actually deploys, not only by prebuild.
    // That distinction shipped a broken reader once already.
    //
    // Followed through the indirection: both commands call ONE runner, because
    // chaining both copies into buildCommand took it past Vercel's
    // 256-character limit and errored two production deploys.
    const runner = read('scripts/copy-reader-assets.mjs');
    assert.match(runner, /copy-pdfjs-assets\.mjs/, 'the runner must actually copy the worker');
    assert.match(vercel.buildCommand, /copy-reader-assets\.mjs/);
    const pkg = JSON.parse(read('package.json'));
    assert.match(pkg.scripts.prebuild, /copy-reader-assets\.mjs/);
    const copyAt = vercel.buildCommand.indexOf('copy-reader-assets.mjs');
    const buildAt = vercel.buildCommand.indexOf('next build');
    assert.ok(copyAt >= 0 && copyAt < buildAt, 'the copy must run BEFORE next build');
});

test('the generated worker is counted against the public budget', () => {
    // It is generated, so a guard that walks the checkout cannot see it. That
    // is exactly how 14 MB of OCR engine nearly deployed unnoticed.
    const budget = code('scripts/ci/check-public-budget.mjs');
    assert.match(budget, /copy-pdfjs-assets\.mjs/);
    assert.match(budget, /\['tesseract', '\.\.\/copy-tesseract-assets\.mjs'\], \['pdfjs', '\.\.\/copy-pdfjs-assets\.mjs'\]/);
});

test('pdf.js is only downloaded by somebody who opens a PDF', () => {
    const pdf = code('src/lib/docscan/pdfText.mjs');
    assert.match(pdf, /await import\('pdfjs-dist\/build\/pdf\.min\.mjs'\)/, 'a static import would ship it to everybody');
    assert.match(pdf, /if \(pdfjsPromise\) return pdfjsPromise/, 'and only once');
    assert.match(pdf, /pdfjsPromise = null;\n\s*throw err/, 'a failed load must not poison every later attempt');
});

test('the dependency is pinned and present', () => {
    const pkg = JSON.parse(read('package.json'));
    assert.ok(pkg.dependencies['pdfjs-dist'], 'pdfjs-dist must be a dependency');
    const lock = JSON.parse(read('package-lock.json'));
    assert.ok(lock.packages['node_modules/pdfjs-dist'], 'and in the lock file');
});

// ---------------------------------------------------------------------------
// FAILING IS SURVIVABLE AND SAID OUT LOUD
// ---------------------------------------------------------------------------

test('an unreadable PDF is reported, not swallowed', () => {
    const pdf = code('src/lib/docscan/pdfText.mjs');
    assert.match(pdf, /export class PdfUnreadableError extends Error/);
    const vault = code('src/components/bankroll/DealerVault.jsx');
    assert.match(vault, /err instanceof OcrUnavailableError \|\| err instanceof PdfUnreadableError/);
    assert.match(vault, /reportReaderFailure\(err, READER_SECTIONS\.DEALER_VAULT, userId\)/);
    // And the user is told, rather than left looking at an empty form.
    assert.match(vault, /Could not auto-extract data\. Please enter manually\./);
});

test('the document is released even when the read throws', () => {
    // A pdf.js document holds a worker and its buffers. Leaking one per failed
    // upload is how a vault session runs a phone out of memory.
    const pdf = code('src/lib/docscan/pdfText.mjs');
    assert.match(pdf, /\} finally \{[\s\S]*?doc\.destroy\(\)/);
});
