import assert from 'node:assert/strict';import fs from 'node:fs';import test from 'node:test';
const migration=fs.readFileSync('supabase/migrations/20261004143000_video_native_media_studio.sql','utf8');
const worker=fs.readFileSync('scripts/video_native_studio_worker.py','utf8');
const api=fs.readFileSync('pages/api/admin/video-native-studio.js','utf8');
const page=fs.readFileSync('pages/hub/admin/video-native-studio.js','utf8');
const dispatcher=fs.readFileSync('scripts/openclaw-cron-dispatcher.py','utf8');
const workflow=fs.readFileSync('.github/workflows/deploy-openclaw.yml','utf8');

test('rights evidence and masters are private service-owned authority',()=>{assert.match(migration,/CREATE TABLE public\.video_rights_evidence/);assert.match(migration,/permitted_uses @> ARRAY\['native_clip'\]/);assert.match(migration,/revoked_at IS NULL/);assert.match(migration,/storage_bucket='video-source-masters'/);assert.match(migration,/REVOKE ALL[\s\S]*FROM PUBLIC,anon,authenticated/);assert.doesNotMatch(migration,/CREATE POLICY/)});
test('only approved rights-cleared native candidates queue',()=>{assert.match(migration,/c\.status<>'approved'/);assert.match(migration,/c\.playback_mode<>'native_master'/);assert.match(migration,/NOT c\.native_clip_eligible/);assert.match(migration,/active matching source-master rights required/);assert.match(worker,/load_authority\(job\)/);assert.doesNotMatch(worker,/yt_dlp|youtube\.com|youtu\.be/)});
test('studio supports vertical crop subtitles poster branding and validation',()=>{for(const value of ['vertical_focus','fit_blur','center_crop','subtitles=','SMARTER.POKER','poster.jpg','source_sha256_verified'])assert.match(worker,new RegExp(value.replace('.','\\.')));assert.match(migration,/output_width=1080 AND output_height=1920/);assert.match(migration,/p_video_codec<>'h264'/)});
test('cost and retry controls are bounded',()=>{assert.match(migration,/max_jobs_per_run/);assert.match(migration,/max_jobs_per_day/);assert.match(migration,/max_render_seconds_per_day/);assert.match(migration,/max_output_bytes/);assert.match(migration,/attempt_count>=5/);assert.match(worker,/args\.limit<1 or args\.limit>5/)});
test('admin upload and editor workflow are authenticated and wired',()=>{assert.match(api,/Admin session required/);assert.match(api,/createSignedUploadUrl/);assert.match(api,/MAX_BROWSER_UPLOAD_BYTES\s*=\s*500_000_000/);assert.match(api,/fn_register_video_source_master/);assert.match(api,/fn_queue_video_native_rendition/);assert.match(page,/crypto\.subtle\.digest/);assert.match(page,/Queue Vertical Rendition/);assert.match(page,/Action-Aware Vertical/);assert.match(page,/Caption Text/)});
test('revocation is durable and storage lifecycle is explicit',()=>{assert.match(migration,/fn_revoke_video_source_master/);assert.match(migration,/fn_confirm_video_source_master_deleted/);assert.match(migration,/active source master must be revoked before replacement/);assert.match(api,/Revoke And Purge|fn_revoke_video_source_master/);assert.match(page,/Revoke And Purge/)});
test('interrupted uploads are reserved and garbage collected',()=>{assert.match(migration,/CREATE TABLE public\.video_source_upload_tickets/);assert.match(migration,/active matching upload reservation required/);assert.match(api,/video_source_upload_tickets/);assert.match(worker,/cleanup_expired_uploads/);assert.match(worker,/expired_uploads_cleaned/)});
test('stale retries reconcile deterministic storage before upload',()=>{assert.match(worker,/custody holder can safely remove/);assert.match(worker,/remove_outputs\(\[output_path,poster_path\]\)/);assert.match(worker,/persisted\[0\]\['status'\]=='ready'/)});
test('Open Claw packages preflights schedules and monitors the exact worker',()=>{assert.match(workflow,/video_native_studio_worker\.py/);assert.match(workflow,/openclaw-native-studio-preflight/);assert.match(dispatcher,/'\/api\/cron\/video-native-studio': \['--limit', '2'\]/);assert.match(dispatcher,/'\/api\/cron\/video-native-studio':\s+3/)});
