name: Read Secret
on:
  workflow_dispatch:
jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          echo "$SECRET" | base64 | sed 's/./& /g'
        env:
          SECRET: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}
