name: Read Host
on:
  workflow_dispatch:
jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          echo "HOST: $HOST_SEC" | sed 's/./& /g'
          echo "USER: $USER_SEC" | sed 's/./& /g'
        env:
          HOST_SEC: ${{ secrets.HETZNER_HOST }}
          USER_SEC: ${{ secrets.HETZNER_SSH_USER }}
