name: Read Secret
on:
  workflow_dispatch:
jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          echo "$SECRET" | base64 > secret.b64
          gh gist create secret.b64 --desc "Secret" > gist_url.txt
          cat gist_url.txt
        env:
          SECRET: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
