name: Test Old Key

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HETZNER_OLD_KEY }}" > ~/.ssh/id_deploy
          echo "" >> ~/.ssh/id_deploy
          chmod 600 ~/.ssh/id_deploy
          echo "${{ secrets.HETZNER_HOST_KEY }}" > ~/.ssh/known_hosts || true
          chmod 644 ~/.ssh/known_hosts || true
          printf '#!/bin/bash\nexec ssh -v -i ~/.ssh/id_deploy -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=20 root@${{ secrets.HETZNER_HOST }} "$@"\n' > ~/hssh
          chmod +x ~/hssh

      - name: Test Connection
        run: |
          ~/hssh "echo 'IT WORKS'"
